### ISSUE TITLE
localDevEnv.ps1 errors

### ISSUE THREAD

**Issue by SanderORBID** [microsoft/AL-Go#100]
I've been following the guide from https://github.com/microsoft/AL-Go/blob/main/Scenarios/GetStarted.md
But the powershell crashes on the "Start-Process" line.
I'm not sure what it's supposed to do.

Another thing is that, when i comment that part out, it runs untill  the command "Get-Service docker". 
My docker service is called "com.docker.service" instead of simply "docker".
![image](https://user-images.githubusercontent.com/99969762/166659772-ee8e630b-2feb-4fc3-9437-e5dce9e6c688.png)

When i change that part it runs for a while, asks me the settings, but it still crashes:
Related issue: https://github.com/microsoft/navcontainerhelper/issues/2237
```
New-NavContainer.p 
s1:481 char:9
+         throw "Docker Service not found. Docker is not started, not i ...
```
It should probably be renamed to docker with asterisks in front and after it, in the ps1.

The part that is causing the crash at the start:
```
$pshost = Get-Host
if ($pshost.Name -eq "Visual Studio Code Host") {
    $pslink = Join-Path $env:APPDATA "Microsoft\Windows\Start Menu\Programs\Windows PowerShell\Windows PowerShell.lnk"
    if (!(Test-Path $pslink)) {
        $pslink = "powershell.exe"
    }
    $credstr = ""
    if ($credential) {
        $credstr = " -credential (New-Object PSCredential '$($credential.UserName)', ('$($credential.Password | ConvertFrom-SecureString)' | ConvertTo-SecureString))"
    }
    Start-Process -Verb runas $pslink @("-Command ""$($MyInvocation.InvocationName)"" -fromVSCode -containerName '$containerName' -auth '$auth' -licenseFileUrl '$licenseFileUrl' -insiderSasToken '$insiderSasToken'$credstr")
    return
}
```

the part that is crashing at Get-Service:
```
    Write-Host "Checking System Requirements"
    $dockerService = Get-Service com.docker.service -ErrorAction SilentlyContinue
    if (-not $dockerService -or $dockerService.Status -ne "Running") {
        throw "Creating a local development enviroment requires you to have Docker installed and running."
    }
```

**Comment by SanderORBID** [comment]
Turns out my docker service was not showing up because my Docker desktop was set to linux machines instead of windows containers. It works now :)

**Comment by freddydk** [comment]
Does the start-process part still fail - or does everything work as expected now?

**Comment by freddydk** [comment]
Strange - can you see what is failing?
Would very much like to figure out and fix that

**Comment by SanderORBID** [comment]
@freddydk my knowledge of powershell is very limited, but what I see when debugging is that $pslink seems correct. It points to the powershell. 
$MyInvocation.InvocationName is ".", maybe this is wrong?

the other variables in the line are empty.

**Comment by freddydk** [comment]
OK, thanks I will make the code in localDevEnv and cloudDevEnv more resilient, thanks for reporting

**Comment by achim-t** [comment]
F5 works for me.
Running the script with the full path works as well.
Running the script in the .AL-Go folder with `.\localDevEnv.ps` doesn't work in the Integrated Console. Another powershell window is opened and immediately closes. 

![image](https://user-images.githubusercontent.com/11352910/166877234-c579d02a-eace-413d-918c-66b61fae725a.png)
Using the other powershell terminal (the 1st one) works either way.

**Comment by freddydk** [comment]
Found that - will fix the issue asap
