### ISSUE TITLE
"Environment xxx is not setup for deployments from branch xxx"

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#1001]
We deploy to this environment all the time. We are attempting to deploy from a feature branch here, to do testing prior to merging that branch into main. Is there something we actually have to do to that environment to enable that kind of deployment? Can we in fact deploy feature branches to test Sandbox environments in this way?  The environment is set up with "No Restriction" with regard to which branches are allowed to deploy to it. Full log is below.

[logs_22017573766.zip](https://github.com/microsoft/AL-Go/files/14727742/logs_22017573766.zip)

**Comment by freddydk** [comment]
https://aka.ms/algosettings#deployto

If Branches are not defined in GitHub settings or AL-Go settings - we default to main.
If Branches are defined in GitHub settings and not in AL-Go settings - we use that
If Branches are defined in AL-Go settings and not in GitHub settings - we use that
If Branches are defined in both places - we use both.

**Comment by buzzwick** [comment]
Ah yes. I get it. The explanation under DeployTo is crystal clear--now that I know the real source of the problem. 
Would it be possible to word the error message so that it implicates Settings, rather than either the environment or the branch? That might eliminate a lot of looking in the wrong places.

In the meantime, thank you very much for the enumeration of the Settings order of priorities. That will go in my collection of AL-Go Post-it notes for quick reference!
