### ISSUE TITLE
DLL / Compiler Folder not deleted for LocalDevEnv

### ISSUE THREAD

**Issue by pri-kise** [microsoft/AL-Go#1002]
I wanted to create a fresh docker environment for the BCApps Repository.

Therefore I used the LocalDevEnv.ps1 script.
https://github.com/microsoft/BCApps/blob/main/build/projects/System%20Application%20Modules/.AL-Go/localDevEnv.ps1
```al
$containerName = "bcapps"
# Define clear text string for username and password
[string]$userName = 'admin'
[string]$userPassword = 'admin'
# Convert to SecureString
[securestring]$secStringPassword = ConvertTo-SecureString $userPassword -AsPlainText -Force
[pscredential]$credential = New-Object System.Management.Automation.PSCredential ($userName, $secStringPassword)

. "C:\Users\user\source\AL\Microsoft\BCApps\build\projects\System Application\.AL-Go\localDevEnv.ps1" -containerName $containerName -auth "UserPassword" -credential $credential -accept_insiderEula -licenseFileUrl "none"
```

The script stopped since I didn't the delete the specific folder compiler (C:\ProgramData\BcContainerHelper\compiler\bcapps) folder for this docker.

The warning or error handling could be improved

**Comment by freddydk** [comment]
What error are you seeing?
I have tried to repro this in different ways, but it just recreates the CompilerFolder
