### ISSUE TITLE
[Question] Support different BC versions

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/AL-Go#1003]
For our module, I need to support various BC versions.

For BC21 and BC22, I have corresponding `dev/21` and `dev/22` branches. 
To apply appropriate bug fixes for these older versions, I have expanded the setting `CICDPullRequestBranches` to `[ "main", "dev/*"]`, to enable Downgrades / Pull Requests to the dev Branches, which not seems to work.

The `PullRequestHandler.yaml` is hard-coded to the main Branch:
`pull_request_target:
branches: [ 'main' ]
`

Am I making a mistake regarding the settings and/or branch policy?

Thank you,
Ralf

**Comment by freddydk** [comment]
You need to run the Update AL-Go System Files workflow for the schedule to take effect
I have updated the documentation to reflect this.
