### ISSUE TITLE
CI/CD tries to deploy to a non-existing not setup environment

### ISSUE THREAD

**Issue by louagej** [microsoft/AL-Go#1006]
Hi,

I have a simple `.github/AL-Go-Settings.json` file with 3 environments defined.

```json
{
  "type": "PTE",
  "templateUrl": "https://github.com/microsoft/AL-Go-PTE@preview",
  "templateSha": "3cc6fcecbe3916c40e0e8bee473b9a51feaa9dfb",
  "NextMinorSchedule": "0 22 * * 0",
  "NextMajorSchedule": "0 23 * * 0",
  "environments": [
    "TEST",
    "DEV",
    "UAT"
  ],
  "DeployToTEST": {
    "EnvironmentName": "TEST",
    "continuousDeployment": true
  },
  "DeployToDEV": {
    "EnvironmentName": "DEV",
    "continuousDeployment": true
  },
  "DeployToUAT": {
    "EnvironmentName": "UAT",
    "continuousDeployment": true
  }
}
```

When the CI/CD pipeline runs, the deploy matrix is trying to deploy to 4 environments:

![image](https://github.com/microsoft/AL-Go/assets/7229592/9860cab7-24c9-4021-a36c-0da27f01039b)

In my repository setting are no environments, but only 2 secrets: 
- `AUTHCONTEXT`
- `GHTOKENWORKFLOW`

![image](https://github.com/microsoft/AL-Go/assets/7229592/3e1eee34-864c-4bb7-8a59-fa04339c1c7f)

**Comment by freddydk** [comment]
Under GitHub Settings -> Environments - is there an environment called TEST*?
Then delete that.

**Comment by louagej** [comment]
Indeed, a `TEST*` environment was created, but I’m uncertain about who or how it was created.

Could it be that the `Publish To Environment` workflow generates an environment if it doesn’t already exist?
