### ISSUE TITLE
Publishing to AppSource don't include the dependency apps

### ISSUE THREAD

**Issue by FrankAuwers** [microsoft/AL-Go#1009]
The library apps are stored on separated repositories. When the CI/CD pipeline runs, the dependencies are found and installed correctly. Also when the release is created, the dependency zip file is also stored in the release.
But when we the publish it to AppSource, only the app file is published into AppSource and not the dependencies.
Because of this, the AppSource validation fails. The dependencies are library apps that are not stored separately as install app on AppSource.
We still needs to copy manual the dependency zip file from the release to the AppSource dependencies location and start the validation again.

Is there a setting to tell the publish to also publish these dependencies?

**Comment by FrankAuwers** [comment]
Can anyone give me some advice about this?

**Comment by freddydk** [comment]
This scenario is not supported today.
Today, library apps in the same AL-Go project as the main app are automatically included in the submission.

I have heard this requirement before and will be introducing a property called DeliverToAppSource.includeDependencies, which you can set to an array of app names (with wildcards) to include when submitting to appsource.

The settings will probably look like this:

![image](https://github.com/microsoft/AL-Go/assets/10775043/228de86b-d31c-4449-bd51-d545f339dd4a)

**Comment by dsaveyn** [comment]
> This scenario is not supported today. Today, library apps in the same AL-Go project as the main app are automatically included in the submission.
> 
> I have heard this requirement before and will be introducing a property called DeliverToAppSource.includeDependencies, which you can set to an array of app names (with wildcards) to include when submitting to appsource.
> 
> The settings will probably look like this:
> 
> ![image](https://private-user-images.githubusercontent.com/10775043/321538588-228de86b-d31c-4449-bd51-d545f339dd4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDUxMzksIm5iZiI6MTcxMjg0NDgzOSwicGF0aCI6Ii8xMDc3NTA0My8zMjE1Mzg1ODgtMjI4ZGU4NmItZDMxYy00NDQ5LWJkNTEtZDU0NWYzMzlkZDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE0MTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZDk3YmNmY2Q0ZDg4NWZmZWY0ZTRjNzc4MTk2YzJjMDJiY2I5NmY0Y2UxMTZmYWJkYzAzZDBhZTQ0YWYwOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A7D7FZa7ompVbvBOoOLFtt36m-NbtxOcES6NC59IfEA)

Any chance you could also make this work library apps present the repo under a seperate project? Each of our apps is in a different project folder in the same repo. See also my post [here](https://github.com/microsoft/AL-Go/issues/979#:~:text=I%20did%20some,an%20AppSource%20App.)

@fvet

**Comment by freddydk** [comment]
@dsaveyn - this will work if you would say "includeDependencies": [ "*" ] - or "includeDependencies": [ "Publisher_*" ]

**Comment by dsaveyn** [comment]
> @dsaveyn - this will work if you would say `"includeDependencies": [ "*" ]` - or `"includeDependencies": [ "Publisher_*" ]` in a future version

@freddydk Awesome, thx!

**Comment by FrankAuwers** [comment]
Thanks

Frank Auwers
www.scapta.com l
 +32 11 600 600 
+32 477 498 527
Corda Campus l Kempische Steenweg 293 bus 38 l 3500 Hasselt 
________________________________
Van: Freddy Kristiansen ***@***.***>
Verzonden: dinsdag 16 april 2024 15:21
Aan: microsoft/AL-Go ***@***.***>
CC: Frank Auwers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [microsoft/AL-Go] Publishing to AppSource don't include the dependency apps (Issue #1009)


It is available in AL-Go preview now. Run update AL-Go System Files with ***@***.***
