### ISSUE TITLE
Continous Delivery to Storage Zip File Problem

### ISSUE THREAD

**Issue by ismailhafid1** [microsoft/AL-Go#1010]
thanks to this documentation :
[https://github.com/microsoft/AL-Go/blob/9ff6fea79b92e8e7ede3da568aad69a941d207f6/Workshop/ContinuousDelivery.md](url) 
i managed to deliver the artifacts to Azure Blobs , but there is one issue with the blob :
When I try to download the zip file from the blob URL, it doesn't work, even though I've tried setting both "application/zip" and "application/x-zip-compressed" as the content type.
Error:
```
<Error>
<Code>ResourceNotFound</Code>
<Message>The specified resource does not exist. </Message>
</Error>
```
However, if I try to download the .app file from the blob URL, it works fine.
 Is there a way to unzip the zip file in the workflow and deliver the .app file instead? We prefer this approach because we use .app files for other purposes, and it would be convenient to have them delivered without manual extraction.

**Comment by freddydk** [comment]
The AL-Go delivery will deliver all apps in one project to a .zip file.
The url to the .zip file can be used directly with the BcContainerHelper function Publish-BcContainerApp and Publish-PerTenantExtensionApps. It can also be used in Copy-AppFilesToFolder, which basically will download and unpack the .zip file and leave all apps in the folder specified.

If this is not useful - you can use custom delivery and do-it-yourself (deliver every single .app file to a blob)
