### ISSUE TITLE
CI/CD Workflow still being scheduled after it was disabled

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/AL-Go#1019]
We have a weird issue here.

Last week I disabled the CICDSchedule:

![image](https://github.com/microsoft/AL-Go/assets/92365904/539677f5-41cd-4fac-95be-80ece4daa8a6)

But it still runs:

![image](https://github.com/microsoft/AL-Go/assets/92365904/a5952d23-63f0-4c33-a21b-f02ccc5d962c)

The setting is nowhere specified in our repo:

![image](https://github.com/microsoft/AL-Go/assets/92365904/5eb91d5e-4639-42b4-8631-84686c62e001)

Am I missing something?

**Comment by aholstrup1** [comment]
Try running the "Update AL-Go System Files" workflow. If you open the CICD.yaml file you will likely see something like this at the top of the file: 
`  schedule:
    - cron: '* * * * *' 
`

Running Update AL-Go System Files after you've removed the CICDSchedule setting should remove that for you.

**Comment by dsaveyn** [comment]
> Try running the "Update AL-Go System Files" workflow. If you open the CICD.yaml file you will likely see something like this at the top of the file: ` schedule: - cron: '* * * * *' `
> 
> Running Update AL-Go System Files after you've removed the CICDSchedule setting should remove that for you.

There's indeed a cron entry in the CICD.yaml file. Maybe this is something that can be documented?

**Comment by freddydk** [comment]
You are right, that we are missing the note that "You need to run Update AL-Go System Files for changes to take effect" under https://aka.ms/algosettings#cicdschedule

**Comment by dsaveyn** [comment]
> You are right, that we are missing the note that "You need to run Update AL-Go System Files for changes to take effect" under https://aka.ms/algosettings#cicdschedule

Thanks @freddydk @aholstrup1 for the help. It seems to be okay now.
