### ISSUE TITLE
Error handling of missing GH CLI not working in PS7

### ISSUE THREAD

**Issue by JeppeBylov** [microsoft/AL-Go#1024]
Hi Freddy,

I'm trying to run the localDevEnv.ps1 script to create a local dev environment. 
This will be the first container running on this machine, so everything has been installed and setup from scratch.

When running the script with PS7 i experience this error:

![image](https://github.com/microsoft/AL-Go/assets/968411/9e3e4dd5-5bb9-4bf8-b973-466cafc073b2)

However, when running the exact same script in PS5:

![image](https://github.com/microsoft/AL-Go/assets/968411/115223ab-55c9-484e-9435-27c9af16cf21)

**Comment by freddydk** [comment]
So, you do have GitHub CLI installed I guess?
If you run gh --version in PS5 and PS7 will it display the version in both?

**Comment by JeppeBylov** [comment]
> So, you do have GitHub CLI installed I guess? If you run gh --version in PS5 and PS7 will it display the version in both?

No. At the time i didn't have GitHub CLI installed. 
Installing it fixed the issue in both versions.

**Comment by freddydk** [comment]
Strange that PS5 looked like it was installed...

**Comment by freddydk** [comment]
I have tried to repro this, but cannot
