### ISSUE TITLE
Word Files Modified When Compiling with localdevenv.ps1 

### ISSUE THREAD

**Issue by frottke** [microsoft/AL-Go#1025]
Hi Freddy,

I hope you can help me with this problem. 

We used to have our own script to create our development environments (Docker containers) and now we want to use the localdenv.ps1 script. Now we have noticed the following:

When we run localdevenv, all apps in our repository are compiled correctly, etc. HOWEVER, all Word files are changed. This can be easily recognised by the fact that they are marked as changed by git. I wonder what happens here in the alc.exe that makes this happen. 

Note: We use ForNAV and these Word files are accordingly also ForNAV layouts.

A first analysis of us has shown that if we open the Word files with WinRar and look at the XML files. The sorting of the elements within the DataItems has changed. At this point I doubted whether I should report it here and instead put it in the AL repository, but the files are **NOT** changed when I use a "AL - Package". Accordingly, this only happens when it is compiled via Al-Go.

```
  _____                               _
 |  __ \                             | |
 | |__) |_ _ _ __ __ _ _ __ ___   ___| |_ ___ _ __ ___
 |  ___/ _` | '__/ _` | '_ ` _ \ / _ \ __/ _ \ '__/ __|
 | |  | (_| | | | (_| | | | | | |  __/ |_  __/ |  \__ \
 |_|   \__,_|_|  \__,_|_| |_| |_|\___|\__\___|_|  |___/

Pipeline name                   localDevEnv
Container name                  MyProject
Image name
ArtifactUrl                     https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/onprem/21.2.49946.49990/de
BcAuthContext                   Not Specified
Environment
ReUseContainer                  False
KeepContainer                   True
useCompilerFolder               False
artifactCachePath
useDevEndpoint                  True
Auth                            UserPassword
CompanyName
MemoryLimit                     0G
FailOn                          error
TreatTestFailuresAsWarnings     False
Enable Task Scheduler           True
Assign Premium Plan             True
Install Test Runner             True
Install Test Framework          True
Install Test Libraries          True
Install Perf. Toolkit           False
InstallOnlyReferencedApps       False
generateDependencyArtifact      False
CopySymbolsFromContainer        False
enableCodeCop                   False
enableAppSourceCop              False
enableUICop                     False
enablePerTenantExtensionCop     False
enableCodeAnalyzersOnTestApps   False
doNotPerformUpgrade             False
doNotPublishApps                False
uninstallRemovedApps            False
escapeFromCops                  False
doNotBuildTests                 False
doNotRunTests                   True
doNotRunBcptTests               True
useDefaultAppSourceRuleSet      False
rulesetFile
generateErrorLog                False
enableExternalRulesets          False
azureDevOps                     False
gitLab                          False
gitHubActions                   False
vsixFile
License file                    Specified
CodeSignCertPfxFile             Not specified
CodeSignCertPfxPassword         Not specified
CodeSignCertIsSelfSigned        False
KeyVaultCertPfxFile             Not specified
KeyVaultCertPfxPassword         Not specified
KeyVaultClientId
BuildOutputFile
ContainerEventLogFile
TestResultsFile                 C:\Users\MyUser\Documents\Repositories\MyProject\TestResults.xml
BcptTestResultsFile             C:\Users\MyUser\Documents\Repositories\MyProject\bcptTestResults.json
TestResultsFormat               JUnit
AdditionalCountries
PackagesFolder                  .packages
OutputFolder
BuildArtifactFolder
CreateRuntimePackages           False
AppVersion
AppBuild                        0
AppRevision                     0
SourceRepositoryUrl
SourceCommit
BuildBy                         BcContainerHelper,6.0.15
BuildUrl
```

the, i assume, relevant command in script -> 

```
.\alc.exe 
/project:"c:\sources\app\Shared\MyProject" 
/packagecachepath:"c:\sources\app\Shared\MyProject\.alPackages" 
/out:"c:\sources\app\Shared\MyProject\MyProject.app" 
/assemblyprobingpaths:"C:\Program Files\Microsoft Dynamics NAV\210\Service","C:\Program Files (x86)\Open XML SDK\V2.5\lib","c:\Windows\Microsoft.NET\Assembly","C:\Test Assemblies\Mock Assemblies"
```

**Comment by freddydk** [comment]
It should only update the word files if the dataset definition has changed.
If you run it a second time - is it then shuffling the word files again?

**Comment by frottke** [comment]
`It should only update the word files if the dataset definition has changed.`

In which context? The repository is freshly cloned based on the main branch. There are no changes to the AL files or Word files.

`If you run it a second time - is it then shuffling the word files again?`

it depends, some files changed again. Some did not. There is no pattern that I can recognize

**Comment by freddydk** [comment]
Would it be possible for you to create a test-repository, which repros this problem either public or allow me access to this demo repo?

**Comment by frottke** [comment]
I was able to reproduce the issue in an test repository, unfortunately not with an simple docx file and al file but an repro still :)

I've invited you to the repository. 

How to repro: 

1. execute .\HandlerlocalDevEnv.ps1 in folder .AL-Go
2. Observe that after the container is created and the app (example) is compiled that the docx is changed.
3. Execute "AL - Package" command, observe that the file is changed once again.
4. start all over again at step 1

easiest way to see that there is a difference is to simply stage the change via git.

**Comment by freddydk** [comment]
The reason for this is that there is a difference between the version of the AL Language Extension installed in your VS Code and the one running in the pipeline.
In the pipeline - the AL Language extension from the version of Business Central used to build is used:
![image](https://github.com/microsoft/AL-Go/assets/10775043/6dbd1c18-e243-443e-b754-a7b9a392ebe0)

In VS Code, you probably have
![image](https://github.com/microsoft/AL-Go/assets/10775043/3df94a46-91b5-44ae-b188-1f7e4c0fce74)

If you modify .AL-Go/Settings and add:
```
  "vsixFile": "latest"
```

Then AL-Go will always use the latest AL Language Extension for this project (you can set it in Repository settings or a global settings variable as well), then AL-Go will use the latest AL Language extension from the marketplace.
Setting it to preview will use preview, setting it to a specific URL will use a specific version.

After setting this - the .docx is no longer re-written - no changes in GIT, no new timestamp.

**Comment by freddydk** [comment]
and.., @frottke - thanks a million for the help setting up a repro repository, which makes troubleshooting so much easier (if not possible at all).

**Comment by frottke** [comment]
> and.., @frottke - thanks a million for the help setting up a repro repository, which makes troubleshooting so much easier (if not possible at all)

Absolutely, setting up a repro repository is the least I can do to help you troubleshooting the issue😄 

The solution works perfectly. Many thanks for your commitment, even at the weekend!

I understand the reasons why the latest version is not used for the build job. But I have to admit, I don't see the reason to do the same when creating the local dev env (for active development). From your point of view, does it make sense to go for the version that is the latest, or even better, the version that is detected in Visual Studio Code? Normally, at least in my experience, developers use the latest version regardless of the project (and therefore runtime version) in Visual Studio Code.

I do have one more question about the local dev env script, but I'll create another issue for that. Should be easier for others to find an answer to that question or similar ones. This here can be closed ! 👍
