### ISSUE TITLE
CI/CD Build fails, but Pull Request Build Succeeds

### ISSUE THREAD

**Issue by JacoBothaDyn** [microsoft/AL-Go#1039]
During Pull Request all Checks pass and Build build succesfully, but then trying to run the CI/CD Build fails. 

Initialization, 
CheckForUpdates and 
PostProcess runs but Builds aren't trigerred.

Assuming it has to do with the following Warning: 

![image](https://github.com/microsoft/AL-Go/assets/39368011/ebabb5c0-b6b5-4ca1-a815-7af6828439fe)

![image](https://github.com/microsoft/AL-Go/assets/39368011/0bb1fa3a-b38a-4bcc-8386-70f79f38a119)

![image](https://github.com/microsoft/AL-Go/assets/39368011/8efb2983-bc7c-4698-badb-4b33b7f53f07)

Please Advise

**Comment by JacoBothaDyn** [comment]
[logs_22809441121.zip](https://github.com/microsoft/AL-Go/files/14996572/logs_22809441121.zip)
Attaching Log Files for reference.

**Comment by JacoBothaDyn** [comment]
Here is the Pull Request Build, just before CI/CD on the Merge. 

![image](https://github.com/microsoft/AL-Go/assets/39368011/a33f5bd1-9646-4db3-b290-a39a9cff65c7)

**Comment by freddydk** [comment]
If you include logs instead of screenshots, we have much more info.

**Comment by freddydk** [comment]
It looks like you have a secret, which contains a value used by environments or like.
Maybe run the troubleshooting workflow to see whether that tells you anything.

**Comment by JacoBothaDyn** [comment]
Figured out the reason. 

The AZURE_CRENTIALS secret specified was a prettyfied json. 

```json
{
 clientId: <clientid>
 ...
}
```

but the curly braces on seperate lines caused the GitHub Actions to mark all curly braces as part of secret, so any output with json in was masked as 3 asterixes where curly braces are found:

example in image below as Markdown treats the Asterisks as bold  when trying to use as is: 

![image](https://github.com/microsoft/AL-Go/assets/39368011/7f4f947e-865d-499d-9968-96830b802cf1)

**Comment by freddydk** [comment]
> Hi JacoBothaDyn,
> 
> We're running into the same issue. You found the issue, but what is the fix? Move the curly braces in AZURE_CREDENTIALS so that they are not on separate lines by themselves?
> 
> Thanks in advance for your assistance, Tom

The fix is to remove all spaces and newline characters from the json - make it a compressed json.
