### ISSUE TITLE
ImportLayer failed in Win32

### ISSUE THREAD

**Issue by kennetlindberg** [microsoft/AL-Go#1040]
Builds fail with below message. Very similar to https://github.com/microsoft/AL-Go/issues/833.

Works with:
"artifact": "//20.2.0.0/fi/closest"
but not with:
 "artifact": "/onprem/20.2.0.0/fi/closest"

Attaching full log. 
[job-logs.txt](https://github.com/microsoft/AL-Go/files/15000303/job-logs.txt)

`Error: Unexpected error when running action. Error Message: re-exec error: exit status 1: output: hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) ExitCode: 1 Commandline: docker build --isolation=process --memory 8G --no-cache --tag my:onprem-20.1.39764.39901-fi c:\bcartifacts.cache\ucu05qhe.tef, StackTrace: at DockerDo, C:\ProgramData\BcContainerHelper\6.0.15\BcContainerHelper\HelperFunctions.ps1: line 272 <- at New-BcImage, C:\ProgramData\BcContainerHelper\6.0.15\BcContainerHelper\ContainerHandling\New-NavImage.ps1: line 711 <- at New-BcContainer, C:\ProgramData\BcContainerHelper\6.0.15\BcContainerHelper\ContainerHandling\New-NavContainer.ps1: line 620 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.15\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 798 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.15\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1036 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.15\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 965 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.15\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 947 <- at Run-AlPipeline, C:\ProgramData\BcContainerHelper\6.0.15\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 909 <- at <ScriptBlock>, C:\3\_work\_actions\microsoft\AL-Go-Actions\v5.0\RunPipeline\RunPipeline.ps1: line 367 <- at <ScriptBlock>, C:\3\_work\_temp\f1bb419c-2064-4e52-be45-77629ab7d065.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
Error: Process completed with exit code 1.`

**Comment by freddydk** [comment]
Could you try again now?

**Comment by freddydk** [comment]
and include the log (failing or succeeding)

**Comment by kennetlindberg** [comment]
Yes, running now, looking promising but I'll get back with the logs when it is done.

**Comment by kennetlindberg** [comment]
Yepp, it worked! Logs:
[job-logs2.txt](https://github.com/microsoft/AL-Go/files/15021382/job-logs2.txt)

**Comment by freddydk** [comment]
Ok, thanks

**Comment by kennetlindberg** [comment]
Thank you!
