### ISSUE TITLE
IncrementVersionNumber - the new version number is less than the old version number 

### ISSUE THREAD

**Issue by akoniecki** [microsoft/AL-Go#1041]
Hi,
I have the following problem with the "IncrementVersionNumber" workflow:

`[IncrementVersionNumber]
Unexpected error when running action. Error Message: The new version number (1.10) is less than the old version number (1.9). The version number must be incremented., StackTrace: at Set-VersionInSettingsFile, D:\a\_actions\microsoft\AL-Go-Actions\v5.0\IncrementVersionNumber\IncrementVersionNumber.psm1: line 108 <- at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v5.0\IncrementVersionNumber\IncrementVersionNumber.ps1: line 46 <- at <ScriptBlock>, D:\a\_temp\989f38ee-08d1-4139-9f8b-28d0b976b3b7.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1`

I couldn't find the exact reason in the code, but it seems the System.Version cast is not applied correctly to variables before ($newValue -lt $oldValue) comparison. 

These are the steps to recreate the issue:
1. Create new repo from AL-Go-PTE template
2. Wait until Initial Build is done
3. Run "Create new app" workflow with sample code parameter
4. Run "Increment Version Number" workflow with Updated Version Number parameter: 1.9
5. Run "Increment Version Number" workflow with Updated Version Number parameter: +0.1

Here is my public repo with the issue recreated: https://github.com/akoniecki/versionincrement-debugging/actions/runs/8718133126/job/23914709863#step:7:60

**Comment by AskeHolst** [comment]
We just got the exact same issue.

`Error: Unexpected error when running action. Error Message: The new version number (2.10) is less than the old version number (2.9). The version number must be incremented., StackTrace: at Set-VersionInSettingsFile, /home/runner/work/_actions/microsoft/AL-Go/f2f452940bc16f36a4c59f1fd1982c566f16c03c/Actions/IncrementVersionNumber/IncrementVersionNumber.psm1: line 108 <- at <ScriptBlock>, /home/runner/work/_actions/microsoft/AL-Go/f2f452940bc16f36a4c59f1fd1982c566f16c03c/Actions/IncrementVersionNumber/IncrementVersionNumber.ps1: line 46 <- at <ScriptBlock>, /home/runner/work/_temp/a3b6a4b4-9bc3-4c1d-ab35-7258a178aaaf.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1`

**Comment by florian-d** [comment]
After updating AL-GO, we encountered the same error during the ‘Create Release’ process. We’re also using AL-Go-PTE.

![image](https://github.com/microsoft/AL-Go/assets/5272800/5703d362-e2d8-4a51-98b8-b78e903231f6)

```
Unexpected error when running action. Error Message: The new version number (23.10.0.0) is less than the old version number (23.9.0.0). 
The version number must be incremented., StackTrace: at Set-VersionInSettingsFile, 
D:\a\_actions\microsoft\AL-Go-Actions\v5.0\IncrementVersionNumber\IncrementVersionNumber.psm1: line 108 <- at <ScriptBlock>, 
D:\a\_actions\microsoft\AL-Go-Actions\v5.0\IncrementVersionNumber\IncrementVersionNumber.psm1: line 154 <- at Set-VersionInAppManifests, 
D:\a\_actions\microsoft\AL-Go-Actions\v5.0\IncrementVersionNumber\IncrementVersionNumber.psm1: line 150 <- at <ScriptBlock>, 
D:\a\_actions\microsoft\AL-Go-Actions\v5.0\IncrementVersionNumber\IncrementVersionNumber.ps1: line 53 <- at <ScriptBlock>, 
D:\a\_temp\d26634c8-a3cc-4341-991e-cf830077b236.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
```
