### ISSUE TITLE
Downloading artifacts from GitHub doesn't work with branch names which include forward slashes

### ISSUE THREAD

**Issue by philipp-mlr** [microsoft/AL-Go#1042]
I'm having issues with deploying artifacts, which were created and uploaded to GitHub by the CI/CD pipeline.

When using the branch pattern `feat/mycoolbranchname` with a forward slash `/`, the artifacts won't get detected during the `Publish to Environment` Action (with version set to `latest` aka latest CI/CD build) at the start of the `Deploy` step.
It looks like forward slashes `/` get escaped into underscores `_` for branch names (and their variables in PS)

During the `Deploy` step, the escaped branch name seems to get passed into the [FindLatestSuccessfulCICDRun ](https://github.com/microsoft/AL-Go/blob/dd5c9ebf4bd06d33d45a26aa2fb3d0620277b1d0/Actions/Github-Helper.psm1#L815) function, where an API Call is made to the GitHub /actions/runs endpoint. 

`$runsURI = "https://api.github.com/repos/$repository/actions/runs?per_page=$per_page&page=$page&exclude_pull_requests=true&status=completed&branch=$branch"`

The issue is that the GitHub API expects the actual branch name for the branch parameter.
Respectively, for `feat/mycoolbranchname` the "escaped" result is `feat_mycoolbranchname`. The value `feat_mycoolbranchname` now gets passed into the request parameter and the API returns 0 results and the script fails.

An example:

![grafik](https://github.com/microsoft/AL-Go/assets/51094573/934c2143-d92b-4cfe-b2a4-887cde339caf)
Branch name starts with a forward slash (feat/phm_test)

![grafik](https://github.com/microsoft/AL-Go/assets/51094573/3f3ef54f-300b-4f70-8491-16622ef4d5e8)
Notice that the forward slash is now an underscore. (The `***` attempts to obfuscate the word "test", weird)

I verified via the GitHub API that there is in fact an artifact to download, if the branch name was correct.

Of course, not using a forward slash for example a branch with the name `feat-mycoolbranchname` works but currently limits the freedom in naming.

**Comment by freddydk** [comment]
I think the problem here is that you have a secret with the value "test" somewhere in the repo, which means that this part of the name will be obfuscated.
Have you tried with a branch without the test word?
If this still fails, we do have a problem, which we will investigate

**Comment by philipp-mlr** [comment]
I tested the API call with curl. When using `feat_phm_test` in the branch name, the API returns zero results. Changing the `feat_phm_test` to `feat/phm_test` (e.g. the correct branch name) for the API Call, the API returns the results as expected.
This also happened with branches in which the word "test" wasn't included, which is why we noticed this behavior in the first place.
