### ISSUE TITLE
403 forbidden with project dependencies

### ISSUE THREAD

**Issue by VHCGK** [microsoft/AL-Go#1047]
I found 2 settings are missing when configuring GHTOKENWORKFLOW

1)
when using fine grained tokens on organisation you can break things by restricting the usage of the PAT tokens.
on the following page:
https://github.com/organizations/enterprise/settings/personal-access-tokens

When using fine grained tokens:
- Allow access via fine-grained personal access tokens
- Do not require administrator approval

When using using classic tokens:
Allow access via personal access tokens (classic)

screenshot if you allow both:
![image](https://github.com/microsoft/AL-Go/assets/123416661/9281ef02-aae2-4e82-ad84-c8fe005d8c8e)

2) fined grained access tokens do not work when having project dependencies in other internal repos.
It just can't download the artifacts, i keep getting 403 forbidden.
like below error:

![image](https://github.com/microsoft/AL-Go/assets/123416661/5fd80f93-9c65-4dee-baff-2708a277f6d1)

this is resolved by granting extra rights to fine grained token:
![image](https://github.com/microsoft/AL-Go/assets/123416661/ac455735-d243-4f70-a92c-1f98d4b2bc41)

![image](https://github.com/microsoft/AL-Go/assets/123416661/71e8d012-0e3a-4e6b-847f-544e9879129b)

Please reflect that in the doc on this page 
https://github.com/microsoft/AL-Go/blob/main/Workshop/Prerequisites.md
or this one in step 6
https://github.com/microsoft/AL-Go/blob/main/Scenarios/UpdateAlGoSystemFiles.md

**Comment by freddydk** [comment]
Thanks - will include these findings in the docs.

**Comment by freddydk** [comment]
@VHCGK - let me know whether this includes everything:

https://github.com/freddydk/AL-Go/commit/dffd5dffda996ce39fa91350b5855beb828fb15b?short_path=c8c6606#diff-c8c6606de179dac62540656c6a7620b9f7b277313f06777d6828d63f0da627bc

**Comment by VHCGK** [comment]
that looks great @freddydk.  thank you!
