### ISSUE TITLE
CI/CD Jobs failing on all projects starting last week at some point.

### ISSUE THREAD

**Issue by BMI-Mike** [microsoft/AL-Go#1052]
<img width="1208" alt="image" src="https://github.com/microsoft/AL-Go/assets/35507227/58407737-9d73-47f8-a03a-1e9750cd4343">

I'm getting the following error and warnings on several AL-Go projects starting at some point last week while out of the office.  So far, it appears that only the CICD workflows are impacted.  Other workflows such as UpdateGitHubGoSystemFiles work just fine.

- CI/CD GitHub Actions has encountered an internal error when running your job.
- InitializationSkip output 'environmentsMatrixJson' since it may contain secret.
- InitializationSkip output 'deploymentEnvironmentsJson' since it may contain secret.
- InitializationSkip output 'projectDependenciesJson' since it may contain secret.
- InitializationSkip output 'buildOrderJson' since it may contain secret.

I am assuming this is related to an AL-Go update since it impacted numerous projects within the same timeframe.

**Comment by BMI-Mike** [comment]
Appears similar to #1039

[logs_23018261293.zip](https://github.com/microsoft/AL-Go/files/15080510/logs_23018261293.zip)

In the Initialization / Complete Job step, I see the following warnings that are not easily seen in the logs.

Evaluate and set job outputs
Set output 'telemetryScopeJson'
Warning: Skip output 'environmentsMatrixJson' since it may contain secret.
Set output 'environmentCount'
Warning: Skip output 'deploymentEnvironmentsJson' since it may contain secret.
Set output 'generateALDocArtifact'
Set output 'deployALDocArtifact'
Set output 'deliveryTargetsJson'
Set output 'githubRunner'
Set output 'githubRunnerShell'
Set output 'projects'
Warning: Skip output 'projectDependenciesJson' since it may contain secret.
Warning: Skip output 'buildOrderJson' since it may contain secret.
Set output 'workflowDepth'
Cleaning up orphan processes

<img width="509" alt="image" src="https://github.com/microsoft/AL-Go/assets/35507227/a6f2b8c7-b138-42ec-a4c9-9967e6b74962">

**Comment by BMI-Mike** [comment]
It appears that having any secret with "pretty" Azure credentials in GitHub, even secret names not used by AL-Go, will cause CICD to fail.

We recently added a secret related to other projects, and that is what broke CICD.  Using the Troubleshooting workflow was a tremendous help to discover why this was happening.  Our IT staff will follow up on the original #1039 issue.

**Comment by freddydk** [comment]
> It appears that having any secret with "pretty" Azure credentials in GitHub, even secret names not used by AL-Go, will cause CICD to fail.
> 
> We recently added a secret related to other projects, and that is what broke CICD. Using the Troubleshooting workflow was a tremendous help to discover why this was happening. Our IT staff will follow up on the original #1039 issue.

In general, AL-Go projects should only have secrets available to them that they need/use - but yes, the way we retrieve secrets, we are subject to this problem.
