### ISSUE TITLE
Workdlows generates compilation V24 errors even if the V24 errors were fixed 

### ISSUE THREAD

**Issue by ismailhafid1** [microsoft/AL-Go#1059]
after the V24 errors started to show up , we began to correct them , test them , and after that we push them to the main branch. BUT when a workflow runs after the fixes ,it keeps showing the error of V24 even if it is already fixed, 
the first NextMajor/Minor workflow shows the error of V24 (before the fix):
![image](https://github.com/microsoft/AL-Go/assets/143097318/7d792b5b-665c-4675-aab6-0a3c5996493e)

when CI CD workflow runs , to merge the fixes to the main branch we got the following error : 
![image](https://github.com/microsoft/AL-Go/assets/143097318/842288a9-5706-4929-825c-ea323d098e9c)
and it shows only warnings and no signs of errors in compilation process of the workflow : 
![image](https://github.com/microsoft/AL-Go/assets/143097318/57b1fab3-53b9-44cc-b691-eee3a028d179)

after running the next minor/major a second time , we get the same error as the CI CD error above :
![image](https://github.com/microsoft/AL-Go/assets/143097318/4c3acd4f-7fe5-4bde-8bfc-0c42f0c2ccb9)

with this issue i can't run my CI CDs to generate an artifact, and that happens with every repository that has V24 errors.
AL GO version : V5.0

**Comment by freddydk** [comment]
These looks like normal errors in your app - can you compile this in VS Code with a BC 24 environment?

**Comment by ismailhafid1** [comment]
it was compiled and I deployed it with vscode as DEV, then I deployed it as PTE and it worked successfully without any errors or warnings,

**Comment by freddydk** [comment]
I think I can see that this happens during install of previous apps.
So, your previous app doesn't work on BC 24 and hence you cannot run upgrade tests.
You can set SkipUpgrade to true in setting to avoid running upgrade tests.
Generally, our recommendation is that these things are fixed during v23 (when running Next Major) to avoid a problem like this.

**Comment by ismailhafid1** [comment]
I m still a little bit confused about this problem , 
the V24 errors are all fixed in the repository and they were tested and deployed in V23+V24(preview) environnements without errors , so basically what i expect from the workflows that generated an error because of V24 is to run , does the checks needed , the errors got fixed and generates a build based on the recent commit that merged to the main branch ,either it was a bug or error in the file no matter which repository we had , if the problem existed and we fixed it it doesn't show up in the next workflow run.
if you can just explain to me a little more about this problem how it can be fixed , why would it need to run the older release of the app when i m generating a new with some fixes ? 
and the skipUpgrade worked thanks !

**Comment by freddydk** [comment]
You are building using v24 today.
The latest released version in your repository is used for upgrade testing - that version does NOT work on v24.
So, when it tries to publish the previous version (the latest released build) - it fails.
AL-Go automatically uses upgrade testing with the latest released bits as explained here: https://github.com/microsoft/AL-Go/blob/main/Workshop/Releasing.md

**Comment by ismailhafid1** [comment]
I understand now  , thanks a lot for the informations .
