### ISSUE TITLE
Customizing Run pipeline for MicrosoftAlgo actions

### ISSUE THREAD

**Issue by nrohinip** [microsoft/AL-Go#1066]
We tried customizing run pipeline actions in the script , which is Microsoft build actions for business central which we are trying to modify and customize it .
While we did the customization(Like commenting the blocks and removing the dependencies) according to the flow and execute it , its breaks In various parts of code and reaches back to MicrosoftAlgohelper scripts which is template written by Microsoft.

Below are Actions we are working on -
[https://github.com/microsoft/AL-Go-PTE/tree/v3.3/.github](https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_AL-2DGo-2DPTE_tree_v3.3_.github&d=DwMGaQ&c=BSDicqBQBDjDI9RkVyTcHQ&r=8NHbXtSL74uuTPeMuMcMdpvr4TH2YuFP5Ms9rK9wt-s&m=qdLZYkIzANY3a9P4vKe4nwD102FCAGrwtWU0ZGm-aCMWYI_ELyfCe6eoPZl6yqlw&s=FJ85LwaKW7TY-zhLLWE_ztOzdhXLBAzoFbScqVt7GgU&e=)
Main CICD pipeline->Algo actions Run pipeline which internally call default scripts written by Microsoft which calls and creates container in the flow.
We are trying to modify the existing code to ignore the Creating container, Resolving dependencies, Installing apps

**Comment by freddydk** [comment]
We do not recommend people modifying AL-Go for personal usage - we want people to always use the latest AL-Go for GitHub.

AL-Go is a tool, which we are evolving to be able to do 100% of the DevOps functionality needed by most partners and you might be able to configure AL-Go to do what you want - or suggest a feature here and collaborate on fixing it.

We have discussed whether we should add customization capabilities and have a prototype - but it hasn't been approved yet.

**Comment by nrohinip** [comment]
Sure , Thanks noted!

**Comment by freddydk** [comment]
This is the PR, which contains the customization capabilities https://github.com/microsoft/AL-Go/pull/853
