### ISSUE TITLE
Repositories use the earliest version of the the dependency instead of the latest version

### ISSUE THREAD

**Issue by ismailhafid1** [microsoft/AL-Go#1069]
i have a lot of repositories that uses another repository as a dependency , so i used appDependencyProbingPaths with the latest version of the release , however instead of getting the latest version of the release , the workflow gets the earliest version of the release , is there any fix for this problem ?
![image](https://github.com/microsoft/AL-Go/assets/143097318/dfbe28b0-ca71-446f-b7c9-4c709d22c0fb)
![image](https://github.com/microsoft/AL-Go/assets/143097318/3fbfcc1a-b2b7-4e4e-b7f0-364470c1a48f)
![image](https://github.com/microsoft/AL-Go/assets/143097318/b09e4cb2-4a4f-42a8-9c3c-bd6626929a1b)

**Comment by ismailhafid1** [comment]
both of the versions got released from the release branch , what i was expecting is the workflow will get the latest version of the release with tag 'latest' but somehow it ignores the tag and ignores all the recent versions and the workflow uses the earliest version of the extension

**Comment by freddydk** [comment]
Could you share the full build log of this problem?

**Comment by ismailhafid1** [comment]
can i send the full build log via email ?

**Comment by ismailhafid1** [comment]
@freddydk  any news about this issue ?

**Comment by ismailhafid1** [comment]
Hello @freddydk , it s been two weeks and we can't find a way to solve this problem , and our workflows don't work because this problem , is there any news or any fix resolve this issue  ?

**Comment by freddydk** [comment]
This documentation in the workshop explains in details how releases are sorted:
https://github.com/microsoft/AL-Go/blob/main/Workshop/Releasing.md

If you go to releases in your repository - the latest release is indeed your v1.0 and not the other releases and the reason for this is that GitHub uses the tag_name (not the name, which can be anything) to sort the releases.
The tag_name needs to be semver and the sorted tag_names are
![image](https://github.com/microsoft/AL-Go/assets/10775043/be8824ce-7235-46f1-ba4f-724b7d3a37c2)

which puts 23.0.0 (v1) on top.

I think it is possible to edit the tag name for a release - but haven't tried.

**Comment by ismailhafid1** [comment]
Thanks for your help
