### ISSUE TITLE
Change version

### ISSUE THREAD

**Issue by MichaelDieringer** [microsoft/AL-Go#1074]
Well, I need to change the ArtifactUrl, currently referring to https://bcartifacts.azureedge.net/sandbox/23.0.12034.13450/dk to version 24.
i prepared our app to 24, and when validating the app against v23, I receive errors like 

Error: AL0185 Codeunit 'No. Series' is missing 
or 
Error: AL0185 ControlAddIn 'BusinessChart' is missing

what am I missing???

**Comment by freddydk** [comment]
https://aka.ms/algosettings#artifact is the setting which controls the artifacts used.
This can be set in .github/AL-Go-Settings.json (for all projects) or .AL-Go/settings,json (for a project) or it can be in settings variables (if you have tried the AL-Go Workshop).

**Comment by MichaelDieringer** [comment]
Many thanks :-) - solved...
