### ISSUE TITLE
Timeouts when downloading Artifacts?

### ISSUE THREAD

**Issue by rbability** [microsoft/AL-Go#1075]
Since around 2 weeks, we are facing problems of CI/CD and NextMajor / NextMinor runs intermittently failing when downloading the platform artifacts. Sometimes if you re-run the Jobs it works, sometimes we have to try multiple times. Today I am able to reproduce it pretty reliably on a Test repo and a self-hosted runner.

I must also add, that despite having a 100Mbit/s connection, downloads from the Artifacts BLOB storages always never go above 30 Mbit/s for us, sometimes only as low as 7 Mbit/s, so downloads can take quite a few minutes to finish.

Also, downloading the artifacts always seem to work, it is just the platform artifacts that we have problems with. But as far as I can see they are around twice the size of the language specific artifacts, and thus should take about twice the time to download.

Environment / further descriptions:
- Self-Hosted runner on Windows Server 2022
- Ran a Update AL-Go System files before doing my tests today, so AL-Go should be on the latest version
- The repo I am testing currently uses AL-Go PTE, but we see the same for AL-Go AppSource Repos
- When downloading the platform artifacts manually by using the version information in the log, I can download them fine with Edge on the same VM where the runner is doing its job. But it takes a while, as mentioned before.

The log looks like this:
![image](https://github.com/microsoft/AL-Go/assets/59822243/fcb40953-336c-4dc5-9702-886d3aa0b442)

I suspect that the download itself is working fine and that we do not have an issue with the BLOB storage, but that the process that triggers the download on the runner side has some kind of timeout that is causing issues for us. But I did not find a Setting for AL-Go yet for that, so I might be wrong.

I did not see any other posts with the same issue, so I think for most people downloading is much quicker than it is for us and thus they do not run into that issue at all.

**Comment by freddydk** [comment]
What is your geographical location?
If you add "artifactDownloadTimeout": 1500 to your settings file - does it work then ?

**Comment by rbability** [comment]
Thank you Freddy, how can you be so quick? :-)

I am sorry that I did not find that parameter. I did CTRL+F the AL-Go Settings page, but could not find it. I hoped that we have something like this, so I am happy I can test it so quickly. I will do a few runs with that parameter to make sure it helps here and that I am not just lucky with my next run. So it will take a bit now for those to get finished.

The runner is hosted in a location in Saxony-Anhalt, (North-East) Germany at the moment. We always had the issue with low bandwidth regarding the artifact downloads and this was also before they moved to a new BLOB storage (that was recently, right?).
When doing the same downloads in another of our locations in Baden-Württemberg, (South) Germany, I can max out a 1Gbit/s connection without a problem. Unfortunately I can not host Servers there ;-)
I suspect it is a thing with the ISP at that Datacenter or a peering issue, but the ISP there was not able to track it down. I bet in Azure all is fine!

**Comment by freddydk** [comment]
The artifactDownloadTimeout is actually not an AL-Go setting - it is a BcContainerHelper setting - but BcContainerHelper settings can also be specified in .github/AL-Go-Settings.json - which is why it works.

**Comment by freddydk** [comment]
Default is 300 seconds for artifacts downloaded from CDN and the double from insider (no CDN).

**Comment by rbability** [comment]
> ...but BcContainerHelper settings can also be specified in .github/AL-Go-Settings.json...

Thank you very much! I will keep that in mind :-)
