### ISSUE TITLE
keyVaultCodesignCertificateName - error

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#1082]
When switching the settings from using 

codeSignCertificateUrlSecretName
codeSignCertificatePasswordSecretName

to using 

keyVaultCodesignCertificateName

I am now getting the following error

```
Installing signing tool version 0.9.1-beta.24123.2 in C:\Users\cfbsadmin\AppData\Local\Temp\SigningTool-305010202
  The tool package could not be restored.
  Tool 'sign' failed to install. This failure may have been caused by:
  
  * You are attempting to install a preview release and did not use the --version option to specify the version.
  * A package by this name was found, but it was not a .NET tool.
  * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
  * You mistyped the name of the tool.
  
```

Would this have to do with wrong permissions to the KeyVault or is this another issue? Any insights would be appreciated.

**Comment by aholstrup1** [comment]
Are you using self-hosted runners? I haven't be able to repro this on a GitHub runner or locally 🤔 

If you're using a self-hosted runner, perhaps you need to add nuget.org as a nuget source 
`dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org`

**Comment by pzentner** [comment]
This might have been it. While we have a few self hosted runners, one didn't have the nuget source setup. And the run that was failing was running on that self hosted runner. We don't have anything right now to test it with, but I'll test again with the next build.

Thanks

**Comment by pzentner** [comment]
I can confirm that it works after adding the nuget source. Thank you
