### ISSUE TITLE
Sync-NAVApp : Table 344 Setup Checklist Line :: The table 'Setup Checklist Line' cannot be located. Removing tables is not allowed unless they  are temporary or are being moved by migration to another app.

### ISSUE THREAD

**Issue by JanakaRDY** [microsoft/AL-Go#1090]
Getting this error when trying to upgrade from BC20 (20.4.44313.44365) to BC22 (22.5.59966.60134).

Sync-NAVApp : Table 344 Setup Checklist Line :: The table 'Setup Checklist Line' cannot be located. Removing tables is not allowed unless they 
are temporary or are being moved by migration to another app.

![image](https://github.com/microsoft/AL-Go/assets/141592851/30e1b4e8-60ef-496d-89a0-162f5f6fedc9)

**Comment by JanakaRDY** [comment]
Hi @freddydk, could you please help me?

**Comment by freddydk** [comment]
What does this have to do with AL-Go for GitHub?

**Comment by freddydk** [comment]
Assuming that you just need a different mode than add though - maybe forcesync or like.

**Comment by JanakaRDY** [comment]
![image](https://github.com/microsoft/AL-Go/assets/141592851/bc752ffe-9a59-4ac0-8b32-b9d1ecd56358)
Changed 0 to Key1in the end of the key and did forcesync to resolve the issue.
