### ISSUE TITLE
Steps in "Publish To Environment" not using custom shell-property from deployment settings

### ISSUE THREAD

**Issue by cegekaJG** [microsoft/AL-Go#1101]
The action "Publish To Environment invokes a few powershell actions with a static definition of the input parameter `shell`, even though most steps pass the value defined in the deployment settings:
https://github.com/microsoft/AL-Go/blob/17311608bf05bcf17459ab94f2120c97a2b024a7/Templates/Per%20Tenant%20Extension/.github/workflows/PublishToEnvironment.yaml#L149-L185
This results in errors on runners missing the correct keyword. Is there a reason why the parameter in the steps "Get Artifacts for deployment" and "Deploy To Power Platform" wasn't updated like the other steps?

**Comment by cegekaJG** [comment]
Bumping this because I need an answer. If it's an oversight, I can create a new PR to fix this, but I need to know if it was left like this on purpose, and how we can fix this if yes.

**Comment by freddydk** [comment]
Sorry, didn't see this.
You are welcome to replace the shell: powershell with the one from the matrix in a PR.
Please note that this needs to be done under Templates/Per Tenant Extension and Templates/AppSource App

Thanks
