### ISSUE TITLE
Build cannot find build artifacts

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#1102]
We get this error consistently on a new repo (migrated from a DevOps repo) 
`Unexpected error when running action. Error Message: Cannot find path 'C:\1\_work\xxx-Services\Noble-Metal-Services\.buildartifacts\Apps' because it does not exist`

I have checked our build server; the path is present up to here: C:\1\_work\xxx-Services\Noble-Metal-Services\Noble-Metal-Services

Any way to know where this is going wrong?  Full log attached below.

[logs_24839909455.zip](https://github.com/user-attachments/files/15838298/logs_24839909455.zip)

**Comment by freddydk** [comment]
It looks like AL-Go doesn't locate your apps?
![image](https://github.com/microsoft/AL-Go/assets/10775043/39f901be-68e8-47d1-af73-646c67710547)

Which means that nothing is built - and then the sign action fails because it cannot find any files to sign.

**Comment by buzzwick** [comment]
It was not locating the apps, but that was due to us not having straightened out the path references in Settings and ALGOORGSETTINGS. A separate issue thread here around those topics led us to get those aligned. Now the builds appear to complete normally. Thank you.
