### ISSUE TITLE
Create hotfix - No artifacts found for this project error message with Create release workflow

### ISSUE THREAD

**Issue by BennoVendrig** [microsoft/AL-Go#1104]
Hi,
I have successfully created a 1.0.0 release of the main by using the Create release workflow. I want to create a hotfix on the 1.0.0. release so release 1.0.1 will be created. But if I use the Create release workflow for this on the release 1.0.0 branch the error message "No artifacts found for this project" appears. What do I wrong to create a hotfix?

Thanks in advance

**Comment by freddydk** [comment]
Tried this in one of my repos.
Have a releasebranch releases/6.3 - make a change in that branch.
Run CI/CD (in that branch - select branch in github workflow)
![image](https://github.com/microsoft/AL-Go/assets/10775043/c2b27249-7cd6-411e-b260-cee06eeb02e5)

After this - run create release (in that branch);
![image](https://github.com/microsoft/AL-Go/assets/10775043/53fb9427-b5b6-4a21-b893-065fea24d142)

After this - I have a 6.3.2 release:
![image](https://github.com/microsoft/AL-Go/assets/10775043/1c68cb1b-4af9-4f70-b760-69701b34d23c)
