### ISSUE TITLE
Increment Version Number - repoVersion in .github/AL-Go-Settings.json is not updated

### ISSUE THREAD

**Issue by aholstrup1** [microsoft/AL-Go#1105]
**Problem**
If you define the repoVersion in .github/AL-Go-Settings.json it isn't updated when running the Increment Version Number workflow. 

In our case, the would like to keep the repoVersion the same across all Al-Go projects so having repoVersion defined on repo level makes sense for us (even if it is a project setting)

**Comment by freddydk** [comment]
Implementation wise, we should probably update the repoVersion in repo settings AND project settings (if it exists) and we should create repoVersion in project settings if it doesn't exist in repo settings.
We should never create it in repo settings and we shouldn't create it in project settings if it exists in repo settings.

Make sense?

**Comment by aholstrup1** [comment]
I agree. Seems like a good approach :)
