### ISSUE TITLE
Question - Workflow specific setting

### ISSUE THREAD

**Issue by louagej** [microsoft/AL-Go#1107]
Hi,

There is a setting `doNotRunTests` that says 
| Name | Description | Default value |
| :-- | :-- | :-- |
| <a id="doNotRunTests"></a>doNotRunTests | This setting forces the pipeline to NOT run the tests in testFolders. Tests are still being built and published. Note this setting can be set in a **workflow specific settings** file to only apply to that workflow | false |

But how can we add a `workflow specific setting`?

**Comment by freddydk** [comment]
https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md#conditional-settings

**Comment by louagej** [comment]
Hi Freddy,
Thank you for your reply.
Is this not a setting for a specific branch? At least this is how I interpretate the documentation link.
But how can I add a setting for a specific workflow?

**Comment by louagej** [comment]
sorry, did read the documentation to fast... Thank you

**Comment by freddydk** [comment]
Actually - the workflow specific settings file mentioned is not conditional settings - it is more like no. 6 under https://aka.ms/algosettings#where-are-the-settings-located.

Both can be used though.

**Comment by freddydk** [comment]
I will update the docs with some references.
