### ISSUE TITLE
Symbol Dowbnload error when running CICD Action during build process

### ISSUE THREAD

**Issue by Eagle-BC** [microsoft/AL-Go#1123]
Getting the following error 

![image](https://github.com/microsoft/AL-Go/assets/173703174/e7199ea0-f148-43b5-926c-387a9dee037f)

**Comment by freddydk** [comment]
It looks like you are missing the app S4C_Slim4 Connector

**Comment by Eagle-BC** [comment]
I have added the zip file in the dependecy folder and gave the path as suggested by you in installapps, but still faced the same issue... Slim4 connector is a PTE app that we have on our sandbox env....

![image](https://github.com/microsoft/AL-Go/assets/173703174/06ae3171-3405-4bb6-aa09-63186885de68)

**Comment by freddydk** [comment]
Please include the full build log

**Comment by Eagle-BC** [comment]
Run microsoft/AL-Go-Actions/RunPipeline@v5.2
  with:
    shell: powershell
    parentTelemetryScopeJson: 7b[2](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:2)2506172616d657465727[3](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:3)223a7b7d2c22456d697[4](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:4)746564223a66616c73652c22436f7272656c6174696f6e4964223a2266313761366630312d663131622d346238332d393261622d326563306338363335656535222c22506172656e744964223a22222c22416c6c506172616d6574657273223a7b7d2c22546f704964223a2266313761366630312d663131622d346238332d393261622d326563306338363335656535222c224e616d65223a22414c2d476f20776f726b666c6f772072616e3a2043494344222c22537461727454696d65223a225c2f446174652831373139343938373835313736295c2f222c2250726f70657274696573223a7b226576656e744964223a22444f30303931222c226263436f6e7461696e657248656c70657256657273696f6e223a22362e302e3139222c22697341646d696e6973747261746f72223a2254727565222c22737461636b5472616365223a225b5c6e2020496e697454656c656d6574727953636f70652061742054656c656d6574727948656c7065722e7073313a206c696e65203231345c6e202043726561746553636f70652061742054656c656d6574727948656c7065722e70736d313a206c696e652037355c6e2020576f726b666c6f77496e697469616c697a652e70733120617420576f726b666c6f77496e697469616c697a652e7073313a206c696e652033385c6e202036643538646366342d366638642d343935312d386330302d3663363265636266313761302e7073312061742036643538646366342d366638642d343935312d386330302d3663363265636266313761302e7073313a206c696e6520345c6e20205c7530303363536372697074426c6f636b5c7530303365206174205c75303033634e6f2066696c655c75303033655c6e5d222c22414c476f56657273696f6e223a2276352e32222c2274797065223a22417070536f7572636520417070222c2274656d706c61746555726c223a2268747470733a2f2f6769746875622e636f6d2f6d6963726f736f66742f414c2d476f2d417070536f75726365406d61696e222c227265706f7369746f7279223a224561676c652d42432f4561676c652d4d47222c2272756e417474656d7074223a2231222c2272756e4e756d626572223a2239222c2272756e4964223a2239363938353237313133227d2c224576656e744964223a22444f30303931227d
    artifact: https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.2.20227.2131[5](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:5)/gb
    project: .
    buildMode: Default
    installAppsJson: []
    installTestAppsJson: []
    token: ***
  env:
    ALGoOrgSettings: 
    ALGoRepoSettings: 
    artifact: https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.2.20227.21315/gb
    keyVaultCodesignCertificateName: 
    generateDependencyArtifact: False
    doNotRunTests: False
    doNotSignApps: False
    useCompilerFolder: False
    Settings: {"keyVaultCertificateUrlSecretName":"","microsoftTelemetryConnectionString":"InstrumentationKey=84bd9223-[6](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:6)7d4-4378-8590-9e4a46023be2;IngestionEndpoint=https://westeurope-1.in.applicationinsights.azure.com/","type":"AppSource App","sendExtendedTelemetryToMicrosoft":false,"appBuild":9,"installTestApps":[],"versioningStrategy":0,"installApps":[],"installTestLibraries":false,"runNumberOffset":0,"codeSignCertificatePasswordSecretName":"codeSignCertificatePassword","vsixFile":"","country":"gb","alDoc":{"continuousDeployment":false,"deployToGitHubPages":true,"maxReleases":3,"groupByProject":true,"includeProjects":[],"excludeProjects":[],"header":"Documentation for {REPOSITORY} {VERSION}","footer":"Documentation for \u003ca href=\"https://github.com/{REPOSITORY}\"\u003e{REPOSITORY}\u003c/a\u003e made with \u003ca href=\"https://aka.ms/AL-Go\"\u003eAL-Go for GitHub\u003c/a\u003e, \u003ca href=\"https://go.microsoft.com/fwlink/?linkid=224[7](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:7)728\"\u003eALDoc\u003c/a\u003e and \u003ca href=\"https://dotnet.github.io/docfx\"\u003eDocFx\u003c/a\u003e","defaultIndexMD":"## Reference documentation\\n\\nThis is the generated reference documentation for [{REPOSITORY}](https://github.com/{REPOSITORY}).\\n\\nYou can use the navigation bar at the top and the table of contents to the left to navigate your documentation.\\n\\nYou can change this content by creating/editing the **{INDEXTEMPLATERELATIVEPATH}** file in your repository or use the alDoc:defaultIndexMD setting in your repository settings file (.github/AL-Go-Settings.json)\\n\\n{RELEASENOTES}","defaultReleaseMD":"## Release reference documentation\\n\\nThis is the generated reference documentation for [{REPOSITORY}](https://github.com/{REPOSITORY}).\\n\\nYou can use the navigation bar at the top and the table of contents to the left to navigate your documentation.\\n\\nYou can change this content by creating/editing the **{INDEXTEMPLATERELATIVEPATH}** file in your repository or use the alDoc:defaultReleaseMD setting in your repository settings file (.github/AL-Go-Settings.json)\\n\\n{RELEASENOTES}"},"templateSha":"","partnerTelemetryConnectionString":"","doNotRunTests":false,"enableCodeAnalyzersOnTestApps":false,"runs-on":"windows-latest","generateDependencyArtifact":false,"excludeEnvironments":[],"keyVaultCertificatePasswordSecretName":"","rulesetFile":"","licenseFileUrlSecretName":"licenseFileUrl","enableExternalRulesets":false,"memoryLimit":"","keyVaultClientIdSecretName":"","testFolders":[],"githubRunner":"windows-latest","doNotBuildTests":false,"environments":[],"companyName":"","assignPremiumPlan":false,"artifact":"","ghTokenWorkflowSecretName":"ghTokenWorkflow","enableTaskScheduler":false,"enableCodeCop":false,"repoVersion":"1.0","doNotPublishApps":false,"unusedALGoSystemFiles":[],"githubRunnerShell":"powershell","appFolders":[],"cacheKeepDays":3,"bcptTestFolders":[],"updateDependencies":false,"cacheImageName":"my","powerPlatformSolutionFolder":"","treatTestFailuresAsWarnings":false,"additionalCountries":[],"enableUICop":false,"customCodeCops":[],"appDependencies":[],"doNotRunBcptTests":false,"skipUpgrade":false,"appDependencyProbingPaths":[],"useCompilerFolder":false,"installTestFramework":false,"keyVaultCodesignCertificateName":"","keyVaultName":"","obsoleteTagMinAllowedMajorMinor":"","applicationDependency":"1[8](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:8).0.0.0","applicationInsightsConnectionStringSecretName":"applicationInsightsConnectionString","shell":"powershell","deliverToAppSource":{"mainAppFolder":"","productId":"","includeDependencies":[],"continuousDelivery":false},"failOn":"error","templateUrl":"https://github.com/microsoft/AL-Go-AppSource@main","projects":[],"projectName":".","testDependencies":[],"appRevision":0,"codeSignCertificateUrlSecretName":"codeSignCertificateUrl","configPackages":[],"useProjectDependencies":false,"appSourceCopMandatoryAffixes":["\u003caffix\u003e"],"buildModes":[],"templateBranch":"","installPerformanceToolkit":false,"pullRequestTrigger":"pull_request_target","doNotSignApps":false,"repoName":"Eagle-MG","fullBuildPatterns":[],"alwaysBuildAllProjects":false,"installOnlyReferencedApps":true,"installTestRunner":false,"adminCenterApiCredentialsSecretName":"adminCenterApiCredentials"}
    BcContainerHelperPath: C:\ProgramData\BcContainerHelper\6.0.1[9](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:9)\BcContainerHelper\BcContainerHelper.ps1
    artifactCacheKey: 
    Secrets: {"licenseFileUrl":"","codeSignCertificateUrl":"","*codeSignCertificatePassword":"","gitHubPackagesContext":"","applicationInsightsConnectionString":""}
    BuildMode: Default
Run $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
Import from C:\ProgramData\BcContainerHelper\6.0.19\BcContainerHelper\BcContainerHelper.ps1
BcContainerHelper version 6.0.19
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on Windows, PowerShell 5.1.20348.2400
use settings and secrets
Analyzing repository
  Checking type
  Checking appFolders, testFolders and bcptTestFolders
  Application Dependency 24.0.0.0
  Checking artifact setting for project
  Downloading artifacts from https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.2.20227.21315/gb
  Downloading artifact /sandbox/24.2.20227.21315/gb
  Downloading C:\Users\runneradmin\AppData\Local\Temp\6300dcb8-0b1e-4e37-b482-311dc6fe6781.zip
  Unpacking artifact to tmp folder using 7zip
  Downloading platform artifact /sandbox/24.2.20227.21315/platform
  Downloading C:\Users\runneradmin\AppData\Local\Temp\cb8882be-1739-488a-a0eb-3d6fefd72203.zip
  Unpacking artifact to tmp folder using 7zip
  Downloading Prerequisite Components
  Downloading c:\bcartifacts.cache\sandbox\24.2.20227.21315\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
  Downloading c:\bcartifacts.cache\sandbox\24.2.20227.21315\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
  Updating app- and test Dependencies
  Analyzing Test App Dependencies
No performance test apps found in bcptTestFolders in .AL-Go\settings.json
Warning: No test apps found in testFolders in .AL-Go\settings.json
Checking appDependencyProbingPaths
Locating previous release
  Getting the latest release from https://api.github.com/repos/Eagle-BC/Eagle-MG/releases/latest - branch main
  Analyzing releases https://api.github.com/repos/Eagle-BC/Eagle-MG/releases
  Warning: No previous release found
Invoke Run-AlPipeline with buildmode Default
Parameters
    _____                               _
   |  __ \                             | |
   | |__) |_ _ _ __ __ _ _ __ ___   ___| |_ ___ _ __ ___
   |  ___/ _` | '__/ _` | '_ ` _ \ / _ \ __/ _ \ '__/ __|
   | |  | (_| | | | (_| | | | | | |  __/ |_  __/ |  \__ \
   |_|   \__,_|_|  \__,_|_| |_| |_|\___|\__\___|_|  |___/
  
  Pipeline name                   CI/CD
  Container name                  bc9698527113
  Image name                      
  ArtifactUrl                     https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.2.20227.21315/gb
  BcAuthContext                   Not Specified
  Environment                     
  ReUseContainer                  False
  KeepContainer                   False
  useCompilerFolder               False
  artifactCachePath               
  useDevEndpoint                  False
  Auth                            UserPassword
  CompanyName                     
  MemoryLimit                     8G
  FailOn                          error
  TreatTestFailuresAsWarnings     False
  Enable Task Scheduler           False
  Assign Premium Plan             False
  Install Test Runner             False
  Install Test Framework          False
  Install Test Libraries          False
  Install Perf. Toolkit           False
  InstallOnlyReferencedApps       True
  generateDependencyArtifact      True
  CopySymbolsFromContainer        False
  enableCodeCop                   False
  enableAppSourceCop              True
  enableUICop                     False
  enablePerTenantExtensionCop     False
  enableCodeAnalyzersOnTestApps   False
  doNotPerformUpgrade             False
  doNotPublishApps                False
  uninstallRemovedApps            True
  escapeFromCops                  False
  doNotBuildTests                 False
  doNotRunTests                   True
  doNotRunBcptTests               True
  useDefaultAppSourceRuleSet      False
  rulesetFile                     
  generateErrorLog                False
  enableExternalRulesets          False
  azureDevOps                     False
  gitLab                          False
  gitHubActions                   True
  vsixFile                        
  License file                    Not specified
  CodeSignCertPfxFile             Not specified
  CodeSignCertPfxPassword         Not specified
  CodeSignCertIsSelfSigned        False
  KeyVaultCertPfxFile             Not specified
  KeyVaultCertPfxPassword         Not specified
  KeyVaultClientId                
  BuildOutputFile                 D:\a\Eagle-MG\Eagle-MG\BuildOutput.txt
  ContainerEventLogFile           D:\a\Eagle-MG\Eagle-MG\ContainerEventLog.evtx
  TestResultsFile                 D:\a\Eagle-MG\Eagle-MG\TestResults.xml
  BcptTestResultsFile             D:\a\Eagle-MG\Eagle-MG\bcptTestResults.json
  TestResultsFormat               JUnit
  AdditionalCountries             
  PackagesFolder                  D:\a\Eagle-MG\Eagle-MG\.packages
  OutputFolder                    D:\a\Eagle-MG\Eagle-MG\.output
  BuildArtifactFolder             D:\a\Eagle-MG\Eagle-MG\.buildartifacts
  CreateRuntimePackages           False
  AppVersion                      
  AppBuild                        9
  AppRevision                     0
  SourceRepositoryUrl             https://github.com/Eagle-BC/Eagle-MG
  SourceCommit                    ec8c8254d47bab5ae4a36bfe0002ee3717cec546
  BuildBy                         AL-Go for GitHub,v5.2
  BuildUrl                        https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113
  Mandatory Affixes               <affix>
  Supported Countries             
  ObsoleteTagMinAllowedMajorMinor 
  Install Apps
  - None
  Install Test Apps
  - None
  Previous Apps
  - None
  Application folders
  - D:\a\Eagle-MG\Eagle-MG\MastergolfBaseExt
  Test application folders
  - None
  BCPT Test application folders
  - None
  BCPT Test suites
  - None
  Custom CodeCops
  - None
  RemoveBcContainer override
  
                  Param([Hashtable]$parameters)
                  Remove-BcContainerSession -containerName $parameters.ContainerName -killPsSessionProcess
                  Remove-BcContainer @parameters
              
Pulling generic image
  
    _____       _ _ _                                          _        _
   |  __ \     | | (_)                                        (_)      (_)
   | |__) |   _| | |_ _ __   __ _    __ _  ___ _ __   ___ _ __ _  ___   _ _ __ ___   __ _  __ _  ___
   |  ___/ | | | | | | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '__| |/ __| | | '_ ` _ \ / _` |/ _` |/ _ \
   | |   | |_| | | | | | | | (_| | | (_| |  __/ | | |  __/ |  | | (__  | | | | | | | (_| | (_| |  __/
   |_|    \__,_|_|_|_|_| |_|\__, |  \__, |\___|_| |_|\___|_|  |_|\___| |_|_| |_| |_|\__,_|\__, |\___|
                             __/ |   __/ |                                                 __/ |
                            |___/   |___/                                                 |___/
  
  Pulling mcr.microsoft.com/businesscentral:ltsc2022
  
  Pulling generic image took 5 seconds
Creating container
  
     _____                _   _                               _        _
    / ____|              | | (_)                             | |      (_)
   | |     _ __ ___  __ _| |_ _ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __
   | |    | '__/ _ \/ _` | __| | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
   | |____| | |  __/ (_| | |_| | | | | (_| | | (__ (_) | | | | |_ (_| | | | | |  __/ |
    \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|
                                       __/ |
                                      |___/
  
  Creaing docker container
  BcContainerHelper is version 6.0.19
  BcContainerHelper is running as administrator
  HyperV is Enabled
  Host is Microsoft Windows Server 2022 Datacenter - [10](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:10).0.20348.2527
  UsePsSession is True
  UsePwshForBc24 is True
  UseWinRmSession is allow
  UseSslForWinRmSession is True
  Docker Client Version is 26.1.3
  Docker Server Version is 26.1.3
  Removing Desktop shortcuts
  Fetching all docker images
  Fetching all docker volumes
  Using image mcr.microsoft.com/businesscentral:ltsc2022
  Creating Container bc9698527[11](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:11)3
  Style: sandbox
  Multitenant: Yes
  Version: 24.2.20227.21315
  Platform: 24.0.2[12](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:12)77.0
  Generic Tag: 1.0.2.36
  Container OS Version: 10.0.20348.2527 (ltsc2022)
  Host OS Version: 10.0.20348.2527 (ltsc2022)
  Using process isolation
  Using locale en-GB
  Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
  Additional Parameters:
  --volume "D:\a\Eagle-MG\Eagle-MG\:c:\sources"
  --expose 5986
  --env customNavSettings=EnableTaskScheduler=False
  Files in C:\ProgramData\BcContainerHelper\Extensions\bc96985271[13](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:13)\my:
  - AdditionalOutput.ps1
  - AdditionalSetup.ps1
  - HelperFunctions.ps1
  - MainLoop.ps1
  - SetupVariables.ps1
  - updatehosts.ps1
  Creating container bc9698527113 from image mcr.microsoft.com/businesscentral:ltsc2022
  787f48efd45013d1af6a61ead858fa685645c471de580d46d1a16bd93ee2cbbc
  Waiting for container bc9698527113 to be ready
  Using artifactUrl https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.2.20227.21315/gb
  Using installer from C:\Run\240
  Installing Business Central: multitenant=True, installOnly=False, filesOnly=False, includeTestToolkit=False, includeTestLibrariesOnly=False, includeTestFrameworkOnly=False, includePerformanceToolkit=False, appArtifactPath=c:\dl\sandbox\24.2.20227.21315\gb, platformArtifactPath=c:\dl\sandbox\24.2.20227.21315\platform, databasePath=c:\dl\sandbox\24.2.20227.21315\gb\BusinessCentral-GB.bak, licenseFilePath=c:\dl\sandbox\24.2.20227.21315\gb\Cronus.bclicense, rebootContainer=True
  Installing from artifacts
  Starting Local SQL Server
  Starting Internet Information Server
  Copying Service Tier Files
  c:\dl\sandbox\24.2.20227.21315\platform\ServiceTier\Program Files
  c:\dl\sandbox\24.2.20227.21315\platform\ServiceTier\System64Folder
  Copying Web Client Files
  c:\dl\sandbox\24.2.20227.21315\platform\WebClient\Microsoft Dynamics NAV
  Copying ModernDev Files
  c:\dl\sandbox\24.2.20227.21315\platform
  c:\dl\sandbox\24.2.20227.21315\platform\ModernDev\program files\Microsoft Dynamics NAV
  Copying additional files
  Copying ConfigurationPackages
  C:\dl\sandbox\24.2.20227.21315\gb\ConfigurationPackages
  Copying Test Assemblies
  C:\dl\sandbox\24.2.20227.21315\platform\Test Assemblies
  Copying Extensions
  C:\dl\sandbox\24.2.20227.21315\gb\Extensions
  Copying Applications
  C:\dl\sandbox\24.2.20227.21315\platform\Applications
  Copying Applications.GB
  C:\dl\sandbox\24.2.20227.21315\gb\Applications.GB
  Copying dependencies
  Importing PowerShell Modules
  Restoring CRONUS Demo Database
  Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
  Exporting Application to CRONUS
  Removing Application from tenant
  Modifying Business Central Service Tier Config File for Docker
  Creating Business Central Service Tier
  Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
  Starting Business Central Service Tier
  Importing license file
  Copying Database on localhost\SQLEXPRESS from tenant to default
  Taking database tenant offline
  Copying database files
  Attaching files as new Database default
  Putting database tenant back online
  Mounting tenant database
  Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
  Sync'ing Tenant
  Tenant is Operational
  Stopping Business Central Service Tier
  Installation took 246 seconds
  Installation complete
  Initializing...
  Setting host.containerhelper.internal to 172.21.[14](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:14)4.1 in container hosts file
  Starting Container
  Hostname is bc9698527113
  PublicDnsName is bc9698527113
  Using NavUserPassword Authentication
  Creating Self Signed Certificate
  Self Signed Certificate Thumbprint 8793A5A3DB3FDF[15](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:15)92B81D9B18E2BE3B5ECF2EFC
  DNS identity bc9698527113
  Modifying Service Tier Config File with Instance Specific Settings
  Modifying Service Tier Config File with settings from environment variable
  Setting EnableTaskScheduler to False
  Starting Service Tier
  Registering event sources
  Creating DotNetCore Web Server Instance
  Using application pool name: BC
  Using default container name: NavWebApplicationContainer
  Copy files to WWW root C:\inetpub\wwwroot\BC
  Create the application pool BC
  Create website: NavWebApplicationContainer without SSL
  Update configuration: navsettings.json
  Done Configuring Web Client
  Enabling Financials User Experience
  Dismounting Tenant
  Mounting Tenant
  Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
  Sync'ing Tenant
  Tenant is Operational
  Creating http download site
  Setting SA Password and enabling SA
  Creating admin as SQL User and add to sysadmin
  Creating SUPER user
  Enable PSRemoting and setup user for winrm
  Creating self-signed certificate for winrm
  Container IP Address: 172.21.150.124
  Container Hostname  : bc9698527113
  Container Dns Name  : bc9698527113
  Web Client          : http://bc9698527113/BC/?tenant=default
  Dev. Server         : http://bc9698527113
  Dev. ServerInstance : BC
  Dev. Server Tenant  : default
  Setting bc9698527113 to 172.21.150.124 in host hosts file
  Setting bc9698527113-default to 172.21.150.124 in host hosts file
  Setting bc9698527113-default to 172.21.150.124 in container hosts file
  
  Files:
  http://bc9698527113:8080/ALLanguage.vsix
  
  Container Total Physical Memory is 8.0Gb
  Container Free Physical Memory is 2.9Gb
  
  Initialization took 66 seconds
  Ready for connections!
  Reading CustomSettings.config from bc9698527113
  Creating Desktop Shortcuts for bc9698527113
  Cleanup old dotnet core assemblies
  Container bc9698527113 successfully created
  
  Use:
  Get-BcContainerEventLog -containerName bc9698527113 to retrieve a snapshot of the event log from the container
  Get-BcContainerDebugInfo -containerName bc9698527113 to get debug information about the container
  Enter-BcContainer -containerName bc9698527113 to open a PowerShell prompt inside the container
  Remove-BcContainer -containerName bc9698527113 to remove the container again
  docker logs bc9698527113 to retrieve information about URL's again
  
  Creating container took 346 seconds
Resolving dependencies
  
   _____                _       _                   _                           _                 _
  |  __ \              | |     (_)                 | |                         | |               (_)
  | |__) |___ ___  ___ | |_   ___ _ __   __ _    __| | ___ _ __   ___ _ __   __| | ___ _ __   ___ _  ___ ___
  |  _  // _ \ __|/ _ \| \ \ / / | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '_ \ / _` |/ _ \ '_ \ / __| |/ _ \ __|
  | | \ \  __\__ \ (_) | |\ V /| | | | | (_| | | (_| |  __/ |_) |  __/ | | | (_| |  __/ | | | (__| |  __\__ \
  |_|  \_\___|___/\___/|_| \_/ |_|_| |_|\__, |  \__,_|\___| .__/ \___|_| |_|\__,_|\___|_| |_|\___|_|\___|___/
                                         __/ |            | |
                                        |___/             |_|
  
  Sorted App folders
  - D:\a\Eagle-MG\Eagle-MG\MastergolfBaseExt
  External dependencies
  - 47f00c3c-f614-4178-8ba0-448d12a9a072:S4C_Slim4 Connector_18.0.0.0.app
  - 10cb69d9-bc8a-4d27-970a-9e110e9db2a5:Microsoft_T_Exclude_APIV2__21.0.0.0.app
  - 437dbf0e-84ff-417a-965d-ed2bb9650972:Microsoft_Base Application_24.0.0.0.app
  - 63ca2fa4-4f03-4f2b-a480-172fef340d3f:Microsoft_System Application_24.0.0.0.app
  Sorted TestApp folders
  - None
Compiling apps
  
     _____                      _ _ _
    / ____|                    (_) (_)
   | |     ___  _ __ ___  _ __  _| |_ _ __   __ _    __ _ _ __  _ __  ___
   | |    / _ \| '_ ` _ \| '_ \| | | | '_ \ / _` |  / _` | '_ \| '_ \/ __|
   | |____ (_) | | | | | | |_) | | | | | | | (_| | | (_| | |_) | |_) \__ \
    \_____\___/|_| |_| |_| .__/|_|_|_|_| |_|\__, |  \__,_| .__/| .__/|___/
                         | |                 __/ |       | |   | |
                         |_|                |___/        |_|   |_|
  
  Using Version 1.0.9.0
  Copying dependencies from D:\a\Eagle-MG\Eagle-MG\.buildartifacts\Dependencies to D:\a\Eagle-MG\Eagle-MG\.packages
  Creating AppSourceCop.json for validation
  AppSourceCop.json content:
  {
      "mandatoryAffixes":  [
                               "\u003caffix\u003e"
                           ]
  }
  
  Compiling D:\a\Eagle-MG\Eagle-MG\MastergolfBaseExt
  Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\240\Service to assemblyProbingPath
  Removing dotnet Framework Assemblies
  Using Symbols Folder: D:\a\Eagle-MG\Eagle-MG\.packages
  Processing dependency Microsoft_Application_24.0.0.0 ()
  Downloading symbols: Microsoft_Application_24.2.20227.21315.app
  Url : http://172.21.150.124:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=24.0.0.0&tenant=default
  Adding dependency to System Application from Microsoft
  Adding dependency to Business Foundation from Microsoft
  Adding dependency to Base Application from Microsoft
  Processing dependency Microsoft_System_1.0.0.0 ()
  Downloading symbols: Microsoft_System_24.0.21277.0.app
  Url : http://172.21.150.124:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=1.0.0.0&tenant=default
  Processing dependency S4C_Slim4 Connector_18.0.0.0 (47f00c3c-f614-4178-8ba0-448d12a9a072)
  Downloading symbols: S4C_Slim4 Connector_18.0.0.0.app
  Url : http://172.21.150.124:7049/BC/dev/packages?appId=47f00c3c-f614-4178-8ba0-448d12a9a072&versionText=18.0.0.0&tenant=default
  ERROR Exception calling "GetResult" with "0" argument(s): "Response status code does not indicate success: 404 (Not Found)."
  Compile-AppInBcContainer Telemetry Correlation Id: c8025a09-4107-4542-b4c5-8f4e000f955c
Removing container
  Get Event Log from container
  Getting event log for bc9698527113
  Removing Session bc9698527113
  Removing container bc9698527113
  Removing entries from hosts
  Removing bc9698527113 from container hosts file
  Removing bc9698527113-* from container hosts file
  Removing Desktop shortcuts
  Removing C:\ProgramData\BcContainerHelper\Extensions\bc9698527113
Run-AlPipeline Telemetry Correlation Id: 61b1ec8c-09a6-42b3-91e7-59cb66714ccc
AL-Go action ran: RunPipeline Telemetry Correlation Id: 9dec1a1e-437a-4822-bbad-fdf4b798261c
Error: Unexpected error when running action. Error Message: Exception calling "GetResult" with "0" argument(s): "Response status code does not indicate success: 404 (Not Found)." Response status code does not indicate success: 404 (Not Found)., StackTrace: at Compile-AppInBcContainer, C:\ProgramData\BcContainerHelper\6.0.19\BcContainerHelper\AppHandling\Compile-AppInNavContainer.ps1: line 497 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.19\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 8[16](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:16) <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.19\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line [19](https://github.com/Eagle-BC/Eagle-MG/actions/runs/9698527113/job/26765335718#step:8:19)63 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.19\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1487 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.19\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1480 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.19\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 947 <- at Run-AlPipeline, C:\ProgramData\BcContainerHelper\6.0.19\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 909 <- at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v5.2\RunPipeline\RunPipeline.ps1: line 361 <- at <ScriptBlock>, D:\a\_temp\be388010-ae0c-4cc8-b675-f429dd299903.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
Error: Process completed with exit code 1.

**Comment by Eagle-BC** [comment]
[Uploading 0_Initialization.txt…]()

**Comment by Eagle-BC** [comment]
[2_Build . (Default) _ . (Default).txt](https://github.com/user-attachments/files/16024769/2_Build.Default._.Default.txt)
[6_PostProcess.txt](https://github.com/user-attachments/files/16024770/6_PostProcess.txt)

**Comment by freddydk** [comment]
If I had the full log, I might have been able to see what was wrong, but I can see that the log says:
![image](https://github.com/microsoft/AL-Go/assets/10775043/b371e2f7-332a-421d-8d0f-b872e5347be1)

Meaning that you somehow have the installApps in the wrong location - or there is something wrong with your settings file.
Unfortunately I cannot see more

**Comment by Eagle-BC** [comment]
I pasted the log files, Are there any other log files....?

**Comment by freddydk** [comment]
I got the build process and the post process, I am missing the initialization job and if any other jobs succeeded.

**Comment by Eagle-BC** [comment]
I deleted the repository, to start with a fresh one...but now the "Use this Template" for al-go-pte is not coming 

![image](https://github.com/microsoft/AL-Go/assets/173703174/dc28c4ed-184b-4572-ac90-bce2c41ad81f)

**Comment by freddydk** [comment]
GitHub moved it up under the 
![image](https://github.com/microsoft/AL-Go/assets/10775043/61ecd8da-b825-4863-8ead-b40ef3a1b317)

**Comment by Eagle-BC** [comment]
![image](https://github.com/microsoft/AL-Go/assets/173703174/8277fa5d-a9df-4087-b05f-469643008d2e)

**Comment by freddydk** [comment]
New Repository ->
![image](https://github.com/microsoft/AL-Go/assets/10775043/f393b12b-0afc-4607-bbf6-bf33eaa989c6)

**Comment by Eagle-BC** [comment]
![image](https://github.com/microsoft/AL-Go/assets/173703174/73feb75b-69d8-4aed-bf38-551458361ee2)

**Comment by Eagle-BC** [comment]
@freddydk I am not able to move forward.. Please help...

**Comment by freddydk** [comment]
I have added a link to the repository as described here: https://github.com/microsoft/AL-Go/issues/1125

**Comment by Eagle-BC** [comment]
![image](https://github.com/microsoft/AL-Go/assets/173703174/438083e2-6406-4e63-9102-c5ec6595d7e3)

Thank you so much
