### ISSUE TITLE
"Use this template" not possible?

### ISSUE THREAD

**Issue by HazardMK** [microsoft/AL-Go#1125]
Hi,

There was a functionality in GitHub to create a repo from template:
![image](https://github.com/microsoft/AL-Go/assets/8171020/85e8fed1-10c9-4901-bdb2-5821f1177f9b)

Now i could not find it anywhere from: https://github.com/microsoft/AL-Go-PTE
![image](https://github.com/microsoft/AL-Go/assets/8171020/ccfe9ff1-61b7-407e-b10d-c5707206e515)

Am i missing something?

**Comment by freddydk** [comment]
It looks like GitHub removed that button - will checkup on that.
In the meantime, I guess you can select the template when creating a new repository?
![image](https://github.com/microsoft/AL-Go/assets/10775043/fc589106-297d-4de8-b277-d90ed12f1bbc)

**Comment by freddydk** [comment]
I found out that you can use this URL: https://github.com/new?template_name=AL-Go-PTE&template_owner=microsoft

**Comment by freddydk** [comment]
I have also added the Use This Template button to the readme.md

![image](https://github.com/microsoft/AL-Go/assets/10775043/77740843-b278-435b-a6ab-e9cd0c917fa3)

**Comment by HazardMK** [comment]
Thank you @freddydk for quick response!

P.S. looks like a button is still there!!! But you can only see it when splitting the browser window in half on you desktop:
![image](https://github.com/microsoft/AL-Go/assets/8171020/d26f9c4d-02f9-49a1-b17c-5e7eeb4ba20e)

My desktop resolution 1920x1080. But you are right, it's something only GitHub related, not AL-GO in any way.

**Comment by freddydk** [comment]
Thanks for the info.

And... - we added an emergency button ourselves:-)
