### ISSUE TITLE
Initial commit failing after clicking on - Create new app ( AL-GO  Template - PTE)

### ISSUE THREAD

**Issue by Eagle-BC** [microsoft/AL-Go#1128]
Hi,

After I created a new Repository from AL-GO-PTE template, I tried to create a new app by going to **-Actions-Create new App**, but the initial commit is always failing

![image](https://github.com/microsoft/AL-Go/assets/173703174/95f73a54-5783-40b9-9da4-4e9a78c5f532)

There is no log files for this..I am just getting this :

![image](https://github.com/microsoft/AL-Go/assets/173703174/d2ff1c76-0d0e-43fe-821f-7f20b29d6fba)

![image](https://github.com/microsoft/AL-Go/assets/173703174/97e1e49f-661d-49a9-a477-e172b2b1f6f2)

**Comment by freddydk** [comment]
Is the repository empty?
Then make it public - and allow me to see what went wrong

**Comment by freddydk** [comment]
This is a public repo, where i added an empty app:

https://github.com/freddydk/mypte1

Seems to work fine.
The add an app failed because I had allow workflows to create pull requests unchecked - then I created the PR manually

**Comment by Eagle-BC** [comment]
I have made the repo public

**Comment by Eagle-BC** [comment]
https://github.com/Eagle-BC/MastersGolf-BC

**Comment by Eagle-BC** [comment]
I think it is failing in private repo 

![image](https://github.com/microsoft/AL-Go/assets/173703174/2c5ef68a-f53f-4c4b-a562-99b3743aefc4)

**Comment by freddydk** [comment]
On the workflow summary, you can see the reason (under annotations)

![image](https://github.com/microsoft/AL-Go/assets/10775043/e92c9eb6-fd5a-487d-a7bf-4a05654e9d96)

Note that public repositories are free - for private repositories, there is a spending limit.
If you are running through the workshop and learning - you should use public.

**Comment by Eagle-BC** [comment]
@freddydk I am crying now ...all of this and the problem was this..........

Thank you so much for prompt reply..appreciate it
