### ISSUE TITLE
ContinuousDeployment = false is ignored in DeployToXXX

### ISSUE THREAD

**Issue by dksander** [microsoft/AL-Go#1133]
Hi,
When I read the documentation for Basic Repo settings: https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md#basic-repository-settings and specific the info about "DeployTo<environmentname>"
"ContinuousDeployment = true if this environment should be used for continuous deployment, else false."
I would expect that the following setup would continuous deploy to my TEST enviroment, while I would manuel have to deploy to the PROD enviroment:
`
{
  "type": "PTE",
  "templateUrl": "https://github.com/microsoft/AL-Go-PTE@main",
  "DeployToPROD": {
    "EnvironmentType": "SaaS",
    "EnvironmentName": "Production",
    "Branches": [
      "main"
    ],
    "SyncMode": "Add",
    "continuousDeployment": "false"
  },
  "DeployToTEST": {
    "EnvironmentType": "SaaS",
    "EnvironmentName": "Sandbox",
    "Branches": [
      "TESTING"
    ],
    "continuousDeployment": "true"
  }
}
`

But that is not the case the, "continuousDeployment": "false" will act just link "continuousDeployment": "true", and the fix is not to include continuousDeployment tag.

I do not know if this is by design or an error, but if it is the case, then perhaps the documentation could be updated?

**Comment by freddydk** [comment]
The continuousDeployment property is a boolean - it looks like you specify it as a string.
Remove the quotes, and it should work.

**Comment by freddydk** [comment]
BTW - the same applies to "true" - should be true.

**Comment by dksander** [comment]
Damn didn't catch that, but you are completely right.
It was fixed when removed **"**
