### ISSUE TITLE
[Bug]: Custom Deploy.ps1 is not used

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/AL-Go#1143]
### AL-Go version

5.2

### Describe the issue

I want to use the `buildModes` to deploy a different version to sandboxes than to AppSource, for licensing purposes.
The only way I found to achieve this is to create a modified deploy.ps1 script like described here:

https://github.com/microsoft/AL-Go/blob/12f2a5618d20a5dd9043db1ed1a56384c840db57/Scenarios/settings.md?plain=1#L261

![image](https://github.com/user-attachments/assets/bbff6ea5-e1c9-43ab-a601-e812478f41c1)

I did change those two parts:
![image](https://github.com/user-attachments/assets/39223b63-5772-4f06-9e2e-d1ce63a1ab56)

but still logs the default message and used the main apps:
![image](https://github.com/user-attachments/assets/6fe84242-58b8-4b90-9a90-f45717b52cdd)

Is there anything I am missing or I can check to resolve this?

### Expected behavior

Custom Deploy.ps1 should be used if put into .github folder

### Steps to reproduce

create a custom Deploy.ps1 file, check the log output

**Comment by freddydk** [comment]
Not sure buildModes should be used for this, @mazhelez do you know?

On the actual question - this is an error in the documentation - we support `DeployTo<environmentType>.ps1` - we don't actually support a complete override of all.

**Comment by mazhelez** [comment]
In some cases, it does make sense to deploy the artifacts from the non-default build mode, as in this particular scenario.

Deploy action, however, seems to be wired to use the `-Apps` artifacts (from the _default_ build mode). https://github.com/microsoft/AL-Go/blob/12f2a5618d20a5dd9043db1ed1a56384c840db57/Actions/Deploy/Deploy.ps1#L46

However, in your custom script you can still query for other artifacts (the way you already do), so I believe if you fix your Deploy.ps1 to be `.github/DeployTo<environmentType>.ps1`, then it should work.

**Comment by StefanMaron** [comment]
@mazhelez 
After I changed the name to `DeployToSandbox.ps1` and added `"EnvironmentType": "Sandbox",` to my deploy configuration, it seems to pick up the script now.

But why does this have to be so complicated? Now its failing because it expect a different parameter configuration than the original `Deploy.ps1`

@freddydk 
If the BuildModes are not meant to be used in deployment or submission to appsource, what is the usecase of them?

**Comment by freddydk** [comment]
I think buildModes was introduced for something different, but it might make sense to add a field "buildMode" to the `DeployTo<env>` setting, this would greatly simplify this scenario I guess and make the buildModes more useful.

**Comment by StefanMaron** [comment]
@freddydk This would solve this issue for me 100%

**Comment by freddydk** [comment]
Shipped in preview
