### ISSUE TITLE
[Bug]: Error when trying to create an Azure Build Agent (https://aka.ms/getbuildagent)

### ISSUE THREAD

**Issue by richardsykora** [microsoft/AL-Go#1144]
### AL-Go version

current version

### Describe the issue

Hi, 
i tried to create an azure build agent via https://aka.ms/getbuildagent and getting this message:

![image](https://github.com/user-attachments/assets/33f69f10-7598-480f-9bb2-830a1cd736aa)

### Expected behavior

to create an azure agent

### Steps to reproduce

browse to: https://aka.ms/getbuildagent

**Comment by freddydk** [comment]
This was a redirection error - fixed now.
