### ISSUE TITLE
[Question]: Updated AL-Go System Files

### ISSUE THREAD

**Issue by Marhoon** [microsoft/AL-Go#1149]
### Question

I am getting following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/Show

Also 
CheckForUpdates There are updates for your AL-Go system, run 'Update AL-Go System Files' workflow to download the latest version of AL-Go.

I keep running the workflow action to update the AL-Go System, but still the warning coming every time

Also i am getting this warning.

CheckForUpdates The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by freddydk** [comment]
Assuming you found out that running Update AL-Go System Files will update your workflows to use the new node.js versions and subsequent runs will no longer show these warnings (after merging the PR create by update)
