### ISSUE TITLE
[Question]: Naming of Nuget Packages in AL-Go 

### ISSUE THREAD

**Issue by AlexanderRichter** [microsoft/AL-Go#1153]
### Question

I am wondering why the nuget Packages created by AL-Go are "still" following the Naming Convention **AL-Go-AppID**

Wouldnt it be more consistent if the Naming of the Nuget Package itself would be according to  the scheme **Publisher.Name[Tag].AppID** shown on TechDays?

**Comment by freddydk** [comment]
NuGet feature is still work in progress in AL-Go for GitHub - hoping to complete this in August.

**Comment by AlexanderRichter** [comment]
cool, thanks for providing timeline on this.
