### ISSUE TITLE
[Bug]: Gertting secrets from Azure key vault fails in Preview

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/AL-Go#1164]
### AL-Go version

preview

### Describe the issue

As soon as I switched to preview, the Initialize step fails when it tries to read secrets from the key vault. 
If I switch back to main, it works again.

### Expected behavior

Initialize should not fail

### Steps to reproduce

Run preview CI/CD with a connected azure key vault

### Additional context (logs, screenshots, etc.)

![image](https://github.com/user-attachments/assets/63df0af6-433b-4ad8-96c3-10b83664677e)

**Comment by freddydk** [comment]
Does it list which secrets it is looking for (above the part included in the screenshot)

**Comment by StefanMaron** [comment]
This is the part above that error message.
The KeyVault is just used for the Code Signing cert
![image](https://github.com/user-attachments/assets/41be3646-0b83-48e2-8bf4-97f10dc92f21)

**Comment by freddydk** [comment]
Got it.
Your app registration then only has permissions to sign apps and we expect it to have permissions to list and read secrets.
It's a bug - will fix this.

**Comment by freddydk** [comment]
@StefanMaron - could you try to run Update AL-Go System files with use `freddydk/AL-Go@issue1164` to see whether this solves the issue. After this - revert back to main again, then I will proceed to get this fix into preview.

**Comment by freddydk** [comment]
I managed to repro myself and see that this indeed fixes the issue
