### ISSUE TITLE
[Question]: Publish To Environment Action: How to Include Dependencies?

### ISSUE THREAD

**Issue by SchulzOli** [microsoft/AL-Go#1178]
### Question

Hi and hello, 

We would like to publish an AppSource App (with the AL-GO Template  "[AL-Go-AppSource](https://github.com/microsoft/AL-Go-AppSource)") to a SaaS Sandbox Environment with the Action "Publish To Environment"

# Our Setup:
This app depends on four other apps. They are in the same Github orga, but in different repos.  All Repos are internal (so not public).
The CI CD Pipeline uses GITHUBPACKAGESCONTEXT to find the right dependencies. So, we do not use the setting keys "appDependencyProbingPaths" or "installApps" at all.

we use the setting key "deployTo" to publish:

``` JSON
  "deployToPrefix-ProductName-QA": {
    "EnvironmentName": "Prefix-ProductName-QA",
    "ContinuousDeployment": false,
    "Scope": "Dev",
    "SyncMode": "ForceSync",
    "Branches": [
      "main"
    ]
  },
```

i also tried these two keys (even though I knew that this would probably not change anything): 
``` JSON
  "generateDependencyArtifact": true,
  "installOnlyReferencedApps": false,
```

# The Problem / Question
The action "Publish to Environment" fails because the dependent apps cannot be found. 
Is there a way to publish the Dependencies with this Action as well or is the common approach to install them before this action? 

i believe it should work because the script can find and download the dependencies.zip in the "Get Artifacts for deployment" step.: 

![image](https://github.com/user-attachments/assets/62a1bdbe-50f2-40ab-8982-7bc03dc838b3)

My guess would be: I have to use the "generateDependencyArtifact" for that and its not working yet with the GITHUBPACKAGESCONTEXT?! But seriously - i dont know.  

full (anonymized) log here: 
[log.txt](https://github.com/user-attachments/files/16730175/log.txt)

**Comment by freddydk** [comment]
Will try to create a repro of this to see whether this is a bug

**Comment by AlexanderRichter** [comment]
Hey there,
i am experiencing pretty much the same thing.

I included all apps i want to install in a Dependency Folder in the Repository.

The al-go Settings in the repo contain

**Comment by freddydk** [comment]
Currently in preview, the DeployTo structure now has a dependencyInstallMode property, which controls how dependencies are handled.

https://aka.ms/algosettings#deployto
