### ISSUE TITLE
[Question]: How can you limit projects for TestCurrrent 

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#1180]
### Question

How can I limit which projects I test, when running TestCurrent, in multi-project repo setting?

Currently we have two projects within our repo (one for base, and one for NL). We do maintain autotests only for the base version, thus we would like to skip NL version. How can we do that?

p.s. we are doing it from cost perspective, since every billable minute matters in Github :)

**Comment by freddydk** [comment]
I would assume that you can add a projects setting to `.github/Test Current.settings.json` and include the projects you want to build.

**Comment by freddydk** [comment]
Remove the appFolders and testFolders and instead insert:

```
"projects": [ "SRS.base" ]
```

My guess that this should work.

**Comment by freddydk** [comment]
appFolders and testFolders are project settings.
Remove them and add [projects](https://aka.ms/algosettings#projects)

```
"projects": ["SRS.base"]
```

that should work.

You can also use [conditionalSettings](https://aka.ms/algosettings#conditional-settings)

**Comment by gntpet** [comment]
Your suggest code changes did work and yes, it is not documented ;)

Thank you @freddydk

**Comment by freddydk** [comment]
Using this issue to fix the docs
