### ISSUE TITLE
[Question]: Next Major Error : Value cannot be null. (Parameter 'input')

### ISSUE THREAD

**Issue by ismailhafid1** [microsoft/AL-Go#1191]
### Question

4 months ago when the V25 errors started occuring in our NextMajor workflow , the errors that we got were AL Errors , however during the last 3 months some repositories started to give us the following error during the build process in NextMajor Workflow :
INSTALLING APPS : 
```
  Publishing C:\ProgramData\BcContainerHelper\Extensions\bc10587642353\85997da9-fbd5-4c10-aad9-f8f6f9ae17da\Insight Works_DocXtender.app
  Value cannot be null. (Parameter 'input')
  
  Exception Script Stack Trace:
  at <ScriptBlock>, <No file>: line 41
  
  PowerShell Call Stack:
  at Invoke-ScriptInBcContainer, C:\ProgramData\BcContainerHelper\6.0.20\BcContainerHelper\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 71
  at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.20\BcContainerHelper\AppHandling\Publish-NavContainerApp.ps1: line [410](https://github.com/Gestisoft-clients/Business-Central-Services-Hilo-Inc/actions/runs/10587642353/job/29338791790#step:8:417)
  at Publish-BcContainerApp, C:\ProgramData\BcContainerHelper\6.0.20\BcContainerHelper\AppHandling\Publish-NavContainerApp.ps1: line 166
  at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.20\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 861
  at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.20\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1291
  at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.20\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1215
  at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.20\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 965
  at Run-AlPipeline, C:\ProgramData\BcContainerHelper\6.0.20\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 927
  at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v5.0\RunPipeline\RunPipeline.ps1: line 367
  at <ScriptBlock>, D:\a\_temp\3dfb5ce8-9908-4729-a53d-d79b8b7eba27.ps1: line 4
  at <ScriptBlock>, <No file>: line 1
```
The parameter section doesn't have a parameter 'input', is there another way to find where the input value comes from ?

**Comment by pzentner** [comment]
We have the same issues. This seems to be for ISVs who provide runtime versions of apps rather than "full apps". The runtime versions typically cannot be imported into the next version as they need to be recompiled. We have gotten the same errors every time for every NextMajor once Microsoft started changing the actual executables.

It's unfortunate that different ISVs still only provide runtime versions and that they do not provide the next version's runtime version until the release (or after the release) of the next major BC version.

**Comment by ismailhafid1** [comment]
i see , so the only solution is to wait for the ISVs to provide us with their V25 apps which can be problematic . 
thanks for the replies
