### ISSUE TITLE
[Question]: Versioning in "Create Release"

### ISSUE THREAD

**Issue by frottke** [microsoft/AL-Go#1192]
### Question

What is the idea behind the concept that if you create a new release via ‘Create Release’ and you enter a new version number that this is not reflected in the artifacts?

What I mean is this:
![image](https://github.com/user-attachments/assets/e0b37bcc-f738-4eac-940b-840947972f08)

I would except that the version in the release branch is "23.4" (assuming that 23.3 was created the same way). Right now I would need to run the CI/CD Action one more time to generate the artifacts with the correct version and then modify the created github release. Sounds wrong to me. Is the idea that this parameter reflects the NEW version number? If so, how would one know if the next version is a major or minor release?

**Comment by freddydk** [comment]
If your main branch is 23.3 and you are working on 23.3, then every build will be 23.3.x.y.
When you then create a release, you create a release of 23.3 (grabbing the binaries from the latest build and releasing them together with the source used to create that build).
You will tag that release with the tag name and if you have specified a release branch - if will create a release branch from that tag (this can also be done later).

Main will then become 23.4 or 24.0 (based on what you specify in new version number) and you will continue working in main.

Your release branch will only be touched if you need to issue a hotfix.

**Comment by frottke** [comment]
Hi Freddy, thank you very much for your quick reply.

I understand that, and I think we now have the same understanding. What I'm still struggling with at the moment is that I have to specify what my next version is (might be 24.4 for a new feature or 24.3.1 for a bugfix) with the previous release. However, the next version might not yet defined at this point. So I don't know whether my next change is major or minor (or even a patch). If we think in terms of SemVer versions, there is also a corresponding meaning behind the versions. See definition -> https://semver.org/

Of course, I could simply not use the parameter when creating a release but I'm curious on why it is designed this way.

**Comment by freddydk** [comment]
It is designed this way because if we don't increase the major.minor in main - then the next build in main would be 24.3.100.0 and the next build from the release branch would then be 24.3.101.0 (this is now newer than the build in the main branch, which is not good).
This is also how we do in Microsoft - when we branch out to a release, then we increase the version number in main.
If you use 24.4 in main - you can always run the Increment version number workflow to make that 25.0 if that is your next version.
