### ISSUE TITLE
[Bug]: Error Update AL Go System File (401 Unauthorized)

### ISSUE THREAD

**Issue by DesarrolloBC** [microsoft/AL-Go#1204]
### AL-Go version

5.3

### Describe the issue

Hello,

I'm trying to update the AL Go System Files, but I keep getting an error Unauthorized. Do not know the reason, the last time I was able to sync without any problem was a month ago.

Downloading BcContainerHelper latest version from Blob Storage
Import from C:\ProgramData\BcContainerHelper\6.0.22\BcContainerHelper\BcContainerHelper.ps1
BcContainerHelper version 6.0.22
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on Windows, PowerShell 5.1.20348.2652
Applying settings from D:\a\D365BC\D365BC\.github\AL-Go-Settings.json
TemplateUrl: https://github.com/microsoft/AL-Go-PTE@main
TemplateSha: 
DownloadLatest: True
The remote server returned an error: ([40](https://github.com/XX/D365BC/actions/runs/10813366223/job/29997227684#step:9:42)1) Unauthorized. 
Unauthorized
...retrying in 1 minute
...retrying in 1 minute
Retry failed as well
The remote server returned an error: (401) Unauthorized. 
Unauthorized
Applying settings from D:\a\D365BC\D365BC\.github\AL-Go-Settings.json
Applying settings from D:\a\D365BC\D365BC\.AL-Go\settings.json
No settings found in D:\a\D365BC\D365BC\.github\Update AL-Go System Files.settings.json
No settings found in D:\a\D365BC\D365BC\.AL-Go\Update AL-Go System Files.settings.json
No settings found in D:\a\D365BC\D365BC\.AL-Go\DesarrolloBC.settings.json
Enabling Microsoft telemetry...
Error: Unexpected error when running action. Error Message: The remote server returned an error: (401) Unauthorized.   Unauthorized , StackTrace: at InvokeWebRequest, D:\a\_actions\microsoft\AL-Go-Actions\v5.3\Github-Helper.psm1: line 112 <- at DownloadTemplateRepository, D:\a\_actions\microsoft\AL-Go-Actions\v5.3\CheckForUpdates\CheckForUpdates.HelperFunctions.ps1: line 31 <- at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v5.3\CheckForUpdates\CheckForUpdates.ps1: line 72 <- at <ScriptBlock>, D:\a\_temp\904b80da-900a-4996-aa7a-25bc84b1fb26.ps1: line 3 <- at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v5.3\Invoke-AlGoAction.ps1: line 17 <- at <ScriptBlock>, D:\a\_temp\904b80da-900a-4996-aa7a-25bc84b1fb26.ps1: line 2 <- at <ScriptBlock>, <No file>: line 1
Error: Process completed with exit code 1.

### Expected behavior

To update the system files correctly.

### Steps to reproduce

Create a new action, specifying the needed parameters and execute.

**Comment by aholstrup1** [comment]
Can you check if: 
1. You have a secret called GHTokenWorklow in your repo secrets (or an org secret shared with your repo)
2. That secret isn't expired
