### ISSUE TITLE
[Question]: How to add app during deployment from the appDependencyProbingPaths

### ISSUE THREAD

**Issue by louagej** [microsoft/AL-Go#1215]
### Question

Hi,

My CICD builds,, but fail during deployment stage:

![image](https://github.com/user-attachments/assets/9a2e26e6-54a2-44d2-9802-c60938993085)

During the Build stage, the app got downloaded from the `appDependencyProbingPaths`
> Downloaded dependencies: D:\a\GTM-BC-9ARaptorDocumentManagement-W1\GTM-BC-9ARaptorDocumentManagement-W1\.dependencies\GTM-BC-9AAdvMan-License-main-Apps-1.1.14.0.zip, (D:\a\GTM-BC-9ARaptorDocumentManagement-W1\GTM-BC-9ARaptorDocumentManagement-W1\.dependencies\GTM-BC-9AAdvMan-License-main-TestApps-1.1.14.0.zip)
> Downloaded dependencies apps: D:\a\GTM-BC-9ARaptorDocumentManagement-W1\GTM-BC-9ARaptorDocumentManagement-W1\.dependencies\GTM-BC-9AAdvMan-License-main-Apps-1.1.14.0.zip
> Downloaded dependencies test apps: (D:\a\GTM-BC-9ARaptorDocumentManagement-W1\GTM-BC-9ARaptorDocumentManagement-W1\.dependencies\GTM-BC-9AAdvMan-License-main-TestApps-1.1.14.0.zip)

But during deployment, the action show this error:
> Deploying to UAT failed.  Status Code 422 : Unprocessable Entity Extension compilation failed error AL1024: A package with publisher '9altitudes', name '9A Advanced Manufacturing - License', and a version compatible with '1.0.0.0' could not be loaded

Is there another setting I forgot, so the apps in the `appDependencyProbingPaths` are deployed as well?

**Comment by louagej** [comment]
I forgot to mention, the depended app `9altitudes_9A Advanced Manufacturing - License_24.8.14.0.app` is added in the artifacts folder of the CICD pipeline

![image](https://github.com/user-attachments/assets/9baebb15-2bc4-403b-b841-bbd4250ba556)

**Comment by AlexanderRichter** [comment]
Hey,
i think we have the same issue already mentioned in #1178 .

**Comment by freddydk** [comment]
If you set the setting "GenerateDependencyArtifact" to true - it should create another build artifact with the dependencies used to build the app - and these should be deployed to the environment as well.
See https://aka.ms/algosettings#generatedependencyartifact

**Comment by louagej** [comment]
Hi,

the settings.json contains this property:
```json
{
  ...
  "deliverToAppSource": {
    "productId": "...",
    "continuousDelivery": false,
    "mainAppFolder": "9A Raptor Document Input",
    "includeDependencies": [
      "9A Raptor Document Management/9A Productivity Suite - Raptor Document Warehouse*.app",
      "dependencies/*.app"
    ]
  },
  "generateDependencyArtifact": true
}
```

And the artifacts also contains the dependend apps:
![image](https://github.com/user-attachments/assets/214f5c08-0c48-4812-843a-a877bc415767)

But the deployment to our UAT fails.

**Comment by freddydk** [comment]
Could I get the full log of the deploy step?

**Comment by louagej** [comment]
Hi,
attached the deployment log:

[logs_28592431426.zip](https://github.com/user-attachments/files/17096663/logs_28592431426.zip)

**Comment by freddydk** [comment]
I can see that currently external dependencies are not automatically included.
I thought they would be - will investigate and see what the right approach is here, but currently - you would have to install that dependency yourself.

**Comment by louagej** [comment]
Hi,

I manually installed the dependency, but the problem persists in `PublishToAppSource` workflow.
Somehow, this dependent app doesn’t get installed during the AppSource validation, even though the app is included in the downloaded artifacts:

```log
Downloading release 2.0.7, projects GTM-BC-9ARaptorDocumentManagement-W1, type Dependencies
project 'GTM-BC-9ARaptorDocumentManagement-W1'
AssetPatterns: 'GTM-BC-9ARaptorDocumentManagement-W1-*-Dependencies-*.zip' | 'GTM-BC-9ARaptorDocumentManagement-W1-Dependencies-*.zip'
https://api.github.com/repos/9altitudes/GTM-BC-9ARaptorDocumentManagement-W1/releases/assets/194591315
'D:\a\GTM-BC-9ARaptorDocumentManagement-W1\GTM-BC-9ARaptorDocumentManagement-W1\.artifacts\GTM-BC-9ARaptorDocumentManagement-W1-main-Dependencies-2.2.60.0.zip'
Project 'GTM-BC-9ARaptorDocumentManagement-W1'
Artifacts:
- GTM-BC-9ARaptorDocumentManagement-W1-main-Apps-2.2.60.0
- GTM-BC-9ARaptorDocumentManagement-W1-main-Dependencies-2.2.60.0
```

The AppSource validation returns this error for every country/version:
```log
Some dependencies could not be found for the country/region 'US' and release '24.5.0' of Business Central. Make sure that these dependencies are part of your submission or that they have already been uploaded to AppSource and that they are available for the targeted country/region and release: '9A Advanced Manufacturing - License' (e340d5b5-f7eb-44db-b802-fd3b7896e0a7) by '9altitudes' version '24.8.0.0'.
```

![image](https://github.com/user-attachments/assets/6c9d01a2-c442-43dd-ba0d-128c362aa672)


Attached you can find the PublishToAppSource log

[logs_28592431426.zip](https://github.com/user-attachments/files/17116466/logs_28592431426.zip)

**Comment by louagej** [comment]
Hi,
I added 2 lines of code in the Actions/Deploy/Deploy.ps1 file that might solve this error.
Can you check PR [1123](https://github.com/microsoft/AL-Go/pull/1223) to see if I'm on the right track?

**Comment by freddydk** [comment]
I will run through the code and have a look.

**Comment by louagej** [comment]
@freddydk ,

Any idea when the [Install dependencies #1225](https://github.com/microsoft/AL-Go/pull/1225) will be released?
