### ISSUE TITLE
[Question]: Build failed with failure downloading license file

### ISSUE THREAD

**Issue by andreasproehl** [microsoft/AL-Go#1221]
### Question

Hi,

the LICENSEFILEURL secret contains a valid development license. It has also not changed since the last successful build 1 month ago. But now the CICD pipeline returns an error when build:

Using license file ***
Downloading C:\ProgramData\BcContainerHelper\Extensions\bc11017570786\my\license.bclicense
Error downloading..., retrying in 3 seconds...

Unexpected error when running action. Error Message: Exception calling "GetResult" with "0" argument(s): "Response status code does not indicate success: 503 (Service Temporarily Unavailable)." Response status code does not indicate success: 503 (Service Temporarily Unavailable)., StackTrace: at Download-File, C:\ProgramData\BcContainerHelper\6.0.23\BcContainerHelper\Common\Download-File.ps1: line 96 <- at New-BcContainer, C:\ProgramData\BcContainerHelper\6.0.23\BcContainerHelper\ContainerHandling\New-NavContainer.ps1: line 1485 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.23\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 822 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.23\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1076 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.23\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1005 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.23\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 971 <- at Run-AlPipeline, C:\ProgramData\BcContainerHelper\6.0.23\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 933 <- at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v5.3\RunPipeline\RunPipeline.ps1: line 355 <- at <ScriptBlock>, D:\a\_temp\049dae2a-638e-4ec1-bde4-c1445b2e74f7.ps1: line 3 <- at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v5.3\Invoke-AlGoAction.ps1: line 17 <- at <ScriptBlock>, D:\a\_temp\049dae2a-638e-4ec1-bde4-c1445b2e74f7.ps1: line 2 <- at <ScriptBlock>, <No file>: line 1

Can you please give me a hint, what causes this error?

**Comment by freddydk** [comment]
Service Temporarily Unavailable it says

Sounds like the place where your license file is stored is having issues?

**Comment by andreasproehl** [comment]
Hello Freddy,

thank you for your quick reply. The accessibility of the url was also my first thought. However, it is accessible from different locations. Also from an Azure-VM:

<img width="779" alt="image" src="https://github.com/user-attachments/assets/8b577549-1c1f-479f-81bb-3ca391813dea">

**Comment by freddydk** [comment]
Did you try using Download-File from BcContainerHelper?
You could also try PS5 and/or PS7 to figure out what the problem could be

**Comment by andreasproehl** [comment]
The Download from BCContainerHelper works:

<img width="1378" alt="image" src="https://github.com/user-attachments/assets/2ff7cdbe-7a03-47b8-8e94-2e712753dc49">

**Comment by andreasproehl** [comment]
Already updated AL-Go System Files successfully. 

Run microsoft/AL-Go-Actions/RunPipeline@v5.3
Run D:\a\_actions\microsoft\AL-Go-Actions\v5.3\RunPipeline/../Invoke-AlGoAction.ps1 -ActionName "RunPipeline" -Action {
Import from C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\BcContainerHelper.ps1
BcContainerHelper version 6.0.24
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on Windows, PowerShell 5.1.20348.2652
use settings and secrets
Analyzing repository
  Checking type
  Checking appFolders, testFolders and bcptTestFolders
  Application Dependency 22.2.0.0
  Checking artifact setting for project
  Downloading artifacts from https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.5.23489.24678/us
  Downloading artifact /sandbox/24.5.23489.24678/us
  Downloading C:\Users\runneradmin\AppData\Local\Temp\ff376d8e-47e2-4d5f-9b71-db6e5af6965f.zip
  Unpacking artifact to tmp folder using 7zip
  Downloading platform artifact /sandbox/24.5.23489.24678/platform
  Downloading C:\Users\runneradmin\AppData\Local\Temp\823bfc1e-6121-4cdc-b58e-47420bec2457.zip
  Unpacking artifact to tmp folder using 7zip
  Downloading Prerequisite Components
  Downloading c:\bcartifacts.cache\sandbox\24.5.23489.24678\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
  Downloading c:\bcartifacts.cache\sandbox\24.5.23489.24678\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Parameters
Pulling generic image
Creating Container
     _____                _   _                _____            _        _
    / ____|              | | (_)              / ____|          | |      (_)
   | |     _ __ ___  __ _| |_ _ _ __   __ _  | |     ___  _ __ | |_ __ _ _ _ __   ___ _ __
   | |    | '__/ _ \/ _` | __| | '_ \ / _` | | |    / _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
   | |____| | |  __/ (_| | |_| | | | | (_| | | |___| (_) | | | | || (_| | | | | |  __/ |
    \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \_____\___/|_| |_|\__\__,_|_|_| |_|\___|_|
                                       __/ |
                                      |___/
  Creaing docker container
  BcContainerHelper is version 6.0.24
  BcContainerHelper is running as administrator
  HyperV is Enabled
  Host is Microsoft Windows Server 2022 Datacenter - 10.0.20348.2700
  UsePsSession is True
  UsePwshForBc24 is True
  UseWinRmSession is allow
  UseSslForWinRmSession is True
  Docker Client Version is 26.1.3
  Docker Server Version is 26.1.3
  Removing Desktop shortcuts
  Fetching all docker images
  Fetching all docker volumes
  Using image mcr.microsoft.com/businesscentral:ltsc2022
  Creating Container bc11035364330
  Style: sandbox
  Multitenant: Yes
  Version: 24.5.23489.24678
  Platform: 24.0.24619.0
  Generic Tag: 1.0.2.46
  Container OS Version: 10.0.20348.2700 (ltsc2022)
  Host OS Version: 10.0.20348.2700 (ltsc2022)
  Using process isolation
  Using locale en-US
  Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
  Using license file ***
  Downloading C:\ProgramData\BcContainerHelper\Extensions\bc11035364330\my\license.bclicense
  Error downloading..., retrying in 6 seconds...
  New-BcContainer Telemetry Correlation Id: b19f5d7d-dfa9-4d19-a190-1206b53cc405
Removing container
Run-AlPipeline Telemetry Correlation Id: d97e2267-87a7-45c0-adda-6f83371c1191
Applying settings from D:\a\docBoxDmsConnector\docBoxDmsConnector\.github\AL-Go-Settings.json
Applying settings from D:\a\docBoxDmsConnector\docBoxDmsConnector\.AL-Go\settings.json
No settings found in D:\a\docBoxDmsConnector\docBoxDmsConnector\.github\CICD.settings.json
No settings found in D:\a\docBoxDmsConnector\docBoxDmsConnector\.AL-Go\CICD.settings.json
No settings found in D:\a\docBoxDmsConnector\docBoxDmsConnector\.AL-Go\andreasproehl.settings.json
Enabling Microsoft telemetry...
Error: Unexpected error when running action. Error Message: Exception calling "GetResult" with "0" argument(s): "Response status code does not indicate success: 503 (Service Temporarily Unavailable)." Response status code does not indicate success: 503 (Service Temporarily Unavailable)., StackTrace: at Download-File, C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\Common\Download-File.ps1: line 96 <- at New-BcContainer, C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\ContainerHandling\New-NavContainer.ps1: line 1485 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 822 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1076 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1005 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 97
Error: Process completed with exit code 1.

Have tried it locally with BCContainerHelper in Version 6.024 and it worked. Don't know what else to check.

**Comment by freddydk** [comment]
You could shoot me an email with the URL - maybe I can see something?

**Comment by andreasproehl** [comment]
Sended to you per Teams.

**Comment by freddydk** [comment]
Replied on Teams.
There is something with the download location of the file, whether it is the certificate, the tls version or other things, I don't know - but the license file works perfectly when copied to one of the locations described here: https://freddysblog.com/2017/02/26/create-a-secure-url-to-a-file/
