### ISSUE TITLE
[Question]: CI/CD Build fails at step/line 476 with a 404 not found

### ISSUE THREAD

**Issue by StreichersBC** [microsoft/AL-Go#1226]
### Question

A dependent appsource app is giving a 404 error in the build.

Error:
Error: Unexpected error when running action. Error Message: Exception calling "GetResult" with "0" argument(s): "Response status code does not indicate success: 404 (Not Found)." Response status code does not indicate success: 404 (Not Found)., StackTrace: at Compile-AppInBcContainer, C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\AppHandling\Compile-AppInNavContainer.ps1: line 465 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 840 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2001 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1528 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1521 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 971 <- at Run-AlPipeline, C:\ProgramData\BcContainerHelper\6.0.24\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 933 <- at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v5.3\RunPipeline\RunPipeline.ps1: line 355 <- at <ScriptBlock>, D:\a\_temp\a50c547d-316f-4a95-bb4c-dedf84a2f5aa.ps1: line 3 <- at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v5.3\Invoke-AlGoAction.ps1: line 17 <- at <ScriptBlock>, D:\a\_temp\a50c547d-316f-4a95-bb4c-dedf84a2f5aa.ps1: line 2 <- at <ScriptBlock>, <No file>: line 1
Error: Process completed with exit code 1.

Copilot analysis:
Verify the URL: http://172.28.96.234:7049/BC/dev/packages?appId=8f7cdd5f-1af2-4ec2-a1f3-ecb959ec395b&versionText=24.24.0.0&tenant=default

The appid is for iPayments Credit Card & Collections app.

I updated the version of the app in my app.json to match the version in AppSource. Ran a commit and sync from VSCode. CI/CD failed with the same error, but the Copilot error explanation did not point to any app.

Manually ran the CI/CD. Now the Copilot error analysis shows the same error but with a blank appID:
![image](https://github.com/user-attachments/assets/74c7fe08-be0d-42cf-9d00-96b97f00bb16)

**Comment by freddydk** [comment]
What version of AL-Go for GitHub are you running?

Do you have a runtime package of the iPayments app in the repo (or a link to it)?

**Comment by freddydk** [comment]
It is almost impossible to read answers from e-mails on GitHub.

Try to set "doNotPublishApps" to true in your .github/AL-Go-Settings.json file.

Symbols packages cannot be published to BC and therefore they can only be used for the build process.

If you could supply to full build log, then we might be able to see why things are not building

**Comment by StreichersBC** [comment]
Sorry. I'll reply here.

Added the doNotPublishApps and (after figuring out how to add it as a Boolean) ran a sync. 

The build failed, but this time, it failed after 6 hours.
[GitHub Build log.txt](https://github.com/user-attachments/files/17465064/GitHub.Build.log.txt)

The error is just- "operation cancelled."
2024-10-18T20:41:49.8571272Z Compiling D:\a\MainApp\MainApp\MainApp
2024-10-19T02:22:39.7729832Z ##[error]The operation was canceled.

Just did another sync to GitHub. If it fails before the end of the day I'll update this.

**Comment by freddydk** [comment]
You could also try to add "useCompilerFolder": true - which causes the compiler to not use containers at all

**Comment by StreichersBC** [comment]
Will this cut the compile time?

My last attempt failed at 6 hours.

These two have used up 90% of my GitHub services (per the email I received yesterday).

**Comment by freddydk** [comment]
yes, it should.

**Comment by StreichersBC** [comment]
Thanks again.

I now have an error indicating a missing app file, but it is a PTE app file provided by a third party. I don't have the code or at GitHub URL.

I added a folder in GitHub called appFolder, put the .app file there, and modified my AL-Go settings.json after reading your documentation to
{
  "country": "us",
  "appFolders": [],
  "testFolders": [],
  "bcptTestFolders": [],
  "doNotPublishApps": true,
  "useCompilerFolder": true,
  "projectName": "StreichersBC",
  "type": "PTE",
  "UpdateGitHubGoSystemFilesSchedule": "0 0 0 * * 6",
  "appFolder": "..\\appFolder"
}

The CI/CD does not find the app:
Error: AL1022 A package with publisher 'Insight Works', name 'Order Fulfillment Worksheet: Streichers', and a version compatible with '1.0.0.5' could not be found in the package cache folders: D:\a\MainApp\MainApp\.packages

I've looked at your documentation and can't find anything on this use case. How do I make this app file available for CI/CD?

**Comment by jonaswre** [comment]
You shouldn't commit app files into your repo. Best way to handle this is to use the AL-Go installApps property. 

Please reference the settings documentation https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md

**Comment by StreichersBC** [comment]
THANK YOU @jonaswre and @freddydk !

I used your advice, found another post on installApps where Freddy gave an example, and for the first time ever, my CI/CD ran. 

Doesn't really do anything yet, but now I can start learning more good stuff about AL-Go!

Thanks again to both of you!

**Comment by jonaswre** [comment]
You are are using AL-Go in Azure Pipelines? 


But if you were using AL-Go  in github it would say your issue is that the installApps needs to ne a URL that can be used to download the file. We typically but it in a azure blob storage.
