### ISSUE TITLE
[Bug]: Error during install previous apps ⚠

### ISSUE THREAD

**Issue by louagej** [microsoft/AL-Go#1235]
### AL-Go version

preview

### Describe the issue

The  CICD action is completing following steps:

- ✅  Initialization 
- ✅  Check For Updates
- ❌  Build
  > ✅ Set up job
  > ✅ checkout
  > ✅ Read settings
  > ✅ Read secrets
  > ✅ Determine ArtifacUrl
  > ✅ Download Project Dependencies
  > ❌ Build
   >- ✅ Run microsoft/AL-Go/Actions/RunPipeline@c198d5ffe9434dda2087ec2c5a9edc61e5118f28
   >- ✅ Run D:\a\_actions\microsoft\AL-Go\c198d5ffe9434dda2087ec2c5a9edc61e5118f28\Actions/RunPipeline/../Invoke-AlGoAction.ps1 -ActionName "RunPipeline" -Action {
        > Analyzing repository
   >- ✅ Locating previous release
   >- ✅ Parameters
   >- ✅ Pulling generic image
   >- ✅ Creating Container
   >- ✅ Resolving dependencies
   >- ✅ Installing apps
   >- ✅ Installed Apps
   >- ✅ Installing app dependencies
   >- ✅ Compiling apps
   >- ✅ Importing test toolkit
   >- ✅ Installing test apps
   >- ✅ Installed Apps
   >- ✅ Compiling test apps
   >- ❌ Installing previous apps

During the Installing previous apps, I get an error message:
```log
Extension compilation failed
  src/BaseExt/tableextension/NALPurchCrMemoHdrExt.TableExt.al(9,29): error AL0185: Table 'CDC Document' is missing
```

the table referring to is a dependency that is available as artifact in the previous release
But since it does not download the dependency of the previous release,  it is of course missing the symbols

```log
Locating previous release
  Getting the latest release from https://api.github.com/repos/9altitudes/GTM-BC-9ARaptorDocumentManagement-W1/releases/latest - branch uat/uat
  Analyzing releases https://api.github.com/repos/9altitudes/GTM-BC-9ARaptorDocumentManagement-W1/releases
  Using 2.0.6 (tag 2.0.6) as previous release
  Downloading release 2.0.6, projects *, type Apps
  project '*'
  AssetPatterns: '*-*-Apps-*.zip' | '*-Apps-*.zip'
  https://api.github.com/repos/9altitudes/GTM-BC-9ARaptorDocumentManagement-W1/releases/assets/1933[85](https://github.com/9altitudes/GTM-BC-9ARaptorDocumentManagement-W1/actions/runs/11144712749/job/30972709388#step:8:88)825
  D:\a\GTM-BC-9ARaptorDocumentManagement-W1\GTM-BC-9ARaptorDocumentManagement-W1\artifacts\GTM-BC-9ARaptorDocumentManagement-W1-main-Apps-2.2.54.0.zip
```

### Expected behavior

The dependencies of a previous release should be downloaded and included in the step install previous apps

### Steps to reproduce

1. Create an app with a dependency folder (holding 3th party dependency app file)
2. Run the CICD action so artifacts are available
3. Create a release for this build
   3.1. Make sure the release has an artifact with the 3th partty app dependency
4. Update you project and remove the dependency folder and it's apps. (3th party apps are downloaded from nuget source)
5. Run the CICD action again

### Additional context (logs, screenshots, etc.)

event log:

[logs_29118352961.zip](https://github.com/user-attachments/files/17230872/logs_29118352961.zip)

**Comment by louagej** [comment]
To give you an idea, this is how the dependency structure of the project looks like:

I just used some abbreviations for our own apps since they are too long to display in the graph:
- RDW = 9A Productivity Suite - Raptor Document Warehouse
- RDW - Core = 9A Productivity Suite - Raptor Document Warehouse

![Image](https://github.com/user-attachments/assets/f646199a-3b2d-4dbb-8735-3f6172ebea28)

**Comment by jonaswre** [comment]
@freddydk We’re encountering the same error, and it seems to be due to issues with the new dependency resolution process.

The main problem lies with the new Microsoft NuGet feed. It’s useless if you’re not simply compiling your app, as symbols cannot be installed within the container, which blocks installation of previous versions.

I see two possible solutions:

1. Provide runtimes directly.
2. Only pull symbols when dontPublish == true and useCompileFolder == true.

Additionally, when downloading symbols, the Microsoft feed should appear last in the priority list. In our setup, even though our app is hosted on our internal feed, it’s still being downloaded from the Microsoft feed instead.

**Comment by freddydk** [comment]
If you add "doNotTrustMicrosoftFeeds": true - then you won't trust the Microsoft feeds and be back to where you were before v6.0

I will definitely go through these thoughts and find a way to only take symbols into account when not publishing.

**Comment by jonaswre** [comment]
> If you add "doNotTrustMicrosoftFeeds": true - then you won't trust the Microsoft feeds and be back to where you were before v6.0
> 
> I will definitely go through these thoughts and find a way to only take symbols into account when not publishing.

While looking at the PR that introduced this I realized the same. Currently trying...

**Comment by jonaswre** [comment]
This doesn't work because it will no longer use the internal Feed for resolution. No compilation fails.

**Comment by louagej** [comment]
The setting  `"doNotTrustMicrosoftFeeds": true` is the one that fixed the issue for me.
