### ISSUE TITLE
[Question]: Artifact dependencies - timeline on release of #1223

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/AL-Go#1251]
### Question

We have the following scenario:

Repo 1
- Core App

Repo 2
- App with dependency on Core App

When publishing to our test environment from Repo 2, we get an error because the dependency to the Core App cannot be resolved (it is not installed on the environment). It would be nice of the deploy also installed the missing dependencies.

I searched through the GitHub issues and found Add artifact Dependencies inside artifactsFolder to be deployed #1223. I believe this is the one we need. Any timeline on this being released?

**Comment by dsaveyn** [comment]
@fvet

**Comment by freddydk** [comment]
Yeah, this PR: https://github.com/microsoft/AL-Go/pull/1225 - should be in within the next week and deployed to preview.

**Comment by dsaveyn** [comment]
> Yeah, this PR: [#1225](https://github.com/microsoft/AL-Go/pull/1225) - should be in within the next week and deployed to preview. 1223 was a different implementation, which was abandoned.

Super, thx for the info!
