### ISSUE TITLE
Build job fails on a hosted runner when app is being published

### ISSUE THREAD

**Issue by ashirokikh** [microsoft/AL-Go#127]
Hi folks,

About 5 mins after starting publishing the app during the Build job, the following error is thrown:

`An unexpected error occurred after a database command was cancelled.`

![image](https://user-images.githubusercontent.com/17916422/168303565-3f174601-6a3e-4113-9ffa-dead81294a30.png)

```
An unexpected error occurred after a database command was cancelled.
  at <ScriptBlock>, <No file>: line 41
  at Invoke-ScriptInBcContainer, C:\Users\runneradmin\AppData\Local\Temp\2cdf2102-97d0-437c-8754-b61235d26036\BcContainerHelper\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 43
  at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\2cdf2102-97d0-437c-8754-b61235d26036\BcContainerHelper\AppHandling\Publish-NavContainerApp.ps1: line 278
  at Publish-BcContainerApp, C:\Users\runneradmin\AppData\Local\Temp\2cdf2102-97d0-437c-8754-b61235d26036\BcContainerHelper\AppHandling\Publish-NavContainerApp.ps1: line 132
  at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\2cdf2102-97d0-437c-8754-b61235d26036\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 646
  at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\2cdf2102-97d0-437c-8754-b61235d26036\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1661
  at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\2cdf2102-97d0-437c-8754-b61235d26036\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1631
  at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\2cdf2102-97d0-437c-8754-b61235d26036\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1620
  at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\2cdf2102-97d0-437c-8754-b61235d26036\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 732
  at Run-AlPipeline, C:\Users\runneradmin\AppData\Local\Temp\2cdf2102-97d0-437c-8754-b61235d26036\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 697
  at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v1.4\RunPipeline\runpipeline.ps1: line 233
  at <ScriptBlock>, D:\a\_temp\168e4bec-56aa-496d-994d-65e447195f99.ps1: line 1
  at <ScriptBlock>, <No file>: line 1
  Publish-BcContainerApp Telemetry Correlation Id: 5841115a-c2fe-44ab-9fd1-279ea2933eea
```

I've tried custom settings in the NewBcContainer override script (which adds extra add-ins) but no luck.

```Powershell
Param([Hashtable]$parameters) 

$addins = Join-Path $PSScriptRoot "add-ins"
$parameters.additionalParameters += @("--volume ""$($addins):c:\run\add-ins""")
$parameters.additionalParameters += @("--env customNavSettings=NavHttpClientMaxTimeout=00:15:00,SqlConnectionIdleTimeout=00:15:00,SqlConnectionTimeout=00:15:00")
$parameters.useGenericImage = "$(Get-BestGenericImageName)-dev"

New-BcContainer @parameters;     
Invoke-ScriptInBcContainer $parameters.ContainerName -scriptblock { $progressPreference = 'SilentlyContinue' } 
```

Not sure what else can be done to pinpoint the cause, the error message doesn't seem to help much.

No issues on a self-hosted runner. 

Thanks

**Comment by freddydk** [comment]
The Microsoft hosted agents are 7GB - is this a large app?
Can you see the memory consumption on the self-hosted environment?

**Comment by freddydk** [comment]
Alternatively, if you can give me read access to the repo, then I can create a private fork, test and fix and then delete the repo again.

**Comment by ashirokikh** [comment]
Thanks for clarification @freddydk, it is a fairly large app. It publishes successfully on a local container with 7GB memory limit but failed on a 6GB container. I understand that Microsoft hosted agents could be VMs with 7GB RAM which is shared by them and docker. Memory on the local container doesn't go higher than 6.2GB while the app is published. I'm happy to share the repo if you believe it can be useful. Happy to close the issue otherwise, will use a self-hosted runner due to the hosted agents memory limitation. Thanks for your help!

**Comment by freddydk** [comment]
I think it would be useful for other partners if a situation like this could give a better error indicating that the partner might need more memory and use self-hosted agents. If you can provide access, I can use your app to test this.
Thanks

**Comment by freddydk** [comment]
BTW - if you look inside the output in **build** job, under the **Run Pipeline** task, expand **Creating Container** you will find information about free memory when the container starts:
![image](https://user-images.githubusercontent.com/10775043/168524760-ad0c07a4-a5e5-41e0-85da-0d83d044aea2.png)

**Comment by freddydk** [comment]
This fix in BcContainerHelper 
https://github.com/microsoft/navcontainerhelper/pull/2467

Should take care of this.
Whenever Invoke-ScriptInBcContainer fails (only when it fails) - it is investigated whether there was an OutOfMemoryException - and then instead of throwing the original error - the error re-thrown is Out Of Memory.
EventLog (happening while running the script) and running/stopped services is also added to the output for better investigation

Looks like this in AL-Go
![image](https://user-images.githubusercontent.com/10775043/168581574-1d346de2-6d47-461c-bf96-56c7b86c8386.png)

Thanks for this.

**Comment by ashirokikh** [comment]
Looks great, thank you @freddydk ! Love your work, always happy to help.

**Comment by freddydk** [comment]
New ContainerHelper 3.0.8 was published today.
