### ISSUE TITLE
[Bug]: AppSource validation failed using "Publish to AppSource" action.

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#1271]
### AL-Go version

6.0

### Describe the issue

Hi everybody, 

We published a release today which failed with an unknown error. The AL-Go logs only showed 

'''Automated validation......................................................................................................................................................................................................................................................................................................................................................................... Failure'''

Republishing from the web interface solved it. (Without any changes)

### Expected behavior

"Publish to AppSource" should only fail if the publishes package has an issue.

### Steps to reproduce

Probably not possible

**Comment by jonaswre** [comment]
> We've found some similar issues:
> 
> * [[Bug] Publish to AppSource - Automated validation: failure #1211](https://github.com/microsoft/AL-Go/issues/1211) , similarity score: 82%
> 
> If any of the above are duplicates, please consider closing this issue out and adding additional context in the original issue.
> 
> > Note: You can give me feedback by 👍 or 👎 this comment.

The step is marked as failed in github.

**Comment by louagej** [comment]
Hi @jonaswre ,

There is probably no way for AL-Go to know what goes wrong during AppSource validation.

But to help you a little further... I had this problem in the past, and had to solve this with telemetry.
What you can do is use your telemetry key that you setup in your app.json and go to the related [applications insights](https://portal.azure.com/#browse/microsoft.insights%2Fcomponents) key on portal.azure.com

Run this query and you should get a list of errors that where generated during you app validation on AppSource

```kql
traces
| where timestamp > ago(100d) // adjust as needed
| where customDimensions.eventId == 'LC0038'
| project timestamp 
, requestId = customDimensions.validationRequestId
, diagnosticCode = customDimensions.diagnosticCode
, diagnosticMessage = customDimensions.diagnosticMessage
, diagnosticSeverity = customDimensions.diagnosticSeverity
, containsHotfix = customDimensions.containsHotfix
, message
```

**Comment by jonaswre** [comment]
Thanks for your suggestions. I'll have a look at the detailed error. But since resubmitting fixed it, I thinks it's more likely an issue on Microsoft's end.

**Comment by freddydk** [comment]
Did you set the checkbox:
![Image](https://github.com/user-attachments/assets/d7ebb89e-3670-49e4-a10f-1d5757693ed3)

when running the action?

When you entered Partner Center after this error - what was the state?

Were the apps uploaded?
Were they validated, ready for go-live? - or did validation actually fail?

Thanks

**Comment by jonaswre** [comment]
The action ran through successfully the "Promote AppSource App..." wasn't set. I think everything got uploaded correctly. But in Partner Center the validation just failed with the following error "Automated validation of the submission has failed. Please retry the operation and contact Partner Center support if it fails again."

When retrying from the partner center it worked correctly.

**Comment by freddydk** [comment]
OK, so something failed in the validation process starting validation or like - I guess you want GitHub to tell you that something went wrong.
I don't have access to the reason why, and I am pretty sure that if you had retried from GitHub it would have succeeded as well.

Not sure I can do anything about this.

**Comment by jonaswre** [comment]
Well Github can't tell me whats wrong if the error occurs after the action has finished but I would want my AppSource submission to only fail if there is actually something wrong on our side right? Maybe Microsoft should automatticly retry if the process is not stable enough to work everytime. 

But this is probably just another thing thats randomly not working sometimes. Supporting my argument if Mircosoft had to use the AppSource as we do for all their apps. Stuff like this would be hunted down.
