### ISSUE TITLE
[Question]: Invoke a codeunit for loading additional data / manipulating the container

### ISSUE THREAD

**Issue by mmenninghaus** [microsoft/AL-Go#1275]
### Question

In our current Azure DevOps Pipeline-setup we use a custom codeunit to manipulate the data of a container / load new data in order to run our tests. The data is stored in our repo and depends on the currently version of the app under test. 
We did not find an action which allows us, to invoke a codeunit inside a container in AL-Go. Is this possible?

**Comment by freddydk** [comment]
Our recommendation is to use [configPackages](https://aka.ms/algosettings#configPackages).
If you cannot use that, our recommendation is to have an app, which populates demo data on install and then have a dependency on this app from the other test apps (ensuring that it is installed first).

If you cannot use that, you can place a file called `ImportTestDataInBcContainer.ps1` in your .AL-Go folder in the project, like this:

```
Param([Hashtable]$parameters)

$country = Get-BcContainerCountry -containerOrImageName $parameters.containerName
$prop = "configPackages.$country"
if ($settings.Keys -notcontains $prop) {
    $prop = "configPackages"
}
if ($settings."$prop") {
    Write-Host "Importing config packages from $prop"
    $settings."$prop" | ForEach-Object {
        $configPackage = $_.Split(',')[0].Replace('{COUNTRY}',$country)
        $packageId = $_.Split(',')[1]
        UploadImportAndApply-ConfigPackageInBcContainer `
            -containerName $parameters.containerName `
            -companyName $settings.companyName `
            -Credential $parameters.credential `
            -Tenant $parameters.tenant `
            -ConfigPackage $configPackage `
            -PackageId $packageId
    }
}
```

This is the override provided by AL-Go for GitHub when using configPackages - but you could really install an app and run a codeunit in this script as well.

**Comment by mmenninghaus** [comment]
Thank you!
