### ISSUE TITLE
[Parameter Request] Please expose applicationInsightsConnectionString

### ISSUE THREAD

**Issue by juliandittmann** [microsoft/AL-Go#130]
In public projects I dont want to publish the `applicationInsightsConnectionString`. Currently the applicationInsightsConnectionString Parameter of `Run-ALPipeline` cannot be set .

To change this, the parameter `applicationInsightsConnectionString` of Run-AlPipeline needs to be added to `$secretsJson`

**Comment by freddydk** [comment]
Will implement this.

**Comment by freddydk** [comment]
Released in preview

**Comment by freddydk** [comment]
Shipped in v1.5
