### ISSUE TITLE
Keyvaultsecrets with umlauts are passed incorrectly and unmasked

### ISSUE THREAD

**Issue by juliandittmann** [microsoft/AL-Go#131]
Steps to reproduce:
- Create a secret with umlauts (ö,ä,ü, ... )
- Run CI/CD workflow

Note: I used a keyvault.

The secrets are recieved correctly from the vault but somehow are passed incorrectly. 
This results in unmasking secrets and futher errors.

Example:
![image](https://user-images.githubusercontent.com/50719320/169031779-10f2dea3-790d-4755-8109-6e1337b0e68a.png)

**Comment by freddydk** [comment]
I have spent a lot of time trying to figure out a way to make this work - and I will have to give up.
I do see this as a bug in GitHub, which I assume they will fix at some point in time.
At the same time, it is crucial that secrets are not revealed by the system, so from the next version of AL-Go - you will get this error if a secret contains characters, which are outside the range of 32..126
![image](https://user-images.githubusercontent.com/10775043/170807870-c0981cc1-56dd-44f5-8157-ee82ba0634e5.png)

One workaround would be to implement support for some secrets could be base64 encoded (like provide ::<base64string>:: as your secret value and I will decode when used). This would be quite a lot of work, and might not be needed. I will assess based on feedback.

**Comment by freddydk** [comment]
I will mark the bug as fixed, as it will no longer reveal your secrets, knowing that you will have to change your URL to NOT contain special characters.

**Comment by freddydk** [comment]
Released in preview

**Comment by freddydk** [comment]
Shipped in v1.5
