### ISSUE TITLE
[Bug]: App signing fails

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#1310]
### AL-Go version

6.1

### Describe the issue

Today I've created a new app and signing failed. Because we havn't had any issues signing apps before. I've tested another app. First I stared a build to confirm signing still works and there are no issues with the runner. AL-Go v6 signed the apps correctly. I then upgraded that app to 6.1 and the signing fails with the following error.  
```
Error: Unexpected error when running action. Error Message: Failed to install signing tool. If you are using a self-hosted runner please make sure you've followed all the steps described in https://aka.ms/algosettings#runs-on., StackTrace: at Install-SigningTool, C:\3\_work\_actions\microsoft\AL-Go-Actions\v6.1\Sign\Sign.psm1: line 40 <- at Invoke-SigningTool, C:\3\_work\_actions\microsoft\AL-Go-Actions\v6.1\Sign\Sign.psm1: line 111 <- at <ScriptBlock>, C:\3\_work\_actions\microsoft\AL-Go-Actions\v6.1\Sign\Sign.ps1: line 69 <- at <ScriptBlock>, C:\3\_work\_temp\ecde9eca-62d6-4a0b-bdfb-cadd831bce0b.ps1: line 3 <- at <ScriptBlock>, C:\3\_work\_actions\microsoft\AL-Go-Actions\v6.1\Invoke-AlGoAction.ps1: line 17 <- at <ScriptBlock>, C:\3\_work\_temp\ecde9eca-62d6-4a0b-bdfb-cadd831bce0b.ps1: line 2 <- at <ScriptBlock>, <No file>: line 1
```

### Expected behavior

Signing should work.

### Steps to reproduce

Run a 6.1 build with signing.

**Comment by freddydk** [comment]
Strange - signing works perfectly here.
Can you share a bit more of your log?

**Comment by freddydk** [comment]
It couldn't be a new version of dotnet sign requiring a new version of dotnet on your runner?
This commit: https://github.com/microsoft/AL-Go/commit/df9e7c1c11c02e7db70276ba31d22f668fd76acb
increases the dotnet sign version requirement - but also should display the output of the install - isn't that visible in the log?

**Comment by jonaswre** [comment]
I checked the logs again. And you are right v6.1 no longer supports .net6.0 on the host runner.

**Comment by jonaswre** [comment]
Installing .net8 fixed it.

**Comment by freddydk** [comment]
[like]  Freddy Kristiansen reacted to your message:
________________________________
