### ISSUE TITLE
[Question]: trustedSigning Identity validation public vs private

### ISSUE THREAD

**Issue by louagej** [microsoft/AL-Go#1342]
### Question

Hi,

In the release [6.1](https://github.com/microsoft/AL-Go/blob/9dbee17f636ca9ba2649b45adc2b65f4fd66af84/RELEASENOTES.md#v61) there is mentioned that we have the possibility to add `trustedSigning` linked to the Azure Trusted Signing.
On the Directions in Vienna, there was mentioned that we should setup a new public Identity validation.
![Image](https://github.com/user-attachments/assets/3b369b9b-74f0-4d98-93c0-173c61ca471b)

Is it possible to have a private identity for this setting as well?
I ask this because in the [Microsoft Learn documentation](https://learn.microsoft.com/en-us/azure/trusted-signing/quickstart?tabs=registerrp-portal%2Caccount-portal%2Corgvalidation%2Ccertificateprofile-portal%2Cdeleteresources-portal#important-information-for-public-identity-validation) it is mentioned the Trusted Signing at this time can onboard only legal business entities that have verifiable tax history of three or more years.
Since I only started at the beginning of this year with my business, this will not be possible for me to create a public identity validation.

**Comment by freddydk** [comment]
I don't know what a private identity means - it is not requirements we (Business Central Team) sets.
You can try to reach out to azure support to see what you can do.
In order to do proper codesigning - we do need a trusted certificate (not self-signed or test)

**Comment by larswestman** [comment]
I think you should go for public (I did)

https://learn.microsoft.com/en-us/azure/trusted-signing/concept-trusted-signing-resources-roles#certificate-profiles

**Comment by louagej** [comment]
Hi,

According the [Microsoft Learn documentation](https://learn.microsoft.com/en-us/azure/trusted-signing/quickstart?tabs=registerrp-portal%2Caccount-portal%2Corgvalidation%2Ccertificateprofile-portal%2Cdeleteresources-portal#important-information-for-public-identity-validation) , I should have verifiable tax history of three or more years.
Unfortunately, 3 years is not something I can magically create.

**Comment by louagej** [comment]
Certificate profile was approved... so the remark `have verifiable tax history of three or more years` is not that strict.
