### ISSUE TITLE
[Question]: Setting up Trusted Signing (got an error after I did that)

### ISSUE THREAD

**Issue by larswestman** [microsoft/AL-Go#1348]
### Question

I have tried to set up trusted signing according to instructions using a managed identity to authenticate to Azure. The managed identity works since I can use it to fetch the license file from an Azure secret. It also has the role of a Profile Signer on the signing account so that should be OK. 

I have this in my settings.json: "trustedSigning": {"Account": "MyAccuntName", "Endpoint": "https://neu.codesigning.azure.net/", "CertificateProfile": "MyCertProfileName"}

The sign step fails during CI/CD with this error:

`
Error: Unexpected error when running action. Error Message: Nuget source https://api.nuget.org/v3/index.json is not added. Please add the source using 'dotnet nuget add source https://api.nuget.org/v3/index.json' or add another source with nuget.org as an upstream source., StackTrace: at AssertNugetSourceIsAdded, C:\ltcbc-tasklet-runner\_work\_actions\microsoft\AL-Go-Actions\v6.1\Sign\Sign.psm1: line 9 <- at Install-SigningTool, C:\ltcbc-tasklet-runner\_work\_actions\microsoft\AL-Go-Actions\v6.1\Sign\Sign.psm1: line 37 <- at Invoke-SigningTool, C:\ltcbc-tasklet-runner\_work\_actions\microsoft\AL-Go-Actions\v6.1\Sign\Sign.psm1: line 111 <- at <ScriptBlock>, C:\ltcbc-tasklet-runner\_work\_actions\microsoft\AL-Go-Actions\v6.1\Sign\Sign.ps1: line 69 <- at <ScriptBlock>, C:\ltcbc-tasklet-runner\_work\_temp\5939f060-8ddf-47de-b5ea-caeb3adf5e60.ps1: line 3 <- at <ScriptBlock>, C:\ltcbc-tasklet-runner\_work\_actions\microsoft\AL-Go-Actions\v6.1\Invoke-AlGoAction.ps1: line 17 <- at <ScriptBlock>, C:\ltcbc-tasklet-ru
Error: Process completed with exit code 1.
`

What am I missing here?

**Comment by aholstrup1** [comment]
Can you try this? 
https://github.com/microsoft/AL-Go/issues/1252#issuecomment-2408915315

**Comment by larswestman** [comment]
Installing .Net SDK on the runner server and adding the nuget source solved it!

`dotnet nuget add source https://api.nuget.org/v3/index.json`
