### ISSUE TITLE
[Question]: ubuntu-24.04

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#1354]
### Question

Hey @freddydk, 

As you probably have seen we do receive warnings regarding upcoming ubuntu update:

> ubuntu-latest pipelines will use ubuntu-24.04 soon. For more details, see https://github.com/actions/runner-images/issues/10636

If you check that ticket number, you will see that they are removing nuget.exe from the image.  Is it going to be an issue for our pipelines?
 
![Image](https://github.com/user-attachments/assets/ce5afbf2-50b5-4fd1-99b8-498404a562e5)

**Comment by freddydk** [comment]
I am actually running tests on 24.04 right now - I don't think that the missing nuget will be a problem

**Comment by freddydk** [comment]
All Linux tests looks green https://github.com/microsoft/AL-Go/actions/runs/12253292365 - a few tests are failing, but that happens sometimes - they will likely pass when I re-run
So, even though the list of included software has decreased quite a bit, we should be good to go.

**Comment by gntpet** [comment]
hey @freddydk,

I see that it runs tests using old image. I think you should have change from ubuntu-latest to ubuntu-24.04, and then executed tests. 

![Image](https://github.com/user-attachments/assets/1da5a1da-dc99-493d-a54b-524d2e700a06)

**Comment by freddydk** [comment]
Nope - this is the test runner (or the orchestrator) - the actual tests are running 24.04:
![Image](https://github.com/user-attachments/assets/50cd8ceb-89b0-4e87-bc29-36d2e8dc07c7)

And the orchestrator most certainly will have no problems with Ubuntu-24.04 - it uses nothing really.
