### ISSUE TITLE
[Question]: how to allow reusing containers on self-hosted runners

### ISSUE THREAD

**Issue by ZackaryW** [microsoft/AL-Go#1360]
### Question

![Image](https://github.com/user-attachments/assets/cda5e2ad-1cc9-44d5-9021-b4605b9a1d84)

**Comment by freddydk** [comment]
That is a part of BcContainerHelper functionality, which we have not adopted in AL-Go for GitHub at this time.
AL-Go for GitHub will automatically build and cache images on self-hosted runners.

**Comment by ZackaryW** [comment]
thanks for responding,
giving that we only intend to build in house extensions serving our own purpose. 

Is there a way to improve the speed of building and deploying by either drastically increase the speed of self-hosted runner or completely bypass using containers similar to how the vscode extension (al-go) is able to build the app (by downloading symbols)

**Comment by freddydk** [comment]
If you add these settings:

```
"useCompilerFolder": true,
"doNotPublishApps": true
```

AL-Go will avoid using containers and instead use a mechanism called CompilerFolder to do the compile.
Additionally, AL-Go will use the GitHub cache to cache the read artifacts, saving time there as well.
Lastly you can then choose to use GitHub hosted Linux runners by setting "runs-on" and "gitHubRunner" to "ubuntu-latest" which are faster and half the price of windows runners - that might be cheaper than maintaining self-hosted runners.
