### ISSUE TITLE
[Bug]: CI/CD Pipelines Failing with Internal Error After Initialization Stage

### ISSUE THREAD

**Issue by ivandjordjevic** [microsoft/AL-Go#1364]
### AL-Go version

6.1

### Describe the issue

Our CI/CD pipelines have stopped working unexpectedly and without any changes on our end. It happens for multiple repositories.

While other workflows like pull requests, test-current, test-nextminor, and test-nextmajor are running without any issues, the CI/CD pipelines consistently fail. 

After the Initialization stage, we encounter the following error during the Matrix: Build stage:
`"GitHub Actions has encountered an internal error when running your job."`
![Image](https://github.com/user-attachments/assets/30156b92-6f4b-4cc1-b9ad-6b57f08775fa)
![Image](https://github.com/user-attachments/assets/105ddb35-2b39-40bc-b44b-e1aaf11745e7)

The Build stage for the project is no longer executed.

### Expected behavior

The CI/CD pipeline should execute successfully, as it did previously, without encountering internal errors.

### Steps to reproduce

1. Created a PTE repository with AL-go template.
2. Our CI/CD pipeline executed successfully two weeks ago.
3. No changes have been made to the repository since the last successful execution.
4. Manually trigger the CI/CD pipeline.
5. Fails with an internal error after the Initialization Stage. The error does not provide details on the issue or resolution.
7. The same issue occurs in other repositories as well, but other workflows are executing successfully,

### Additional context (logs, screenshots, etc.)

[Initialization.txt](https://github.com/user-attachments/files/18148384/Initialization.txt)
[CheckForUpdates.txt](https://github.com/user-attachments/files/18148391/CheckForUpdates.txt)
[PostProcess.txt](https://github.com/user-attachments/files/18148394/PostProcess.txt)

**Comment by freddydk** [comment]
Could you try to run the TroubleShooting workflow - it seems like there is a problem with some secrets which have been made available to the repository. These secrets seems to be wrongly formatted, meaning that some of the variables AL-Go transfers from one job to another are suddenly seen as containing secrets:

```
2024-12-16T10:10:51.6423431Z ##[warning]Skip output 'projectDependenciesJson' since it may contain secret.
2024-12-16T10:10:51.6424929Z ##[warning]Skip output 'buildOrderJson' since it may contain secret.
```

If you have a secret, which contains line breaks, then the character `{` might suddenly be seen as a secret and this would break AL-Go for GitHub

Troubleshoot should tell you if any secrets like this exists.

**Comment by ivandjordjevic** [comment]
@freddydk That's definitely a step in the right directions. I didn't know there is a troubleshooting WF, nice feature btw. Thanks!

I don't have access to all of the organization secrets so I'll need to verify first with the team.

The troubleshooting is giving me this warning so it's likely the case:
`- Warning: Secret <redacted> contains line breaks. JSON formatted secrets available to AL-Go for GitHub should be compressed JSON (i.e. NOT contain any line breaks).`

[Troubleshooting.txt](https://github.com/user-attachments/files/18149997/Troubleshooting.txt)

**Comment by freddydk** [comment]
It is likely the Azure_Credentials secret, which isn't compressed.
This means the a number of characters are now seen as secrets and values transferred back and forth between jobs are hidden to avoid exposing secrets.

JSON structured secrets needs to be compressed.

**Comment by freddydk** [comment]
BTW - it is a good rule of thumb that organizational secrets are only made available to repositories which actually needs them (which could also be the reason for this problem for you).

**Comment by ivandjordjevic** [comment]
Thanks, that resolved the issue!
