### ISSUE TITLE
Deploy to multiple tenants with same environment names

### ISSUE THREAD

**Issue by achim-t** [microsoft/AL-Go#142]
How can I deploy to multiple tenants, when the environments have the same name? 

In Github I can create an environment "sandbox" and add a secret AUTHCONTEXT which includes the tenant id. For the next tenant I would have to create another environment "sandbox". I tried to give it another name, but then deploy fails, because the environment can't be found. How can I set the environmentName to something different than the name of the Github environment?

**Comment by freddydk** [comment]
https://freddysblog.com/2022/05/06/deployment-strategies-and-al-go-for-github/

You can name your environments in github as customer1_sandbox and customer2_sandbox and then create a secret called environmentName underneath the environment with the actual BC saas environment
