### ISSUE TITLE
Commit Message for "Increment Version Number" workflow

### ISSUE THREAD

**Issue by achim-t** [microsoft/AL-Go#143]
I used +0.1 to only increment the minor version.

[commit](https://github.com/achim-t/solid-rotary-phone/commit/8d2e65d27d8ab5ac98123b4ed2b388bd4985db1f)

The commit message reads `'New Version number 0.1'` when it should read `'New Version number 1.1'`. 

(`'New Version number +0.1'` might be acceptable as well.)

Also, the .json files is are formatted differently from the VS Code formatter. It looks like the change is much bigger than it actually is.

**Comment by freddydk** [comment]
Will fix the commit message bug

The .json files are formatted using the PowerShell ConvertTo-Json - I don't think I can influence that, meaning that the first time you do this, it will look like this. Not sure I can do much about that.
In the Pull Request you can click: Ignore WhiteSpace changes.

VS Code doesn't format unless you ask specifically about it.

**Comment by freddydk** [comment]
The message will be

Increment Version number by 0.1

if you used the incremental step and

New Version number 1.1

if you use the absolute

**Comment by freddydk** [comment]
Shipped in v2.0
