### ISSUE TITLE
Create App fails without sample code

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/AL-Go#144]
I have just tried to create a new app without sample code and it fails with this error
![image](https://user-images.githubusercontent.com/24838311/171329278-ee0a33db-6519-4fad-895b-c5d068a33ad3.png)

Its on version 1.5

**Comment by StefanMaron** [comment]
The Action works with the exact same settings when I run it with sample code

**Comment by freddydk** [comment]
I have hotfixed this issue.
