### ISSUE TITLE
Question: Run-ALValidation

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/AL-Go#151]
Is there a way to run Run-ALValidation for appsource apps?
I did not find an Action for this and doesnt seem to be included in the current CI/CD

**Comment by freddydk** [comment]
I have been debating a lot with myself whether or not to add this to the AppSource template as a separate workflow, which you could add a schedule to. Today it isn't there.

**Comment by StefanMaron** [comment]
thanks, So I might look into creating an Action for this myself :)

**Comment by freddydk** [comment]
In the preview, you will find that you can do Continuous Delivery to AppSource Validation.
It will never invoke the Go-Live, but it will leave the app ready to go-live.
