### ISSUE TITLE
Error when loading dependencies from releases

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/AL-Go#152]
I am currently seeing problems with the download of dependencies within the same repo but different project.

The appDependencyProbingPaths is set like this.
(I tried to add "latestBuild" but that made it even worse)

![image](https://user-images.githubusercontent.com/24838311/171837370-d9207e31-8001-47b3-bcf0-3d57419a7c36.png)

The log look like this:
![image](https://user-images.githubusercontent.com/24838311/171837527-0829629a-17d3-48f1-9d1f-9bc61ea7bb44.png)

Judging from the comments, the script fails in this line:

https://github.com/microsoft/AL-Go/blob/45b834f0569f2f1d79c776ef7c4ad80f70008165/Actions/Github-Helper.psm1#L371

**Comment by freddydk** [comment]
I am actually working on this right now (ran into this myself as well)

**Comment by freddydk** [comment]
This should be fixed in preview

This project: https://github.com/BusinessCentralApps/DependencyDemo is an example of having dependencies to both a public and a private repo (one that you obviously cannot see)

**Comment by freddydk** [comment]
Shipped in v2.0
