### ISSUE TITLE
Question - considering of git clone to add existing app

### ISSUE THREAD

**Issue by Koubek** [microsoft/AL-Go#154]
Hello Freddy,

I can see you are using *secure URL* approach to get the remote content. Have you been considering using `git clone` to achieve that goal? Maybe I am missing something, maybe there are some valid reasons for using (only) the existing manner.

Thanks!!!

**Comment by freddydk** [comment]
the add existing app can be run 5 times to extract just the app and add that.
You can also drag and drop your source files directly on-to github.com.

I have thought about adding support for other mechanisms to provide the app, git clone could certainly be one to extract whatever apps are available in that repo
