### ISSUE TITLE
Initial Add existing app fails with "Cannot find path"

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#155]
Just getting started here: after resolving an error too embarrassing to recount, I am getting a "Cannot find path" that I do not understand. I am using the Dropbox download URL hack that you described. Have I left something out of setup? Here is the full log of the "Update" segment:

Run microsoft/AL-Go-Actions/AddExistingApp@v1.5
Run try { D:\a\_actions\microsoft\AL-Go-Actions\v1.5\AddExistingApp/AddExistingApp.ps1 -actor 'buzzwick' -token '***' -parentTelemetryScopeJson '{"Parameters":{},"Emitted":false,"CorrelationId":"b4abc177-8be3-4165-[9](https://github.com/buzzwick/Upstate-Coin/runs/6793790923?check_suite_focus=true#step:2:10)ced-e1585c49bc46","ParentId":"","AllParameters":{},"TopId":"b4abc177-8be3-4165-9ced-e1585c49bc46","Name":"AL-Go workflow ran: AddExistingAppOrTestApp","StartTime":"\/Date(1654692539044)\/","Properties":{"eventId":"DO0090","bcContainerHelperVersion":"3.0.10","isAdministrator":"True","stackTrace":"[\n  InitTelemetryScope at TelemetryHelper.ps1: line 212\n  CreateScope at TelemetryHelper.psm1: line 44\n  WorkflowInitialize.ps1 at WorkflowInitialize.ps1: line 37\n  8094155c-678a-42d6-9d5b-8b86efa85925.ps1 at 8094155c-678a-42d6-9d5b-8b86efa85925.ps1: line 1\n  \u003cScriptBlock\u003e at \u003cNo file\u003e\n]","repository":"66CD3F8766B3351220F7BF694C6D0E51ED306B365A98B3C63ABE7A4B51643077","runAttempt":"1","runNumber":"9","runId":"2461591682"},"EventId":"DO0090"}' -project '.' -url 'https://www.dropbox.com/s/qddpaeetkb8isaox1/Upstate%20Coin.zip?dl=1' -directCommit ('N' -eq 'Y') } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message))"; exit 1 }
git config --global user.email buzzwick@users.noreply.github.com
git config --global user.name buzzwick
git config --global hub.protocol https
git clone ***github.com/buzzwick/Upstate-Coin
Cloning into 'Upstate-Coin'...
git checkout -b k1fwc1fg.utd
Switched to a new branch 'k1fwc1fg.utd'
Downloading BcContainerHelper latest version
BcContainerHelper version 3.0.10
BcContainerHelper emits usage statistics telemetry to Microsoft
Reading .github\AL-Go-Settings.json
Reading .AL-Go\settings.json
Downloading C:\Users\RUNNER\~1\AppData\Local\Temp\9365abc6-69c2-483b-af76-f48bdbdcc090.app
C:\Users\RUNNER\~1\AppData\Local\Temp\8dca50f0-5f15-4b[14](https://github.com/buzzwick/Upstate-Coin/runs/6793790923?check_suite_focus=true#step:2:16)-ac44-41b0c78ef28a -> C:\Users\RUNNER\~1\AppData\Local\Temp\16bf2fbe-11fe-495e-bf4e-bd5f21bdc472
done
Error: Couldn't add an existing app.
 Cannot find path 'C:\Users\RUNNER\~1\AppData\Local\Temp\8dca50f0-5f[15](https://github.com/buzzwick/Upstate-Coin/runs/6793790923?check_suite_focus=true#step:2:17)-4b14-ac44-41b0c78ef28a' because it does not exist.
AL-Go action ran: AddExistingApp Telemetry Correlation Id: b9fa576e-8101-4a78-8[21](https://github.com/buzzwick/Upstate-Coin/runs/6793790923?check_suite_focus=true#step:2:23)0-dc2eaf56f80f
Removing BcContainerHelper
Error: Process completed with exit code 1.

**Comment by freddydk** [comment]
The reason for this is, that your .zip file contains both the source of an app and an .app file.
If you remove the .app file from the .zip file and retry - it should work.
I will fix this bug for the next release.

**Comment by buzzwick** [comment]
I was off for a couple of days last week. Tried this again, without the .app file, but seems I run into the same error. Is there something not right about the Dropbox download?

Run microsoft/AL-Go-Actions/AddExistingApp@v1.5
Run try { D:\a\_actions\microsoft\AL-Go-Actions\v1.5\AddExistingApp/AddExistingApp.ps1 -actor 'buzzwick' -token '***' -parentTelemetryScopeJson '{"Parameters":{},"Emitted":false,"CorrelationId":"0[9](https://github.com/buzzwick/Upstate-Coin/runs/6861553837?check_suite_focus=true#step:2:10)b08dd7-e209-474a-847b-f963288b7c6b","ParentId":"","AllParameters":{},"TopId":"09b08dd7-e209-474a-847b-f963288b7c6b","Name":"AL-Go workflow ran: AddExistingAppOrTestApp","StartTime":"\/Date(1655124432805)\/","Properties":{"eventId":"DO0090","bcContainerHelperVersion":"3.0.10","isAdministrator":"True","stackTrace":"[\n  InitTelemetryScope at TelemetryHelper.ps1: line 212\n  CreateScope at TelemetryHelper.psm1: line 44\n  WorkflowInitialize.ps1 at WorkflowInitialize.ps1: line 37\n  1fc96cf6-6cdc-44e6-bb88-3fda8226b6b9.ps1 at 1fc96cf6-6cdc-44e6-bb88-3fda8226b6b9.ps1: line 1\n  \u003cScriptBlock\u003e at \u003cNo file\u003e\n]","repository":"66CD3F8766B3351220F7BF694C6D0E51ED306B365A98B3C63ABE7A4B51643077","runAttempt":"1","runNumber":"10","runId":"2488434993"},"EventId":"DO0090"}' -project '.' -url 'https://www.dropbox.com/s/c70drcolkoxt9l6/Upstate%20Coin.zip?dl=1' -directCommit ('N' -eq 'Y') } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message))"; exit 1 }
Cloning into 'Upstate-Coin'...
git config --global user.email buzzwick@users.noreply.github.com
git config --global user.name buzzwick
git config --global hub.protocol https
git clone ***github.com/buzzwick/Upstate-Coin
git checkout -b ls5ij2py.rhb
Switched to a new branch 'ls5ij2py.rhb'
Downloading BcContainerHelper latest version
BcContainerHelper version 3.0.10
BcContainerHelper emits usage statistics telemetry to Microsoft
Reading .github\AL-Go-Settings.json
Reading .AL-Go\settings.json
Downloading C:\Users\RUNNER~1\AppData\Local\Temp\2ddc982f-e992-49[12](https://github.com/buzzwick/Upstate-Coin/runs/6861553837?check_suite_focus=true#step:2:14)-a817-ad4a5a94721b.app
C:\Users\RUNNER\~1\AppData\Local\Temp\53fe70f6-55d7-4100-97de-3d5d9ea0c675 -> C:\Users\RUNNER\~1\AppData\Local\Temp\e7e7dd65-5eb6-454e-923f-1f1ed2e052f3
done
Error: Couldn't add an existing app.
 Cannot find path 'C:\Users\RUNNER\~1\AppData\Local\Temp\53fe70f6-55d7-4100-97de-3d5d9ea0c675' because it does not exist.
AL-Go action ran: AddExistingApp Telemetry Correlation Id: 8aa5b4b1-03b1-4e26-bc23-76dd9d[16](https://github.com/buzzwick/Upstate-Coin/runs/6861553837?check_suite_focus=true#step:2:18)5a4a
Removing BcContainerHelper
Error: Process completed with exit code 1.

**Comment by freddydk** [comment]
This is fixed in preview

**Comment by buzzwick** [comment]
Wonderful, thank you. If I recall, there is a Workflow to update the scripts in my working repository. How do we track when Preview has become the released version?

**Comment by freddydk** [comment]
When the new version is released, you will get a notification in your CI/CD workflows
The CheckForUpdates jub will emit a warning stating that there are updated AL-Go system files.

**Comment by buzzwick** [comment]
Brilliant. Thank you.

**Comment by freddydk** [comment]
Shipped in v2.0
