### ISSUE TITLE
versioningStrategy 2 seems to not use 24h format

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/AL-Go#156]
when running a build in the morning and in the after noon the second build fails because the version no is lower that the one in the morning:

this revision no should be 132032

![image](https://user-images.githubusercontent.com/24838311/172628818-f83a4c26-065a-4c12-983a-f672b812c3c8.png)

Also, the format should always be HHMMSS. I think that in this example the leading zero is cut off

**Comment by StefanMaron** [comment]
Update:
When you change the `hh` to capital, it should work
`[Int32]([DateTime]::UtcNow.ToString('HHmmss'))`

https://github.com/microsoft/AL-Go/blob/413bd8697728dffb9ebd13f61ecc5f54fdf3388c/Actions/ReadSettings/ReadSettings.ps1#L69

capital `HH` is for 24h format and lowercase for 12h format. 
If I think about it, the leading zero is proably not needed, since the parts of the version are more like integer than text.

**Comment by freddydk** [comment]
Will fix this to HHmmss as Stefan suggests.
The leading zero is not needed as the version numbers are sorted numerically and not alfabetically.
Will be in a preview release today or during the weekend.

**Comment by freddydk** [comment]
This is fixed in preview

**Comment by freddydk** [comment]
Shipped in v2.0
