### ISSUE TITLE
AL-Go-PTE CI/CD workflow issue

### ISSUE THREAD

**Issue by vvkjndl** [microsoft/AL-Go#158]
Hi @freddydk 

Most likely I am doing something wrong as I am still new to your AL-Go project and still trying to figure things out.

As per our organization's current use case, as of now we want to use AL-Go only to deploy apps on our customer tenants. We are not currently planning to move the remaining development processes to GitHub/AL-Go yet.

With that in mind, I created a template from microsoft/AL-Go-PTE repository, added a pre-compiled application from our Azure Blob Storage using the work flow `AddExistingAppOrTestApp.yaml`. The workflow decompiled the application back to source code and added the folder to the repository.

Then I ran the `CICD.yaml` workflow to publish the artifacts that could be used later on by workflow `PublishToEnvironment.yaml`.

I am getting this error in CD/CD workflow.

```
Using Version 2020.10.12.0
  Using Symbols Folder: D:\a\ATRC\ATRC\.packages
  Downloading symbols: Microsoft_Application_20.2.41144.42022.app
  Url : http://172.27.140.104:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=17.0.0.0&tenant=default
  Adding dependency to System Application from Microsoft
  Adding dependency to Base Application from Microsoft
  Downloading symbols: Microsoft_System_20.0.41086.41991.app
  Url : http://172.27.140.104:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=17.0.0.0&tenant=default
  Downloading symbols: Microsoft_System Application_20.2.41144.42022.app
  Url : http://172.27.140.104:7049/BC/dev/packages?publisher=Microsoft&appName=System%20Application&versionText=20.2.0.0&tenant=default
  Downloading symbols: Microsoft_Base Application_20.2.41144.42022.app
  Url : http://172.27.140.104:7049/BC/dev/packages?publisher=Microsoft&appName=Base%20Application&versionText=20.2.0.0&tenant=default
  Compiling...
  .\alc.exe /project:"c:\sources\YIBASE - Base App" /packagecachepath:"c:\sources\.packages" /out:"c:\sources\.output\iNECTA LLC_YIBASE - Base App_2020.10.12.0.app" /analyzer:C:\build\vsix\extension\bin\Analyzers\Microsoft.Dynamics.Nav.PerTenantExtensionCop.dll /assemblyprobingpaths:"C:\Program Files (x86)\Microsoft Dynamics NAV\200\RoleTailored Client","C:\Program Files\Microsoft Dynamics NAV\200\Service","C:\Program Files (x86)\Open XML SDK\V2.5\lib","c:\Windows\Microsoft.NET\Assembly","C:\Test Assemblies\Mock Assemblies"
  Microsoft (R) AL Compiler version 9.2.9.37800
  Copyright (C) Microsoft Corporation. All rights reserved
  
  Compilation started for project 'YIBASE - Base App' containing '1079' files at '16:10:00.453'.
  
  warning PTE0014: The XML file 'c:\sources\YIBASE - Base App\file0_extensionsPermissionSet.xml' should not contain Permissions or Permission Sets. Instead, use the dedicated AL object 'PermissionSet'.
  
  Compilation ended at '16:10:29.298'.
  
  D:\a\ATRC\ATRC\.output\iNECTA LLC_YIBASE - Base App_2020.10.12.0.app successfully created in 54 seconds
  iNECTA LLC_YIBASE - Base App_2020.10.12.0.app copied to D:\a\ATRC\ATRC\.packages
  Using Version 16.0.12.0
  Using Symbols Folder: D:\a\ATRC\ATRC\.packages
  Downloading symbols: iNECTA LLC_YIBASE - Base App_2020.10.12.3.app
  Url : http://172.27.140.104:7049/BC/dev/packages?publisher=iNECTA%20LLC&appName=YIBASE%20-%20Base%20App&versionText=2020.10.12.3&tenant=default
  ERROR The remote server returned an error: (404) Not Found.
  Compile-AppInBcContainer Telemetry Correlation Id: 55374dd3-908f-4d9e-a068-bed26efd97c8
Removing Container
Run-AlPipeline Telemetry Correlation Id: 8ed8cc57-609f-415a-bd67-ff510e52ad65
Error: The remote server returned an error: (404) Not Found. No published package matches the provided arguments.
AL-Go action ran: RunPipeline Telemetry Correlation Id: 71601ac0-6c13-4ec9-9e61-fda63e2f7178
Removing BcContainerHelper
Error: Process completed with exit code 1.
```

**Comment by freddydk** [comment]
You would probably be easier off just using the Publish-PerTenantExtensionApps in the repo, where you build your app.
AL-Go for GitHub is an end 2 end tool - disassembling and using parts is not recommended and will probably cause you more issues in the long run.

**Comment by vvkjndl** [comment]
I will be taking care of the remaining processes through automation to make look like it's end-to-end on AL-Go repositories.

I was just not sure about this error. Shouldn't the CI/CD workflow performing the install of compiled app on container before proceeding with downloading symbols again?

```
 D:\a\ATRC\ATRC\.output\iNECTA LLC_YIBASE - Base App_2020.10.12.0.app successfully created in 54 seconds
  iNECTA LLC_YIBASE - Base App_2020.10.12.0.app copied to D:\a\ATRC\ATRC\.packages
  Using Version 16.0.12.0
  Using Symbols Folder: D:\a\ATRC\ATRC\.packages
  Downloading symbols: iNECTA LLC_YIBASE - Base App_2020.10.12.3.app
  Url : http://172.27.140.104:7049/BC/dev/packages?publisher=iNECTA%20LLC&appName=YIBASE%20-%20Base%20App&versionText=2020.10.12.3&tenant=default
  ERROR The remote server returned an error: (404) Not Found.
```

**Comment by freddydk** [comment]
During compilation phase it places the app files in the symbols folder so that it doesn't need to download the symbols.

**Comment by freddydk** [comment]
The flow of Run-AlPipeline is something like this:

1. Create Container
2. Install pre-requisites
3. Compile all apps in order of dependencies (download symbols from container for base app and other pre-reqs. Copy all apps to symbols folder after compile - ready for next app to be compiled)
4. Install test pre-requisites (and test toolkit)
5. Compile all test apps
6. Install previous version of apps in order of dependencies (if exists)
7. Upgrade or Install apps in order of dependencies
8. Install test apps
9. run tests
10. run bcpt tests

**Comment by freddydk** [comment]
You cannot control the parameters to Run-AlPipeline.
You can override some of the commands that Run-AlPipeline is using:

https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md#expert-level

but note that the more of these very special tweaks you are using, the more certain you are to be broken when a new release of AL-Go is shipped.

**Comment by vvkjndl** [comment]
My CI/CD workflow problem got resolved by adding an empty parameter of `installApps` to `.AL-Go/settings.json` file.

"installApps":  [
    ],

Strange, maybe Read-Settings script needs a fixing or we can add this empty parameter to the template itself.

**Comment by vvkjndl** [comment]
@freddydk I have two identicial AL-Go-PTE repositories. I have verified by diff that both are completely identical.

In one repo the CI/CD workflow is working fine and in other repository CI/CD workflow is failing on same error I mentioned earlier in this thread.

```
  Using Version 2020.10.7.0
  Using Symbols Folder: D:\a\ATRC\ATRC\.packages
  Downloading symbols: Microsoft_Application_20.2.41144.42689.app
  Url : http://172.21.150.78:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=17.0.0.0&tenant=default
  Adding dependency to System Application from Microsoft
  Adding dependency to Base Application from Microsoft
  Downloading symbols: Microsoft_System_20.0.41086.42556.app
  Url : http://172.21.150.78:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=17.0.0.0&tenant=default
  Downloading symbols: Microsoft_System Application_20.2.41144.42689.app
  Url : http://172.21.150.78:7049/BC/dev/packages?publisher=Microsoft&appName=System%20Application&versionText=20.2.0.0&tenant=default
  Downloading symbols: Microsoft_Base Application_20.2.41144.42689.app
  Url : http://172.21.150.78:7049/BC/dev/packages?publisher=Microsoft&appName=Base%20Application&versionText=20.2.0.0&tenant=default
  Compiling...
  .\alc.exe /project:"c:\sources\YIBASE - Base App" /packagecachepath:"c:\sources\.packages" /out:"c:\sources\.output\iNECTA LLC_YIBASE - Base App_2020.10.7.0.app" /analyzer:C:\build\vsix\extension\bin\Analyzers\Microsoft.Dynamics.Nav.PerTenantExtensionCop.dll /assemblyprobingpaths:"C:\Program Files (x86)\Microsoft Dynamics NAV\200\RoleTailored Client","C:\Program Files\Microsoft Dynamics NAV\200\Service","C:\Program Files (x86)\Open XML SDK\V2.5\lib","c:\Windows\Microsoft.NET\Assembly","C:\Test Assemblies\Mock Assemblies"
  Microsoft (R) AL Compiler version 9.2.9.49054
  Copyright (C) Microsoft Corporation. All rights reserved
  
  Compilation started for project 'YIBASE - Base App' containing '1079' files at '12:41:09.278'.
    
  Compilation ended at '12:41:30.409'.
  
  D:\a\ATRC\ATRC\.output\iNECTA LLC_YIBASE - Base App_2020.10.7.0.app successfully created in 44 seconds
  iNECTA LLC_YIBASE - Base App_2020.10.7.0.app copied to D:\a\ATRC\ATRC\.packages
  Using Version 16.0.7.0
  Using Symbols Folder: D:\a\ATRC\ATRC\.packages
  Downloading symbols: iNECTA LLC_YIBASE - Base App_2020.10.12.3.app
  Url : http://172.21.150.78:7049/BC/dev/packages?publisher=iNECTA%20LLC&appName=YIBASE%20-%20Base%20App&versionText=2020.10.12.3&tenant=default
  ERROR The remote server returned an error: (404) Not Found.
  Compile-AppInBcContainer Telemetry Correlation Id: a4730990-b3f4-4664-86de-b3a4de9dee52
```


```
  Using Version 2020.10.17.0
  Using Symbols Folder: D:\a\ATRC-Old02\ATRC-Old02\.packages
  Downloading symbols: Microsoft_Application_20.2.41144.42689.app
  Url : http://172.22.44.226:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=17.0.0.0&tenant=default
  Adding dependency to System Application from Microsoft
  Adding dependency to Base Application from Microsoft
  Downloading symbols: Microsoft_System_20.0.41086.42556.app
  Url : http://172.22.44.226:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=17.0.0.0&tenant=default
  Downloading symbols: Microsoft_System Application_20.2.41144.42689.app
  Url : http://172.22.44.226:7049/BC/dev/packages?publisher=Microsoft&appName=System%20Application&versionText=20.2.0.0&tenant=default
  Downloading symbols: Microsoft_Base Application_20.2.41144.42689.app
  Url : http://172.22.44.226:7049/BC/dev/packages?publisher=Microsoft&appName=Base%20Application&versionText=20.2.0.0&tenant=default
  Compiling...
  .\alc.exe /project:"c:\sources\YIBASE - Base App" /packagecachepath:"c:\sources\.packages" /out:"c:\sources\.output\iNECTA LLC_YIBASE - Base App_2020.10.17.0.app" /analyzer:C:\build\vsix\extension\bin\Analyzers\Microsoft.Dynamics.Nav.PerTenantExtensionCop.dll /assemblyprobingpaths:"C:\Program Files (x86)\Microsoft Dynamics NAV\200\RoleTailored Client","C:\Program Files\Microsoft Dynamics NAV\200\Service","C:\Program Files (x86)\Open XML SDK\V2.5\lib","c:\Windows\Microsoft.NET\Assembly","C:\Test Assemblies\Mock Assemblies"
  Microsoft (R) AL Compiler version 9.2.9.49054
  Copyright (C) Microsoft Corporation. All rights reserved
  
  Compilation started for project 'YIBASE - Base App' containing '1079' files at '12:46:04.366'.
  
  Compilation ended at '12:46:33.955'.
  
  D:\a\ATRC-Old02\ATRC-Old02\.output\iNECTA LLC_YIBASE - Base App_2020.10.17.0.app successfully created in 53 seconds
  iNECTA LLC_YIBASE - Base App_2020.10.17.0.app copied to D:\a\ATRC-Old02\ATRC-Old02\.packages
  Using Version 16.0.17.0
  Using Symbols Folder: D:\a\ATRC-Old02\ATRC-Old02\.packages
  Compiling...
  .\alc.exe /project:"c:\sources\YEXLOT - Extended Lot Management" /packagecachepath:"c:\sources\.packages" /out:"c:\sources\.output\iNECTA LLC_YEXLOT - Extended Lot Management_16.0.17.0.app" /analyzer:C:\build\vsix\extension\bin\Analyzers\Microsoft.Dynamics.Nav.PerTenantExtensionCop.dll /assemblyprobingpaths:"C:\Program Files (x86)\Microsoft Dynamics NAV\200\RoleTailored Client","C:\Program Files\Microsoft Dynamics NAV\200\Service","C:\Program Files (x86)\Open XML SDK\V2.5\lib","c:\Windows\Microsoft.NET\Assembly","C:\Test Assemblies\Mock Assemblies"
  Microsoft (R) AL Compiler version 9.2.9.49054
  Copyright (C) Microsoft Corporation. All rights reserved
```

In second log, you can clearly see that it proceeds with compiling the next app without failing. I am confused how can this occur when two repositories are fully identical.

**Comment by freddydk** [comment]
if you can give me read access to the two repos, then I can have a look.
You can email me the url's

**Comment by vvkjndl** [comment]
@freddydk Would it be possible to have a screen sharing session at a time of your preference?

**Comment by freddydk** [comment]
As already stated, I think you are trying to do something, which AL-Go wasn't intended for.
In general, if people have a problem, which I can see might affect many other partners, then I can do screen sharing to save time for all.
In this case, I think the biggest time saver is for me to have a look at what you have done.

**Comment by vvkjndl** [comment]
@freddydk I have given you read access on both repositories after remove app folders. If you go Actions and examine the CI/CD workflows that was auto-triggered with name "json file formatting", you will see that in old repository CI/CD workflow does complete without any failures. In the new one it fails with the same error that I mentioned in this thread.

Both repositories are completely identical.

In the old repository where the CI/CD workflow is completing successfully, the error was originally there but somehow it's not coming again (you can verify that in previous runs).

**Comment by freddydk** [comment]
Thanks, will try to get the time to have a look over the weekend.

**Comment by freddydk** [comment]
The reason for this is, that "YEXLOT - Extended Lot Management" hase a dependency on Base App 2020.10.12.3 and the app you just built has version 2020.10.9.0. Since no symbols exists in the .packages folder, it tried to download them: 
![image](https://user-images.githubusercontent.com/10775043/175890559-247d6ce8-98c0-45a8-a980-9924c9072c03.png)
In the "old" repo, you have done more builds and the version number has climbed past the version number required, which is why it works.

You might want to investigate version number strategies.

**Comment by freddydk** [comment]
You can remove my access again.

**Comment by vvkjndl** [comment]
Thanks @freddydk for looking into this and your access has been removed.

It took me some time to fully comprehend your comment and pinpoint the exact issue. But hey, I learnt something new i.e. versioning in app.json. Thanks. :)

**Comment by freddydk** [comment]
Yeah, CI/CD is complex, and AL-Go is really trying to make it much simpler for "every-day usage", but it isn't always possible
