### ISSUE TITLE
Problems with Pull Requests

### ISSUE THREAD

**Issue by Koubek** [microsoft/AL-Go#159]
Hello Freddy,

We are experiencing problems with Pull Requests being created during the execution of actions:
```
pull request create failed: GraphQL: GitHub Actions is not permitted to create or approve pull requests (createPullRequest)
```

I have found some (hopefully relevant) issues that could correspond:
https://github.com/cli/cli/issues/1820
https://github.com/cli/cli/issues/1985

We are currently using GitHub in trial mode (GitHub Enterprise Cloud trial) as we are basically exploring possibilities. Not sure if this could correspond somehow but I saw something similar (some limitations) when were checking GitLab in trial mode.

**Comment by freddydk** [comment]
Are you using self-hosted agents?

**Comment by freddydk** [comment]
In your repository, Settings -> Actions -> General, what do you see under workflow permissions:
![image](https://user-images.githubusercontent.com/10775043/173805534-904c5eaa-4ae3-4381-baee-08b0f1dc6e52.png)

and what workflows do you have the problem in?

**Comment by Koubek** [comment]
Sorry I haven't provided these details:
- We run on hosted (default) agents. We currently don't use the trial self-hosted agents.
- We use the latest version of actions.
- I can see the problem was that `Allow GitHub Actions to create and approve pull requests` was disabled on the organization level and then inactive also on the repo level.

I will check this again and let you know. Thanks a lot!!!

**Comment by Koubek** [comment]
I can confirm going to the organization level and activation of `Allow GitHub Actions to create and approve pull requests` made the trick. It's working fine now.

Again, thanks for your quick help!
