### ISSUE TITLE
Next minor and major stopped working last week 

### ISSUE THREAD

**Issue by mail2joh** [microsoft/AL-Go#165]
Hi
I am testing AL-Go for Github and Next minor and major stopped working last week with error.
_Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (400) Bad Request."_
![image](https://user-images.githubusercontent.com/19235259/174628939-a66a8032-19dc-4bdb-b6d3-ecec9213fcf4.png)

I get same error in reproduced repo
* Create repo from template
* Create app
* CI/CD
* next minor or major

inssidersastoken is not changed.
What can be the problem ?

**Comment by freddydk** [comment]
Are you using self-hosted agents?
What OS are they running?
You state that you get the same error in 4 workflows.
The screenshot is from test next major and happens during analyzing artifacts - not all workflows are analyzing artifacts so they must be different errors.
Maybe you have an error in a settings file?

If you can provide me read access to the repo, I will have a look.

**Comment by freddydk** [comment]
The latest containerhelper adds some resilience to the function getting artifacts - this should take care of this problem.
Does the problem still exist?

**Comment by freddydk** [comment]
Looks like something is wrong with the insider sas token secret.
You can promote me to admin and I can have a look.

**Comment by mail2joh** [comment]
I do not know how to promote you admin. This is a personal repo, not a organisation.

**Comment by mail2joh** [comment]
Somehow I changed  InsiderSasToken secret to quotation marks "", when I tested azure keyvault vs. github secret
I have tested several times now with and without quotation marks. 
You can close this issue.
