### ISSUE TITLE
Is it possible to skip CI/CD when you commit code change to main, feature or release branch ?

### ISSUE THREAD

**Issue by mail2joh** [microsoft/AL-Go#167]
Is it possible to skip CI/CD when you commit code change to main, feature or release branch ?
I would like to control if I want to kick of CI/CD or if I want to schedule it instead. Is this possible ?
As I understand I can skip CI/CD if I create a branch with another name like "user/feature" or "user/bugix"...
Is it possible to add in settings "DoNotCDCD" or "SkipCICD" ?

**Comment by freddydk** [comment]
Today, I don't think this is doable.
What would the reason be to do this?

**Comment by mail2joh** [comment]
I want only to not CI/CD when needed. 
For example when I start a new project, before everything works, then I do not want to run CI/CD. But I want to commit code to save it to repo.
Another example is that I want to commit several commits, but really only need to run CI/CD one per day.

As I understand I can create a branch not named release/*, feature/*, to be able to skip CI/CD.

**Comment by freddydk** [comment]
Got it - I will think of a solution for this.

**Comment by mail2joh** [comment]
Thank you

**Comment by mail2joh** [comment]
That sounds great. I Will try it.

**Comment by freddydk** [comment]
Shipped in v2.0
