### ISSUE TITLE
Error when running pipeline for AppSource App with Preview template

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#168]
I am currently using the preview template of the AppSource app AL Go, because of the local dev environment change. I am not sure what other changes are happening in there, but I am running in a new error, which happened only with this repo so far. The error is

Error: RunPipeline action failed. Error: An item with the specified name C:\github-01-1\_work\repo\app\output already exists. Stacktrace: at <ScriptBlock>, C:\github-01-1\_work\_actions\microsoft\AL-Go-Actions\preview\RunPipeline\runpipeline.ps1: line 229 at <ScriptBlock>, C:\github-01-1\_work\_temp\1e0daef1-1c8c-4462-8dd7-a03b8481f69a.ps1: line 1 at <ScriptBlock>, <No file>: line 1

Looking at the script, it fails at:

New-Item $buildArtifactFolder -ItemType Directory | Out-Null

The easiest fix would probably be to test, if it exists before creating it, but I don't know, if anything underlying is causing this different behavior.

**Comment by freddydk** [comment]
Would it be possible to allow me read access to this repo so that I can have a look why this happens.
Thanks

**Comment by freddydk** [comment]
I will change the folder to be named ".dependencies" - and will delete it after the run.
Also, I will add ,dependencies to .gitignore
Names like output should be allowed for people to use themselves - they should not be reserved,

Thanks again for reporting this.

**Comment by freddydk** [comment]
This is fixed in the latest preview.

**Comment by freddydk** [comment]
Please note this: https://freddysblog.com/2022/06/27/working-with-al-go-for-github-preview/
when working with preview versions.

**Comment by freddydk** [comment]
Shipped in v2.0
