### ISSUE TITLE
Create Release - Store in Azure Storage Blob

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#170]
I have configured the AppSource App (the same I had the other issues with) to publish the apps to an Azure Storage Blob during the creation of a release. When I am adding the storage context to the repo as a secret, it runs through and publishes it correctly.

However, when I don't define the secret, but define it in the settings file (having the storage context in a key vault), it does not work.

From what I can see, the CreateRelease.yaml has in PublishToStorage as the first line "if ($ENV:StorageContext)" and I would assume that this is not set/updated from the key vault, but only filled when using the secret.

**Comment by freddydk** [comment]
The storagecontext environment variable should be set by ReadSecrets a little earlier in the workflow.
Should look like this:
![image](https://user-images.githubusercontent.com/10775043/175944757-a9a9ca53-0664-4659-86aa-8e63bfaeadf9.png)

Could you share the output of the workflow?

**Comment by pzentner** [comment]
I actually removed the repo and restarted based on our other conversation about releases for different BC versions. So, I was trying to reproduce this in a new repo to ensure that there was nothing else that I screwed up. However, this doesn't seem to work as I can't get the CICD pipeline to run through as it stops with an error during the RunPipeline (exit code 1 at New-BcImage). Trying to resolve this, then reproduce the issue, and send you the output.

**Comment by pzentner** [comment]
I apologize for the delay, it took me a while to fix the github runner. So, I have the AZURE_CREDENTIALS secret defined and it works when building the app, since it's taking the license, the certificate and everything else from there.

However, when I create a release, I am reviewing the "Read secrets" output and here is the output that is probably the issue:

```
BcContainerHelper emits usage statistics telemetry to Microsoft
Trying to get the secret(StorageContext) from the github environment.
Could not find secret StorageContext in Github secrets or Azure Key Vault.
The following secrets was not found: StorageContext (Secret StorageContext)

```
In the keyvault, I do have this though:

![image](https://user-images.githubusercontent.com/30480594/176547659-f7ea3cac-c181-4eeb-aa71-4e259701035f.png)

and in the .AL-Go/settings.json, I have the following:

![image](https://user-images.githubusercontent.com/30480594/176547793-8ab108ab-8fac-4d91-94b9-247494ef8d0d.png)

**Comment by freddydk** [comment]
Definitely looks like a bug

**Comment by freddydk** [comment]
Strange
When I run Create Release, I see this:

![image](https://user-images.githubusercontent.com/10775043/176603745-201f44eb-7192-4822-95b8-5d914fc26270.png)

Which clearly indicates that it reads the storagecontext from the keyvault.
It can't be a permissions problem as the Create Release workflow is requesting more permissions than the CI/CD workflow.
BTW - you don't need the StorageContextSecretName - that is default.

If you invite me as a collaborator, I can have a look to see what is going wrong

**Comment by pzentner** [comment]
I ran the update of the sustem files yesterday, so it shouldn't be that. But it is weird that it worked for you.

Did you try it on a self hosted runner? I have seen a couple differences, but couldn't pinpoint them, so I didn't report anything. Just wondering, if it's different.

One thing I noticed is that the CI/CD workflow seems to have to times reading the secrets- the normal and from the PR. Does the Create Release one doesn't read the AZURE_CREDENTIALS one correctly? But that then would mean, it couldn't read anything.

I gave you access for two repository where it's happening.

**Comment by freddydk** [comment]
Sorry, this one totally slipped my mind
Was this solved?

**Comment by pzentner** [comment]
I have tried getting this to work with the latest main branch, but it does seem to still not work. I didn't make any changes from the setups/configuration from before.

**Comment by freddydk** [comment]
The preview branch does have a number of changes to the Delivery process. A new deliver action and deliver to storage and deliver to appsource now as seperate jobs.
Earlier, the delivery was done either directly in RunPipeline action or Release action.
Could you try to Update AL-Go System files with https://github.com/microsoft/AL-Go-\<type\>@preview ?

**Comment by freddydk** [comment]
I have tested the delivery to storage with multi-project, single-project, secrets, key-vaults etc. - and everything should work in the preview branch.

**Comment by pzentner** [comment]
I can confirm that this is now working.

One question though and I don't know, if this needs to be a new issue. When the CI/CD action ran (and it delivered it properly to storage), I am getting the following error on the PostProcess "Unexpected error when running action (Cannot bind argument to parameter 'telemetryScopeJson' because it is an empty string.)".
