### ISSUE TITLE
Adding Test App not showing in Workspace

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/AL-Go#171]
Should adding a Test app update the workspace?  It does not for me, wondering if this is intentional.

**Comment by freddydk** [comment]
It should add it to the workspace, yes.
Will check

**Comment by tscottjendev** [comment]
I see you noted you can't reproduce.  Here is the steps I did for this repo.
Created the repo from the AL-GO-PTE repo template
Added a new APP, changing the WorkSpace from "." to PTEFLOW as I wanted to test multiple apps (using the sample code).
after trying to add new app without the "PTEFLOW" workspace name, I added a new Test App (without the sample code).
The test app does not show in the workspace.

Happy to add you to the repo if that would assist you in your investigation.

**Comment by tscottjendev** [comment]
yes, this field 
![image](https://user-images.githubusercontent.com/102963427/175923172-079279bb-bf6a-4b8d-9ceb-57f17369c451.png)

**Comment by freddydk** [comment]
Yep - that results in a multi-project repo, which really is intended for having totally unrelated (or maybe even conflicting) apps in the same repository - basically every project ships seperatly.
If the apps have inter-dependencies - you should keep the . and have all apps in the same root project,

I will check the issue
