### ISSUE TITLE
[Question] Selection of Apps when creating a Release

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/AL-Go#172]
I am wondering how the release action selects the apps to include in that release in a multi Project repository.
Sometimes I have multiple changes on 2 of the 3 projects but only one apps gets included in the release.
I was not really able to find any logic on how the apps get selected yet.

**Comment by freddydk** [comment]
The intention should be that it would grab the latest build from all projects (if no specific version was specified)
I assume that this doesn't happen?

**Comment by StefanMaron** [comment]
ah, I was talking about name and tag.
The App version is always latest. 
but most of the time the latest build only built one project.

![image](https://user-images.githubusercontent.com/24838311/176151578-a72fae9d-cb15-4ab0-8fc0-d47fb402b643.png)

**Comment by freddydk** [comment]
This might be a bug.
For now, you can probably set "alwaysBuildAllProjects":  true in the repo settings file (.github\AL-Go-Settings.json) - then it should build all projects every time - and probably release them as well.

**Comment by StefanMaron** [comment]
Okay, thanks.
Let me know if I can give any more input.

**Comment by freddydk** [comment]
I think I will need to make an overhaul on the multi-project repo - I have found a few things.
That might be after my vacation (which starts tomorrow)

**Comment by freddydk** [comment]
Have a fix for this.
Will be in the preview branch tomorrow.

**Comment by freddydk** [comment]
This fix is in preview now.

**Comment by freddydk** [comment]
Shipped in v2.0
