### ISSUE TITLE
versioningStrategy value 16 not parsing as documented

### ISSUE THREAD

**Issue by vvkjndl** [microsoft/AL-Go#174]
**Documentation:**

```
versioningStrategy

The versioning strategy determines how versioning is performed in this project. The version number of an app consists of 4 tuples: Major.Minor.Build.Revision. Major and Minor are read from the app.json file for each app. Build and Revision are calculated. Currently 3 versioning strategies are supported:

0 = Build is the github run_number for the CI/CD workflow, increased by the runNumberOffset setting value (if specified). Revision is the github run_attempt subtracted 1.
1 = Build is the github run_id for the repository. Revision is the github run_attempt subtracted 1.
2 = Build is the current date as yyyyMMdd. Revision is the current time as hhmmss. Date and time are always UTC timezone to avoid problems during daylight savings time change. Note that if two CI/CD workflows are started within the same second, this could yield to identical version numbers from two different runs.
+16 use repoVersion setting as appVersion (Major and Minor) for all apps
```

`/.github/AL-Go-Settings.json`

```
    "repoVersion": "2022.06.28.003",
    "versioningStrategy": 16,
```

**Expected version while compiling apps:**
```
[System.Version]"2022.06.28.003"
```

**Parsed version while compiling apps:**
```
[System.Version]"2022.06.28.003.11.0"
`Cannot convert value "2022.06.28.003.11.0" to type "System.Version". Error: "Version string portion was too short or too long."`
```

It seems to be appending the `run_attempt` of the `CI/CD` workflow even when using `16` as declared value for `versioningStrategy`.

**Comment by freddydk** [comment]
RepoVersion should only consist of major,minor
![image](https://user-images.githubusercontent.com/10775043/176360034-e0c3d73f-cd61-4a36-a619-8d7705646817.png)
versioningstrategy determines how build.revision are calculated (and from where major.minor are read)

**Comment by vvkjndl** [comment]
Would it be possible to use a user specified version in literal form while compiling i.e. use the same exact version as specified in version parameter of `app.json`.

**Excerpt from app.json:**

```
    "version":  "2022.06.28.003",
```

**Comment by freddydk** [comment]
Docs updated
![image](https://user-images.githubusercontent.com/10775043/176361952-47f2b29c-5de6-41a6-ade8-6de309586e25.png)

There is no way you can "disable" auto-numbering of apps, unless you override the compileapp function and stamp your own version number into app.json

AL-Go is designed for when it builds and maintains these things automatically.

There is another setting called UpdateDependencies, which also has an effect on dependency version numbers and artifacts selection.

**Comment by vvkjndl** [comment]
@freddydk There are some settings.json files for Current, NextMinor and NextMajor in `.github` folder.

`AL-Go-PTE/.github/Test Current.settings.json`

```
{
    "artifact":  "////latest",
    "cacheImageName":  "",
    "versioningStrategy":  15
}
```
What exactly does the value `15` does when used? It appears to be undocumented.

**Comment by freddydk** [comment]
15 means that build no. is hardcoded to maxint and revision is hardcoded to 0
This is not intended for other usage than the workflows, which doesn't produce any artifacts
