### ISSUE TITLE
Question - Schedule for running next major / minor version

### ISSUE THREAD

**Issue by CarlOhlsson** [microsoft/AL-Go#175]
We are currently using Azure DevOps where all our customer have scheduled jobs to check all PTE apps against the next versions. I will start to move customer over to GitHub soon and cant figure out how to set up the same schedule here.

Do I need to create my own workflow or am I missing something? I see there are workflows I can run manual but do not see any way to automate it.

**Comment by freddydk** [comment]
You need to set the NextMajorSchedule in .github\AL-Go-Settings.json and run the Update AL Go System Files, then the Next Major workflow will run on a schedule.
Example: https://github.com/BusinessCentralApps/BingMaps.PTE/blob/main/.github/AL-Go-Settings.json

Will add a blog post on this
