### ISSUE TITLE
Issue when creating new release if main branch is protected

### ISSUE THREAD

**Issue by CarlOhlsson** [microsoft/AL-Go#176]
I just turned on branch protection on the main branch and ran into issues when creating a new release. When I had no branch protection it worked fine.

The job "UpdateVersionNumber" gives the following output message.

> remote: error: GH006: Protected branch update failed for refs/heads/main.        
> remote: error: At least 1 approving review is required by reviewers with write access.        
> To https://github.com/***-****-*******/PTE-ABC123
>  ! [remote rejected] main -> main (protected branch hook declined)

The only rule I am using is the "Require a pull request before merging". How to get around this?

**Comment by freddydk** [comment]
Will look into this next week

**Comment by CarlOhlsson** [comment]
Currently having issues with updating the version number that i think is related to this.

> pull request create failed: GraphQL: GitHub Actions is not permitted to create or approve pull requests (createPullRequest)
Error: Increasing the version number failed. 

Solved the issue by going to my organization and enabling "Allow GitHub Action to create and approve pull requests" at Settings -> Actions -> General. After enabling the this setting I can now protect the branch and create a release. However this creates a pull request that i need to approve each time i update the version number from the action or when creating a release.

**Comment by freddydk** [comment]
If you set the Direct Commit to Y, then it will commit directly instead of creating a PR:
![image](https://user-images.githubusercontent.com/10775043/185632798-059edf89-78b3-44a5-85b4-ad7909ff295e.png)

**Comment by freddydk** [comment]
I will see if I can check whether it is allowed to create a PR - and then fail with a better error message.
