### ISSUE TITLE
"Could not find a part of the path..."

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#177]
Making another attempt to get past Step 1, since it looks like we may be deploying to the cloud soon. Still cannot complete the first workflow, "Add existing app or test app." Here is the log; is it really something wrong with the path to the .zip file of the DevOps repository?

Run microsoft/AL-Go-Actions/AddExistingApp@v1.5
Run try { D:\a\_actions\microsoft\AL-Go-Actions\v1.5\AddExistingApp/AddExistingApp.ps1 -actor 'buzzwick' -token '***' -parentTelemetryScopeJson '{"Parameters":{},"Emitted":false,"CorrelationId":"215667aa-2b8e-46[9](https://github.com/buzzwick/Upstate-Coin/runs/7548827881?check_suite_focus=true#step:2:10)3-bc21-eb8d845a8451","ParentId":"","AllParameters":{},"TopId":"215667aa-2b8e-4693-bc21-eb8d845a8451","Name":"AL-Go workflow ran: AddExistingAppOrTestApp","StartTime":"\/Date(1658955287189)\/","Properties":{"eventId":"DO0090","bcContainerHelperVersion":"3.0.11","isAdministrator":"True","stackTrace":"[\n  InitTelemetryScope at TelemetryHelper.ps1: line 2[12](https://github.com/buzzwick/Upstate-Coin/runs/7548827881?check_suite_focus=true#step:2:14)\n  CreateScope at TelemetryHelper.psm1: line 44\n  WorkflowInitialize.ps1 at WorkflowInitialize.ps1: line 37\n  a9514981-30d8-4bf1-9ab8-074f1689a418.ps1 at a9514981-30d8-4bf1-9ab8-074f1689a418.ps1: line 1\n  \u003cScriptBlock\u003e at \u003cNo file\u003e\n]","repository":"66CD3F8766B3351220F7BF694C6D0E51ED306B365A98B3C63ABE7A4B51643077","runAttempt":"1","runNumber":"[13](https://github.com/buzzwick/Upstate-Coin/runs/7548827881?check_suite_focus=true#step:2:15)","runId":"2749578613"},"EventId":"DO0090"}' -project '.' -url 'C:\_Clients\UpstateClone.zip' -directCommit ('N' -eq 'Y') } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message))"; exit 1 }
git config --global user.email buzzwick@users.noreply.github.com
git config --global user.name buzzwick
git config --global hub.protocol https
git clone ***github.com/buzzwick/Upstate-Coin
Cloning into 'Upstate-Coin'...
git checkout -b s4nxhmy2.42w
Switched to a new branch 's4nxhmy2.42w'
Downloading BcContainerHelper latest version
BcContainerHelper version 3.0.11
BcContainerHelper emits usage statistics telemetry to Microsoft
Reading .github\AL-Go-Settings.json
Reading .AL-Go\settings.json
Downloading C:\Users\RUNNER~1\AppData\Local\Temp\c6d69562-d2b4-446f-8ac6-c25495d[14](https://github.com/buzzwick/Upstate-Coin/runs/7548827881?check_suite_focus=true#step:2:16)ca9.app
**Error downloading..., retrying in 5 seconds...
Error: Couldn't add an existing app.
 Exception calling "DownloadFile" with "2" argument(s): "Could not find a part of the path 'C:\_Clients\UpstateClone.zip'."**
AL-Go action ran: AddExistingApp Telemetry Correlation Id: 6ad65775-ed[19](https://github.com/buzzwick/Upstate-Coin/runs/7548827881?check_suite_focus=true#step:2:21)-48ae-8798-3bbb0962c5a4
Removing BcContainerHelper
Error: Process completed with exit code 1.

**Comment by freddydk** [comment]
it looks like you provide a local path as a URL?
It needs to be a direct download url to the file (dropbox or like)

**Comment by buzzwick** [comment]
Oh. Right. I remember that. Will try that again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by buzzwick** [comment]
Had to re-research the creation of a direct download URL, this one from dropbox:
`https://www.dropbox.com/s/ld1j12ij8h4jd66/UpstateClone.zip?dl=1`

Progress, in the form of a failure for a different reason:

Run microsoft/AL-Go-Actions/AddExistingApp@v1.5
Run try { D:\a\_actions\microsoft\AL-Go-Actions\v1.5\AddExistingApp/AddExistingApp.ps1 -actor 'buzzwick' -token '***' -parentTelemetryScopeJson '{"Parameters":{},"Emitted":false,"CorrelationId":"5af744ae-d708-45f3-[9](https://github.com/buzzwick/Upstate-Coin/runs/7561349658?check_suite_focus=true#step:2:10)6a1-7d9da54ad718","ParentId":"","AllParameters":{},"TopId":"5af744ae-d708-45f3-96a1-7d9da54ad718","Name":"AL-Go workflow ran: AddExistingAppOrTestApp","StartTime":"\/Date(1659016112765)\/","Properties":{"eventId":"DO0090","bcContainerHelperVersion":"3.0.11","isAdministrator":"True","stackTrace":"[\n  InitTelemetryScope at TelemetryHelper.ps1: line 212\n  CreateScope at TelemetryHelper.psm1: line 44\n  WorkflowInitialize.ps1 at WorkflowInitialize.ps1: line 37\n  5f66be46-6c40-4088-8adb-211532bcd108.ps1 at 5f66be46-6c40-4088-8adb-211532bcd108.ps1: line 1\n  \u003cScriptBlock\u003e at \u003cNo file\u003e\n]","repository":"66CD3F8766B3351220F7BF694C6D0E51ED306B365A98B3C63ABE7A4B51643077","runAttempt":"1","runNumber":"16","runId":"2754231858"},"EventId":"DO0090"}' -project '.' -url 'https://www.dropbox.com/s/ld1j12ij8h4jd66/UpstateClone.zip?dl=1' -directCommit ('N' -eq 'Y') } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message))"; exit 1 }
Cloning into 'Upstate-Coin'...
git config --global user.email buzzwick@users.noreply.github.com
git config --global user.name buzzwick
git config --global hub.protocol https
git clone ***github.com/buzzwick/Upstate-Coin
git checkout -b hyziibzy.cd4
Switched to a new branch 'hyziibzy.cd4'
Downloading BcContainerHelper latest version
BcContainerHelper version 3.0.11
BcContainerHelper emits usage statistics telemetry to Microsoft
Reading .github\AL-Go-Settings.json
Reading .AL-Go\settings.json
Downloading C:\Users\RUNNER-1\AppData\Local\Temp\ef178778-95fd-405a-a970-8929e9dc51db.app
C:\Users\RUNNER~1\AppData\Local\Temp\f16a336f-9e8a-4a[13](https://github.com/buzzwick/Upstate-Coin/runs/7561349658?check_suite_focus=true#step:2:15)-ae9d-cc36a275ade0 -> C:\Users\RUNNER-1\AppData\Local\Temp\3b4d6322-e634-445e-824b-[16](https://github.com/buzzwick/Upstate-Coin/runs/7561349658?check_suite_focus=true#step:2:18)24d47a5474
done
Error: Couldn't add an existing app.
 Cannot find path 'C:\Users\RUNNER-1\AppData\Local\Temp\f16a336f-9e8a-4a13-ae9d-cc36a275ade0' because it does not exist.
AL-Go action ran: AddExistingApp Telemetry Correlation Id: 4d802ed7-[17](https://github.com/buzzwick/Upstate-Coin/runs/7561349658?check_suite_focus=true#step:2:19)6a-4935-bdfa-d7ee8455f9df
Removing BcContainerHelper
Error: Process completed with exit code 1.


Where to next?

**Comment by freddydk** [comment]
You probably need to remove the file from dropbox - your URL was exposed here.

**Comment by buzzwick** [comment]
Done. Thank you for pointing that out. Seems to be a lot of difficulty in the initial finding of the .zip archive?

**Comment by freddydk** [comment]
Instead of giving a URL to a .zip file which contains both an .app file and the source for the app - just provide a URL to the .app file itself.

**Comment by buzzwick** [comment]
Aha. That went much better. Now I have one working repository, that I can experiment with, and learn. A bit disorienting coming from DevOps, but will deal. I see that using this in a commercial environment will require upgrading to a commercial GitHub account. So the next steps will be political...
Thank you.
