### ISSUE TITLE
Creating Service Principal "Use Azure KeyVault for secrets with AL-Go"

### ISSUE THREAD

**Issue by bmi-it** [microsoft/AL-Go#178]
In #7 (Use Azure KeyVault for secrets with AL-Go) the prerequisite actions to Use Key Vault secrets in GitHub Actions workflows asks us to Define a service principal.  The command we are supposed to run is:

`az ad sp create-for-rbac --name {myApp} --role contributor --scopes /subscriptions/{subscription-id}/resourceGroups/{MyResourceGroup} --sdk-auth`

I've replaced the relevant values like this:
`az ad sp create-for-rbac --name "github-app" --role contributor --scopes /subscriptions/*********/resourceGroups/********** --sdk-auth`

Instead of the expected JSON output, I receive the following error:
```
Changing "github-app" to a valid URI of "http://github-app", which is the required format used for service principal names
Values of identifierUris property must use a verified domain of the organization or its subdomain: 'http://github-app'
```

Is there an updated procedure to create the Service Principal?

**Comment by freddydk** [comment]
The referenced documentation here: https://docs.microsoft.com/en-us/azure/developer/github/github-key-vault should still be good. I guess you just need to use a URL in your possession (ex. https://myapp.<yourdomainname>)

**Comment by bmi-it** [comment]
Thank you Freddy.  In the past using other App Registrations, I did not need to name the app registration that was in the format of a URL so this was new to me and not well understood from the documentation.

**Comment by freddydk** [comment]
This is a change forced on us from the Azure security team.
I will see if I can change the documentation to mention this,
