### ISSUE TITLE
Step 2, Add test app, always ended up failed when running the workflow

### ISSUE THREAD

**Issue by v3ux** [microsoft/AL-Go#179]
Hi,

I use the forked PTE Repo for this issue https://github.com/microsoft/AL-Go-PTE

I've been stuck for couple days figures it out why test app workflow always ended up failed.
I followed this step: https://github.com/microsoft/AL-Go/blob/main/Scenarios/AddATestApp.md

Here's my HelloWorld.al commit which altered the string in the message:
https://github.com/v3ux/app1-bc/commit/2778350b8bd4b08bd793045111e5ecb2693e5ca9

The HelloWorld.Test.al which should reflect to the altered string in the message
https://github.com/v3ux/app1-bc/commit/64ebe0daade99f540f0eb8296650ef2dfd0d0282

The workflow throwed an error 
https://github.com/v3ux/app1-bc/actions/runs/2781385436

The code was failing. I've checked the logic and it should pass.

I didn't know why the test code failed, but it seems the code inside HelloWorldMessageHandler was never run thus always faling the test. I tried to add another intentional error (throw error whenever message string is greater than 0), and it also failed 
Commit here: https://github.com/v3ux/app1-bc/commit/08b7bad59185c9bb39056768ab1c07ac7e862b47
Workflow here: https://github.com/v3ux/app1-bc/runs/7684397389
 
I was curious, so I looked under the workflow logs, I can't find the base app. Was it supposed to be included in the compile process?
I mean, test app (HelloWorld.Test) depends on the base app (HelloWorld), so it could run correctly right? Was it supposed something in here like workflow compling the base app so the test app could run correctly?
![image](https://user-images.githubusercontent.com/108313663/182993787-000ba5d5-1134-46a9-bc61-f57e91da8784.png)

For the record if I published the app from first 2 commit, it passed in my sandbox environment
![image](https://user-images.githubusercontent.com/108313663/182994264-e5769501-0236-4b21-8052-0d78d25ba1dd.png)

**Comment by freddydk** [comment]
You have added this line:

```
if (StrLen(Message) > 0) then
            Error('Message has string with length %1', StrLen(Message));
```

Which throws an error if the string is not empty.
That error is not displayed (it is in a handler function) - but the messagedisplayed variable is never set.

**Comment by freddydk** [comment]
The problem might also be that you have made this a multi-project repository.
You probably specified a project name when creating an app.

You should move the .AL-Go folder from app-v1 to the root and remove the .AL-Go folder from app-v1-test.
This turns this into a single project repo with 2 apps.

**Comment by v3ux** [comment]
> You have added this line:
> 
> ```
> if (StrLen(Message) > 0) then
>             Error('Message has string with length %1', StrLen(Message));
> ```
> 
> Which throws an error if the string is not empty. That error is not displayed (it is in a handler function) - but the messagedisplayed variable _is never set_.

I had the same thought at first, thought it was because missing MessageDisplayed initialization (though I was pretty sure the default value of non initialize boolean vairable should be false). I tried in this commit (set it to false) and it didn't work
https://github.com/v3ux/app1-bc/commit/1919764a374b3337d01010cbb2cea6dcd1b92e96

**Comment by v3ux** [comment]
> The problem might also be that you have made this a multi-project repository. You probably specified a project name when creating an app.
> 
> You should move the .AL-Go folder from app-v1 to the root and remove the .AL-Go folder from app-v1-test. This turns this into a single project repo with 2 apps.

I followed exactly from 

#1 https://github.com/microsoft/AL-Go/blob/main/Scenarios/GetStarted.md
#2 https://github.com/microsoft/AL-Go/blob/main/Scenarios/AddATestApp.md

I believe those steps mention to put a name for the project (#1.4 and #2.1), please correct me if I'm wrong.

The directory tree ended up like that as I followed those instructions, I didn't touch anything. Even when vscode complains there's no app.json in most outer path, I didn't commit it and push it into git, keep only 2 app.json which one is the app, another one is the test app.

I will try what you're suggest in the last sentence. Hopefully that would do the trick.

**Comment by v3ux** [comment]
> You should move the .AL-Go folder from app-v1 to the root and remove the .AL-Go folder from app-v1-test. This turns this into a single project repo with 2 apps.
This didn't work. The pipeline reported it didn't find any repo instead of building it.
https://github.com/v3ux/app1-bc/runs/7686750493

![image](https://user-images.githubusercontent.com/108313663/183025386-a1f15fb0-3162-4db6-9663-9107ef4ebd9f.png)

**Comment by v3ux** [comment]
> The problem might also be that you have made this a multi-project repository. You probably specified a project name when creating an app.

Alright, I think I found the project name you mention. In this image from the instruction, it didn't show (older template perhaps?)
https://github.com/microsoft/AL-Go/blob/main/Scenarios/images/1b.png

While the latest one has it. Yes I remembered filled it with something.
![image](https://user-images.githubusercontent.com/108313663/183028953-fc8b95b6-897b-4e5b-b788-af7f5c9bee1a.png)

I will try to create another repo. This time, keep the top textbox as it is.

**Comment by freddydk** [comment]
Or move the .AL-Go folder as described

**Comment by v3ux** [comment]
Alright, found the culprit. Indeed filling the project name causing a bit different directory tree compared to the "leave it as it is"/default project name.


> Or move the .AL-Go folder as described

Apprently this won't be enough, because filling project name ended up creating similar like this on the right side. The left side is the correct one.
![image](https://user-images.githubusercontent.com/108313663/183049669-bf550c7f-4632-4fd0-9b85-10e0ee19f480.png)

Problem is fixed, I will close this issue.

**Comment by freddydk** [comment]
You're right - forgot about that.
