### ISSUE TITLE
cloudDevEnv.ps1 for existing Sandbox environment?

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#181]
Having cloned a github AL-Go repository to local drive and opened in VS Code, can we use cloudDevEnv.ps1 to connect to an existing Azure BC sandbox environment? As it is, when we run the script it only executes outside VS Code--not in the Terminal session--runs the Powershell profile, and then errors out so fast we can't see it. But we are not sure if we need to, if we already have the environment created in the cloud. Do we? 

Here is all we get in the Terminal:

`. "c:\Users\<user>\xxx\AL\PROJECTS\Elemet\.AL-Go\cloudDevEnv.ps1"
>
> . "c:\Users\<user>\xxx\AL\PROJECTS\Elemet\.AL-Go\cloudDevEnv.ps1"`

**Comment by freddydk** [comment]
if you open and run the script in powershell ISE - does it provide any info?

**Comment by buzzwick** [comment]
Runs normally, then wants a verification code from my device. I have Authenticator, but nothing there works. No sign of a code anywhere.

**Comment by buzzwick** [comment]
Sorry, did not see the code right there in the address line.

**Comment by buzzwick** [comment]
Now I get a PS prompt:

Checking .AL-Go\dbaldwin.settings.json
Checking type
Checking appFolders and testFolders
Application Dependency 20.0.0.0
Updating app- and test Dependencies
Analyzing Test App Dependencies
WARNING: No performance test apps found in bcptTestFolders in .AL-Go\settings.json
WARNING: No test apps found in testFolders in .AL-Go\settings.json
Attempting authentication to https://api.businesscentral.dynamics.com/user_impersonation offline_access using device login...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FWHW73B59 to authenticate.
Waiting for authentication..................................Removing BcContainerHelper

PS C:\Users\<user>\AL\PROJECTS\<repo name>>
