### ISSUE TITLE
Issue with referencing project from multi-project repository

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#188]
Hey @freddydk,

I followed your blog [post](https://freddysblog.com/2022/04/28/structuring-your-github-repositories/), and made multi-project repository with 3 projects: core, Italian & norvegian apps. 

My Norvegian app depends on core app. Therefore, i want to set it at  appDependencyProbingPaths. I tried to do likes this:

```
{
    "country":  "no",
    "appFolders":  [
    ],
    "testFolders":  [
    ],
    "appDependencyProbingPaths":  [
        {
            "repo":  "sede-res/srs-bc",
            "release_status":  "include",
            "projects":  "SRS.core"
        }
    ]
}
```
or like this:
```
{
    "country":  "no",
    "appFolders":  [
    ],
    "testFolders":  [
    ],
    "appDependencyProbingPaths":  [
        {
            "repo":  ".",
            "release_status":  "include",
            "projects":  "SRS.core"
        }
    ]
}
```

but it gives the following error message: **You cannot call a method on a null-valued expression.**

full log uploaded at wetransfer [here](https://wetransfer.com/downloads/389f84856b60bef90011d14ea9ef359720220905140444/a10013f9facf12585f133c7bb1f62db120220905140502/a66f9b)
Any advice?

**Comment by freddydk** [comment]
Are you using the preview?
I think this functionality is only in preview - which will be released later this week.

**Comment by gntpet** [comment]
You were right, i was using stable channel. Once i switched to preview, it resolves dependencies successfully from the same repository.
