### ISSUE TITLE
Warnings: Resource not accessible by integration

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#189]
When I run CI/CD pipeline, I keep seeing access warnings

`The remote server returned an error: (403) Forbidden. Resource not accessible by integration `

I do have GhTokenWorkflow defined, but if I understand it's used for the AL-GO updates only. Am i missing some other token?

p.s. My repo is private repository with preconfigured 2FA.

https://docs.github.com/rest/deployments/environments#list-environments
![image](https://user-images.githubusercontent.com/16342128/188569468-d8c851e2-1ab4-463f-a90b-442d7df88c7e.png)

**Comment by freddydk** [comment]
Personal or organizational account?
What is your plan?
Free or Pro/Teams?

The free plans doesn't support environments for private repos - they should be ignored - but maybe there is a bug.
Will investigate

**Comment by gntpet** [comment]
I can confirm that it was fixed
