### ISSUE TITLE
PublishToEnvironment is not working with AL-Go-PTE@preview"

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#190]
Hey @freddydk , 
I believe there's a bug with PublishToEnvironment.yaml on preview version. 

You are setting strategy from step Initialization, while this variable is not set there.

![image](https://user-images.githubusercontent.com/16342128/188676143-7766594a-54bb-47ca-af43-4cd462a374ae.png)

You made the following change in preview
![image](https://user-images.githubusercontent.com/16342128/188675571-f1aaf897-709a-41a3-a4e1-594386ebc645.png)

As a result my PublishToEnvironment does not work at all

![image](https://user-images.githubusercontent.com/16342128/188676504-53ad0da3-a995-42c5-a326-b6ddbac9f92f.png)

while EnvironmentsJson comes with correct data
![image](https://user-images.githubusercontent.com/16342128/188676391-b8a3f327-11ff-4339-9615-91f8fabf56d8.png)

p.s. i'm using preview version due to another issue I had :)

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
That is a bug
I think the line should be
    strategy: ${{ fromJson(needs.Analyze.outputs.environments) }}
Instead of Initialization

Could you try to modify the yaml and test?

**Comment by freddydk** [comment]
I have deployed a fix in preview for this.

**Comment by gntpet** [comment]
Thank you very much. Fix worked.
