### ISSUE TITLE
Remove-Item Error by setting up enviroment

### ISSUE THREAD

**Issue by ManDa-GmbH** [microsoft/AL-Go#192]
I use this documentation for the start.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/al-go/algo-get-started

by "Setting up the environment in Visual Studio Code" step 4 i get the error message

> Remove-Item : Ein Objekt im angegebenen Pfad "C:\Users\M0B28~1.DUD" ist nicht vorhanden.
> In C:\Users\XXXXXXX\AppData\Local\Temp\tmp8D90.tmp.ps1:268 Zeichen:9
> +         Remove-Item -Path "$tempName.zip"
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Remove-Item], PSArgumentException
>     + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.RemoveItemCommand

I using fresh installed Windows 11 with all updates connected Work/Scool account

**Comment by freddydk** [comment]
We did discover some issues when running local and cloud devenv from VS Code.
These issues are fixed in the preview - and will be fixed in the next version

Could you try to run the script from PowerShell ISE or a PowerShell prompt.

**Comment by ManDaMDuda** [comment]
Theare is the same issue with exacly the same Issue, buth different tmp file.
It do's not mater if i use ISE, Powershell or VS.

One Comment on the Description. i needet to first run command
_Set-ExecutionPolicy Bypass_

**Comment by freddydk** [comment]
Sorry for the delay, was busy on Tech Days prep and execution.
Could you share the full output of the script running (either here or in email to freddyk at microsoft.com)

**Comment by ManDaMDuda** [comment]
I have send you a email with direkt snip from PowerShell window.

**Comment by freddydk** [comment]
This shouldn't happen anymore - added some resilience to this step in 2.2
