### ISSUE TITLE
Issue with "Publish To Environment" for mult-project repository

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#193]
Hey @freddydk , 
I followed your blog and setup multi-project repository in very similar matter as you did for [contoso-app2](https://github.com/BusinessCentralApps/Contoso-App2/)

I do have 3 projects within repo: core, Italy, and Denmark and I have to environments Italy-env & Denamark-env. 

When I run "Publish To Environment", my natural expectation is that Italian app goes to Italan environment, and Danish app goes to Danish environment. But, it publishes all apps to both environments. 

I checked workflow [code](https://github.com/microsoft/AL-Go-PTE/blob/preview/.github/workflows/PublishToEnvironment.yaml) 

and I see that you are passing **secrets.Projects** as a param for Projects. 

![image](https://user-images.githubusercontent.com/16342128/188814799-842ed664-2819-47ae-9d5e-80563636c298.png)

Is it a bug here, or I am missing some configuration?

**Comment by freddydk** [comment]
I think you can create an environment secret called projects to state which projects to install on this environment.

**Comment by gntpet** [comment]
Thank you for a hint. 
Indeed adding PROJECTS secret did work. The only downside of handling it as a secret is that it's impossible to what's being deployed in the logs

![image](https://user-images.githubusercontent.com/16342128/188849002-431d1697-af92-4a93-8b1a-146f3c18e3d7.png)

Plus, you cannot see what's currently configured under environment, since it is a secret. 

Thank you again for your help.

**Comment by freddydk** [comment]
It isn't supported at the time, but I will probably add support for using a repository setting instead.
like environmentname-projects or like.

**Comment by gntpet** [comment]
You already have field "Environments" under .AL-go\settings.json, would it be and idea to use it for resolving where the app should be deployed?

**Comment by freddydk** [comment]
Yes exactly

Today, you can have environments in GitHub or in settings.
You can have authcontext defined in environments secrets or repo secrets
So it is just enabling AL-Go to look for <environmentname>_projects in settings I guess - will investigate this

**Comment by freddydk** [comment]
fixed in the latest preview

**Comment by freddydk** [comment]
Shipped in v2.0
