### ISSUE TITLE
Local DevEnv creation fails when checking System Requirements/Docker service

### ISSUE THREAD

**Issue by UrpoKo** [microsoft/AL-Go#195]
Line 78 "$dockerService = Get-Service docker -ErrorAction SilentlyContinue" fails to get anything to $dockerService because the service name is actually "com.docker.service".

This happened to me with Docker desktop version 4.12.0 (85629)

**Comment by freddydk** [comment]
Are you running this inside VS Code - or in a PowerShell prompt?
(I found some problems with VS Code, which are fixed in preview)

**Comment by UrpoKo** [comment]
This was directly from PowerShell, in Admin mode. It started to work when I changed the service name from "docker" to "com.docker.service" in the script. Maybe some wildcards would work equally good.
"$dockerService = Get-Service docker -ErrorAction SilentlyContinue"
-> "$dockerService = Get-Service com.docker.service -ErrorAction SilentlyContinue"

**Comment by freddydk** [comment]
Will check this out, thanks for the info

**Comment by freddydk** [comment]
Will check for the dockerd process instead - that is the safe bet.
The service name depends on whether you have docker engine, docker desktop or mirantis (docker enterprise) I think.

**Comment by freddydk** [comment]
Shipped in v2.0
