### ISSUE TITLE
Question: When I run localDevEnv.ps1 I get a popup asking me if I want to allow powershell to make changes

### ISSUE THREAD

**Issue by dvanes67** [microsoft/AL-Go#212]
to my system, Shortly after that a window opens, and closes again, And then the script ends.

Start-Process -Verb runas $pslink @("-Command ""$scriptName"" -fromVSCode -containerName '$containerName' -auth '$auth' -licenseFileUrl '$licenseFileUrl' -insiderSasToken '$insiderSasToken'$credstr")

is the last line executed, It just stops after that.
What am I doing wrong?

Edit: 
Running the script from powershell ise seems to work ..

**Comment by dvanes67** [comment]
The resulting container doesn't work tho

**Comment by freddydk** [comment]
> The resulting container doesn't work tho
As in you cannot login?
or you cannot download symbols?

**Comment by freddydk** [comment]
BTW - AL-Go v2.0 (now preview) has some enhancements to invoking localDevEnv from VS Code or from PowerShell.

**Comment by dvanes67** [comment]
The resulting container doesn't let me connect to it, or publish an app.

**Comment by freddydk** [comment]
I need more info in order to help you.
What happens? What error? How does launch.json look? etc. etc.

The more info you share - the faster I can help you resolve the issue.

**Comment by dvanes67** [comment]
This is my current launch.json:
{
    "version":  "0.2.0",
    "configurations":  [
                           {
                               "type":  "al",
                               "request":  "launch",
                               "name":  "Local Sandbox (devdennis)",
                               "server":  "http://devdennis",
                               "serverInstance":  "BC",
                               "port":  7049,
                               "tenant":  "default",
                               "authentication":  "UserPassword"
                           }
                       ]
}
This is the debug console in VSC when I try to publish the default (hello world) app
[2022-09-21 08:45:50.42] Publishing AL application using launch configuration 'Local Sandbox (devdennis)'.
[2022-09-21 08:45:50.74] Targeting server 'http://devdennis', server instance 'BC' and tenant 'default'.
[2022-09-21 08:45:50.84] Using user name and password authentication. User name used is: 'dennisve'.
[2022-09-21 08:45:50.86] Sending request to http://devdennis:7049/BC/dev/metadata?tenant=default
[2022-09-21 08:45:50.98] Error: An internal error has occurred

I had already added some al code (2 tables, 3 pages) so when I tried to create a new container this morning I got some messages about missing permission sets. Adding those does not solve the above issue (internal error).

The container is running, I can access it, using the shortcuts on my desktop.
I did notice that after I created a new container, the links on my desktop were overwritten...

I'll keep trying to get this to work,

**Comment by freddydk** [comment]
Did you try to clear credentials in VS Code?

**Comment by dvanes67** [comment]
At the moment it looks like everything is working, except running the script from VSC

> Did you try to clear credentials in VS Code?

**Comment by freddydk** [comment]
You mean running the localDevEnv - that will work from v2.0 - releasing later this week - and you can upgrade using the Update AL-Go System Files.

**Comment by dvanes67** [comment]
> You mean running the localDevEnv - that will work from v2.0 - releasing later this week - and you can upgrade using the Update AL-Go System Files.

Yes, I meant LocalDevEnv.ps1 and no, I tried with a preview v2.0 this morning in VSC. Same thing happens. It asks for confirmation to allow changes to my system, then a popup, then nothing.

**Comment by freddydk** [comment]
Ok - when it asks for permissions to change things, I assume that it writes in VS Code that your user do not have permissions to run docker commands. I will double check this

**Comment by dvanes67** [comment]
> Ok - when it asks for permissions to change things, I assume that it writes in VS Code that your user do not have permissions to run docker commands. I will double check this

I can't see what happens in the window that pops up, it closes immediately, but when I check my eventlog, I dont see any errors concerning VSC and/or docker.

**Comment by freddydk** [comment]
This looks to be due to ExecutionPolicy.
If you open a powershell prompt and run

`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
`
Then it should work.

Will include a check on executionpolicy in v2.0

**Comment by freddydk** [comment]
Shipped in v2.0
