### ISSUE TITLE
LocalDevEnv.ps1 fails with "Illegal characters in path."

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#215]
We created an AL-Go repository for our AppSource extension code. When I clone that repo and run LocalDevEnv.ps1 from inside VSCode (we do this routinely for Docker containers), it opens a separate PowerShell window that looks like it loads the BC modules but then immediately closes. If I open PowerShell as admin and run the script, it runs but fails consistently as below. Questions:
1. Any clue as to the source of the "illegal character"?
2. I can create a Docker container with the latest BC version--but do I need to use this script for the container if I am working with code from the AL-Go repository?
3. Is there some reason this script does not run within the VSCode PowerShell terminal?

  _                     _   _____             ______
 | |                   | | |  __ \           |  ____|
 | |     ___   ___ __ _| | | |  | | _____   __ |__   _ ____   __                                                         | |    / _ \ / __/ _` | | | |  | |/ _ \ \ / /  __| | '_ \ \ / /                                                         | |____ (_) | (__ (_| | | | |__| |  __/\ V /| |____| | | \ V /                                                          |______\___/ \___\__,_|_| |_____/ \___| \_/ |______|_| |_|\_/                                                                                                                                                                                  This script will create a docker based local development environment for your project.                                  
NOTE: You need to have Docker installed, configured and be able to create Business Central containers for this to work.
If this fails, you can setup a cloud based development environment by running cloudDevEnv.ps1

All apps and test apps will be compiled and published to the environment in the development scope.
The script will also modify launch.json to have a Local Sandbox configuration point to your environment.

Checking ..\.github\AL-Go-Settings.json
Checking .AL-Go\settings.json
Checking ..\.github\.settings.json
Checking .AL-Go\.settings.json
Checking .AL-Go\dbaldwin.settings.json
Checking System Requirements

Container name
--------------
Please enter the name of the container to create (default bcserver) bcappsource
bcappsource selected

Authentication mechanism for container
--------------------------------------
a Windows Authentication
b Username/Password authentication

Select authentication mechanism for container (default b)
Username/Password authentication selected

LicenseFileUrl
--------------
When developing PTEs, you can optionally specify a developer licensefile with permissions to object IDs of your dependant apps

Local path or a secure download URL to license file  (default none) "C:\_CAI Licenses\CAIv20.flf"
"c:\_cai licenses\caiv20.flf" selected

Downloading BcContainerHelper latest version
Using Expand-Archive
BcContainerHelper version 4.0.3
BcContainerHelper emits usage statistics telemetry to Microsoft
Checking ..\.github\AL-Go-Settings.json
Checking .AL-Go\settings.json
Checking ..\.github\localDevEnv.settings.json
Checking .AL-Go\localDevEnv.settings.json
Checking .AL-Go\dbaldwin.settings.json
Checking type
Checking appFolders and testFolders
Application Dependency 18.0.0.0
Checking artifact setting
Downloading artifacts from https://bcartifacts.azureedge.net/sandbox/20.5.45456.46935/us
Updating app- and test Dependencies
Analyzing Test App Dependencies
WARNING: No performance test apps found in bcptTestFolders in .AL-Go\settings.json
WARNING: No test apps found in testFolders in .AL-Go\settings.json
WARNING: No apps found in appFolders in .AL-Go\settings.json
Repository is empty
WARNING: No app folders found
  _____                               _
 |  __ \                             | |
 | |__) |_ _ _ __ __ _ _ __ ___   ___| |_ ___ _ __ ___
 |  ___/ _` | '__/ _` | '_ ` _ \ / _ \ __/ _ \ '__/ __|
 | |  | (_| | | | (_| | | | | | |  __/ |_  __/ |  \__ \
 |_|   \__,_|_|  \__,_|_| |_| |_|\___|\__\___|_|  |___/

Pipeline name               localDevEnv
Container name              bcappsource
Image name
ArtifactUrl                 https://bcartifacts.azureedge.net/sandbox/20.5.45456.46935/us
SasToken                    Not Specified
BcAuthContext               Not Specified
Environment
ReUseContainer              False
KeepContainer               True
Auth                        UserPassword
Credential                  Specified
CompanyName
MemoryLimit                     8G
Enable Task Scheduler           False
Assign Premium Plan             False
Install Test Runner             False
Install Test Framework          False
Install Test Libraries          False
Install Perf. Toolkit           False
InstallOnlyReferencedApps       True
generateDependencyArtifact      False
CopySymbolsFromContainer        False
enableCodeCop                   False
enableAppSourceCop              False
enableUICop                     False
enablePerTenantExtensionCop     True
doNotPerformUpgrade             False
doNotPublishApps                False
uninstallRemovedApps            False
escapeFromCops                  False
doNotBuildTests                 False
doNotRunTests                   True
doNotRunBcptTests               True
useDefaultAppSourceRuleSet      False
rulesetFile
azureDevOps                     False
gitLab                          False
gitHubActions                   False
License file                    Specified
CodeSignCertPfxFile             Not specified
CodeSignCertPfxPassword         Not specified
CodeSignCertIsSelfSigned        False
KeyVaultCertPfxFile             Not specified
KeyVaultCertPfxPassword         Not specified
KeyVaultClientId
BuildOutputFile
TestResultsFile                 C:\Users\dbaldwin\OneDrive - Computer Associates, Inc. - MBS\Documents\_ALPROJECTS\_PS\TestResults.xml
BcptTestResultsFile             C:\Users\dbaldwin\OneDrive - Computer Associates, Inc. - MBS\Documents\_ALPROJECTS\_PS\bcptTestResults.json
TestResultsFormat               JUnit
AdditionalCountries
PackagesFolder
OutputFolder
BuildArtifactFolder
CreateRuntimePackages           False
AppVersion
AppBuild                        0
AppRevision                     0
Install Apps
- None
Install Test Apps
- None
Previous Apps
- None
Application folders
- None
Test application folders
- None
BCPT Test application folders
- None
Custom CodeCops
- None

  _____       _ _ _                                          _        _
 |  __ \     | | (_)                                        (_)      (_)
 | |__) |   _| | |_ _ __   __ _    __ _  ___ _ __   ___ _ __ _  ___   _ _ __ ___   __ _  __ _  ___
 |  ___/ | | | | | | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '__| |/ __| | | '_ ` _ \ / _` |/ _` |/ _ \
 | |   | |_| | | | | | | | (_| | | (_| |  __/ | | |  __/ |  | | (__  | | | | | | | (_| | (_| |  __/
 |_|    \__,_|_|_|_|_| |_|\__, |  \__, |\___|_| |_|\___|_|  |_|\___| |_|_| |_| |_|\__,_|\__, |\___|
                           __/ |   __/ |                                                 __/ |
                          |___/   |___/                                                 |___/

INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
Pulling mcr.microsoft.com/businesscentral:10.0.19041.1415

Pulling generic image took 4 seconds

   _____                _   _                               _        _
  / ____|              | | (_)                             | |      (_)
 | |     _ __ ___  __ _| |_ _ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __
 | |    | '__/ _ \/ _` | __| | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | |____| | |  __/ (_| | |_| | | | | (_| | | (__ (_) | | | | |_ (_| | | | | |  __/ |
  \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|
                                     __/ |
                                    |___/

BcContainerHelper is version 4.0.3
BcContainerHelper is running as administrator
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows 10 Pro - 21H1
Docker Client Version is 20.10.17
Docker Server Version is 20.10.17
Removing Desktop shortcuts
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.19041.1415
Creating Container bcappsource
Style: sandbox
Multitenant: Yes
Version: 20.5.45456.46935
Platform: 20.0.45448.46843
Generic Tag: 1.0.2.13
Container OS Version: 10.0.19041.1415 (2004)
Host OS Version: 10.0.19043.1826 (21H1)
WARNING: Host OS is 21H1 and Container OS is 2004, defaulting to process isolation. If you experience problems, add -isolation hyperv.
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file "c:\_cai licenses\caiv20.flf"
New-BcContainer Telemetry Correlation Id: 0690c709-5eaf-404c-87ec-a243e36380ba
Run-AlPipeline Telemetry Correlation Id: 3e29b780-9c81-433f-bdf0-b73aff0ad835
Removing BcContainerHelper
Exception calling "GetExtension" with "1" argument(s): "Illegal characters in path."
At C:\Users\dbaldwin\AppData\Local\Temp\24447d37-d247-46f6-9aa9-a61f50061f20\BcContainerHelper\ContainerHandling\New-Na
vContainer.ps1:1479 char:13
+             $ext = [System.IO.Path]::GetExtension($licenseFile)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException

**Comment by fselles** [comment]
Same here. Tried local license file and Azure Secure URL. Without a license file everything works ok and the container is build. Any thoughts or updates?

**Comment by buzzwick** [comment]
Okay, so it turns out the "illegal characters" are in the path to the license file, and they are...quotes. Single or double quotes around the file path to the license, the script does not like them. Enter the path without them and the container is built just fine. 
A possible enhancement: strip leading and trailing single/double quotes off the path submitted, just to avoid a somewhat nonspecific error message. Or specify the form of the path string in the prompt. Either way, finally got a container built.

Also: turns out that the handy little "run" icon in the upper right corner of the VSCode Powershell extension does not work. You get the rapidly-disappearing external Powershell window, then nothing. Using the Terminal->Run Current File runs the script in the terminal window as it should. Who knew.

**Comment by freddydk** [comment]
The Latest Version of BcContainerHelper runs on PowerShell 7, meaning that the mechanism of spinning up a seperate PowerShell window isn't needed anymore.
LocalDevEnv and CloudDevEnv now runs fine inside VS Code.
