### ISSUE TITLE
Deploy Apps to Online Sandbox 

### ISSUE THREAD

**Issue by kb-dynaway** [microsoft/AL-Go#219]
Hi Freddy,

I try to publish the apps that we develop to online sandbox using documentation provided in this script [https://github.com/microsoft/AL-Go/blob/main/Scenarios/RegisterSandboxEnvironment.md](url) .  However, I run into issue as below

`An App with same app Id '<AppID>' is Already published with Global scope with name '<AppName>'. Please use the Extension market place to install the extension or use a new app id for the current extension.`

In my own scripts I was able to avoid such error by running -scope Tenant

`Publish-BCContainerApp -bcAuthContext $authContext -environment $EnvironmentName -appFile $_.FullName -syncMode ForceSync -scope Tenant
`

Can you check if that would be possible also in AL GO since this is critical functionality for us.

**Comment by freddydk** [comment]
QQ - right before the error in the log, which of the following messages er displayed:
1. Using S2S, publishing apps using automation API
2. Publishing apps using development endpoint
3. Publishing apps using automation API
Thanks

**Comment by kb-dynaway** [comment]
Using S2S, publishing apps using automation API

But not right before. 

I have there whole section about:
Extensions before:
![image](https://user-images.githubusercontent.com/106300783/193663418-7723cc10-3518-4e92-9868-d6f2006a45a5.png)

then 
Publishing and InstallingERROR The remote server returned an error: (400) Bad Request.

Extensions after:
![image](https://user-images.githubusercontent.com/106300783/193663458-1afa2fa9-4030-4a4a-b3ea-e90f10486eb0.png)

**Comment by freddydk** [comment]
Yeah, so that mechanism uses S2S - hence is using the automation API (Publish-PerTenantExtensionApps)
Not sure I can control anything there, will have a look.

If you change to impersonation - it will use Publish-BcContainerApp instead - and should work

**Comment by kb-dynaway** [comment]
Is there instruction how to do it? Do I need to add the token or removing the ClientSecret would be enough?

**Comment by freddydk** [comment]
`New-BcAuthContext -includeDevicelogin | New-AlGoAuthContext | Set-Clipboard
`
should be enough

**Comment by kb-dynaway** [comment]
the instruction helped - Thank you very much @freddydk . Just for others to give step by step how to do so:
1. Copy line from Freddy.
2. Paste in PowerShell and add -tenentId after New-BCAuthContext
3. Run the command - it will copy to clipboard the Auth. Context
4. Paste the whole to secret AUTHCONTEXT for the environment

**Comment by freddydk** [comment]
Note that the refresh token is only good for 90 days - then it needs renewal
