### ISSUE TITLE
Setting failOn does not work properly

### ISSUE THREAD

**Issue by kb-dynaway** [microsoft/AL-Go#220]
Hi Freddy,

I specified the settings.json as below:

`{
    "country":  "us",
    "AppSourceCopMandatoryAffixes":  [
        <ourPrefixes>
    ],
    "appFolders":  [
    ],
    "enableCodeCop": true,
    "enableUICop": true,
    "failOn": "warning"
}`

However I do not get failOn warnings. It is still passing the build.

![image](https://user-images.githubusercontent.com/106300783/193640497-4a91295f-4c1a-467c-bde0-1244d855b25d.png)

And here is what I can find in the build:

![image](https://user-images.githubusercontent.com/106300783/193640624-1be2c3db-0a29-4ce7-bcc0-adfbf719e165.png)

Is there anything that I should change in the settings?

**Comment by freddydk** [comment]
In the build output, under Build, Run pipeline, expand the very first run line.
What is the value of failon there:
![image](https://user-images.githubusercontent.com/10775043/193654381-81753d75-dd6b-4b4f-a7c8-3f096555453c.png)

(Just to see if your setting is correctly found)

**Comment by kb-dynaway** [comment]
Thx the case - there is no such parameter in the parameters

**Comment by freddydk** [comment]
Not in parameters - in env variables under the first > Run...

**Comment by freddydk** [comment]
You can search the log

**Comment by kb-dynaway** [comment]
Ok now see it: 
![image](https://user-images.githubusercontent.com/106300783/193663890-497a4dd2-5165-4dc1-b1ef-93e25040b433.png)

**Comment by freddydk** [comment]
Ok, so the setting gets read correctly - will investigate

**Comment by freddydk** [comment]
The error is in ContainerHelper - will be fixed in the next preview (which automatically is selected when using AL-Go preview).
