### ISSUE TITLE
Example how to use "artifact" setting

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#222]
Hey @freddydk , 

I would like my app to be build on the latest version for v20. At the moment, I hardcoded URL within "artifcat" setting in file Al-GO-Settings.json

![image](https://user-images.githubusercontent.com/16342128/193766365-f65914f2-d862-4bac-ad4d-f819c01ae9e8.png)

According to AL-GO settings documentatation there's an option to use 'search specification', but it's a bit unclear how to do it. Can you provide an example? Is it necessary to specify storageaccount? If yes, what should it be then?

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/al-go/algo-settings#advanced-settings

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
It is basically the parameters for Get-BcArtifactUrl with / between them.
`"artifact":  "storageaccount/type/version/country/select"`
defaults are
`bcartifacts/sandbox//us/latest`
so, in your case:
`"artifact":  "//20/base/latest"`
might do it?
