### ISSUE TITLE
Increase the version of App - can it support dependency app increase

### ISSUE THREAD

**Issue by kb-dynaway** [microsoft/AL-Go#223]
Hi Freddy,

Would it be possible to add a parameter to the Action "Increment version number" to update also dependency apps numbers. It would be useful if the apps that in the same repository/project are updated then also dependent app would have the dependency increased. 

For example:

I have 3 Apps:  A, B, C. App B depends on A, and C depends on A and B.

I update Apps version to 2210.1:

**Current situation:** App.json is updated in all 3 apps but only app version is updated
**What would be nice:**  App.json is updated in all 3 apps - version of app is updated, the version in section dependency is also updated to the new version

**Comment by freddydk** [comment]
I will think about this - might be the right thing to do for apps in the same repo/project.

**Comment by fvet** [comment]
+1

We currently scripted this in Azure DevOps via a custom pipeline. Would be great if we can achieve the same if we would move to GitHub...

![image](https://github.com/microsoft/AL-Go/assets/25268332/b8231dfd-0446-4f7e-ace4-6d3b96969168)

@freddydk  Any plans on providing support for updating all **dependencies** for apps managed in the same repo when running 'Create Release' / 'Increment version number'?

![image](https://github.com/microsoft/AL-Go/assets/25268332/1b2e8d34-e308-42c7-99c7-10da8882f44b)

**Comment by freddydk** [comment]
As you can see in this PR: https://github.com/BusinessCentralApps/buildorder/pull/168/files the next version will also update dependencies to other apps in the same repository.
