### ISSUE TITLE
Set doNotBuildTests and doNotRunTests on Actions Test Current, Next Minor, Next Major

### ISSUE THREAD

**Issue by kb-dynaway** [microsoft/AL-Go#224]
Hi Freddy,

Would it be possible to add to the Actions related to tests Set **doNotBuildTests** and **doNotRunTests** parameters? It would allow to handle scenario like below:

- Every time when build is triggered the tests are skipped (it is taking over 1 hour to run all tests and most of them we know will pass)
- Every night or once per week I would like to run the build including all tests to be sure next releases and current release is still working 

At this moment if in settings there is **doNotBuildTests** and **doNotRunTests** the tests are always skipped - either triggered manually or automatically.

The current workaround could be to have two repositories one with Apps and one with Test Apps. But this add addtional complexity for the developers that they would like to avoid.

Let us know what would be other options to handle scenario above

**Comment by freddydk** [comment]
If you set DoNotBuildTests and DoNotRunTests to true in AL-Go-Settings.json - and then set them to false in Test Current.settings.json + add scheduling info to the test current settings to run nightly then you should have what you are looking for.

**Comment by kb-dynaway** [comment]
Great! I will test it and close the issue after that. Thank you a lot.

**Comment by kb-dynaway** [comment]
Works as expected. Thank you
