### ISSUE TITLE
Feature request: Treat failed tests as warnings

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#225]
Hey @freddydk,

Currently all failed tests are threated as errors in CI/CD pipeline. It would be handy to have an option to display failed tests as warning. Thus, it would not fail entire pipeline. 

We just flipped big extension to the latest BC, and naturally we have quite a list of failing tests cases. In this situation, we still want our extension to be build and deployed to test environment, & we want to run tests cases and follow its results. 

At the moment, we just completely disabled test running within CI/CD pipeline using "doNotRunTests" param.

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
You should be able to set "failsOn":  "None" in settings - not totally sure that this works though - will investigate.

**Comment by gntpet** [comment]
according to your comments [here](https://github.com/microsoft/navcontainerhelper/blob/983882f55b10ab649a13b50539cbb679cf3b5c4c/AppHandling/Run-AlPipeline.ps1), failon is used only for compiler warnings/errors. So you could threat compiler warnings as errors.

**Comment by freddydk** [comment]
Yeah - will investigate that - and also include an option to not fail on test failures.

**Comment by freddydk** [comment]
Next version you will have a property called 
```
treatTestFailuresAsWarnings
```
which you can set to true and instead of a failing build, you will get: 
![image](https://user-images.githubusercontent.com/10775043/197389635-1bdab0fa-f3b6-4aef-b30f-e0569d3e0860.png)

**Comment by gntpet** [comment]
Just tested it. It works perfectly. Thank you @freddydk
