### ISSUE TITLE
Feature request: Allow deployments with "Schema Sync Mode" = Force

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#227]
Hey @freddydk, 

Would it be possible to add an additional option to environment settings, allowing us to deploy extensions with "Schema Sync Mode" = Force.

It's very common that during feature development process, you change fields names or remove stuff. In those scenarios, CI/CD fails due to the breaking changes. Then, you have to deploy artifacts manually to the sandbox environment, and restart failed jobs for build to complete. 

It would be great to have this setting per environment settings, since there are some environments were you really want to prevent accident deployment with breaking changes. 

Not sure if API allows that, but it's possible todo it through UI. 
![image](https://user-images.githubusercontent.com/16342128/194497358-b62adb9c-7e38-488e-8dab-06e6870c1ce7.png)

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
Sounds like a fair request - will look into this.

**Comment by freddydk** [comment]
Automation API doesn't support ForceSync.
What did you setup as authentication?
If you are using S2S, then AL-Go will use Publish-PerTenantExtensionApps (automation API) to publish to the environment.
If you are publishing to production, then AL-Go will always use Publish-PerTenantExtensionApps 
if you are publishing to a sandbox environment and your authcontext is a refreshtoken (i.e. impersonation), then AL-Go will publish to the Dev. Endpoint - and should support force sync.

**Comment by gntpet** [comment]
I'm deploying to sandbox and see that it's using dev endpoint

![image](https://user-images.githubusercontent.com/16342128/196103375-ca3fd4fc-1cb4-4ea7-b9fd-72525620be63.png)

**Comment by freddydk** [comment]
Ok - will have a look whether I can/should enable forcesync either always or selective when deploying to dev endpoint

**Comment by freddydk** [comment]
I have filed a bug on the API team to enable this through the management API
When this is done, this will be implemented.

**Comment by freddydk** [comment]
The implementation is now done in BC SaaS and in BcContainerHelper - will add this as a paratmeter in the DeployTo structure in settings.
