### ISSUE TITLE
Deployment to SaaS Sandboxes fails with timeout

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#249]
We have a repo that has 8 different apps to be deployed as PTEs.

I am not sure why it takes so long to publish those apps, but the deployment task has been running for 1 hour and then received an "401 unauthorized" error at the last app to deploy. It seems that it is an issue with the timeout, since I am assuming that the authorization is done at the beginning and then everything is deployed. The app was actually deployed, so I am assuming that it was checking, if the deployment worked and failed at that point.

While, in my eyes, the deployment should never take that long, if it does, it seems there is no way to deploy at all (at least not without the pipeline failing).

**Comment by freddydk** [comment]
Sounds like the same problem as: https://github.com/microsoft/navcontainerhelper/issues/2718
You could try to add the following setting to .github\AL-Go-Settings.json
```
"NoOfSecondsToSleepAfterPublishBcContainerApp": 10
```
It is really a ContainerHelper setting, but containerHelper settings can be specified directly in AL-Go as well.

Let me know how this goes - I will file an issue on the platform team if this solves the issue.

**Comment by pzentner** [comment]
This seems to have resolved this issue.

**Comment by freddydk** [comment]
Ok, so it seems like there is a race condition, where publishing apps (probably with schema changes) needs to complete before the next can be published.
Will create a bug for the server team and keep the workaround here.

Thanks

**Comment by freddydk** [comment]
@pzentner - can you still repro this if you set the NoOfSecondsToSleepAfterPublishBcContainerApp to 0?
If that is the case, we would very much like to borrow the apps with which you can repro this.
Thanks
