### ISSUE TITLE
Deployment to production fails on status Unknown, but app is succesfully deployed

### ISSUE THREAD

**Issue by PeterDerks** [microsoft/AL-Go#259]
Hi,

The AL Go workflow "Publish to Environment" deployment gives a fail status:
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/33145826/197480946-b52d9676-d569-4acb-a92c-b87b554e4ae1.png">

When I look in BC then I see a status "Unknown". After a while the app is succesfully installed without issues.

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/33145826/197481569-352c63d7-879d-4cae-b140-d64db35441a9.png">

CI/CD deployments give no issues.

**Comment by freddydk** [comment]
Is this a multi-project repo - and both projects are deployed to the same environment?

**Comment by PeterDerks** [comment]
This is a single project deployed to multiple environments

**Comment by freddydk** [comment]
I'd probably need to see what actually happens in the workflows to troubleshoot this.
Any chance you can add me to the repo - or provide the full output of the workflows?

**Comment by PeterDerks** [comment]
[VC_raw_output.txt](https://github.com/microsoft/AL-Go/files/9850371/VC_raw_output.txt)

as you can see there is a status Unknown:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/33145826/197490631-0185bf24-08fc-43fd-a0cf-9dce44bf6b79.png">

**Comment by freddydk** [comment]
Ok, it looks like some kind of unknown error happens while waiting for the deployment.
What I don't quite understand is, that there are two jobs with Deploy to LIVE
It looks like it is deploying to the same environment simultaneously?

**Comment by PeterDerks** [comment]
The environments are different. They are named LIVE (customer A), LIVE (Customer B), etc.   We use the ENVIRONMENTNAME secret.

<img width="652" alt="image" src="https://user-images.githubusercontent.com/33145826/197493132-9e67ab1e-1c3e-44cb-b1f1-2c82eddd1fc4.png">

The deployment is eventually succesfull on both tenant environments.

**Comment by freddydk** [comment]
Got it.
Will investigate

**Comment by freddydk** [comment]
There was a retry algorithm in Publish-PerTenantExtensionApps, which in this case got bypassed.
A fix is included in the next preview of BcContainerHelper. Should be live in an hour.

If you add a setting to .github\AL-Go-Settings.json called

"bcContainerHelperVersion":  "preview"

then AL-Go should shift and use the preview of BcContainerHelper, which should have this fix.
Can you check this out and report back?

**Comment by PeterDerks** [comment]
thanks freddy for your support.
