### ISSUE TITLE
PTE with references to ForNAV

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/AL-Go#263]
I have a PTE that is referencing the ForNAV libraries in a report.  I am getting this error when compiling the app.  Is there a way to support this in a PTE?

  Error: AL0451 An assembly named 'ForNav.Reports.6.3.0.2260, PublicKeyToken=null' could not be found in the assembly probing paths 'C:\Program Files\Microsoft Dynamics NAV\210\Service, C:\Program Files (x86)\Open XML SDK\V2.5\lib, c:\Windows\Microsoft.NET\Assembly, C:\Test Assemblies\Mock Assemblies,

**Comment by freddydk** [comment]
Is this for on-premises?
I assume you got the ForNAV app to add as a dependency, right?
Did you also get this DLL?

**Comment by tscottjendev** [comment]
Yes, this on premise.

No I did not have the ForNAV App.  I will try that again. 

I have the DLL.  

I am not sure how to do this.

**Comment by freddydk** [comment]
On-premises isn't supported out-of-the-box and the primary reason is, that stuff like DLLs and such can be tricky to get right,
If you add me to the repo, then I can try to modify some settings to make this work - then I can help others in the same situation with a blog post maybe,

**Comment by tscottjendev** [comment]
Thanks @freddydk.  I will get that setup and we can discuss.

**Comment by tscottjendev** [comment]
@freddydk I have added you to as a contributor to the repo.  The branch with AL:GO is `setupALGO`

**Comment by freddydk** [comment]
Do you have the DLL checked in to the repo - or where do you have the DLL?

**Comment by tscottjendev** [comment]
It is not currently checked in but I can put it there.  Give me a bit.  Trying to get ready for Directions EMEA (just like you :P)

**Comment by freddydk** [comment]
Yeah, I won't be looking at anything this week, so no hurries:-)

**Comment by tscottjendev** [comment]
I added a `.netpackages` folder to the setupALGO branch with the DLL's needed.

**Comment by tscottjendev** [comment]
@freddydk,  I have migrated this to a "cloud ready" app.  So. there are no DLLs to worry about.  

I can't find the settings documentation on how to include dependent app files.  I thought I found it once but not now.
