### ISSUE TITLE
Can’t create an empty company for the tests

### ISSUE THREAD

**Issue by navlarste** [microsoft/AL-Go#266]
**Cenario:**
We want to create an empty company to do our tests, we create all the test data with code.

**The problem:**
•	Creates a new repo with Actions "Create a new app" and "Create a new test app" without any problems. It is for Cloud.
•	Adds the line "companyName": "Test" in AL-GO settings
Gets the following error: 
RunPipeline action failed. Error: **Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder**

![image](https://user-images.githubusercontent.com/32996357/198883032-3f5bd30d-72fe-47c2-ba01-c4d7a3620781.png)

**Comment by freddydk** [comment]
According to this: https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md#run-alpipeline-script-override
You can override behaviors from Run-AlPipeline.

Meaning that if you place a file called ImportTestDataToBcContainer.ps1 in the .AL-Go folder, you can write a script, which prepares your container for test runs.

The file should start with:

Param([Hashtable]$parameters)

and the parameters hashtable will contain three properties:

ContainerName
Tenant
Credential

In AL-Go the default behavior of this is to import Configuration packages like this:

UploadImportAndApply-ConfigPackageInBcContainer `
                                -containerName $parameters.containerName `
                                -Credential $parameters.credential `
                                -Tenant $parameters.tenant `
                                -ConfigPackage $configPackage `
                                -PackageId $packageId

where configpackage and packageid are determined by settings.
If you override the function yourself, the configpackage functionality is disabled and you have to do everything yourself.
