### ISSUE TITLE
CICD Branches

### ISSUE THREAD

**Issue by darrenwaller** [microsoft/AL-Go#267]
Do you have an example of how to get this working? We are using different branch names to 'main' so would like to use these settings. Can you also confirm which files these settings should be added.

New Repo setting: CICDPushBranches can be specified as an array of branches, which triggers a CI/CD workflow on commit. Default is main', release/*, feature/*
New Repo setting: CICDPullRequestBranches can be specified as an array of branches, which triggers a CI/CD workflow on pull request. Default is main

Thank you

**Comment by freddydk** [comment]
These settings goes into 
`.github\AL-Go-Settings.json`

and then you run Update AL-Go System Files, which will modify the yaml files for you.
I am not sure that AL-Go for GitHub will work with the main repo called anything but main.
I have a work item in the backlog to ensure that this works, but for now - main for the main repo is the safest bet.
