### ISSUE TITLE
Test Next Minor, Test Next Major, CI/CD are failing when appDependencyProbingPaths is defined

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#269]
I am currently using the preview version of AL-Go and last night all builds started failing with the error message that an app can't be downloaded when trying to download symbols. The app that can't be downloaded is defined in the appDependencyProbingPaths - referencing another repo in the same organization.

Did anything change within the process recently? It seems like it doesn't install the apps anymore that are referenced this way.

**Comment by gntpet** [comment]
I'm experiencing similar issue related to appDependencyProbingPaths. In my case, I'm using release status="include", but pipeline fails with an error:

`Error: Invalid release status 'include' is encountered.`

my al go settings files looks like this:
```
{
    "country":  "it",
    "appFolders":  [
    ],
    "testFolders":  [
    ],
    "appDependencyProbingPaths":  [
        {
            "repo":  ".",
            "release_status":  "include",
            "projects":  "SRS.core"
        }
    ]
}
```

**Comment by pzentner** [comment]
@gntpet I think your issue is different. The valid release statuses - according to documentation are:

release_status = latestBuild/release/prerelease/draft (default release)

So, I am assuming that this is why yours is failing with the error you are getting.

**Comment by gntpet** [comment]
That's undocummeted 'feature', which is used when when you have multiple projects within the same repository. So, instead of downloading dependencies from releases, it just look at 'dependecy' folder within same repo. It was working fine 5 days ago. 

Anyhow, I'm creating new ticket #270 for it.

**Comment by freddydk** [comment]
BTW - for multiple projects - the next preview will have a new setting called useProjectDependencies, which will build projects in the right order and use the output from the other build.
= like it should be:-)
You can see here: https://github.com/businesscentralapps/buildorder how this works.

Set UseProjectDependencies to true and run Update AL-Go System Files - then your pipelines will build things in layers.

**Comment by pzentner** [comment]
I can confirm that it's working now. Not sure, if you want to close the issues or if you want me to, in an instance like this. Leaving it open for you :)

**Comment by freddydk** [comment]
Thanks for the confirmation, I will close this.
