### ISSUE TITLE
CI/CD is failing when "release_status"="include"

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#270]
Hey @freddydk, 
We do have an issue with build pipelines with "release_status"="include". I get the following error message:

`RunPipeline action failed. Error: Invalid release status 'include' is encountered.`

I get this error with _stable_ & _preview_ versions of AL-GO-PTE

CI/CD was working fine 5 days ago. 

My AL_GO Settings file looks like this:
```
{
    "country":  "it",
    "appFolders":  [
    ],
    "testFolders":  [
    ],
    "appDependencyProbingPaths":  [
        {
            "repo":  ".",
            "release_status":  "include",
            "projects":  "SRS.core"
        }
    ]
}
```

let me know if you need full log.

**Comment by gntpet** [comment]
uploading log file
[logs_174.zip](https://github.com/microsoft/AL-Go/files/9913427/logs_174.zip)

**Comment by freddydk** [comment]
If you update system files from preview now - it should work again.
But look at the comment in the other bug - you should try UseProjectDependencies.

**Comment by freddydk** [comment]
BTW . with useProjectDependencies, you can remove the appDependencyProbingPaths above

**Comment by gntpet** [comment]
Pipelines are running again. thank you very much @freddydk

Just a question regarding updates. Do you have a blogpost or some page explaining AL-GO update/release process. Our pipeline stopped working, without updating al-go system files. So I presume we got some dynamic updates by fetching other repo, on a fly, am I right?

Is it possible for us to control updates? Meaning, get updates only when I update al-go system files. This way I could verify first, if pipeline is still working before merging update to _master_.

**Comment by freddydk** [comment]
When you are using preview, you are subject to be broken like this, sorry.
Shouldn't happen - but it can.
Not sure if I can make the preview process better - I will think about this.
Once v2.1 has shipped - you can switch to use @main - then you won't be broken - also not if v2.2 or later are released.

**Comment by gntpet** [comment]
Yesterday, I tried to switch back from preview to main, but it did not work either or I mixed something up. Anyhow, we will try to switch to main channel once 2.1 is released. Thank you again
