### ISSUE TITLE
Create Release error

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#274]
When creating a release - using the preview AL-Go-AppSource, I am getting an error at the DeliverToStorage step. Error is below. Didn't change the storage context and it's compressed and doesn't have any new lines. I also ran the "Update AL-Go System Files" to make sure that I'm on the latest version before reporting it.

At D:\a\_temp\4[90](https://github.com/xxx/xxx/actions/runs/3388395687/jobs/5630373918#step:9:91)e2e6b-bab4-4d07-835f-a054b14736e4.ps1:7 char:43
+ Write-Host "storageContext=$storageContext"
+                                           ~
The string is missing the terminator: ".
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

**Comment by freddydk** [comment]
That was a bug.
Please Update AL-Go System Files and retry.

**Comment by pzentner** [comment]
I can confirm that this works now
