### ISSUE TITLE
Publish to AppSource workflow

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#276]
I tried publishing an app using the workflow and am getting the following error message:

WARNING: AuthContext.Scopes is 'https://api.businesscentral.dynamics.com/', should have been 'https://api.partner.microsoft.com/.default'

When trying "New-BcAuthContext" with the proper scope, it works, but it seems that the scope isn't set correctly when running the workflow? Am I missing something in the settings? I do not have it set to automatic delivery during build.

**Comment by freddydk** [comment]
When you say the scope isn't set correctly when running the workflow - what do you mean?
The scope is part of the authcontext and not set in the workflow (or maybe i misunderstood something) - it is just validated in the workflow.

**Comment by pzentner** [comment]
You answered my question basically... The scope was missing in the AppSourceContext.

Second question in the process: Is there a way to define an external repo as the library app (or "apps") when publishing to AppSource? I can only see the "appSourceMainAppFolder" and it seems that the "appDependencyProbingPaths" is not used in the process. Is there any other way to define this?

**Comment by freddydk** [comment]
Right now, the remaining apps from the same repository are attached as library apps.
Apps from other repositories are expected to be submitted from there.

**Comment by pzentner** [comment]
Thank you!

**Comment by freddydk** [comment]
BTW - there is a function called 

New-ALGoAppSourceContext -authContext $authcontext

![image](https://user-images.githubusercontent.com/10775043/200086983-66129964-7045-4aa3-923a-297024bb890d.png)

which will test and format your authcontext correctly.

you can add | Set-Clipboard to put the value into the clipboard.
