### ISSUE TITLE
Int overflow with "versioningStrategy": 1

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL-Go#277]
When setting "versioningStrategy": 1 in settings.json I get an overflow error: 

`ReadSettings action failed. Error: Cannot convert value "3401625876" to type "System.Int32". Error: "Value was either too large or too small for an Int32." Stacktrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v2.1\ReadSettings\ReadSettings.ps1: line 64 at <ScriptBlock>, D:\a\_temp\efdfdcfb-ed32-440f-a64a-5ecde45fe317.ps1: line 1 at <ScriptBlock>, <No file>: line 1`

The GITHUB_RUN_ID of 3401625876 is way beyond the limit of Int32.

This is not important to me, having a 10 digit build number just becomes too much, but I was curious and wanted see what versioningStrategy 1 version numbers would look like.

**Comment by freddydk** [comment]
Yeah, not sure what has happened there.
Looks like the RUN_ID is globally unique now.
When I run two instances of a sample workflow, I get
3402775260
and
3402775415

Which kind of looks like a continuation of yours (340xxxxxxx)
I do not have any proof, but I am pretty sure the implementation was like described:
![image](https://user-images.githubusercontent.com/10775043/200153367-f9644a1a-4946-4a82-bdbe-a9eb04c95247.png)

and the number was increased for any workflow in that repo.
Now it seems to be any workflow in any repo - over the last 6 hours - increasing with around 200.000 an hour.

I will remove support for versioninigstrategy 1 - it looks like it hasn't worked for more than 6 months (or so)

I might create a new versioningstrategy. where build is run_id div (maxvalue-x) and release is run_id mod (maxvalue-x)+run_attempt, where x is the max number of attempts you could imagine.
