### ISSUE TITLE
Overflow error with "Update Build Job Check Run"

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#280]
Hey @freddydk, 

We are experiencing strange error with "Update Build Job Check Run" step. It fails with overflow error. See the image bellow. 
![image](https://user-images.githubusercontent.com/16342128/200575056-a23388f6-1394-4d95-b9d7-72bd3dc6c5a0.png)

I have a feeling it's related to the full tests results that are being passed to the body. 
![image](https://user-images.githubusercontent.com/16342128/200575223-4d40e17c-6b90-4750-abc7-4425155ba723.png)

Could it be something related to the new property "treatTestFailuresAsWarnings" that we are using?
Please let me know, if you need more detailed job log.

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
I have hotfixed this and only include the first 10 errors. (temp fix)
Will keep this bug open to fix this by including as many bugs as the buffer allows (real fix)

**Comment by gntpet** [comment]
Should I run AL-GO update?

**Comment by freddydk** [comment]
Not needed

**Comment by freddydk** [comment]
preview should be stable now and will only have few changes towards december 1st timeframe when it will merge into main.
