### ISSUE TITLE
Question: How to configure "UseProjectDependencies"

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#290]
I have a repo with multiple projects. Project A is required as a dependency for project B, but not for any others.

I have updated the system files and added "UseProjectDependencies": true to "AL-Go-Settings.json" in the root of the repo. Is there anything else that needs to be done (aka, defining appDependencyProbingPaths or something)?

When I am running the pipeline, everything builds except project B fails with the error that the symbols for the app from project A cannot be downloaded (not found). So, it doesn't get installed when running project Bs pipeline.

In case you need to look at anything, I am adding you to the repo...

**Comment by freddydk** [comment]
You need to run Update Al Go System files after you set UseProjectDependencies - did you do that?

**Comment by freddydk** [comment]
secret in settings won't work.
You can specify the name of a secret in settings - but secrets belong in secrets.

**Comment by freddydk** [comment]
Looks better now - BTW I do have a few fixes to the PR process coming

**Comment by pzentner** [comment]
> secret in settings won't work.
> You can specify the name of a secret in settings - but secrets belong in secrets.

Sorry, that's what I meant. I have the following in the settings.json of each project as well as in the AL-Go-Settings (even though I shouldn't have to as it's the default name, right?):

    "ghTokenWorkflowSecretName": "ghTokenWorkflow",

Then, in the key vault, I have the actual token.

but, unless I define the token as a repository secret, it doesn't seem to be working. You saw that the update of the system files failed and now that I added it again to the repo secrets, it ran through again.

I would have expected one more project to be in the first round of builds. The "Customizations" project is mentioned as a dependency in the "manufacturing" one. But, I guess, because it was built successfully before, it doesn't do this anymore. If this runs through, my original question is resolved.

Just wondering what is up with the ghWorkflowToken and why it's not working unless it's defined as a repo secret in GitHub. Or should I try it again now that everything else worked?

**Comment by freddydk** [comment]
If you want to grab your secrets from a keyvault you need the Azure_Credentials secret.
Then you can add the keyvaultname as a property in that compressed json string - or you need the keyvault name in AL-Go-Settings.json (for repo specific usage like update al go system files)
When using secrets in projects (like builds) the keyvaultname can be specified in the project,

**Comment by freddydk** [comment]
BTW - you typically only need the xxxSecretName if the secretname is different than xxx

**Comment by pzentner** [comment]
This works for every other project I have - I am using an organization secret for the AZURE_CREDENTIALS.

When I had the ghWorkflowTokenSecretName defined in the settings.json, the "Update AL-Go-System Files" workflow was failing. Once I added it into the repo secrets, it started working (obviously). However, when I moved it over to the AL-Go-Settings.json, it didn't work, but that is the issue, I think: I forgot the keyvaultname also in the al-go-settings.

I would assume that the update system files workflow doesn't go into the projects to gather any secrets, but only on the root and al-go-settings would be the only one then.

**Comment by freddydk** [comment]
You should be able to remove all the xxxSecretName settings (except for the codesigncert ones)

**Comment by freddydk** [comment]
Btw - the repo settings file will ALWAYS be applied.
The project settings files are only used when building or deploying specific projects.

**Comment by pzentner** [comment]
This was successfully completed. Thanks for you help
