### ISSUE TITLE
Issues with new pull-request handler in @preview channel

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#291]
Hey @freddydk , 

After making pull request, CICD pipeline now has 6 jobs instead of 3.

![image](https://user-images.githubusercontent.com/16342128/202398944-ffdae9b8-1baf-4e63-a75d-e9765ce60cfd.png)

they all 3 fail, while trying to download depdency

![image](https://user-images.githubusercontent.com/16342128/202399548-68341113-5050-40d0-8633-46cb813cee5a.png)

the ones that succeeds, compiles those dependencies, since they are within the same repo

![image](https://user-images.githubusercontent.com/16342128/202399978-95f0cd1d-4a87-44f1-9310-05ed8514c3f1.png)

p.s. I know I should move to stable channel, but we like testing latest technology :) 

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
Will roll out a fix for this later today.
And I do appreciate when people are using preview - so thanks for that.

**Comment by gntpet** [comment]
FYI, the same happens with stable channel as well.

**Comment by freddydk** [comment]
Isn't this fixed in preview now?

**Comment by gntpet** [comment]
It wasn't. we moved to stable channel for now. Now it seems ok
