### ISSUE TITLE
Multi Project repo - error in Test Current, Next Minor, and Next Major

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#292]
When building one of the projects, which has the dependency to another, it shows this error

Error: The remote server returned an error: (403) Forbidden. 

This comes after stating that the base app wasn't built and its trying to download from artifacts. However, the base app was built in the previous build step.

It's the same repo you already have access to from yesterday.

Am I doing something wrong again?

**Comment by pzentner** [comment]
The "download from different repo" is the one base app that is defined in a different repo. However, the other dependency is in the same repo and is built before this app. This is the full error:

```
Checking project dependencies
Checking appDependencyProbingPaths
Dependency to projects '*' in https://github.com/nav-x-llc/library@main, version latest, release status release
Warning: No performance test apps found in bcptTestFolders in .AL-Go\settings.json
Project: xxx-Manufacturing
Project dependencies: xxx-Customizations
Locating all Apps artifacts from probing paths
xxx-Customizations not build, downloading from artifacts
Analyzing artifacts
https://api.github.com/repos/nav-x-llc/xxx/actions/artifacts?per_page=100&page=1
Error: The remote server returned an error: (403) Forbidden. 

Forbidden
```

The token that I have defined is a token that has full access to anything. The main thing is that in the "Test Current, Next Major..." it should be building the apps, but it says "not build, downloading from artifacts". Why would it not build it or rather it did build it, but why would it think that it didn't build it?

**Comment by freddydk** [comment]
This is a bug when using UseProjectDependencies.
A design flaw actually - will find a way around this.

**Comment by freddydk** [comment]
The problem was, that in PR check builds, test current, test next minor and test next major - the workflow doesn't publish any artifacts - and shouldn't
The fix is to create apps and testapps artifacts with a different name pattern and have a time-to-live of 1 day.
