### ISSUE TITLE
Handle different UAT and Main Branching in AL-Go for github

### ISSUE THREAD

**Issue by dksander** [microsoft/AL-Go#293]
Hey @freddydk,
The following description is an issue I suppose most VAR/PTEs deals with a lot.

**Problem:**
The customer orders Feature A and Feature B. Feature A take an hour to develop, but feature B take a week to develop, next week both features is ready and deploy to the customers UAT environment.

Now the customer test and approve feature B, and needs this it to be deployed immediately because it is business critical, but they will need more time to test Feature A. 

In our current setup we are using multiple branches to be deployed, at different environments at the customer, and I can’t see how AL-Go for Github can do the same and we need this.

Some features the customers approve within hours and others within months, and none of our customer will accept the needs to wait to finish all UAT for every feature currently in UAT branch.
We are currently doing that with having a Production/Main and a Testing/UAT branch within the same repo and moving code from UAT branch with tooling.
This is a real scenario:
![SimpleDev](https://user-images.githubusercontent.com/9249578/202642686-034a0849-ecae-4ecd-a6a3-14f922930f13.png)

 In this case it works, but when we are adding even more features and more developers this does not work right now in AL-Go for GitHub with only one main branch please consider the following scenario: 
![MultiDev](https://user-images.githubusercontent.com/9249578/202642786-64293d56-d631-4fd3-8eed-99f11571286f.png)

 
In the example Feature A and Feature C is both finished in development within main branch but the customer only actable feature C to be deployed in Production and later Feature B is developed and will moved to production, and feature A will first once in the future be acceptable to Production environment.

How can we accomplice this with AL-Go for GitHub?

**Comment by freddydk** [comment]
Thanks,

I think the request here would be to have a UAT branch, which can do CD to a UAT environment instead of only doing this from main - and of course not only one, but the ability to setup CD from various branches to various environments, right?

I guess the actual cherry-picking of features from UAT to the main branch, would be GIT gymnastics, not something AL-Go for GitHub should do, but something you do with other GIT tools, right?

**Comment by dksander** [comment]
Hey @freddydk 
Yes exactly 👍 If the CI/CD could be setup to run from multiple branches that would solved it. 
In Azure Devops I have the same build pipeline running on multiple branch and a different release pipeline per branch.

In my opinion the git gymnastics should be in another tool, mostly to allow each developers to choose a tool of their own choosing

**Comment by freddydk** [comment]
Yeah - today you can control which branches controls pull_request and push - but the deploy part is fixed to main.
I do have an item in the backlog for being able to use a different name for the main branch, but I think it would make a lot of sense to be able to control delivery and deployment as well for branches.
Will add this issue to that topic and include it when we get to that.

**Comment by freddydk** [comment]
You can see the backlog here: https://github.com/orgs/microsoft/projects/521/views/1?filterQuery=branch

**Comment by freddydk** [comment]
BTW - don't be confused that the item is currently located in the backlog column - the columns are not necessarily an order of priority - my assumption is that we will fix this sooner rather than later

**Comment by dksander** [comment]
That is really great! 
If you need test people for this, you can reach out to me at anytime
