### ISSUE TITLE
Possible Enhancement: Schedule deployment to environments

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#296]
The ask would be to be able to schedule a deployment action based on environment. This would be important, if you want to deploy PTEs into production environments, since you don't want to deploy them when users are in the system.

I am not sure what the best way would be, but one possibility would be to separate the Deploy into "Deploy" and "Deploy Production" and "hardcode" the "Deploy Production" to run only for "(Production)" environments. Then allow the definition of a cron schedule in the settings file, like it is possible for Current, NextMinor, and NextMajor. The problem with this approach would be that it would always deploy, but maybe that's not a big deal - as soon as the release turns from a "preview" into a release, it could be deployed.

Not sure, if this could also be a property of the environment where you can define "run hours".

The main issue is, in my eyes, that we would have a lot of scheduled jobs running or consuming minutes just to check, if something needs to be published or not.

Don't know, if you can define "on release creation after a certain time" (aka, execute deploy when a new release is created (not preview) and run the action after 6 pm).

Currently, I am using an outside tool that triggers the execution of a workflow through the GitHub API and it's manageable, but it would be great to have this all within GitHub/AL-Go and I would think that this could be useful for partners.

**Comment by freddydk** [comment]
The on schedule trigger in GitHub only allows us to make workflows, which are triggered repeatedly, following this syntax: https://crontab.guru/

We have discussed many solutions to this problem:
1. Allow DevOps pipelines to publish the app to an environment without installing it and schedule the install of an app inside Business Central.
2. Allow Business Central to directly pull the new version from a NuGet package created from your workflows.
3. Allow creation of a specific publish workflow for a production environment, which would trigger during "run hours" and publish if a new version was released. These workflows would be disabled after the version was deployed and enabled again by the release workflow.
4. Investigate whether a tool like https://posthook.io could be used easily to have an external service trigger a workflow run in your repository with a defined set of parameters.

Will move the suggestion to the backlog and investigate close when time allows.
