### ISSUE TITLE
Organize AL-Go repository

### ISSUE THREAD

**Issue by freddydk** [microsoft/AL-Go#302]
- [x] Main branch in https://github.com/microsoft/AL-GO is the "working" branch, i.e. the latest code
- [x] When deploying to preview, we will always deploy from main to AL-Go-PTE@preview and AL-Go-AppSource@preview, but there will be no preview branch of AL-Go-Actions. Instead, the preview branches will point to a SHA in the microsoft/AL-go/Actions (utilizing direct AL-Go functionality)
- [x] Setup CODEOWNERS, CI/CD process etc.
- [ ] Setup end2end testing to be run after completed CI in main branch
- [ ] Setup continuous deployment to preview from main
- [ ] Only allow fork PR's against main
- [ ] Setup github pages for deployment of documentation, scenarios, workshop etc. (investigate whether we can have preview and main)
- [ ] Have readme.md point to github pages
- [ ] Change aka.ms links to point to github pages

**Comment by mazhelez** [comment]
I have a couple of comments for now:
- Is there a reason we need to create _release_ branches? I believe we can simply use _git tags_ to mark releases.
We can leverage GitHub releases and any release will contain the "current source code" for the templates and actions, the release notes, etc.
On top on that, if we keep the AL-Go version as a setting (in the repos that use AL-Go), we could unblock the scenario for bringing back earlier version (in case the latest one has some unforeseen issues).
This is the way the GitHub actions are released at least. See [actions/checkout](https://github.com/actions/checkout). There are development branches, but the tags are nice and clean.

- Let's be diligent with RELEASENOTES: every PR should also affect that file (only adding to the _Preview_ section). We can introduce a check for that.
We can even be smart about the versioning based on the _Preview_ section.

- Not sure if that's part of the repo organization, but there's also a need of AL-Go library (PS library), with some commonly used functionalities. For instance, as part of my latest task (in ALAppExtensions repo) I had to create a pack a custom nuget and push it to nuget.org. Packing and pushing would have been so easy if we could integrate the corresponding actions that GitHub provides. However, if AL-Go is to allow customization only through PS scripts, there needs to be a library that exposes commonly used functionalities (such as nuget pack and push). Where would such library live? In AL-Go? In another related repo?

**Comment by freddydk** [comment]
My primary concern (and reason for release branches) is the documentation, workshops etc.
but maybe we can just use GitHub pages for that, then a release branch might not be needed.
Agree with releaenotes - let's get that updated and not approve any PR's which hasn't

For PowerShell functionality that should be available in scripts like the deliverto - I have put those in BcContainerHelper for now.
Reason for BcContainerHelper is that it is my only shipping vehicle for things like this.

I think BcContainerHelper needs to evolve into a BC module (like the AZ module), consisting of:

```
bc.auth
bc.nuget
bc.admincenterapi
bc.containerhelper
```

and then functionality like this would be clear in one of these modules.
These modules should be PS7 compatible, which would mean that we can switch a number of our runners to use linux instead of windows to save money (the build job which runs containers won't be able to change yet)
but for now - I would just place it in BcContainerHelper, where there already is a function for pushing to NuGet (without using the nuget.exe)
