### ISSUE TITLE
Downloading Signing Tools: Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."

### ISSUE THREAD

**Issue by janlehmkuhl** [microsoft/AL-Go#307]
**Error**
The following error message comes up at irregular intervals when signing our AppSource app:
`RunPipeline action failed. Error: Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request." Stacktrace: at Invoke-ScriptInBcContainer, C:\Users\ctm-admin\AppData\Local\Temp\56830cf8-55d0-4f00-8734-febfd1544175\BcContainerHelper\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 112 at Sign-BcContainerApp, C:\Users\ctm-admin\AppData\Local\Temp\56830cf8-55d0-4f00-8734-febfd1544175\BcContainerHelper\AppHandling\Sign-NavContainerApp.ps1: line 68 at <ScriptBlock>, C:\Users\ctm-admin\AppData\Local\Temp\56830cf8-55d0-4f00-8734-febfd1544175\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 687 at <ScriptBlock>, C:\Users\ctm-admin\AppData\Local\Temp\56830cf8-55d0-4f00-8734-febfd1544175\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1703 at <ScriptBlock>, C:\Users\ctm-admin\AppData\Local\Temp\56830cf8-55d0-4f00-8734-febfd1544175\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1693 at <ScriptBlock>, C:\Users\ctm-admin\AppData\Local\Temp\56830cf8-55d0-4f00-8734-febfd1544175\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1692 at <ScriptBlock>, C:\Users\ctm-admin\AppData\Local\Temp\56830cf8-55d0-4f00-8734-febfd1544175\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 758 at Run-AlPipeline, C:\Users\ctm-admin\AppData\Local\Temp\56830cf8-55d0-4f00-8734-febfd1544175\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 723 at <ScriptBlock>, C:\actions-runner\_work\_actions\microsoft\AL-Go-Actions\v2.1\RunPipeline\RunPipeline.ps1: line 343 at <ScriptBlock>, C:\actions-runner\_work\_temp\b37a9f1f-233b-4a11-a540-2f224d736482.ps1: line 1 at <ScriptBlock>, <No file>: line 1`

If we take a closer look at the log, this error message appears when downloading the "**Downloading Signing Tools**".

**The complete log is attached**
[logs_94.zip](https://github.com/microsoft/AL-Go/files/10103274/logs_94.zip)

**Note**
The error actually only comes up at irregular intervals and is not reproducible. In most cases, restarting the CI/CD pipeline helps us and the error message does not appear a second time.

**Comment by freddydk** [comment]
Sounds like the container doesn't have internet access or cannot resolve DNS.
You can try to add -dns 'hostdns' when you create the container (if you have the latest BcContainerHelper)

**Comment by freddydk** [comment]
Wrong answer - didn't see this was in AL-Go - are you running self-hosted agents?

**Comment by freddydk** [comment]
Looks like this is a self-hosted agent - what OS is that running on?

**Comment by freddydk** [comment]
The AL-Go equivalent of my first suggestion would be to add this to your .github/AL-Go-Settings.json:

```
    "defaultNewContainerParameters": { "dns": "hostDNS" }
```

**Comment by janlehmkuhl** [comment]
It's a self-hosted runner on Windows Server 2022, I'll take your setup and give feedback.

**Comment by janlehmkuhl** [comment]
Unfortunately, after I made the adjustment, at least one pipeline run ran into the same error again

![image](https://user-images.githubusercontent.com/94679485/204291883-98c038c6-abd7-4011-96e8-d796b673974c.png)
![image](https://user-images.githubusercontent.com/94679485/204292327-56c85cb5-b2f1-439a-a278-17b633902bcd.png)
![image](https://user-images.githubusercontent.com/94679485/204291983-c828ad6b-8103-4800-a85f-50520482b19b.png)

**Comment by freddydk** [comment]
Do you have one self-hosted runner or multiple?
Is it always one of the runners failing?
Could you maybe paste the full RunPipeline output from the failing job?

**Comment by janlehmkuhl** [comment]
These runners are all hosted on Azure

**Comment by freddydk** [comment]
Did it ever happen in any of the Test Current, Test Next Minor or Test Next Major?
If not, could you try to set cacheImageName to an empty string and retry? (the test workflows doesn't cache the image)

**Comment by janlehmkuhl** [comment]
Yes, it has also occurred in the Test Current and Test Major pipelines. Log attached. I'll try your suggestion and remove the CacheImage property.

[logs_TestCurrent.zip](https://github.com/microsoft/AL-Go/files/10105129/logs_TestCurrent.zip)
[logs_TestNextMajor.zip](https://github.com/microsoft/AL-Go/files/10105130/logs_TestNextMajor.zip)

**Comment by freddydk** [comment]
Running out of suggestions here...
How were the agents created?

**Comment by janlehmkuhl** [comment]
The host machines were set up on Azure in Germany-West-Central without any special configuration. The host agent services were created according to GitHub instructions and started as a service with administrator permissions. No antivirus software was installed. Windows Defender is active by default. 

After I removed the "cacheImage" property, at least all jobs are running smoothly so far. I will start another stress test with several jobs in a row this night and give feedback.

Maybe these are two interesting resources I found online:
1) https://github.com/microsoft/navcontainerhelper/issues/2486
2) https://stackoverflow.com/questions/13712462/exception-calling-downloadfile-with-2-arguments-an-exception-occurred-d

I can't derive anything from them, unfortunately.

**Comment by freddydk** [comment]
Yeah, those two doesn't have anything to do with this, I think - the first was download error due to CDN - and the second one was because of wrong parameter usage.
The code failing is this:
```
                Write-Host "Downloading Signing Tools"
                $winSdkSetupExe = "c:\run\install\winsdksetup.exe"
                $winSdkSetupUrl = "https://go.microsoft.com/fwlink/p/?LinkID=2023014"
                (New-Object System.Net.WebClient).DownloadFile($winSdkSetupUrl, $winSdkSetupExe)
                Write-Host "Installing Signing Tools"
```

Which doesn't really make sense.
Let me know if avoiding the image creation solves the issue, then I have something to go after.

**Comment by janlehmkuhl** [comment]
The same random behavior. But this time only two ran into the same one error. 
![image](https://user-images.githubusercontent.com/94679485/204478930-82f3fbbe-caa2-4765-87eb-899e585f9792.png)

**Comment by FreundDK** [comment]
I will add some resilience to this and add some dumps when it fails, to make us smarter.
Expect this tonight or tomorrow

**Comment by freddydk** [comment]
Checked in a fix in ContainerHelper.
Should be in preview in approx. 1 hour (when this is done: https://github.com/microsoft/navcontainerhelper/actions/runs/3575845920)
You can add a setting to .github\AL-Go-Settings.json called

"BcContainerHelperVersion": "preview"

Then it should grab the preview.

**Comment by janlehmkuhl** [comment]
Our repository is now switched to the preview of BcContainerHelper. I will start the pipelines tonight once the build of BcContainerHelper has gone through. Feedback hopefully tomorrow.

**Comment by janlehmkuhl** [comment]
Same random behavior but different error message in the same place. Log attached. This pipeline is the only one that has failed so far. The others are still running.
[logs_231_TestCurrent.zip](https://github.com/microsoft/AL-Go/files/10116253/logs_231_TestCurrent.zip)

**Comment by freddydk** [comment]
Unfortunately, it doesn't show me the error, as I forgot that the GetExtendedErrorMessage isn't inside the container:-(
I have just checked in a fix where the function is included - hopefully that will reveal the true error message.
So, this build should result in a new preview with this fix.
Sorry
https://github.com/microsoft/navcontainerhelper/actions/runs/3577192798

**Comment by janlehmkuhl** [comment]
No Problem. Attached is the error log of a failed job (Test Current)
[logs_264_TestCurrent.zip](https://github.com/microsoft/AL-Go/files/10117353/logs_264_TestCurrent.zip)

**Comment by freddydk** [comment]
That one apparently didn't get the latest containerhelper from the CDN, very annoying:-(
I did already fix this in the preview of AL-Go to avoid the CDN when going for the preview, but I would need another output - where the containerhelper version is 789 (this one was BcContainerHelper version 4.0.7-preview785)
Maybe we need to wait for tomorrows failures.

**Comment by janlehmkuhl** [comment]
These failed jobs should have been created by the latest BcContainerHelper version.

[logs_293_CICD.zip](https://github.com/microsoft/AL-Go/files/10120908/logs_293_CICD.zip)
[logs_301_TestCurrent.zip](https://github.com/microsoft/AL-Go/files/10120909/logs_301_TestCurrent.zip)

**Comment by freddydk** [comment]
Any failing jobs this evening?

**Comment by janlehmkuhl** [comment]
Yes, unfortunately!

[logs_353_CICD.zip](https://github.com/microsoft/AL-Go/files/10130623/logs_353_CICD.zip)
[logs_354_TestCurrent.zip](https://github.com/microsoft/AL-Go/files/10130624/logs_354_TestCurrent.zip)
[logs_355_TestNextMajor.zip](https://github.com/microsoft/AL-Go/files/10130625/logs_355_TestNextMajor.zip)

![image](https://user-images.githubusercontent.com/94679485/205003350-452b3b53-b272-4309-b07d-14a745d705c1.png)

**Comment by freddydk** [comment]
OK, so that become even more weird.

I am now downloading the signing tools from a different location (the same location, where a lot of the other pre-requisites are downloaded).

Which leads my focus back on the VMs - strange that this is the first time ever I hear about Sign-BcContainerApp is failing and it is not only used in AL-Go, but probably all over.

Any chance that I could get RDP access to one of the VMs and do some testing?
Email me info to freddyk at microsoft dot com if possible, thanks

**Comment by janlehmkuhl** [comment]
Let's preface this by saying that we already had the same error on Azure DevOps. There it was VMs hosted by Microsoft. Not self-hosted machines.

Please send an e-mail to jan.lehmkuhl@ctm-computer.de and I will reply with the credentials to the vms

**Comment by freddydk** [comment]
I could repro this on the machines.
Machines were running Docker from Mirantis, installed by the DockerMsftProvider.
I removed the docker version and installed the free Docker Engine using the script provided here: (https://freddysblog.com/2021/10/30/docker-and-business-central/)

The way to replace the Mirantis docker version with docker engine was to follow this check-list:
1. Restart
2. Cleanup docker using this https://freddysblog.com/2018/12/11/clean-up-after-yourself-docker-your-mom-isnt-here/
3. restart
4. Run UnInstall-Package -name docker -providerName DockerMsftProvider
5. Run UnInstall-Module -name dockerMsftProvider
6. Restart
7. Remove c:\programdata\docker (if not already gone)
8. Download and run this script: https://github.com/microsoft/nav-arm-templates/blob/master/InstallOrUpdateDockerEngine.ps1

Waiting for confirmation that this solved the issue.
I have never before heard of any problems with Mirantis, but it looks like some throttling was going on.

**Comment by janlehmkuhl** [comment]
Unfortunately, I have to tell you that the error still appears again. To be on the safe side, I restarted the build servers today. Error remains. Several pipelines have run into an error.

[logs_TestNextMajor.zip](https://github.com/microsoft/AL-Go/files/10149354/logs_TestNextMajor.zip)

**Comment by freddydk** [comment]
Are you saying that they worked fine for a few days and now they are failing again?

**Comment by janlehmkuhl** [comment]
Yep, that's exactly what I'm trying to say. I will now create a new build agent based on your template and disable the other agents and get back to you with the results.

**Comment by janlehmkuhl** [comment]
So with your BuildAgent it seems to work. I still wonder where the difference is with my BuildAgents though.

What I noticed so far:
1) Your Azure VM template only allows machines of category "D". Is there a specific reason for this?
2) Your build agents are managed with the user "NT AUTHORITY\Network Service". Mine with the admin user. 
3) The other Docker engine already discussed.

I think you can close the issue tomorrow, after my feedback.

**Comment by freddydk** [comment]
1. I did a query of which machines were available on most datacenters - the result is in the template. You should be able to fork the repo, modify the ARM template and create what you want.
2. This is in order to avoid the admin user password and expiry of that

The big question is really whether the agents generated from the ARM template also will fail after a few days?

**Comment by janlehmkuhl** [comment]
I have found the solution for me. My virtual machines were configured with "Enable accelerated networking" = true.

**Possible solutions that help:** 
1)  Always use this script to create a Build Agent VM: https://aka.ms/getbuildagent
or
2) When you create a new virtual machine on Azure manually using the "Create a virtual Machine" wizard, make sure that in the "Networking" tab the "Enable accelerated networking" property is set to "no".

**Comment by freddydk** [comment]
THANKS Jan

This was exactly the kind of outcome I was hoping for - figuring out why this happened for other people to find/follow.

THANKS
