### ISSUE TITLE
Workflows missing in migrating to ALGO

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/AL-Go#308]
I am following the steps in https://freddysblog.com/2022/04/27/migrating-to-al-go-for-github/ for the "From GitHub (if you are “just” using it as a source code repository)" scenario.

I had done this about a month ago initially and everything seemed fined.  I have addressed some issues and pushed new commits to the branch in which I added the AL:GO components.  I went to the Actions tab to see the workflow runs and there are no workflows in the list.  There is a record of my original manual run of the CICD workflow but no workflows to run and nothing has "kicked off" automatically.  What have I messed up?

The workflows are in the repo
![image](https://user-images.githubusercontent.com/102963427/204774162-5924f461-5b71-46c2-8a87-53ddb8ef3e8f.png)

But there are no actions to run however the original run is show in the history.
![image](https://user-images.githubusercontent.com/102963427/204774402-1c52a4a5-8fbd-46a4-8593-cba4faa9f9fc.png)

**Comment by freddydk** [comment]
You need to merge the PR in order to run the workflows in the PR.
When handling PRs - AL-Go uses the existing workflows for testing the app changes in the PR.
Once you merge the PR, the merge commit CI/CD workflow will use the new workflows.

**Comment by tscottjendev** [comment]
When I merge the pull request it has completed without running the CI/CD action.  Now the main branch does not "build" due to errors in the feature branch.  What have I missed?

Todd Scott?
Senior Developer
***@***.***
Jendev, The Powerhouse, Queens Road, St Helier, Jersey JE4 8NY
T:  +44 (0)1534505344
 W: www.jendev.com

**Comment by tscottjendev** [comment]
Did I miss documentation for this?  I could not find anything in the repo.

**Comment by tscottjendev** [comment]
@freddydk how do I add another branch to "force" the AL:Go to run the CI/CD on something more than just Main.

**Comment by freddydk** [comment]
There are two settings called CICDPushBranches and CICDPullRequestBranches you can add to the repo settings file (.github\AL-Go-Settings.json)
This should affect which branches gets run.
You will need to run the Update AL-Go System Files workflow in order for these changes to take effect.

**Comment by freddydk** [comment]
These properties have been added to the documentation now https://aka.ms/algosettings#CICDPushBranches
