### ISSUE TITLE
Difference in naming between .zip and .app-files

### ISSUE THREAD

**Issue by ann-katrin-stellmacher** [microsoft/AL-Go#310]
Hi, 
as we need .app-files for separate testing, we discovered that there is a difference between the naming of .zip and .app-files.

For example we have Project 1 with app.json/"version": "2.0.0.0", which results in a .zip with naming "1.0.8.0.zip" and a .app with "2.0.8.0.app"
![image](https://user-images.githubusercontent.com/77147338/205048058-4a5b67b6-6ace-4271-94fd-9edb07fe9cab.png)
and Project 2 with app.json/"version": "1.30.0.0", which results in a .zip with naming "1.0.572.0.zip" and a .app with "1.30.572.0.app"
![image](https://user-images.githubusercontent.com/77147338/205048818-df298085-9cf0-427f-aed9-f3d2cc22fc9f.png)

This behavior is seen in both pull request artifacts and merge artifacts. We have not set the parameter "repoVersion" on either project and this behavior is present for repositories that build AL-Go/AppSource as well as for AL-Go/PTE.

Where does this come from? As I understand the Minor.Major are taken from the app.json of the project, but how do I interact with the naming of the .zip-file? This has caused some comfusion since they do differ but we cannot figure out why.

**Comment by freddydk** [comment]
The reason for this is that you can have multiple apps in every project/repo.
A screenshot from the workshop is here:
![image](https://user-images.githubusercontent.com/10775043/205059199-e061a19d-7751-4004-9a15-00314f2097df.png)
If you want the same major/minor for apps (as repo), you need to set VersioningStrategy to 16 in your repo settings (.github\AL-Go-Settings.json) as described on page 26 in https://aka.ms/algoworkshop

**Comment by ann-katrin-stellmacher** [comment]
Thank you for the explanation!
