### ISSUE TITLE
Branching enhancements

### ISSUE THREAD

**Issue by freddydk** [microsoft/AL-Go#312]
Add to branching:
- Support delivery and deployment from multiple branches (https://github.com/microsoft/AL-Go/issues/293)
  - For continuous deployment, an environment should have a property for which branch it gets deployed from (today this is hardcoded to main)
  - For Continuous delivery, the deliveryContext should be able to determine branches (with wildcards) for - and include branch in parameters to custom delivery
- Potentially also deploy to environment from PRs for testing (see https://github.com/microsoft/AL-Go/issues/281)
- Support a main branch with a different name than main

**Comment by freddydk** [comment]
## Implementation

**Continuous Delivery**
The deliveryContext (which is always a compressed .json construct), can contain a branches property, which can be an array of branches, where this delivery should be invoked. The branch specification can include wildcards (like release/*).
StorageContext can now also contain {branch} in the containerName or the blobName property, which will be replaced with the branch name delivering.

**Continuous Deployment**
In .github\AL-Go-Settings.json, you can create a setting called **<environmentname>-Branches**, which is an array of branches, which will deploy to this environment. The branch specification can include wildcards (like release/*), although this probably won't be used a lot in continuous deployment.

For both, if artifacts are to be delivered or deployed, artifacts will be generated and published on the build (including the branch name)

Create Release can also be done from other branches.

With this, we should be able to use a different name for the main branch - still some testing to do for this.

**Comment by CPretorius1986** [comment]
1. Busy evaluating this for our purposes, and found that the following presents when deploying from main and UAT branch..

ConvertFrom-Json : Invalid JSON primitive: System.Collections.Specialized.OrderedDictionary.
At D:\a\_temp\4250a6d6-b048-44e0-b117-81757d528ad1.ps1:5 char:44
+   $deployToSetting = $deployToSettingStr | ConvertFrom-Json
+                                            ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
 
Error: Process completed with exit code 1.

The Authcontext seems to be failing in CI/CD.yaml

2. I also received the below on initialization but could get around by pointing to V2.2 Initialization file

Run microsoft/AL-Go-Actions/WorkflowInitialize@main
Run try { D:\a\_actions\microsoft\AL-Go-Actions\main\WorkflowInitialize/WorkflowInitialize.ps1 -eventId $ENV:_eventId } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
           _           _____          __              _____ _ _   _    _       _       ::Error::WorkflowInitialize action failed. Error: The property 'm' cannot be found on this object. Verify that the property exists. Stacktrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\main\AL-Go-TestRepoHelper.ps1: line 209 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\main\AL-Go-TestRepoHelper.ps1: line 208 at Write-Big, D:\a\_actions\microsoft\AL-Go-Actions\main\AL-Go-TestRepoHelper.ps1: line 20[6](https://github.com/XX/XX/actions/runs/3689041336/jobs/6244662515#step:6:7) at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\main\WorkflowInitialize\WorkflowInitialize.ps1: line 30 at <ScriptBlock>, D:\a\_temp\3dfe20be-15f7-4866-830c-11c9b6808c02.ps1: line 1 at <ScriptBlock>, <No file>: line 1
Error: Unexpected error when running action (The term 'TrackException' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.)
Error: Process completed with exit code 1.

**Comment by freddydk** [comment]
On 1 - could you share your Settings file containing the DeployTo Setting?
On 2 - how did you get into a situation, where your yaml files pointed to workflowinitialize@main?

**Comment by freddydk** [comment]
Thinking about this - it looks like you are editing the .yaml files.
If that is true, you should never do that.

Run Update AL-Go System Files workflow with https://github.com/microsoft/AL-Go-PTE@preview (or AL-Go-AppSource@preview) - then you should not see the issues above

**Comment by CPretorius1986** [comment]
> Thinking about this - it looks like you are editing the .yaml files. If that is true, you should never do that.
> 
> Run Update AL-Go System Files workflow with https://github.com/microsoft/AL-Go-PTE@preview (or AL-Go-AppSource@preview) - then you should not see the issues above

Thanks Freddydk, appreciate the feedback...I read the information/manuals once more today and figured this is/was me being an idiot. 

Thanks for the pointer, I will try and revert.
