### ISSUE TITLE
license file with permission to the objects used in the app

### ISSUE THREAD

**Issue by Marhoon** [microsoft/AL-Go#313]
I get the following error when build the app.

Error: When building an AppSource App, you need to create a secret called LicenseFileUrl, containing a secure URL to your license file with permission to the objects used in the app.

I need to know: 
1) How to generate license file for each customer with permission to the objects used in the app.
2) how to add the License file for each customer.

Appreciate all great job, and effort for making this happen for us.

**Comment by freddydk** [comment]
For Business Central Online - customers will have access to all AppSource app objects automatically.
For Business Central On-premises you need to add your objects to the customer license file using the same mechanisms as it has been the case for many years with NAV and BC on premises (I have never tried this myself)
For your AppSource app development, you need an object range and a license file - consult https://aka.ms/bcpublisher to find those.
For PTE development, you don't need a license file, as you will be using the 50000-99999 object range which is included in the CRONUS demo license.

**Comment by Marhoon** [comment]
Hi Sir Appreciated your great input, its help us alot.

For LicenseFileUrl which license now we add our own development license we received from Microsoft Dynamics ? with *.flf extension?

**Comment by freddydk** [comment]
Yes, althougfh .bclicense is preferred for appSource apps - as .flf is deprecated from 22.x

**Comment by Marhoon** [comment]
For PTE development, you don't need a license file, as you will be using the 50000-99999 object range which is included in the CRONUS demo license.
So this range will work for the customer when he using his license range?

Also if there is any best article to setup the secret Key Vault? since its little bit confusing to put the path of the license.

**Comment by freddydk** [comment]
If the customer is using Business Central online - you do not need to worry about the license file - everything is taken care of.
On licensefileurl - you can consult some of the walkthroughs here on the site. Ex. https://github.com/microsoft/AL-Go/blob/main/Scenarios/SetupCiCdForExistingAppSourceApp.md
