### ISSUE TITLE
Make it possible to avoid syncing certain workflows

### ISSUE THREAD

**Issue by mazhelez** [microsoft/AL-Go#318]
Currently, if a workflow is deleted, the next run of `Update AL-Go System Files` will bring it back, polluting the view of workflow/actions.

There should be a configuration to avoid syncing workflows that are not in use.
`

**Comment by freddydk** [comment]
I agree that a setting in the repo settings file, which lists unused workflows (specified by workflow filenames) would be the way to go. The Update AL-Go System Files would then remove these files if they exist (instead of comparing their content)

**Comment by freddydk** [comment]
No, this should be a list of unused workflows - NOT a list of used workflows.
So, if the partner adds their own workflow or AL-Go comes out with a new workflow - they would be included (until you remove them if you like)

**Comment by jonaswre** [comment]
Sorry I was just asking in general wether added action are removed on update. 

Wasn't suggesting any changes.

**Comment by freddydk** [comment]
I know:-)
Actions added into an AL-Go repo are left alone by the update action (unless there is an action with the same name added in the AL-Go template).
AL-Go only touches known workflows.
