### ISSUE TITLE
Deploy to SaaS sandboxes fails in preview

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#325]
When publishing apps to SaaS sandboxes, the deploy process shows the installed apps and then, when trying to install the new apps (or updates to existing apps), it fails with the following error message:

"The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again."

I am assuming something changed recently in how the Invoke-WebRequest functionality is implemented in PS, but not sure, if that is actually the case.

**Comment by freddydk** [comment]
That is likely a bug in ContainerHelper - will issue a fix asap

**Comment by freddydk** [comment]
should work in approx 1 hour

**Comment by pzentner** [comment]
Thank you, @freddydk!

I can confirm that it's working. And I apologize, I probably should have dug in more to see that it was part of BcContainerHelper and not AL-Go per se. But that's the great part of having control over both projects ;)

Merry Christmas and a Happy New Year!

**Comment by freddydk** [comment]
No problem

Merry Christmas and Happy New Year to you and yours as well...

**Comment by freddydk** [comment]
BTW - this bug was introduced after changing Publish-PerTenantExtensionApps to use v2.0 of the management API supporting force sync.
Will add support for setting Force Sync in AL-Go as well.
