### ISSUE TITLE
Using our own container

### ISSUE THREAD

**Issue by Marhoon** [microsoft/AL-Go#326]
We used https://github.com/microsoft/AL-Go-AppSource 

When we run localDevEnv.ps1 can we use our own container instead of creating new one?

And if we didn't use localDevEnv.ps1 can we create our own launch.json

**Comment by freddydk** [comment]
localDevEnv is only there to assist you with setting up a development environment.
You can do that yourself and/or create launch.json as you see fit - you are not forced to use the localDevEnv function.
