### ISSUE TITLE
Publish AppSource App to Online Environment

### ISSUE THREAD

**Issue by janlehmkuhl** [microsoft/AL-Go#330]
We would like to publish the latest build of our AppSource app to one of our partner sandboxes at each CICD run. Unfortunately, I always get a 500 error returned. Is this possibly because this app is already registered in the AppSource? 

What is the best way for us to automatically publish our AppSource app to one of our partner sandboxes so we can manually test the latest build?

![image](https://user-images.githubusercontent.com/94679485/210565710-608a71e7-cf27-46d4-9295-33ab39942698.png)
Please note that the correct TSO Licensing App is already installed, just in a newer version than specified in the Dependencies, hence this additional "error message". Other PTEs can be installed via this path without any problems, but this action makes little sense to me to exist in the "AL-Go-AppSource" repo if it only works for PTEs. What am I doing wrong? Is there another way?

**Comment by jonaswre** [comment]
Hi, this seems to be a common problem currently. I have answered in the following Discussion.

https://github.com/microsoft/AL-Go/discussions/329

See if that helps you.

**Comment by janlehmkuhl** [comment]
#329 does it for me! Thanks!
