### ISSUE TITLE
AS0079 errors in Test Current

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#331]
Testing an app using the Test Current action. We get numerous errors referring to missing affixes, e.g.:

`[Build .: CAi Software Precious Metals Solution/src/src/tableext/CAiRefSalesHeader.TableExt.al#L232](https://github.com/CAI-Software-Inc/PMRefining-AppSource/commit/e0629cc58e1fdd2114f2af28b7043b22a0a96835#annotation_7703452048)
AS0079 The procedure 'CAI_CalcAllPoolCharges' in TableExtension 'CAI Sales Header' must have at least one of the mandatory affixes`

`[Build .: CAi Software Precious Metals Solution/src/src/pageext/CAiRefSalesOrderSubform.PageExt.al#L28](https://github.com/CAI-Software-Inc/PMRefining-AppSource/commit/e0629cc58e1fdd2114f2af28b7043b22a0a96835#annotation_7703452111)
AS0011 The identifier 'CAI PMCS Account No.' must have at least one of the mandatory affixes '<affix>'.`

CAI is actually our registered affix. Is there a way to signal this to the workflow, or is there some other way to clear these when the affix is apparently present?

This does not seem to come up for every symbol (unless the reporting is hard-limited to 10 errors and 10 warnings).

**Comment by freddydk** [comment]
Did you modify the mandatoryAffixes setting in .AL-Go\settings.json? (the default is '<affix>' and needs to be replaced with your affixes.

**Comment by buzzwick** [comment]
That did work, thank you for pointing me toward those settings.
