### ISSUE TITLE
Versioning of App and Builds

### ISSUE THREAD

**Issue by rolandpthompson** [microsoft/AL-Go#332]
I've been looking at the AL-Go (PTE), brilliant stuff.
However, I can't wrap my head around how the versioning is supposed to work.
Obviously we have the version in the app.json for the extensions, but when the CI/CD build kicks off it creates a different one, then not modifying the app.json.
So we end up with a mismatch of versions. Are we basically saying the version in the app.json is essentually redundant if using this method.

Looked online for resource re this, and have seen the settings info @ https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md

Feel I have missed something important somewhere.

Thanks

**Comment by freddydk** [comment]
Thanks

Version consists (as you know) of 4 parts.

Major and Minor are used from app.json in every app.
Build and release are auto-applied on every build, meaning that the builds coming from your CI/CD pipeline will always have correct version numbers.

Apps built in VS-Code will always have wrong version numbers - but apps built in VS-Code should never be used for installing anywhere (except for in development environments / dev. endpoint) where the version number doesn't matter.

https://aka.ms/ALGoWorkshop slides 23 - 26 does talk a little to this, but maybe it needs some more explaining.

When you create a release, the create release workflow will offer you to update the app.json AFTER creating the release with the current version number - in order for you to be able to hotfix the newly released version.

**Comment by rolandpthompson** [comment]
Ah ok, that makes sense then.

Haven’t seen that ppt before, so missed that, some reading to do.

Having used GitHub, but new to AL-Go think it just needs a revisit of how internally we create/deploy projects.
Which is good for the future.

Thanks Freddy.

**Comment by rolandpthompson** [comment]
Am I right in thinking then that when using a workspace setup, all app within it will get the new version number (even if nothing changes in a specific App)?

**Comment by freddydk** [comment]
Not sure what you mean by Workspace Setup?

**Comment by rolandpthompson** [comment]
The current App in question is part of a set for a customer, as such we have used a VS Code workspace to setup the repo

Like so,
***@***.***

Base is the main extension, all the others have a dependency on base.
So we thought this was the best way to do it given what we inherited from the previous partner.

But, when I push to github and create a release it updated all the app.json versions.
Given this was the first release with Al-Go I thought it might be that, but subsequent releases do the same, the version no. of all the Apps in the repos get updated.
I assume this is by design?

Hopefully that makes sense, appreciate your thoughts.

**Comment by freddydk** [comment]
A VS Code workspace is "just" a file describing the folders you work with, AL-Go doesn't really care about these.
AL-Go will use the appFolders specified in .AL-Go/settings.json - or locate app folders itself - and build all apps in dependency order.
If all apps shouldn't be build every time, then you can setup multiple repositories with dependencies - or you can setup multiple projects in one repository.
Feel free to add me to your repo - then I can see what we are talking about and whether you have set things up correctly.
Thanks

**Comment by rolandpthompson** [comment]
Morning Freddy

Yes, we have multiple projects in one repository, there is one App called base to which the others have a dependency on.
I’ve sent the invite for the repository, appreciate your feedback on the correct setup.

Thanks
Roland
