### ISSUE TITLE
Publish to Production - AL-Go Preview

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#333]
We have a client environment with the name "XXX Production". Currently, it is setup as an environment with the name "XXX Production (Production)" in the repo.

When trying to publish, I am getting an error stating that the environment "XXX" cannot be found. It doesn't only cut off the "(Production)" part, but also the "Production Part" before that.

I am currently not using "DeployTo..." settings. 

I am not sure, if it's an issue that there are spaces in the BC environment name or if the issue is that the word "Production" is cut out, even though it is part of the actual environment name, but wanted to bring that to your attention.

**Comment by freddydk** [comment]
AL-Go will try to deduct the BC Environment name based on the GitHub Environment name, but it will remove everything after the first space. You can override this in settings.
Either using DeployTo - or by using a secret or a setting called <environmentname>_environmentName (in your case XXX_environmentName).

**Comment by pzentner** [comment]
Thank you, Freddy. Based on the documentation here: https://github.com/microsoft/AL-Go/blob/main/Scenarios/RegisterProductionEnvironment.md

I would have expected the behavior a little different, meaning that everything before "(Production)" would be considered the environment name. It is clear that the behavior works different and that's fine - I can work with that obviously. Maybe it would be good to document somewhere the behavior.

**Comment by freddydk** [comment]
I will modify the documentation to save time for other people, thanks.
