### ISSUE TITLE
Publish To Environment  Action stopped working

### ISSUE THREAD

**Issue by kb-dynaway** [microsoft/AL-Go#358]
I have an issue since update the AL Go files that Publish To QA Environment  stopped working with below issue in step **AuthContext**. I  created new authcontext but still the same issue.

`The property 'name' cannot be found on this object. Verify that the property exists.`

![image](https://user-images.githubusercontent.com/106300783/212633756-3e6cdc66-1b3f-4c11-b267-9c0e593d4986.png)

**Comment by freddydk** [comment]
Did you update to v2.3 (I think I have fixed this bug)

**Comment by freddydk** [comment]
Note that you can downgrade by specifying microsoft/AL-Go-PTE@v2.2 if you like - then you can use microsoft/AL-Go-PTE@main when I have fixed this.

**Comment by freddydk** [comment]
Found the bug - I will issue a hotfix asap
You can update system files again shortly

**Comment by freddydk** [comment]
Hotfix uploaded - update your AL Go System Files and retry - sorry for this.

**Comment by kb-dynaway** [comment]
Confirm it works now
