### ISSUE TITLE
Creating a release and deploying from a release branch

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL-Go#360]
A few days ago release "2.3" was created in a repo, build 2.3.8.0 was published to AppSource (low build no. as we migrated the repo to GH just before 2.3). Main branch incremented to 2.4.
Development ongoing in 2.4, now at 2.4.14.0

We needed to hotfix 2.3 after release. 
Changes were made on the release/2.3 branch which resulted in build 2.3.16.0.
So far so good.

What would be the way to use the "Publish to AppSource" workflow to pick up 2.3.16.0 and submit it? 
I get errors that it does not exist, I guess because it was build of the release/2.3 branch.

```
Artifacts 2.3.16.0
Projects:
.
Using AppSourceContext
Project '[REDACTED]'
Analyzing artifacts
https://api.github.com/repos/prymeGlobal/[REDACTED]/actions/artifacts?per_page=100&page=1
project ''[REDACTED]'
Error: Deliver action failed. Error: ERROR: Could not find any Apps artifacts for projects *, version 2.3.16.0 Stacktrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v2.3\Deliver\Deliver.ps1: line 169 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v2.3\Deliver\Deliver.ps1: line 150 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v2.3\Deliver\Deliver.ps1: line 98 at <ScriptBlock>, D:\a\_temp\0f90fede-a49d-4e64-80b2-47ed0dd49904.ps1: line 2 at <ScriptBlock>, <No file>: line 1
```

Similarly, I cannot get "Create Release" workflow to complete.
```
projects:
- .
Repo Artifacts count: 41
Downloaded Artifacts count: 41
Analyzing artifacts for project [REDACTED]
Search for [REDACTED]-main-Apps-2.3.16.0
Error: No artifacts found for this project
Error: Process completed with exit code 1.
```

Not urgent, I did it manually, but I would be nice to understand how it is supposed to work.

**Comment by freddydk** [comment]
Will investigate

**Comment by freddydk** [comment]
The root cause of this is the same as #371
