### ISSUE TITLE
Support for enableTaskScheduler?

### ISSUE THREAD

**Issue by BMI-Mike** [microsoft/AL-Go#362]
After attending the AL-Go Office Hours call today, it was suggested that I can enable the Task Scheduler by adding a new stanza to AL-Go-Settings.json like this:

```
{
    "type": "PTE",
    "templateUrl": "https://github.com/microsoft/AL-Go-PTE@main",
    "PartnerTelemetryConnectionString": "InstrumentationKey=xxxxxxxx;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/",
    "SendExtendedTelemetryToMicrosoft": true,
    "environments": [
        "MyEnv-DEV"
    ],
    "nextMajorSchedule": "0 0 * * *",
    "nextMinorSchedule": "0 0 * * *",
    "currentSchedule": "0 0 * * *",
    "DefaultNewContainerParameters": {
        "enableTaskScheduler": true
    }
}
```

The relevant portion of the file is simply:
`"DefaultNewContainerParameters": {
        "enableTaskScheduler": true
    }`

When running localDevEnv.ps1, I see the following message "Setting defaultNewContainerParameters = @{enableTaskScheduler=True}" which is a good sign.  But later, in the parameter list I see "Enable Task Scheduler           False".

I have confirmed that the Task Scheduler is not running in the local environment.  If I import configuration packages into the BC container (using https://freddysblog.com/2019/09/19/using-apis-on-containers/), the import never completes and remains in a scheduled state.

```
& $scriptPath -containerName $containername -credential $credential -companyName $companyName -packageId $packageId -packageFilename $packageFilename
Invoke GET on http://172.29.150.238:7048/BC/api/v1.0/companies?$filter=name%20eq%20'MY%20DEMO%20COMPANY'&tenant=default
Removing Configuration Package US.ENU.STANDARD (if it exists)
Invoke DELETE on http://172.29.150.238:7048/BC/api/microsoft/automation/v1.0/companies(8ff11186-8e96-ed11-89e4-93bb6fe78e29)/configurationPackages('US.ENU.STANDARD')?tenant=default
Invoke-BCContainerApi Telemetry Correlation Id: 40b40a59-de9a-4a4a-857c-ebc4e458807d
Creating Configuration Package US.ENU.STANDARD
Invoke POST on http://172.29.150.238:7048/BC/api/microsoft/automation/v1.0/companies(8ff11186-8e96-ed11-89e4-93bb6fe78e29)/configurationPackages?tenant=default
Uploading Configuration Package US.ENU.STANDARD
Invoke PATCH on http://172.29.150.238:7048/BC/api/microsoft/automation/v1.0/companies(8ff11186-8e96-ed11-89e4-93bb6fe78e29)/configurationPackages('US.ENU.STANDARD')/file('US.ENU.STANDARD')/content?tenant=default
Importing Configuration Package US.ENU.STANDARD
Invoke POST on http://172.29.150.238:7048/BC/api/microsoft/automation/v1.0/companies(8ff11186-8e96-ed11-89e4-93bb6fe78e29)/configurationPackages('US.ENU.STANDARD')/Microsoft.NAV.import?tenant=default
Scheduled................................................................................................................................
```

I expected the Task Scheduler to run in this container, but it appears it is not.

**Comment by freddydk** [comment]
I can see that the problem is that the EnableTaskScheduler really is controlled by the Run-AlPipeline command and that overrides the setting.
You have 4 options really:
1. Use the ConfigPackages setting to have AL-Go apply the packages automatically (https://aka.ms/AlGoSettings#configPackages)
2. Create a file called NewBcContainer.ps1 in the .AL-Go folder in the project where you need this with this content:
```
{
    Param([Hashtable] $parameters)
    $parameters.enableTaskScheduler = $true
    New-BcContainer @parameters
    Invoke-ScriptInBcContainer $parameters.ContainerName -scriptblock { $progressPreference = 'SilentlyContinue' }
}
```
3. Create a file called ImportTestDataInBcContainer.ps1 in the .AL-Go folder in the project where you need this and put the code in there to import and apply the config package.
```
{
    Param([Hashtable] $parameters)
    # properties in the hashtable are containerName, tenant and credential
}
enableTaskScheduler will be enabled at this time.
4. wait until I add a setting for enableTaskScheduler (within a week or so)

**Comment by BMI-Mike** [comment]
Thank you Freddy.  I'll explore each of the solutions you provided.

**Comment by BMI-Mike** [comment]
I updated a repo to use the preview AL-Go version.  I can confirm this new setting is working as expected.  Thank you Freddy!
