### ISSUE TITLE
Publish to Appsource fails on 2.3 - worked on 2.2 

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL-Go#364]
We did a Publish to AppSource last week which was successful (after adding some settings as discussed in #344 ).

This week it fails in the Deliver step with _AppSourceProductId needs to be specified in ./.AL-Go/settings.json in order to deliver to AppSource_ - but it is specified, there has been no changes to Al-Go/settings.json since the last publish.

```
Run microsoft/AL-Go-Actions/Deliver@v2.3
Run try { D:\a\_actions\microsoft\AL-Go-Actions\v2.3\Deliver/Deliver.ps1 -actor $ENV:_actor -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -projects $ENV:_projects -deliveryTarget $ENV:_deliveryTarget -artifacts $ENV:_artifacts -type $ENV:_type -atypes $ENV:_atypes -goLive ($ENV:_goLive -eq 'Y') } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 4.0.10
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Reading .github\AL-Go-Settings.json
Reading .AL-Go\settings.json
Artifacts current
Projects:
.
Using AppSourceContext
Project '[REDACTED]'
Analyzing releases https://api.github.com/repos/prymeGlobal/[REDACTED]/releases
Downloading release 1.3, projects [REDACTED], type Apps
project '[REDACTED]'
https://api.github.com/repos/prymeGlobal/[REDACTED]/releases/assets/[92](https://github.com/prymeGlobal/[REDACTED]/actions/runs/3950304612/jobs/6762682397#step:6:93)158904
'D:\a\[REDACTED]\[REDACTED]\.artifacts\[REDACTED]-main-Apps-1.2.40.0.zip'
Artifacts:
- [REDACTED]-main-Apps-1.2.40.0
Analyzing repository
Checking project dependencies
Checking appDependencyProbingPaths
Dependency to projects '*' in https://github.com/prymeGlobal/prymeSystem@main, version latest, release status release
Azure.Storage Module is available in version 2.1.0
Using Azure.Storage version 2.1.0
Attempting authentication to *** using clientCredentials...
Authenticated as app ***
Error: Deliver action failed. Error: AppSourceProductId needs to be specified in ./.AL-Go/settings.json in order to deliver to AppSource Stacktrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v2.3\Deliver\Deliver.ps1: line 418 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v2.3\Deliver\Deliver.ps1: line 98 at <ScriptBlock>, D:\a\_temp\5ec95d98-e4bc-4e29-bd28-61e8eec69a3a.ps1: line 2 at <ScriptBlock>, <No file>: line 1
AL-Go action ran: Deliver Telemetry Correlation Id: a5761b86-6abf-4a57-881f-7944b8941b17
Removing BcContainerHelper
Error: Process completed with exit code 1.
```

settings.json
```
{
  "country": "gb",
  "AppSourceCopMandatoryAffixes": [
    "[REDACTED]"
  ],
  "appFolders": [
    "[REDACTED]"
  ],
  "testFolders": [
    "[REDACTED].Test"
  ],
  "bcptTestFolders": [],
  "installApps": [
    "https://[REDACTED]"
  ],
  "enableCodeCop": true,
  "enableUICop": true,
  "appDependencyProbingPaths": [
    {
      "repo": "https://github.com/prymeGlobal/prymeSystem",
      "version": "latest",
      "release_status": "release",
      "projects": "*",
      "authTokenSecret": "GHTOKENWORKFLOW"
    }
  ],
  "appSourceProductId": "[GUIDREDACTED]",
  "RepoVersion": "1.3"
}
```

**Comment by freddydk** [comment]
Any chance you can add me to the repo?

**Comment by AskeHolst** [comment]
I have added you

**Comment by freddydk** [comment]
For some reason, which I do not understand at the moment, the AppSourceProductId is now case sensitive.
If you modify the first letter to be A - then it probably works.

ContainsKey should not be case sensitive - but I did find some PS bugs indicating that this might not always be the case:
https://github.com/PowerShell/PowerShell/issues/7761

And... I can repro the problem on my own AppSource app - so you can remove me again from your repo.

Thanks for adding me - I will find the right fix

**Comment by AskeHolst** [comment]
Thanks you for the quick help as usual. I'll try renaming appSourceProductId to AppSourceProductId. 
I cannot try it today as I did a submission using PS instead and that one is pending manual validation, but there will be submissions from other repos to try.

**Comment by freddydk** [comment]
Now I know why...
This code:
```
$ht = [ordered]@{
  "enableCodeCop" = $true
  "enableUICop" = $true
  "appSourceProductId" = "e1ba3e63-821e-41e5-97c5-1f271ec3c0b4"
}
$ht2 = [Hashtable]$ht

$ht2.ContainsKey('AppSourceProductId')
$ht2.ContainsKey('appSourceProductId')
```
returns
```
False
True
```

So if the HashTable once was an orderedDictionary - then it is case sensitive.

**Comment by AskeHolst** [comment]
So that would mean a potential problem with other settings as well, right?
And your settings help has all settings starting with a lowercase letter whereas the predefined settings from the template are uppercase, so there will be a mix. 

It's always the little things like case sensitivity and dns... 😜

**Comment by freddydk** [comment]
Yes, after discovering this I am a bit worried - but... - everything can be fixed.
I found that using 

$ht.keys -contains 'value'

is always case insensitive - also if it comes from a ordered dictionary.

Settings values in AL-Go should not be cases sensitive.

**Comment by AskeHolst** [comment]
That's what hotfixes are for

**Comment by freddydk** [comment]
Should be fixed in preview now.
