### ISSUE TITLE
LocalDevEnv.ps1 fails with "Cannot bind argument to parameter 'Path" because it is an empty string

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#367]
I am currently using the preview version and tried to run LocalDevEnv with the following command in VS Code.

& [fullpath]\.AL-Go\localDevEnv.ps1 -licenseFileUrl "url to license" -containerName testbc -auth UserPassword -credential (New-Object System.Management.Automation.PSCredential ("user", (ConvertTo-SecureString "password" -AsPlainText -Force)))

I am getting above error in localDevEnv line 33. 

This happens because of a typo: You are using "GetProject -folder -ALGoFolder", but the syntax is "GetProject -folder -projectALGoFolder"

**Comment by pzentner** [comment]
Adding one more issue in the same localDevEnv.ps1

I line 131, there is a ` missing:

```
CreateDevEnv `
    -kind local `
    -caller local `
    -containerName $containerName `
    -baseFolder $baseFolder `
    -project $project 
    -auth $auth `
    -credential $credential `
    -licenseFileUrl $licenseFileUrl `
    -insiderSasToken $insiderSasToken

```

Should Be

```
CreateDevEnv `
    -kind local `
    -caller local `
    -containerName $containerName `
    -baseFolder $baseFolder `
    -project $project `
    -auth $auth `
    -credential $credential `
    -licenseFileUrl $licenseFileUrl `
    -insiderSasToken $insiderSasToken

```

**Comment by freddydk** [comment]
Thanks
On the PSScriptRoot - these two buttons:
![image](https://user-images.githubusercontent.com/10775043/213505010-d218cd71-3269-451e-b9f8-dd144f1a779c.png)
the left one should have $psscriptroot set, the right one shouldn't.
Are you seeing this differently?
Are you running PS5 or PS7?

**Comment by pzentner** [comment]
I updated the initial comment as I was wrong. It wasn't $PSScriptRoot, it was the following:

This happens because of a typo: You are using "GetProject -folder -ALGoFolder", but the syntax is "GetProject -folder -projectALGoFolder"

I did some more testing and then figured it out - didn't work regardless of what I passed in

**Comment by freddydk** [comment]
should look like this:

```
$project = GetProject -baseFolder $baseFolder -projectALGoFolder $PSScriptRoot
```

**Comment by freddydk** [comment]
I have hotfixed the preview templates as well - thanks for this
Looks like a merge problem and the localDevEnv and cloudDevEnv are not really part of any automated testing.
Will figure out a way to add some testing to these to avoid a problem like this again.

**Comment by freddydk** [comment]
Just rolled out a new preview - issue is still fixed.
