### ISSUE TITLE
'There are updates for your AL-Go system' and 'No previous release found' for builds on release branches 

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL-Go#371]
When merging PRs to a release/* branch, there is an output of 'There are updates for your AL-Go system'.
Could this be due to the release branch being created when 2.2 was current? The main branch is on 2.3.
Probably this is nothing to worry about, but incorrect warnings are annoying (we try to run a "no warnings" policy).

We also get a 'No previous release found', but there are multiple previous releases. Is this by design due to it being hard to determine the correct previous build in a release branch? Builds on main do find the previous release.

This is not critical, we are back to a partially manual process for hotfixes due to #360 anyway. So this is as much a heads-up about a potential issue.

**Comment by freddydk** [comment]
The release branch should locate the released bits from this release as previous release
will investigate together with 360 today

**Comment by freddydk** [comment]
In the Runpipeline job, could you locate the section with Locating Previous release and send the output of that?
![image](https://user-images.githubusercontent.com/10775043/213861339-166169fb-0090-4f1e-8d3e-32e2ed806bf2.png)

**Comment by AskeHolst** [comment]
The output is short:

```
Locating previous release
  Analyzing releases https://api.github.com/repos/prymeGlobal/[REDACTED]/releases
  Warning: No previous release found
```

I added you as a collaborator in case you need to have a look. Feel free to change settings or run workflows.

**Comment by freddydk** [comment]
I don't think I have your email - could you shoot me an email and explain to me how you created the release branch?
Manually - or through the Create Release workflow?

**Comment by freddydk** [comment]
The release branch was called release/2.3 - I created a release/2.3.0 from the same tag - now it finds the previous release.
I would expect 2.3 to find the same - let me investigate that.
If the branch is created in Create Release - it should have the name of the tag (2.3.0)

**Comment by freddydk** [comment]
Yeah, there definitely is a bug here - not only the branch name.

**Comment by freddydk** [comment]
Have submitted a fix for the known bugs in release branches.
The "There are updates" will not be removed - if your release branch is running on an old version of AL-Go - you should be notified.
You can run the Update AL-Go System files on this.
I will create an item in the backlog for supporting that the Update AL-Go System Files can update all release branches as well.

**Comment by AskeHolst** [comment]
How would you run Update AL-Go System files in a release branch? 
I did try to run it with "Run workflow from" set to the **release branch** when I encountered this 3 days ago. This updated the **main branch** using the logic from the release branch (fortunately it only changed whitespace in json files).

**Comment by freddydk** [comment]
that might be a different problem - you should be able to update al-go system files and specify a branch from which the pipeline should run. Will check that.

**Comment by freddydk** [comment]
I have hotfixed the issue that you cannot update AL-Go System files in a release branch.

**Comment by AskeHolst** [comment]
Yes, updating AL-Go System files in a release branch works now, thank you.
