### ISSUE TITLE
Question: Creating new Azure VM runner

### ISSUE THREAD

**Issue by CarlOhlsson** [microsoft/AL-Go#375]
When AL-Go was new I created a self-hosted Azure runner by following the instructions and it worked instantly.

Now I need to create another VM but I cannot get it to work, I can see in the documentation you are supposed to select “Windows Server 2019 with Containers” but now I can only select “Windows Server 2019” or “Windows Server 2022”. The VM is created but I never see any runners showing up in github. It seems like the powershell scrips that should be run on the servers fails for some reason. Think I might be using incorrect parameters.

I see the options “Install Hyper V” and “Run Inside Docker” but the documentation do not mention them. What should I set these parameters to for a basic configuration of github runners?

**Comment by freddydk** [comment]
Yeah, the 2019 with Containers was discontinued by the Azure Team.
But... - leaving all options as default should just work
Will try to create one myself.

**Comment by CarlOhlsson** [comment]
Works if you leave "Install Hyper V" and "Run Inside Docker" as default… I used them because I thought they compensated for the discontinued VM with containers image.

**Comment by freddydk** [comment]
My assumption is then that the VM Size selected didn't support Hyper-V and therefore that would fail
Do you remember which size you selected?

**Comment by CarlOhlsson** [comment]
At one point I remember finding the log file for the powershell script and I figured out that it had an error at a certain point, so I tried to run it again manually from there and it seemed to work. I got the runners working and showing on github however all my workflow failed with the error. 

docker: Error response from daemon: invalid volume specification: 'C:\agent\_work\PTE-XXXXXXX\PTE-XXXXXXXXXX\:c:\sources': invalid mount config for type "bind": bind source path does not exist: c:\agent\_work\pte-XXXXXXXXX\pte-XXXXXXXXX\.

Sadly I removed the VM and just tried again thinking I must have done something wrong without saving the log file….

Think i was trying with
Windows Server 2019
Standard_D4s_v3 & Standard_D8s_v3

And parameters
Install Hyper V = true
Run Inside Docker = true

**Comment by freddydk** [comment]
The run inside docker is probably the thing that caused the issue.
It tries to run the agents inside docker.

Thanks

/Freddy
