### ISSUE TITLE
CICD jobs that are triggered by the pull request trigger run directly to an error if title contains quotes

### ISSUE THREAD

**Issue by janlehmkuhl** [microsoft/AL-Go#376]
In my case, I currently have no clues where else to look. Do you have a tip for me? 
Attached is the log of the PullRequestHandler

![image](https://user-images.githubusercontent.com/94679485/214275061-4e612301-3c87-4228-a518-5b0ccd6993bf.png)
[PullRequestHandler_Log.zip](https://github.com/microsoft/AL-Go/files/10488916/PullRequestHandler_Log.zip)

**Comment by freddydk** [comment]
Likely a settings problem.
fromJson calculates a strategy from settings.
You can either invite me to the repo or drop the repo and project settings files here,

**Comment by freddydk** [comment]
This is likely not a settings problem, sorry about before.
If you can invite me to the repo, I will have a look.

**Comment by janlehmkuhl** [comment]
Your're invited

**Comment by freddydk** [comment]
Looks like it is related to the name... - grabbed the name of a failed PR and my BingMaps repo fails as well.
![image](https://user-images.githubusercontent.com/10775043/214284574-c3adce58-3d36-4a87-bf9e-0e1e908752a3.png)

**Comment by janlehmkuhl** [comment]
Okay! Great that you were able to reproduce this so quickly. We have now changed the name of the PR and it is running again for now. I think you will certainly investigate this further.

Thanks for the quick help!

**Comment by freddydk** [comment]
Looks like it is the quotes
![image](https://user-images.githubusercontent.com/10775043/214286801-dd42aa05-c513-4693-9e7e-295726f8fc1c.png)

Will fix this in the next version

**Comment by freddydk** [comment]
If you want a quick fix - you can modify the cicd.yaml and replace the run-name line (line 16) with this:

```
run-name: ${{ github.event_name != 'workflow_run' && 'CI/CD' || format('Check pull request from {1}/{2}{0} {3}',':',github.event.workflow_run.head_repository.owner.login,github.event.workflow_run.head_branch,github.event.workflow_run.display_title) }}
```
This should fix the issue
