### ISSUE TITLE
Get extension fails when username in windows contains "ilegal characters"

### ISSUE THREAD

**Issue by DanielMagMat** [microsoft/AL-Go#380]
When attempting to create local container using .ps1 file it fails when username in windows contains "ilegal character: ñ"

My lastname has a "ñ" and it is failing when script attempts to create a container.

`Error: Exception calling "GetExtension" with "1" argument(s): "Illegal characters in path."
Stacktrace: at New-BcContainer, C:\Users\DanielMagañ\AppData\Local\Temp\f119c7d6-251e-4a52-a8b5-53805a3d6aa5\BcContainerHelper\ContainerHandling\New-NavContainer.ps1: line 1492
at <ScriptBlock>, C:\Users\DanielMagañ\AppData\Local\Temp\f119c7d6-251e-4a52-a8b5-53805a3d6aa5\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 647
at <ScriptBlock>, C:\Users\DanielMagañ\AppData\Local\Temp\f119c7d6-251e-4a52-a8b5-53805a3d6aa5\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 840
at <ScriptBlock>, C:\Users\DanielMagañ\AppData\Local\Temp\f119c7d6-251e-4a52-a8b5-53805a3d6aa5\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 783
at <ScriptBlock>, C:\Users\DanielMagañ\AppData\Local\Temp\f119c7d6-251e-4a52-a8b5-53805a3d6aa5\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 766
at Run-AlPipeline, C:\Users\DanielMagañ\AppData\Local\Temp\f119c7d6-251e-4a52-a8b5-53805a3d6aa5\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 731
at CreateDevEnv, C:\Users\DanielMagañ\AppData\Local\Temp\tmpD594.tmp.ps1: line 1598
at <ScriptBlock>, C:\DEVELOPMENT\AL\Dataverse-Sales-Integration-Mexico\.AL-Go\localDevEnv.ps1: line 123
at <ScriptBlock>, <No file>: line 1`

**Comment by freddydk** [comment]
Is this the latest version of AL-Go - did you just create this repo?

**Comment by DanielMagMat** [comment]
Hello @freddydk . Thanks for checking in. Yes, its the most recent one released. I just created it this weekend.

**Comment by freddydk** [comment]
Thanks - I did go through everything with special characters a few releases ago - but apparently I missed something:-(
Will check this out.

**Comment by DanielMagMat** [comment]
Hello @freddydk. Apparently, this issue was in my end. I made a clean installation of all components, and it resolved my issue.
Sorry for the distraction. And thank you very much.

**Comment by DanielMagMat** [comment]
Hello @freddydk. Apparently, this issue was in my end. I made a clean installation of all components, and it resolved my issue.
Sorry for the distraction. And thank you very much.
