### ISSUE TITLE
Publish To Environment: InternalServerError : Internal Server Error Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by rolandpthompson** [microsoft/AL-Go#381]
I have 3 environments setup.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/6749639/215867510-d9ddf391-1809-4570-a59a-4a6e53c98129.png">

QA works fine, and i can push the 'latest' build to PROD too. But whenever i try and publish to the MyFAT (FAT) environment i always get, Internal Server Error Object reference not set to an instance of an object.

Both MyFAT and QA were a copy of the production sandbox, so were identical.
I've run out of ideas to try and fix it, any ideas?
Screenshots below

<img width="770" alt="image" src="https://user-images.githubusercontent.com/6749639/215867348-d7493917-2714-4d02-8916-d54ae492bf4a.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/6749639/215867229-a9ca649d-4d84-405f-9bdf-c8e3125c0def.png">

**Comment by rolandpthompson** [comment]
I've been looking a bit more into this.

Finally, I have created a copy of my FAT environment, called it UAT, then created an Environment in Github called UAT (FAT) with an environment name of uat.
That then works (this was a direct copy of the sandbox uat), so no idea why it works now.
Any combination of the below names seems to fail where the environment in BC is called FAT

FAT (FAT)
MyFAT (FAT)

Completely puzzled by this.
Are there certain names we should avoid?

**Comment by freddydk** [comment]
I will try to create some environments and test this - it should just work.

**Comment by freddydk** [comment]
Could you share your repo settings file (from .github)?

**Comment by freddydk** [comment]
From the image - the AL-Go environment name is MyFAT - but it tries to publish to a BC environment name called FAT.
If your environments are defined in GitHub environments, you might have an Environment secret under the environment which sets the BC environment name.
You could also have a setting called "MyFAT_EnvironmentName": "FAT" which would accomplish the same.

**Comment by freddydk** [comment]
Removed my former comment.
The error is an internal server error - and seems to be happening on the server side
I would assume you get the same if you tried to publish the app from VS Code to FAT - maybe that would reveal more information?

**Comment by rolandpthompson** [comment]
> Removed my former comment. The error is an internal server error - and seems to be happening on the server side I would assume you get the same if you tried to publish the app from VS Code to FAT - maybe that would reveal more information?

Ah ok, i removed the environment, but i will try it again and see what happens

**Comment by rolandpthompson** [comment]
Tested it again, had to create another environment, typical worked fine this time, so i think we can close this for now.
