### ISSUE TITLE
Code Signing in which workflow

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#386]
Not sure where to post a simple query, but:
Which workflow(s) would I run in order to confirm that the signing certificate URL secret is working and the workflow can access it with the password secret?
What would I be looking for (other than obvious errors) to confirm the result?
Thanks.

**Comment by freddydk** [comment]
The is no workflow to test the secret - but you can run the CI/CD workflow to see that it signs the app.

**Comment by buzzwick** [comment]
I suspected it was CI/CD. That runs without error, and the produced artifact indeed has a digital signature.
One more hurdle cleared—thank you!
