### ISSUE TITLE
Specify version when building

### ISSUE THREAD

**Issue by rolandpthompson** [microsoft/AL-Go#387]
So our production & sandbox environments are currently on 21.3.51409.51575 - no new versions available yet

<img width="597" alt="image" src="https://user-images.githubusercontent.com/6749639/217237329-a61847be-7441-4359-b187-6836e5523b1d.png">

I've made some code changes and have done a pull request, which fired off the CI/DI etc.
But it failed with an error - i know what the error is, a field has been added in 21.4 - which we are handling, but as we don't have 21.4 yet can we specify which version the CI/DI works, as its trying to use 21.4

<img width="941" alt="image" src="https://user-images.githubusercontent.com/6749639/217237987-fd9d9435-4520-4033-8259-f4def429b33e.png">

So, now I have an update I can't push via AL-Go, even though I know it will work with the current version.

**Comment by freddydk** [comment]
What is the Application dependency in your app.json file?

**Comment by rolandpthompson** [comment]
I don’t have specific one, is that what I’m missing then?

***@***.***

**Comment by freddydk** [comment]
Could you paste your app.json here? (or email it to freddyk at microsoft dot com)

**Comment by rolandpthompson** [comment]
Yes thats done it, threw up some other changes i needed to make but all sorted now.
