### ISSUE TITLE
Create release action - CreateReleaseBranch error

### ISSUE THREAD

**Issue by kennetlindberg** [microsoft/AL-Go#391]
When I tried to create a release, I got the following error in the "Create Release Branch" job

![image](https://user-images.githubusercontent.com/31550641/218092192-d3298d54-6227-4818-86f0-3a0709961330.png)

**Comment by freddydk** [comment]
What version of AL-Go is this?
(In the initialize step you can see the version number)

**Comment by kennetlindberg** [comment]
I have my own fork of AL-Go, and it was updated 2 days ago, so it is quite recent. Sorry for the stupid question, but where do I find the version?

**Comment by freddydk** [comment]
In the initialize step, you can see the version number

**Comment by freddydk** [comment]
you can also paste the url to your own fork here.

**Comment by kennetlindberg** [comment]
https://github.com/kennetlindberg/AL-Go

**Comment by freddydk** [comment]
Would it be possible to add me to the repo on which this happens - this might be a bug, which I would like to investigate

**Comment by kennetlindberg** [comment]
I've sent you an invite.

**Comment by freddydk** [comment]
It is actually the CreateReleaseJob (CreateReleaseNotes) step which fails:
![image](https://user-images.githubusercontent.com/10775043/220938916-cc93b901-c645-4579-9669-e1628c549d2f.png)
But without erroring out - and then not setting the release branch name - causing another error down the road.

Will investigate more

**Comment by freddydk** [comment]
The root cause of this problem was that the Tag (which in the description needs to be SemVer compatible) was not SemVer compatible.
This caused one action to fail silently and subsequently another action to fail later.
In the next verson, the action will fail with a message that the Tag needs to be SemVer compatible version number.
