### ISSUE TITLE
Continuous deployment to production in partner sandboxes

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#398]
As many partner use the partner sandbox offering by microsoft, it would be useful to have a flag in the enviroment configuration in github to bypass the following check.  

https://github.com/microsoft/AL-Go/blob/bfe872fc91d440d74a1368bd6bd03add979c5549/Actions/Deploy/Deploy.ps1#L152
 
If you are allowed to continuous deploy into the production enviroment of your partner sandbox. You can use the production enviroment as a template for the sandboxes.

**Comment by jonaswre** [comment]
Is this supported in the latest preview?

**Comment by freddydk** [comment]
Yes - you can create a DeployTo<env> and set ContinuousDeployment to true in that

**Comment by freddydk** [comment]
https://aka.ms/algosettings#deployto

**Comment by freddydk** [comment]
Also SyncMode and EnvironmentType for custom deployment

**Comment by jonaswre** [comment]
Thanks alot
