### ISSUE TITLE
"No AL Workspace Folder is Active"

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#405]
One VS Code user has just switched from working from DevOps repos to pulling from our AL-Go repo.  This user has had no trouble with push/pull, publishing branches, etc. No matter how we pull or open the new AL-Go repo or open the al workspace from the AL-Go template, attempts to Run Without Debugging (Ctrl-F5) get one of two errors:

"No AL Workspace folder is active"
"No Active Project was found. Make sure to select in VS Code Explorer."

None of us have ever seen these messages before; I have been entirely unsuccessful in finding relevant solutions on the web. There seems to be no VS Code documentation on making a workspace folder active, or selecting a Project.

Is there a preferred method of opening either the workspace file or the repo folder so as to ensure an active folder/project?

**Comment by freddydk** [comment]
After opening the workspace file of a repo, I believe he needs to open one file from one of the projects to activate that.
It isn't really related to AL-Go, it is general AL Language extension behavior.
