### ISSUE TITLE
Artifact Storage

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/AL-Go#406]
I am sure there is an obvious answer to this but I can't find it.  Where are my build artifacts stored?  I get this message:

> Artifact JI-InternalSystem-NEW-_DEV-BuildOutput-1.0.10.0 has been successfully uploaded!

But I have no idea where this is uploaded to?

**Comment by jonaswre** [comment]
I guess that would have been published into the artifacts of the workflow. If you go into the Workflow in the header is a column named Artifact with a number underneath. If you click on the number you should see all artifacts.

**Comment by freddydk** [comment]
exactly:
![image](https://user-images.githubusercontent.com/10775043/220248060-fdd408c0-042e-4a4c-a222-7fe527c0d363.png)
You can download them from here.
They are available there for the number of days defined by your GitHub settings (probably 90).
When you create a release, these artifacts are released and will be kept indefinite.

**Comment by tscottjendev** [comment]
There is only the build output file, no apps.  What am I missing?
![image](https://user-images.githubusercontent.com/102963427/220268742-bf873e0c-9cfa-4d1a-ac95-74bfb7c52f46.png)

**Comment by freddydk** [comment]
What workflow is this?

**Comment by tscottjendev** [comment]
CICD

**Comment by tscottjendev** [comment]
I have attached the logs here
[logs_12.zip](https://github.com/microsoft/AL-Go/files/10801030/logs_12.zip)

**Comment by freddydk** [comment]
As it is today, only builds from main branch or from release branches will produce artifacts (or if delivery is setup from that branch).

**Comment by tscottjendev** [comment]
So even if I add the _DEV to the CICD branch options?

Thanks.

**Comment by freddydk** [comment]
Today, yes
