### ISSUE TITLE
How to have CICD check as part of PR

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/AL-Go#413]
How can I have the CICD run as part of the checks that need to be run BEFORE a PR is committed the the destination branch?

E.g. have `someBugFix` branch and I want to pull it into 'feature/someNewFeature` branch.  How can I make sure that the PR does not get committed to the `feature/someNewFeature` branch with first passing the CICD action?

You show checks in your [Branching strategies for your AL-Go for GitHub repo](https://freddysblog.com/2022/05/03/branching-strategies-for-your-al-go-for-github-repo/) post but can't find where to have them happen.  What am I missing.

**Comment by freddydk** [comment]
Normally, we do not assume that you are using PRs against a feature branch.
We assume you are using PRs from the feature branch into main.
When working in the feature branches, you typically push to the feature branch and CI/CD will run then.
If you want to have double PRs (against feature branch and then again against main), you should be able to include feature branch in CICDPullRequestBranches setting to also run PR builds there.

**Comment by tscottjendev** [comment]
Okay so I have done a "Create Release" action that used a PR to update the version number in Main.  The PR does not include the CICD check BEFORE the final push to Main.  Is it because it is from an Action?  Should any PR into Main have a  requirement to committed that CICD completes successfully?

![image](https://user-images.githubusercontent.com/102963427/221158438-4e9d2db1-c126-4c35-9a10-8b522e2b5bd9.png)

**Comment by tscottjendev** [comment]
The CICD does kick off after the commit though.

![image](https://user-images.githubusercontent.com/102963427/221159183-0cba4070-806b-4f60-9ec1-b0a6a119bf81.png)

**Comment by freddydk** [comment]
This is because the default token used when running workflows, cannot kick off another workflow. This is by design: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
In v3.2 there is a checkbox in the parameter on Create Release (use GhTokenWorkflow) - using that will work.
