### ISSUE TITLE
What branching strategy is AL:GO trying to support.

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/AL-Go#414]
On the surface it looks like GitFlow but when I try to create a Release Branch from my Develop branch I get an error saying that there are no artifacts and it errors out.  AL:GO does not create artifacts on anything but `Main`, `feature/*` or `release/*` branches.   How can I create a release branch with the latest code if the Create Release action doesn't also create artifacts?
[logs_13.zip](https://github.com/microsoft/AL-Go/files/10813057/logs_13.zip)

**Comment by freddydk** [comment]
There are a million ways to do branching and in order to create an easy tool, we have to set some limits.
The assumption in AL-Go for GitHub is that the main branch is your stable, ship-ready development branch.
You branch off main to create a feature branch - develop in that and when you merge into main, it will run a PR build and then a final commit build after the merge.
The final Commit build (after the merge) will produce artifacts you can release.
When creating a release branch, you do that from the latest commit build or from a specific version of a commit build - always from main.
If you modify the release branch, that too creates artifacts
If you want to cherry-pick a feature from main into an old release branch, that change will again produce artifacts you can release.

**Comment by CPSTOS** [comment]
Hi @freddydk ,
I'm currently setting up a project for my team. This issue made me qustion our planned approach. Initially we wanted to develop in feature/ticket branches and merge those to a "test" branch, which should automatically be deployed to a test instance.
Once tested, the changes should be merged to a release branch, being deployed to the production instance out of working hours.

"main" was not involved so far ;)
Could you please give me some guidance on what branches to use, to get the test/production deployment working with AL:GO?

**Comment by CPSTOS** [comment]
That got me further. Unfortunately I'm stuck at `Error: Deploying to TEST failed.  No company `
Would you be so nice to give me a hint? thank you!

`Run microsoft/AL-Go-Actions/Deploy@v3.0
  with:
    shell: powershell
    parentTelemetryScopeJson: 7b[2](https://github.com/xx/BC-CP-Master/actions/runs/4725105662/jobs/8383761911#step:7:2)2506172616d657465727[3](https://github.com/xx/BC-CP-Master/actions/runs/4725105662/jobs/8383761911#step:7:3)223a7b7d2c22[4](https://github.com/xx/BC-CP-Master/actions/runs/4725105662/jobs/8383761911#step:7:4)[5](https://github.com/xx/BC-CP-Master/actions/runs/4725105662/jobs/8383761911#step:7:5)[6](https://github.com/xx/BC-CP-Master/actions/runs/4725105662/jobs/8383761911#step:7:6)d69[7](https://github.com/xx/BC-CP-Master/actions/runs/4725105662/jobs/8383761911#step:7:7)4746564223a66616c73652c22436f7272656c6174696f6e4964223a2235303164353763312d656565352d346434622d613935642d64306563373[8](https://github.com/xx/BC-CP-Master/actions/runs/4725105662/jobs/8383761911#step:7:8)383636346135222c22506172656e744[9](https://github.com/xx/BC-CP-Master/actions/runs/4725105662/jobs/8383761911#step:7:9)64223a22222c22416c6c506172616d6574657273223a7b7d2c22546f704964223a2235303164353763312d656565352d346434622d613935642d643065633738383636346135222c224e616d65223a22414c2d476f20776f726b666c6f772072616e3a205075626c697368546f456e7669726f6e6d656e74222c22537461727454696d65223a225c2f446174652831363831373632333234373937295c2f222c2250726f70657274696573223a7b226576656e744964223a22444f30303937222c226263436f6e7461696e657248656c70657256657273696f6e223a22342e302e3136222c22697341646d696e6973747261746f72223a2254727565222c22737461636b5472616365223a225b5c6e2020496e697454656c656d6574727953636f70652061742054656c656d6574727948656c7065722e7073313a206c696e65203231345c6e202043726561746553636f70652061742054656c656d6574727948656c7065722e70736d313a206c696e652037315c6e2020576f726b666c6f77496e697469616c697a652e70733120617420576f726b666c6f77496e697469616c697a652e7073313a206c696e652033375c6e202032623136376231312d623938332d346666382d623733392d6132316339356638353662392e7073312061742032623136376231312d623938332d346666382d623733392d6132316339356638353662392e7073313a206c696e6520325c6e20205c7530303363536372697074426c6f636b5c7530303365206174205c75303033634e6f2066696c655c75303033655c6e5d222c22414c476f56657273696f6e223a2276332e30222c2274797065223a22505445222c2274656d706c61746555726c223a2268747470733a2f2f6769746875622e636f6d2f6d6963726f736f66742f414c2d476f2d505445406d61696e222c227265706f7369746f7279223a22636f666665652d706572666563742f42432d43502d4d6173746572222c2272756e417474656d7074223a2236222c2272756e4e756d626572223a2235222c2272756e4964223a2234373235313035363632227d2c224576656e744964223a22444f30303937227d
    type: Publish
    projects: *
    environmentName: VEVTVA==
    artifacts: current
    actor: CPSTOS
    token: ***
  env:
    ALGoOrgSettings: 
    ALGoRepoSettings: 
    type: PTE
    unusedALGoSystemFiles: 
    projects: 
    country: de
    artifact: 
    companyName: ***
    repoVersion: 1.0
    repoName: BC-CP-Master
    versioningStrategy: 0
    runNumberOffset: 0
    appBuild: 5
    appRevision: 5
    keyVaultName: 
    licenseFileUrlSecretName: licenseFileUrl
    insiderSasTokenSecretName: insiderSasToken
    ghTokenWorkflowSecretName: ghTokenWorkflow
    adminCenterApiCredentialsSecretName: adminCenterApiCredentials
    applicationInsightsConnectionStringSecretName: applicationInsightsConnectionString
    keyVaultCertificateUrlSecretName: 
    keyVaultCertificatePasswordSecretName: 
    keyVaultClientIdSecretName: 
    codeSignCertificateUrlSecretName: codeSignCertificateUrl
    codeSignCertificatePasswordSecretName: codeSignCertificatePassword
    additionalCountries: 
    appDependencies: 
    appFolders: CP-Master
    testDependencies: 
    testFolders: CP-Master.Test
    bcptTestFolders: 
    installApps: 
    installTestApps: 
    installOnlyReferencedApps: True
    generateDependencyArtifact: False
    skipUpgrade: False
    applicationDependency: 18.0.0.0
    updateDependencies: False
    installTestRunner: False
    installTestFramework: False
    installTestLibraries: False
    installPerformanceToolkit: False
    enableCodeCop: False
    enableUICop: False
    customCodeCops: 
    failOn: error
    treatTestFailuresAsWarnings: False
    rulesetFile: 
    assignPremiumPlan: False
    enableTaskScheduler: False
    doNotBuildTests: False
    doNotRunTests: False
    doNotRunBcptTests: False
    doNotPublishApps: False
    doNotSignApps: False
    configPackages: 
    appSourceCopMandatoryAffixes: 
    obsoleteTagMinAllowedMajorMinor: 
    memoryLimit: 
    templateUrl: https://github.com/microsoft/AL-Go-PTE@main
    templateBranch: 
    appDependencyProbingPaths: 
    useProjectDependencies: False
    runs-on: windows-latest
    shell: powershell
    githubRunner: windows-latest
    githubRunnerShell: powershell
    cacheImageName: my
    cacheKeepDays: 3
    alwaysBuildAllProjects: False
    microsoftTelemetryConnectionString: InstrumentationKey=84bd9223-67d4-4378-8590-9e4a46023be2;IngestionEndpoint=https://westeurope-1.in.applicationinsights.azure.com/
    partnerTelemetryConnectionString: 
    sendExtendedTelemetryToMicrosoft: False
    environments: test
    buildModes: 
    CICDPushBranches: test release
    CICDPullRequestBranches: release
    DeployTotest: {"Branches":["test"],"companyName":"***","EnvironmentName":"Test","Projects":"*","Runs-on":"Windows-2019"}
    Settings: {"keyVaultCertificateUrlSecretName":"","microsoftTelemetryConnectionString":"InstrumentationKey=84bd9223-67d4-4378-8590-9e4a46023be2;IngestionEndpoint=https://westeurope-1.in.applicationinsights.azure.com/","type":"PTE","sendExtendedTelemetryToMicrosoft":false,"appBuild":5,"doNotRunBcptTests":false,"versioningStrategy":0,"installApps":[],"installTestLibraries":false,"runNumberOffset":0,"codeSignCertificatePasswordSecretName":"codeSignCertificatePassword","country":"de","partnerTelemetryConnectionString":"","insiderSasTokenSecretName":"insiderSasToken","doNotRunTests":false,"runs-on":"windows-latest","generateDependencyArtifact":false,"templateUrl":"https://github.com/microsoft/AL-Go-PTE@main","keyVaultCertificatePasswordSecretName":"","rulesetFile":"","licenseFileUrlSecretName":"licenseFileUrl","memoryLimit":"","keyVaultClientIdSecretName":"","testFolders":["CP-Master.Test"],"githubRunner":"windows-latest","doNotBuildTests":false,"environments":["test"],"companyName":"***","assignPremiumPlan":false,"artifact":"","ghTokenWorkflowSecretName":"ghTokenWorkflow","enableTaskScheduler":false,"enableCodeCop":false,"repoVersion":"1.0","doNotPublishApps":false,"doNotSignApps":false,"unusedALGoSystemFiles":[],"githubRunnerShell":"powershell","cacheKeepDays":3,"bcptTestFolders":[],"updateDependencies":false,"cacheImageName":"my","treatTestFailuresAsWarnings":false,"additionalCountries":[],"enableUICop":false,"customCodeCops":[],"appDependencies":[],"DeployTotest":{"Branches":["test"],"companyName":"***","EnvironmentName":"Test","Projects":"*","Runs-on":"Windows-2019"},"appDependencyProbingPaths":[],"installTestFramework":false,"useProjectDependencies":false,"keyVaultName":"","installOnlyReferencedApps":true,"CICDPushBranches":["test","release"],"obsoleteTagMinAllowedMajorMinor":"","applicationDependency":"18.0.0.0","applicationInsightsConnectionStringSecretName":"applicationInsightsConnectionString","shell":"powershell","failOn":"error","installTestApps":[],"testDependencies":[],"appRevision":5,"codeSignCertificateUrlSecretName":"codeSignCertificateUrl","configPackages":[],"projects":[],"appSourceCopMandatoryAffixes":[],"buildModes":[],"templateBranch":"","installPerformanceToolkit":false,"CICDPullRequestBranches":["release"],"appFolders":["CP-Master"],"repoName":"BC-CP-Master","alwaysBuildAllProjects":false,"skipUpgrade":false,"installTestRunner":false,"adminCenterApiCredentialsSecretName":"adminCenterApiCredentials"}
    AuthContext: ***
    RepoSecrets: {"AuthContext":"***","test-AuthContext":"","test_AuthContext":"","test-EnvironmentName":"","test_EnvironmentName":"","EnvironmentName":"","projects":""}
Run try { D:\a\_actions\microsoft\AL-Go-Actions\v3.0\Deploy/Deploy.ps1 -actor $ENV:_actor -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -projects $ENV:_projects -environmentName $ENV:_environmentName -artifacts $ENV:_artifacts -type $ENV:_type } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
  try { D:\a\_actions\microsoft\AL-Go-Actions\v3.0\Deploy/Deploy.ps1 -actor $ENV:_actor -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -projects $ENV:_projects -environmentName $ENV:_environmentName -artifacts $ENV:_artifacts -type $ENV:_type } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
  shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
  env:
    ALGoOrgSettings: 
    ALGoRepoSettings: 
    type: PTE
    unusedALGoSystemFiles: 
    projects: 
    country: de
    artifact: 
    companyName: ***
    repoVersion: 1.0
    repoName: BC-CP-Master
    versioningStrategy: 0
    runNumberOffset: 0
    appBuild: 5
    appRevision: 5
    keyVaultName: 
    licenseFileUrlSecretName: licenseFileUrl
    insiderSasTokenSecretName: insiderSasToken
    ghTokenWorkflowSecretName: ghTokenWorkflow
    adminCenterApiCredentialsSecretName: adminCenterApiCredentials
    applicationInsightsConnectionStringSecretName: applicationInsightsConnectionString
    keyVaultCertificateUrlSecretName: 
    keyVaultCertificatePasswordSecretName: 
    keyVaultClientIdSecretName: 
    codeSignCertificateUrlSecretName: codeSignCertificateUrl
    codeSignCertificatePasswordSecretName: codeSignCertificatePassword
    additionalCountries: 
    appDependencies: 
    appFolders: CP-Master
    testDependencies: 
    testFolders: CP-Master.Test
    bcptTestFolders: 
    installApps: 
    installTestApps: 
    installOnlyReferencedApps: True
    generateDependencyArtifact: False
    skipUpgrade: False
    applicationDependency: 18.0.0.0
    updateDependencies: False
    installTestRunner: False
    installTestFramework: False
    installTestLibraries: False
    installPerformanceToolkit: False
    enableCodeCop: False
    enableUICop: False
    customCodeCops: 
    failOn: error
    treatTestFailuresAsWarnings: False
    rulesetFile: 
    assignPremiumPlan: False
    enableTaskScheduler: False
    doNotBuildTests: False
    doNotRunTests: False
    doNotRunBcptTests: False
    doNotPublishApps: False
    doNotSignApps: False
    configPackages: 
    appSourceCopMandatoryAffixes: 
    obsoleteTagMinAllowedMajorMinor: 
    memoryLimit: 
    templateUrl: https://github.com/microsoft/AL-Go-PTE@main
    templateBranch: 
    appDependencyProbingPaths: 
    useProjectDependencies: False
    runs-on: windows-latest
    shell: powershell
    githubRunner: windows-latest
    githubRunnerShell: powershell
    cacheImageName: my
    cacheKeepDays: 3
    alwaysBuildAllProjects: False
    microsoftTelemetryConnectionString: InstrumentationKey=84bd9223-67d4-4378-8590-9e4a46023be2;IngestionEndpoint=https://westeurope-1.in.applicationinsights.azure.com/
    partnerTelemetryConnectionString: 
    sendExtendedTelemetryToMicrosoft: False
    environments: test
    buildModes: 
    CICDPushBranches: test release
    CICDPullRequestBranches: release
    DeployTotest: {"Branches":["test"],"companyName":"***","EnvironmentName":"Test","Projects":"*","Runs-on":"Windows-2019"}
    Settings: {"keyVaultCertificateUrlSecretName":"","microsoftTelemetryConnectionString":"InstrumentationKey=84bd9223-67d4-4378-8590-9e4a46023be2;IngestionEndpoint=https://westeurope-1.in.applicationinsights.azure.com/","type":"PTE","sendExtendedTelemetryToMicrosoft":false,"appBuild":5,"doNotRunBcptTests":false,"versioningStrategy":0,"installApps":[],"installTestLibraries":false,"runNumberOffset":0,"codeSignCertificatePasswordSecretName":"codeSignCertificatePassword","country":"de","partnerTelemetryConnectionString":"","insiderSasTokenSecretName":"insiderSasToken","doNotRunTests":false,"runs-on":"windows-latest","generateDependencyArtifact":false,"templateUrl":"https://github.com/microsoft/AL-Go-PTE@main","keyVaultCertificatePasswordSecretName":"","rulesetFile":"","licenseFileUrlSecretName":"licenseFileUrl","memoryLimit":"","keyVaultClientIdSecretName":"","testFolders":["CP-Master.Test"],"githubRunner":"windows-latest","doNotBuildTests":false,"environments":["test"],"companyName":"***","assignPremiumPlan":false,"artifact":"","ghTokenWorkflowSecretName":"ghTokenWorkflow","enableTaskScheduler":false,"enableCodeCop":false,"repoVersion":"1.0","doNotPublishApps":false,"doNotSignApps":false,"unusedALGoSystemFiles":[],"githubRunnerShell":"powershell","cacheKeepDays":3,"bcptTestFolders":[],"updateDependencies":false,"cacheImageName":"my","treatTestFailuresAsWarnings":false,"additionalCountries":[],"enableUICop":false,"customCodeCops":[],"appDependencies":[],"DeployTotest":{"Branches":["test"],"companyName":"***","EnvironmentName":"Test","Projects":"*","Runs-on":"Windows-2019"},"appDependencyProbingPaths":[],"installTestFramework":false,"useProjectDependencies":false,"keyVaultName":"","installOnlyReferencedApps":true,"CICDPushBranches":["test","release"],"obsoleteTagMinAllowedMajorMinor":"","applicationDependency":"18.0.0.0","applicationInsightsConnectionStringSecretName":"applicationInsightsConnectionString","shell":"powershell","failOn":"error","installTestApps":[],"testDependencies":[],"appRevision":5,"codeSignCertificateUrlSecretName":"codeSignCertificateUrl","configPackages":[],"projects":[],"appSourceCopMandatoryAffixes":[],"buildModes":[],"templateBranch":"","installPerformanceToolkit":false,"CICDPullRequestBranches":["release"],"appFolders":["CP-Master"],"repoName":"BC-CP-Master","alwaysBuildAllProjects":false,"skipUpgrade":false,"installTestRunner":false,"adminCenterApiCredentialsSecretName":"adminCenterApiCredentials"}
    AuthContext: ***
    RepoSecrets: {"AuthContext":"***","test-AuthContext":"","test_AuthContext":"","test-EnvironmentName":"","test_EnvironmentName":"","EnvironmentName":"","projects":""}
    _actor: CPSTOS
    _token: ***
    _parentTelemetryScopeJson: 7b22506172616d6574657273223a7b7d2c22456d6974746564223a66616c73652c22436f7272656c6174696f6e4964223a2235303164353763312d656565352d346434622d613935642d643065633738383636346135222c22506172656e744964223a22222c22416c6c506172616d6574657273223a7b7d2c22546f704964223a2235303164353763312d656565352d346434622d613935642d643065633738383636346135222c224e616d65223a22414c2d476f20776f726b666c6f772072616e3a205075626c697368546f456e7669726f6e6d656e74222c22537461727454696d65223a225c2f446174652831363831373632333234373937295c2f222c2250726f70657274696573223a7b226576656e744964223a22444f30303937222c226263436f6e7461696e657248656c70657256657273696f6e223a22342e302e3136222c22697341646d696e6973747261746f72223a2254727565222c22737461636b5472616365223a225b5c6e2020496e697454656c656d6574727953636f70652061742054656c656d6574727948656c7065722e7073313a206c696e65203231345c6e202043726561746553636f70652061742054656c656d6574727948656c7065722e70736d313a206c696e652037315c6e2020576f726b666c6f77496e697469616c697a652e70733120617420576f726b666c6f77496e697469616c697a652e7073313a206c696e652033375c6e202032623136376231312d623938332d346666382d623733392d6132316339356638353662392e7073312061742032623136376231312d623938332d346666382d623733392d6132316339356638353662392e7073313a206c696e6520325c6e20205c7530303363536372697074426c6f636b5c7530303365206174205c75303033634e6f2066696c655c75303033655c6e5d222c22414c476f56657273696f6e223a2276332e30222c2274797065223a22505445222c2274656d706c61746555726c223a2268747470733a2f2f6769746875622e636f6d2f6d6963726f736f66742f414c2d476f2d505445406d61696e222c227265706f7369746f7279223a22636f666665652d706572666563742f42432d43502d4d6173746572222c2272756e417474656d7074223a2236222c2272756e4e756d626572223a2235222c2272756e4964223a2234373235313035363632227d2c224576656e744964223a22444f30303937227d
    _projects: *
    _environmentName: VEVTVA==
    _artifacts: current
    _type: Publish
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 4.0.16
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Analyzing releases https://api.github.com/repos/xx/BC-CP-Master/releases
Downloading release 1.0.0, projects *, type Apps
project '*'
https://api.github.com/repos/xx/BC-CP-Master/releases/assets/[10](https://github.com/xx/BC-CP-Master/actions/runs/4725105662/jobs/8383761911#step:7:10)4[11](https://github.com/xx/BC-CP-Master/actions/runs/4725105662/jobs/8383761911#step:7:11)5220
D:\a\BC-CP-Master\BC-CP-Master\.artifacts\BC-CP-Master-test-Apps-1.0.29.0.zip
Downloading release 1.0.0, projects *, type Dependencies
project '*'
Apps to deploy
D:\a\BC-CP-Master\BC-CP-Master\.artifacts\BC-CP-Master-test-Apps-1.0.29.0.zip
Attempting authentication to https://api.businesscentral.dynamics.com/.default using clientCredentials...
Authenticated as app ***
https://businesscentral.dynamics.com/***/TEST/deployment/url
Using S2S, publishing apps using automation API
Publish-PerTenantExtensionApps Telemetry Correlation Id: 85a4[15](https://github.com/xx/BC-CP-Master/actions/runs/4725105662/jobs/8383761911#step:7:15)cd-dcb2-4ad4-ab75-[46](https://github.com/xx/BC-CP-Master/actions/runs/4725105662/jobs/8383761911#step:7:46)8[81](https://github.com/xx/BC-CP-Master/actions/runs/4725105662/jobs/8383761911#step:7:81)b4c6a2a
Error: Deploying to TEST failed.  No company 
Removing BcContainerHelper
Error: Process completed with exit code 1.`

**Comment by CPSTOS** [comment]
That one was a permissions problem. Got it now!
