### ISSUE TITLE
Create Release Failed IncrementVersionNumber action failed.

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/AL-Go#415]
Getting this message 
> IncrementVersionNumber action failed. Error: pull request create failed: GraphQL: GitHub Actions is not permitted to create or approve pull requests (createPullRequest) 

Is there are permission I missed setting up?  This is an GitHub Enterprise repo.

Log files:
PR to Main [logs_14.zip](https://github.com/microsoft/AL-Go/files/10815373/logs_14.zip)
Create Release [logs_16.zip](https://github.com/microsoft/AL-Go/files/10815387/logs_16.zip)

**Comment by freddydk** [comment]
In your org. settings, go Actions -> general -> Workflow permissions: and set the checkbox.
![image](https://user-images.githubusercontent.com/10775043/220958409-95cc5f7d-f11d-461f-a315-df2628e617f9.png)

Same checkbox is also on the repo.

Or - you can choose to say Direct COMMIT = Y to not use a PR.

**Comment by freddydk** [comment]
In v3.2 all actions creating PRs or pushing directly to a repo have a new checkbox in the parameters:
![image](https://github.com/microsoft/AL-Go/assets/10775043/e3c345cd-7755-498f-acf3-a23b184a414d)

If you check this box, the GhTokenWorkflow (if exists) is used to create the PR/Push - and this token should have permissions to create PRs - and will cause depending workflows to be kicked off following a PR/Push
