### ISSUE TITLE
Delivery in AppSource fails

### ISSUE THREAD

**Issue by janlehmkuhl** [microsoft/AL-Go#416]
It seems that the delivery of our AppSource is no longer working. I have already described the problem in the following ticket. Can you guys take a look at it? In our case, it is not a "multi-project repository" and it has always worked before. All necessary parameters mentioned in the log are set.

https://github.com/microsoft/AL-Go/issues/356

**Comment by janlehmkuhl** [comment]
[logs_1814.zip](https://github.com/microsoft/AL-Go/files/10816183/logs_1814.zip)

**Comment by freddydk** [comment]
I think there is a problem with settings and casing still.
Could you try to change the A in appSourceProductId to a capital A - to see whether this fixes the issue.

**Comment by janlehmkuhl** [comment]
This solved the problem! Thanks!

**Comment by freddydk** [comment]
Reopening the issue - as I need to fix the casing problem.

Thanks

**Comment by freddydk** [comment]
Actually - there is a bug for this #385
