### ISSUE TITLE
Explanation of versioning

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#421]
We are successfully making changes to our base app and deploying to test online environments via CI/CD. One topic that is out of control, however, is versioning. By way of illustration, we have 
`In app.json: 21.200.3`
`What gets deployed: 21.2.43.0`
`"latest" release: 21.2.1.33 (but the -main-Apps.zip is 21.1.32.0)`

1. Is there somewhere I can find an explanation of how/when each of these gets generated or incremented?
2. Assuming we remove our environments as a factor (i.e., we delete and recreate the sandboxes), is there a way to reset the base version number and get these all to align?

**Comment by freddydk** [comment]
In app.json, you have 21.200.3 - I assume you mistyped and should be 21.2.0.3?
With every build, version number is created by AL-Go.
Every app will get major.minor from app.json and build.release will be calculated by AL-Go determined by VersioningStrategy (default is run-number.0)
The artifacts for the project/repo will be versioned by repoversion (in settings) and the same build.release as the apps.
When creating a release, you should update the major.minor (the Create Release workflow can do this for you).

**Comment by freddydk** [comment]
It is described under versioning in the AL-Go Workshop (https://aka.ms/algoworkshop)

**Comment by buzzwick** [comment]
Thanks, I have the workshop material; I am now looking at Versioning with a little more understanding and will try to document the flow of numbering from there, so our developers (and my manager) can understand what is going on.

Two questions:
--Slide 25 suggests that the artifact zip file takes its major.minor version from RepoSettings.RepoVersion, but the app file it contains takes its major.minor version from App.json. Does this mean they have to be manually kept in synch?

--Do the AL-Go workflows ever write back to App.json to update the version number there?

**Comment by freddydk** [comment]
It is actually the projectsettings.repoVersion (not reposettings.repoversion) will update docs.
Every repo can contain multiple projects.
Every project can contain multiple apps.
Every project will have it's own .zip file.
RepoVersion will only name the .zip file.
If the .zip file contains 5 apps - these can have different version numbers (major.minor) and are not necessarily in sync - this is why the .zip file is named after projectsettings.repoversion instead of one of the apps.

The Increment Version number will update app.json (major and minor only)
And the Create Release will call the increment version number as well.

If VersioningStrategy is 16 - then RepoVersion and App Version will remain in sync - repoversion will be stamped into app.json (always only major.minor)

Why is it named repoversion when it really is a projectversion - well - it is from before we had multiple projects...:-(

**Comment by buzzwick** [comment]
Even more helpful--especially about the zip file/app file discrepancies. It would be impossible to divine all this from just the exploded-view in the Workshop slides. I would love to have a whole clinic just around these overall management workflows, in Orlando. In the meantime:
--Is CI/CD the only workflow that requires that a Release be present? 
--Our app.json version is currently 21.2.0.3--but publish to QA results in 21.2.44.0 in Extension Management. It looks like a VersioningStrategy of -1 would keep those in synch, yes (and is there a reason -1 is not documented on the Microsoft Learn page for AL-Go Settings)?

**Comment by freddydk** [comment]
CI/CD doesn't require a release to be present - it uses it if it is there as a previous version.
Publish to environment defaults the version to current, which is the latest released version (latest is the latest build)

I think versioningstrategy -1 means that you will use the Business Central artifact version as your version number - you don't want that.

**Comment by freddydk** [comment]
I will try to create some more in-depth descriptions of some of these parts.

**Comment by buzzwick** [comment]
I could use that. I am sure others could.  A narrative description of some hypothetical, representative develop/deploy cycles, illustrating how these various parts would interact to produce things like releases and version numbers, might be a useful format for helping users understand how to use the various settings.  I would be happy to help in any way that I could.

I read the workshop slide (26) to mean that versioningStrategy -1 would take Build and Release from the App.json Version.  But I think you are right--the deployment resulting from updating the settings.json to versioningstrategy -1 pushed out a version  21.4.52563.53772. Which looks a lot like the BC artifact version. So we won't do that.

**Comment by buzzwick** [comment]
One more question related to versioning: in the course of learning how all this works, our versioning (app.json, releases, artifacts) has gotten out of synch and does not reflect reality (we now show 21.2 for major.minor, but since we are still in development it should really be 21.0.0.0. Assuming we can simply delete any test environments we have deployed to, what would be a procedure to reset all these versions to a common starting point (like 21.0.0.0) and go from there?

**Comment by buzzwick** [comment]
One thing not clear:

  1.  Increment Version and Create Release both accept a new version number (absolute or incremental)
  2.  “Increment Version will update app.json” (Create Release calls Increment Version, so it also updates app.json indirectly)
  3.  “Repoversion will be stamped into app.json”

I read this to say that BOTH repoversion and Increment Version update app.json (this seems not right)

But does Increment Version ALSO update repoversion?

It looks like repoversion is simply a storage location for version number (major.minor), and that Increment Version/Create Release are meant to be the “drivers” of increasing the version number.

Do I have that right?

**Comment by buzzwick** [comment]
Another mystery:

From the CI/CD workflow, deploying to the QA environment:

App CAI Software_CAI Software Precious Metals Solution_21.6.68.0.app successfully published

But at the QA environment Extension Management:

***@***.***

Should we expect these to be the same? Or is there yet another versioning mechanism at work?

Thanks.

**Comment by buzzwick** [comment]
And yet on FAT, in the same CI/CD workflow run:

***@***.***

This run, however failed at the Deploy stage:

Publishing CAI Software_CAI Software Precious Metals Solution_21.6.68.0.app to ***v2.0/FAT/dev/apps?SchemaUpdateMode=synchronize&dependencyPublishingOption=ignore
192<https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/runs/4393528300/jobs/7694099913#step:8:194>Publish-BcContainerApp Telemetry Correlation Id: 0fcff8bd-8d14-4c84-b10c-65d9cf31c8d1
193<https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/runs/4393528300/jobs/7694099913#step:8:195>Error: Deploying to FAT failed. Exception calling "GetResult" with "0" argument(s): "An error occurred while sending the request."
194<https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/runs/4393528300/jobs/7694099913#step:8:196>Removing BcContainerHelper
195<https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/runs/4393528300/jobs/7694099913#step:8:197>Error: Process completed with exit code 1.


From: David Baldwin
Sent: Saturday, March 11, 2023 1:30 PM
To: microsoft/AL-Go ***@***.***>
Subject: RE: [microsoft/AL-Go] Explanation of versioning (Issue #421)

Another mystery:

From the CI/CD workflow, deploying to the QA environment:

App CAI Software_CAI Software Precious Metals Solution_21.6.68.0.app successfully published

But at the QA environment Extension Management:

***@***.***

Should we expect these to be the same? Or is there yet another versioning mechanism at work?

Thanks.

**Comment by navdotnetreqs** [comment]
I think this still needs clarifications, it's really not clearly explained in the docs.

For example, one new thing was that PR's always have build version max int, and this cannot be changed.

https://github.com/microsoft/AL-Go/issues/1868


https://github.com/microsoft/AL-Go/blob/main/Workshop/Versioning.md
https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md#versioningStrategy
