### ISSUE TITLE
External dependencies in multi project repos that use useProjectDependencies

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#427]
I've had to switch a single project/multi app repo to a multi project/single app repo to be able to deploy to app source. 

I've now encountered an issue where builds triggered from a PR wont install/download dependencies which come from another repo (using nuget). 

In both runs, external dependecies are correctly identified. 

But in the run from the PR this line is never executed. 

https://github.com/microsoft/navcontainerhelper/blob/81f0eba49b606545316fd560a42a3f0f2da16d91/AppHandling/Run-AlPipeline.ps1#L1051.

The pipeline skips this section and then fails the compilation with a 404 when trying to download the symbols. 

![image](https://user-images.githubusercontent.com/3731681/221972140-af147cbf-ff26-4525-a35c-3c23f1f3d096.png)
The failed build

![image](https://user-images.githubusercontent.com/3731681/221972212-b40e0a51-48c7-42ff-b8bb-d05d70d2f402.png)
The succeeded build

And the changes in the PR are only a few al files nothing major.

**Comment by jonaswre** [comment]
@freddydk 

And I can't revert to main...

Downloading BcContainerHelper preview version from Blob Storage
BcContainerHelper version 4.0.14-preview902
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Using template from https://github.com/microsoft/AL-Go-AppSource@main
Using ArchiveUrl https://api.github.com/repos/microsoft/AL-Go-AppSource/zipball/main
Analyzing projects
- BeyondCatalog
Folders containing apps are .\BeyondCatalog\app,.\BeyondCatalog\test
- BeyondDataImporterCatalogBridge
Folders containing apps are .\BeyondDataImporterCatalogBridge\app
- BeyondRecordSearchCatalogBridge
Folders containing apps are .\BeyondRecordSearchCatalogBridge\app
Analyzing dependencies
- BeyondCatalog
Set ProjectDependencies for BeyondCatalog to 
No additional dependencies found, add project to build order
- BeyondDataImporterCatalogBridge
Set ProjectDependencies for BeyondDataImporterCatalogBridge to BeyondCatalog
Found dependencies to projects: BeyondCatalog
- BeyondRecordSearchCatalogBridge
Set ProjectDependencies for BeyondRecordSearchCatalogBridge to BeyondCatalog
Found dependencies to projects: BeyondCatalog
#1 - build projects: BeyondCatalog
- BeyondDataImporterCatalogBridge
No additional dependencies found, add project to build order
- BeyondRecordSearchCatalogBridge
No additional dependencies found, add project to build order
#2 - build projects: BeyondDataImporterCatalogBridge, BeyondRecordSearchCatalogBridge
Calculated dependency depth to be 2
Checking .github\workflows\*
- AddExistingAppOrTestApp.yaml
Updated workflow 'Add existing app or test app' (.github\workflows\AddExistingAppOrTestApp.yaml) available
- CICD.yaml
Updated workflow ' CI/CD' (.github\workflows\CICD.yaml) available
- CreateApp.yaml
Updated workflow 'Create a new app' (.github\workflows\CreateApp.yaml) available
- CreateOnlineDevelopmentEnvironment.yaml
Updated workflow ' Create Online Dev. Environment' (.github\workflows\CreateOnlineDevelopmentEnvironment.yaml) available
- CreatePerformanceTestApp.yaml
Updated workflow 'Create a new performance test app' (.github\workflows\CreatePerformanceTestApp.yaml) available
- CreateRelease.yaml
Updated workflow ' Create release' (.github\workflows\CreateRelease.yaml) available
- CreateTestApp.yaml
Updated workflow 'Create a new test app' (.github\workflows\CreateTestApp.yaml) available
- Current.yaml
Updated workflow ' Test Current' (.github\workflows\Current.yaml) available
- IncrementVersionNumber.yaml
Updated workflow ' Increment Version Number' (.github\workflows\IncrementVersionNumber.yaml) available
- NextMajor.yaml
Updated workflow ' Test Next Major' (.github\workflows\NextMajor.yaml) available
- NextMinor.yaml
Updated workflow ' Test Next Minor' (.github\workflows\NextMinor.yaml) available
- PublishToAppSource.yaml
Updated workflow ' Publish To AppSource' (.github\workflows\PublishToAppSource.yaml) available
- PublishToEnvironment.yaml
Updated workflow ' Publish To Environment' (.github\workflows\PublishToEnvironment.yaml) available
- PullRequestHandler.yaml
cannot locate env:/workflowDepth:
Error: CheckForUpdates action failed. Error: The property 'content' cannot be found on this object. Verify that the property exists. Stacktrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\CheckForUpdates\CheckForUpdates.ps1: line 260 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\CheckForUpdates\CheckForUpdates.ps1: line 168 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\CheckForUpdates\CheckForUpdates.ps1: line 159 at <ScriptBlock>, D:\a\_temp\d71cf225-efdd-4d99-aab7-b6aa8a208b74.ps1: line 2 at <ScriptBlock>, <No file>: line 1
AL-Go action ran: CheckForUpdates Telemetry Correlation Id: f3cee5ac-[56](https://github.com/byndit/BeyondCatalog/actions/runs/4297621455/jobs/7490813531#step:8:58)da-42b0-8ae2-87336[60](https://github.com/byndit/BeyondCatalog/actions/runs/4297621455/jobs/7490813531#step:8:62)60018

**Comment by freddydk** [comment]
Any chance I can see the full output?
Or get access to the repo?

**Comment by freddydk** [comment]
I have hotfixed the CheckForUpdates action. You should be able to revert to main now.
But... - I would still like to find out why NuGet stopped working in preview.

**Comment by freddydk** [comment]
Running some tests myself now.

**Comment by freddydk** [comment]
Cannot repro the problem
![image](https://user-images.githubusercontent.com/10775043/222008857-f18a49e8-b6d6-4055-8139-02ad7f4eb1f5.png)

**Comment by jonaswre** [comment]
I'll reproduce the issue and give you access once I'm in the office. 

One little sidenote we have the following structure.


Repo A:
- App A

Repo B:
- App 1
- App 2


App 2 two has a dependency on App 1 and App A and fails do resolve App A

**Comment by freddydk** [comment]
I am in the US and will go to bed in an hour - if I can have a look beforehand? (then I can sleep better:-))

**Comment by jonaswre** [comment]
@freddydk Im in the office now an gave you access.

**Comment by freddydk** [comment]
In PullRequestHandler.yaml, line 169 and line 292, could you add GitHubPackagesContext to the secrets to retrieve.
That should fix the issue.

**Comment by jonaswre** [comment]
Build is running. I'll let you know if this fixes it. 
#428 can then close this issue.

Thanks alot and sleep well.

**Comment by freddydk** [comment]
Thanks - flying home to Denmark tomorrow

**Comment by freddydk** [comment]
Problem was only in the PR handler - right?
I saw the CI/CD build complete

**Comment by jonaswre** [comment]
Yes the builds that were run directly were successful.

**Comment by freddydk** [comment]
I think there is another issue with this - the PR handler won't deliver the package when building.

**Comment by jonaswre** [comment]
I think its time to switch to a self hosted agent soon.... 

Will the PR Handler download all missing dependencies and then injects them into the build?

**Comment by freddydk** [comment]
Yes, but the PR handler won't deliver to nuget (and shouldn't)
If you leave me with access to this repo - then I can check a few extra things tomorrow.

**Comment by jonaswre** [comment]
Yes sure. 
But that PR will have to be closed I cant leave that open. I'll additionally create a repo to reproduce this.

**Comment by freddydk** [comment]
That's fine - I just need to be able to see the settings - I know the problem and can create a repro repo myself.

**Comment by jonaswre** [comment]
Build succeeded now.

**Comment by freddydk** [comment]
Got it - the failure before was actually not the BeyondCatalog - it was the BeyondDataImporter (from a different repo).
It gets the BeyondCatalog through thisbuild-artifacts - that works.

So, I think this fix is good.

Thanks for trying out the preview to get these things sorted out.

**Comment by jonaswre** [comment]
Yes thats correctly BeyondDataImporter is a dependency thats needed for the bridge app thats downloaded from nuget. BeyondCatalog is gotten through "useProjectDependencies". 

No problem. Im just glab to be away from maintaining Azure Devop scrips😆 

On that note. I've created a issuse a week ago that not super urgent it just currently means I can't use "Publish to AppSource" in that repo. I think there are still some things to do in regards to delivering multi project repos. 
https://github.com/microsoft/AL-Go/issues/418

If you need me to test something pre-preview let me know.

**Comment by freddydk** [comment]
Thanks
Have just deployed a new preview with these things fixed.
Will have a look at your other issue next week - flying home today...

**Comment by jonaswre** [comment]
Thanks alot have a good flight.

**Comment by freddydk** [comment]
shipped in 3.1
