### ISSUE TITLE
No viable required status check

### ISSUE THREAD

**Issue by cegekaJG** [microsoft/AL-Go#443]
From what I can gather, `PullRequestHandler` determines whether a PR requires a check and skips it if it doesn't. Which is nice, but if I want to use it as a required status check, I run into a problem because all PRs that don't trigger will be waiting for a check that never shows up.
I'm not entirely sure I fully understand what causes the workflow to not fire - the YAML ignores Markdown files and only looks for PR with `main` as the target, but whenever I run an action that changes the repo such as `CreateNewPerformanceTestApp`, `PullRequestHandler` also won't fire even through there are multiple new AL object files.
I'd prefer it if the status check always ran, while still ignoring changes to Markdown files - I at least need a successful test to get past the status requirement.

![image](https://user-images.githubusercontent.com/120664985/225922422-845b1a68-a992-4924-a28d-38b16f51ad38.png)

Edit: I noticed that PullRequestHandler finishes before CI/CD, so I realize that is another oversight. Of course, you could use the standard CI/CD workflow, but that just means any changes that don't trigger that workflow will be stuck.

**Comment by freddydk** [comment]
With the changes currently in preview, this should be fixed.
The PullRequestHandler will be responsible for the actual build.

**Comment by freddydk** [comment]
v3.0 has the new PullRequestHandler
