### ISSUE TITLE
Republish after upgrade

### ISSUE THREAD

**Issue by johngentile** [microsoft/AL-Go#444]
Hi, I'm brand new to GitHub and AL-Go.   Our Sandbox environment upgraded this morning. When trying to run the action "Publish to Environment", I get an error that an new version was already synchronized.  Typically, I make a code change, complete the pull request and the app is automatically published, so this is the first time I'm redeploying.  I've tried to run the action "Increment Version Number" which runs without error, but doesn't actually increment version number.  I've tried the action to "Create Release", and I see my repoVersion updating settings.json, but the version number still isn't updating on the published app.  Can you tell me what the sequence of events are to republish, or do I have to fake a change and complete a pull request to fire off the "CI/CD" action?  Thank you!

**Comment by freddydk** [comment]
Sorry for the delay in answering.
After modifying the version number you can run the CI/CD workflow to generate an app with the new version number.

**Comment by johngentile** [comment]
Hi Freddy, this doesn't synchronize the numbers everywhere.  The version number updates in the release name and the .AL-Go\Settings.json file, but the artifacts folder and app name inside the artifacts folder doesn't update.  Can you advise?

**Comment by freddydk** [comment]
This workshop step explains in details how versioning should work: https://github.com/microsoft/AL-Go/blob/main/Workshop/Versioning.md

and, when I run the increment version number - it creates a PR which changes all app.json files + the repoversion.
https://github.com/BusinessCentralApps/BingMaps.PTE/pull/233/files

Is this not what you see?
Did you only see the change in the .AL-Go/Settings.json file?

**Comment by freddydk** [comment]
The issue about not running the CI/CD and creating a new artifact after creating a release or incrementing the version number can be tracked in Issue #555
