### ISSUE TITLE
Feature Request: Rename workspace config to app name

### ISSUE THREAD

**Issue by cegekaJG** [microsoft/AL-Go#449]
The filename of the workspace config file remains `al.code-workspace`, even after the `Create a new App` action, which gets confusing fast when you often have to switch between multiple projects - they all are referred to as `al (Workspace)` in some views, like the welcome page of VS Code.
Since the app should be created before cloning the repository, there shouldn't be any reason not to rename the file.

**Comment by freddydk** [comment]
There is a work-item on this, which will be prioritized when time permits.
In the mean-time, you can just rename the file yourself - AL-Go will locate and update the workspace file even though it was renamed.
