### ISSUE TITLE
Warnings about non-existing app and test folders in preview

### ISSUE THREAD

**Issue by freddydk** [microsoft/AL-Go#451]
![image](https://user-images.githubusercontent.com/10775043/227125477-eda30494-a549-4e98-9b02-afa0f1972ea1.png)

https://github.com/freddydkorg/App1

Folders do exist.

**Comment by mazhelez** [comment]
@freddydk could this related to (and possibly fixed by) https://github.com/microsoft/AL-Go/pull/430

**Comment by freddydk** [comment]
This was caused by https://github.com/microsoft/AL-Go/pull/430
a -not is missing

**Comment by freddydk** [comment]
Shipped in v3.1
