### ISSUE TITLE
The "Runs-on" parameter in AL-Go-Settings triggers errors in "UpdateVersionNo" during action "Create Release"

### ISSUE THREAD

**Issue by janlehmkuhl** [microsoft/AL-Go#460]
**Repro Steps**

1) Create a repo like: https://github.com/ctmcomputer/AL-Go-PTE-Repro (There, you are welcome to take a closer look at the error)
2) Add "runs-on" parameter in AL-Go-Settings releated to any of your self-hosted runner tags.
3) Update AL-Go System Files
4) Create an "Hello World"-like App
5) Run and complete CI/CD
6) Create Release with default parameters

**Additional Information**
- I tried to fix this error by installing PowerShell 7 but it doesn't helped.
- It happens in all of our 48 AL-Go Repositories.

**Error**
IncrementVersionNumber action failed. Error: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified" Stacktrace: at CmdDo, C:\Windows\TEMP\c646f541-e565-41ce-9b5f-da7984adca30\BcContainerHelper\HelperFunctions.ps1: line 102 at invoke-gh, C:\Windows\TEMP\c646f541-e565-41ce-9b5f-da7984adca30\BcContainerHelper\Common\Invoke-gh.ps1: line 26 at CommitFromNewFolder, C:\CTMBuildAgent03-1\_work\_actions\microsoft\AL-Go-Actions\v3.0\AL-Go-Helper.ps1: line 1182 at <ScriptBlock>, C:\CTMBuildAgent03-1\_work\_actions\microsoft\AL-Go-Actions\v3.0\IncrementVersionNumber\IncrementVersionNumber.ps1: line 122 at <ScriptBlock>, C:\CTMBuildAgent03-1\_work\_temp\fd3df88d-b586-420d-86b6-d176fc8dcebd.ps1: line 2 at <ScriptBlock>, <No file>: line 1

**Log**
[UpdateVersionNumber_LogError.zip](https://github.com/microsoft/AL-Go/files/11137135/UpdateVersionNumber_LogError.zip)

**Comment by freddydk** [comment]
Your self-hosted runner needs to have GitHub CLI installed.
Please leave the issue open, we will produce a better error message explaining what you need to do.

Thanks

**Comment by freddydk** [comment]
You can find GitHub CLI here: https://cli.github.com/

**Comment by janlehmkuhl** [comment]
@freddydk Thank you very much. After installing the CLI and restarting all build agents, the release is now working again.
