### ISSUE TITLE
Incorrect AppSource delivery despite 'appSourceContinuousDelivery' set to false

### ISSUE THREAD

**Issue by janlehmkuhl** [microsoft/AL-Go#461]
**Description**
Our app is always delivered to the AppSource, even though the "appSourceContinuousDelivery" parameter is set to false.

**Logs**
[Rent_DeliverToAppSourceLog.zip](https://github.com/microsoft/AL-Go/files/11137595/Rent_DeliverToAppSourceLog.zip)

**Comment by mazhelez** [comment]
@janlehmkuhl Is the issue the same or similar to https://github.com/microsoft/AL-Go/issues/451

If so, please close the current one as duplicate and mention your findings in the original one.

**Comment by janlehmkuhl** [comment]
@mazhelez Part of the problem is addressed in #451, I agree with you on that. The second part of my issue, however, is that our app is constantly being delivered to the AppSource even though the "appSourceContinuousDelivery" parameter is set to false. I will remove the part of the problem related to #451 from this issue.

**Comment by freddydk** [comment]
@janlehmkuhl - please share your .AL-Go\settings.json here, thanks.

**Comment by freddydk** [comment]
@janlehmkuhl could it be that you have set the AppSourceContinuousDelivery to "false" instead of false.
i.e. a string instead of a boolean?
