### ISSUE TITLE
Cache specific artifact for self-hosted agent?

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#474]
From the "Create build container" task log of a DevOps build pipeline:

`Using artifactUrl https://bcartifacts.azureedge.net/onprem/19.0.29894.30693/us`

Can we use the two Powershell lines 

$artifacturl = Get-BCArtifactUrl -country "us" -version '19.0.29894.30693'
New-BcImage -artifactUrl $artifactUrl -imageName BCCloud:latestBC

on the agent host machine to cache the image for this container build? And if so, what would be the correct -imagename parameter value?

**Comment by freddydk** [comment]
On self-hosted agents, AL-Go for GitHub will automatically cache images.
If you create a setting called 

"artifact": "https://bcartifacts.azureedge.net/onprem/19.0.29894.30693/us"

then AL-Go will always use this version and thus cache a docker image.

**Comment by buzzwick** [comment]
Thanks, that will apply once we move some of these to the AL-Go platform. Is there an equivalent for a DevOps yaml pipeline that would feed into the BCContainerHelper settings?

**Comment by freddydk** [comment]
Sorry for the late reply - on DevOps, if you are managing your own scripts, you would just hardcode the artifacts and add -imagename 'my' to the New-BcContainer, then it will cache the image.
