### ISSUE TITLE
Issue with deployment step ind CICD Action

### ISSUE THREAD

**Issue by MartinFellow** [microsoft/AL-Go#476]
Hi. 
Not sure what the issues is caused by, but after opdating the AL-Go to version 3.0 all our CICD pipelines fails. 
![image](https://user-images.githubusercontent.com/106743383/232581720-55fe47cd-9afa-4b03-8517-b85f65a8cf09.png)

I suspect that the error has something to do with the two messages below. 
Because the Initialize stage shows this in the "complete job"
![image](https://user-images.githubusercontent.com/106743383/232582139-5c38664e-998b-45c0-a973-9d1640987cf0.png)

We do not have github "real" environments, but are using the settings.json in the AL-Go. And secrets for the authcontext and environmentname. 
It worked with version 2.4 of AL-Go.

I'll be happy to provide any other information.

**Comment by MartinFellow** [comment]
So this is my settings.json in the al-go folder
![image](https://user-images.githubusercontent.com/106743383/234290912-e5867eca-b600-4231-b22a-4f0cb80c8669.png)

And this is my project secrets:
![image](https://user-images.githubusercontent.com/106743383/234291419-2a55be16-5393-4c8d-b267-b8543f40c6b1.png)

And i can do a manual deployment afterwards, with the action for that and the point to DEV og TEST and that works. 
Thanks

**Comment by freddydk** [comment]
What is the value of the EnvironmentName secrets (is that Dev, Prod and Test)?

**Comment by MartinFellow** [comment]
Its: "Udvikling", "Production" og "Test"
No quotes off course

**Comment by freddydk** [comment]
Try to remove the 3 environment name secrets and create these settings:
"DeployToDev": {
    "EnvironmentName":  "Udvikling"
},
"DeployToProd": {...

etc.

**Comment by MartinFellow** [comment]
That worked, so we will just use this going forward, great help thanks.

Sorry for posting a question in this, but if you have a short answer it would be a great help. 
Is it possible to make the ci/cd action only post to sandboxes and not the production as well?

**Comment by freddydk** [comment]
The CD action will not deploy to production - it will discover that it is a prod environment and abandon.
If you add (Production) to the environment name in the environments setting - (like "PROD (Production)") then it will never create a job for that.

**Comment by MartinFellow** [comment]
My bad i missed that it was actually skipped, just saw it all ran green on the deployment. 
Thanks alot for the help and the great product that al-go for github is for us!
