### ISSUE TITLE
Error: IncrementVersionNumber action failed. Error: Settings file .\.AL-Go\settings.json is malformed.  Cannot bind argument to parameter 'object' because it is null.. Stacktrace: at <ScriptBlock>

### ISSUE THREAD

**Issue by DanielMagMat** [microsoft/AL-Go#477]
I am stucked at creating a release. I have followed workshop, videos and resolution of similar issues #352  . But I do not seem to find the answer to my issue. Maybe a bug, Am I missing something?

Help appreciated.

Getting this error:

Error: IncrementVersionNumber action failed. Error: Settings file .\.AL-Go\settings.json is malformed.  Cannot bind argument to parameter 'object' because it is null.. Stacktrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\IncrementVersionNumber\IncrementVersionNumber.ps1: line 89 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\IncrementVersionNumber\IncrementVersionNumber.ps1: line 61 at <ScriptBlock>, D:\a\_temp\0d13274b-fec2-469c-9d68-815f7ea71e88.ps1: line 2 at <ScriptBlock>, <No file>: line 1

**Comment by jonaswre** [comment]
Hi, it seems like you settings json correctly formated.

From experience it's most often a , in the last property. If you can't find the issue. It would be helpful to see the settings.json.

**Comment by DanielMagMat** [comment]
It is a one app project.
I leave you the code in the settings.json file:

`
{
  "country": "mx",
  "appFolders": [],
  "testFolders": [],
  "bcptTestFolders": [],
  "insiderSasTokenSecretName": "InsiderSasToken",
  "licenseFileUrlSecretName": "LicenseFileUrl",
  "configPackages": ["STANDARD"],
  "doNotRunBcptTests": true
}
`

**Comment by freddydk** [comment]
What are you entering as new version number?

**Comment by jonaswre** [comment]
Okay, your json is valid. I've found an oddity.

https://github.com/microsoft/AL-Go/blob/b90607c6ca55e8d764a1723ca93774858197da7c/Actions/IncrementVersionNumber/IncrementVersionNumber.ps1#L89

Error Message Template:
`Settings file $project\$ALGoSettingsFile is malformed`

Your Error Message:
`Settings file ..AL-Go\settings.json is malformed`

This lets me to the conclusion you have specified the wrong project. 
The error message should be `Settings file .\.AL-Go\settings.json is malformed`

**Comment by DanielMagMat** [comment]
@freddydk I have tried with +0.1, 1.1, +0.2, 1.2

I have used Preview Al Go and Current. I have tried only using IncrementVersionNumber Workflow with same results.

**Comment by DanielMagMat** [comment]
Last run did indeed prompted

`IncrementVersionNumber action failed. Error: Settings file .\.AL-Go\settings.json is malformed.  Cannot bind argument to parameter 'object' because it is null.. Stacktrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\IncrementVersionNumber\IncrementVersionNumber.ps1: line 89 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\IncrementVersionNumber\IncrementVersionNumber.ps1: line 61 at <ScriptBlock>, D:\a\_temp\27af9152-6953-4ed4-8234-e21e780b42a5.ps1: line 2 at <ScriptBlock>, <No file>: line 1`

**Comment by freddydk** [comment]
Any chance you could add me to the repo, so that I can have a look?
My GitHub username is freddydk.

Thanks

**Comment by freddydk** [comment]
The repo you invited me to is empty???

**Comment by DanielMagMat** [comment]
I am sorry I invited you to wrong repo. I have now corrected that and send you right invite.

**Comment by freddydk** [comment]
You have an empty line in the beginning of the settings file - try to remove that.
![image](https://user-images.githubusercontent.com/10775043/234538899-ce8907c5-759f-479c-a0d3-c9d1f3a667eb.png)

The InitializeWorkflow actually should check all settings files for validity and report whether or not they are valid, but apparently there is a bug in that, which causes it to skip the test - will fix that.

**Comment by DanielMagMat** [comment]
This indeed resolved the issue. Thanks very much @freddydk !
