### ISSUE TITLE
Narrative description of the build/release cycle

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#478]
Relating to https://github.com/microsoft/AL-Go/blob/main/Workshop/Releasing.md

The meaning of the yellow arrows in the branching diagram is not clear, and is not explained until the end of the article. I read the yellow arrows in the diagram to mean that Release/1.0 leads to Hotfix 1.0.x, Hotfix 1.0.x leads to Hotfix 1.0.y, and Release/1.0, Hotfix 1.0.x, and Hotfix 1.0.y are eventually merged into the main branch. This is probably not correct. An expert denizen of GitHub might possibly interpret them correctly, but a novice user has no way of knowing what they actually mean--and even when they have read through the entire article, they still have to draw their own conclusions about what they mean.
	
After reading over the article several times, I think the yellow arrows are indicating something like 
	

> "once created as a release, Release/1.0 will serve as the 'previous release' for Hotfix 1.0.x, and once made into a release, Hotfix 1.0.x will serve as the 'previous release' for Hotfix 1.0.y. Similarly, Release/1.0 will serve as the 'previous release' for the build merging Feature/B into main, and Hotfix 1.0.x will serve as the 'previous release' for the build merging Feature/C into main, and so on."

All of this is _indicated_ by "After the build is completed, you will need to release this new build in order for CI/CD to see the new bits as a release," but since this is the last thing to appear in the segment it is not available to aid in the interpretation of the diagram, and its full significance is easily missed. My suggestion would be to add, immediately after the diagram, something like
	
	"The diagram illustrates the following build-release cycle:
	
		○ When Release/1.0 is created as a release using the Create Release action, the major version of each app in the main branch is incremented to 2.0.  "2.0" is  also stored in the project Settings file as repoversion. The repoversion number is used to stamp the artifacts (i.e., zip files) produced by subsequent builds of the main branch. 
		
		○ When the feature branch Feature/B is merged into main, Release/1.0 is used as the 'previous release' for that build of the main branch. Major version of the apps is not incremented for that build, but build and revision numbers are, automatically, by the workflow.
		
		○ Similarly, when Hotfix 1.0.x is merged into the Release/1.0 release branch, Release/1.0 is also used as the "previous release." Hotfix 1.0.x must then be made into a release using the Create Release action. This will make it available as the 'previous release' for both the build merging feature branch Feature/C into main and the build merging Hotfix 1.0.y into the release branch Release/1.0.
		
		○ When major version 2.0 is made into a new release, the *minor* version of each app in the main branch is incremented by 1. [Question: Why is only the minor version incremented here, and not the major version as when Release/1.0 was made into a release?].
		
		○ Release/2.0 subsequently serves as the 'previous release' for Hotfix 2.0.z, and for the build that merges feature branch Feature/D into the main branch.
		
		○ And so on down the line…"
		
This may seem like overkill, but (assuming my interpretation is accurate) it provides a narrative complement to the more telegraphic diagram, screenshots, and annotations. All of those are clear and correct, but very challenging for the novice to decode and synthesize. Novice users really benefit from having both. 
	
One other suggestion: the annotation
	
	"This build of the release branch will use the 'latest released build, which has a version number lower than the one you are building as previous release and will use the version numbers from the release branch for versioning" 
	
took several readings to properly parse out. It might be clearer to say
	
	This build of the release branch, incorporating the hotfix, will increment the build/revision numbers of the release branch itself and apply them to the app files in the release branch. It will use the project release tagged "latest" as the "previous release" for purposes of checking for breaking changes etc. during the build. That project release tagged "latest" will by definition have a lower build/revision number than this current build of the release branch.

**Comment by freddydk** [comment]
Thanks David, will add this to the description.
