### ISSUE TITLE
CI/CD fails with "The property 'ClientServicesCredentialType' cannot be found on this object."

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#494]
Trying to update the AL-Go Settings file, to add appDependencyProbingPaths and its associated JSON values. This is in a repository in which we just added a dependency to an app in another repo in this organization. Cannot find where the Action is looking for ClientServicesCredentialType.

un microsoft/AL-Go-Actions/RunPipeline@v3.0
Run try { D:\a\_actions\microsoft\AL-Go-Actions\v3.0\RunPipeline/RunPipeline.ps1 -actor $ENV:_actor -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -project $ENV:_project -projectDependenciesJson $ENV:_projectDependenciesJson -settingsJson $ENV:_settingsJson -secretsJson $ENV:_secretsJson -buildMode $ENV:_buildMode } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 4.0.16
BC.HelperFunctions emits usage statistics telemetry to Microsoft
use settings and secrets
Analyzing repository
Checking project dependencies
Checking appDependencyProbingPaths
Dependency to projects 'CAI Software Precious Metals Solution' in https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution@main, version latest, release status include
Using token as AuthTokenSecret
Warning: Dependencies with release_status 'include' must be to other projects in the same repository.
Warning: No performance test apps found in bcptTestFolders in .AL-Go\settings.json
Warning: No test apps found in testFolders in .AL-Go\settings.json
Project: 
Downloading dependencies
Locating previous release
Invoke Run-AlPipeline with buildmode Default
Parameters
Creating container
Resolving dependencies
Compiling apps
Removing container
Run-AlPipeline Telemetry Correlation Id: ab8c532d-2054-4144-8b15-e1a3d6a2c746
Error: RunPipeline action failed. Error: The property 'ClientServicesCredentialType' cannot be found on this object. Verify that the property exists. Stacktrace: at Compile-AppInBcContainer, C:\Users\runneradmin\AppData\Local\Temp\b497b599-8561-4e63-ade5-9b913ba10fdb\BcContainerHelper\AppHandling\Compile-AppInNavContainer.ps1: line 475 at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\b497b599-8561-4e63-ade5-9b913ba10fdb\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 710 at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\b497b599-8561-4e63-ade5-9b913ba10fdb\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1752 at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\b497b599-8561-4e63-ade5-9b913ba10fdb\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1326 at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\b497b599-8561-4e63-ade5-9b913ba10fdb\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1319 at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\b497b599-8561-4e63-ade5-9b913ba10fdb\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 826 at Run-AlPipeline, C:\Users\runneradmin\AppData\Local\Temp\b497b599-8561-4e63-ade5-9b913ba10fdb\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 788 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v3.0\RunPipeline\RunPipeline.ps1: line 367 at <ScriptBlock>, D:\a\_temp\a9aa7c19-c5a9-442d-a800-b514119dcc59.ps1: line 2 at <ScriptBlock>, <No file>: line 1
AL-Go action ran: RunPipeline Telemetry Correlation Id: 538c9084-8245-4e23-bc4f-da4ff6fc3125
Get Event Log from container
Getting event log for bc4822476658
Removing BcContainerHelper
Error: Process completed with exit code 1.

**Comment by freddydk** [comment]
This is a bug in ContainerHelper (will fix that)

But you run into this because your appDependencyProbingPath setting couldn't resolve the dependency.
1. the release_status include can only be used for other projects in the same repo.
2. you didn't specify an AuthTokenSecret in your settings (which is needed when adding a dependency to a private repo).
3. you specified a project name, but the repo referenced only has one project (i.e. the .AL-Go folder is in the root)

I took the liberty of modifying the settings and kicked off a build, which seems to succeed.
