### ISSUE TITLE
UpdateSystemFiles fails

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#497]
I have a schedule that updates system files once a week. 

The latest updates failed with the following error.

Error: CheckForUpdates action failed. Error: The property 'CurrentSchedule' cannot be found on this object. Verify that the property exists. Stacktrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\CheckForUpdates\CheckForUpdates.ps1: line 181 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\CheckForUpdates\CheckForUpdates.ps1: line 162 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\CheckForUpdates\CheckForUpdates.ps1: line 153 at <ScriptBlock>, D:\a\_temp\42b94f56-91a7-4a74-9704-f17c81a78c4d.ps1: line 2 at <ScriptBlock>, <No file>: line 1

My repo settings contain a currentSchedule entry that used to work. 

Maybe a capitalization error was introduced again?

**Comment by freddydk** [comment]
You are right - another one of these.
I will fix asap and then add a todo to see if I can add a test, which ensures that this doesn't happen again.

**Comment by freddydk** [comment]
Shipped in v3.1
