### ISSUE TITLE
Action Create a new app - app.json require changes

### ISSUE THREAD

**Issue by bc4all** [microsoft/AL-Go#501]
Hi Freddy,

I would like to ask you to update the app.json in that is created in action Create a new app.

Below are needed updates:
**application:** 
**Current value:**  "application": "19.0.0.0",
**Expected value:**  "application": "22.0.0.0",

**features:**
**Current value:** missing
**Expected value:** "features": ["NoImplicitWith"]

Those two are changes that every time need to be modify in the app.json file.

Best regards,
Krzysztof

**Comment by freddydk** [comment]
Fixed in v3.1
