### ISSUE TITLE
App unexpectedly included in artifacts zip file

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/AL-Go#505]
PTE apps

the settings.json "appFolders" only contains a single folder name.
al.code-workspace file contains two apps, test app and the performance test app.

Apps.zip file contains both apps from al.code-workspace.
TestApps.zip file contains only the test app, not performance test app.

I expected that by specifying only one app in "appFolders" the build process would ignore the other one.
I am using the "other" app to do manual testing on the "primary" app.

**Comment by freddydk** [comment]
I would expect that as well.
Any chance you can add me to the repo so I can see what happened?

**Comment by freddydk** [comment]
Download the logs and send them to me together with your settings files maybe
