### ISSUE TITLE
Error: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop

### ISSUE THREAD

**Issue by ivanrlg** [microsoft/AL-Go#507]
Hello Freddy,

I'm getting this error, I don't know if I'm doing something wrong.

This is an AppSource App.

Running BCPT tests
    _____                   _               ____   _____ _____ _______   _            _       
   |  __ \                 (_)             |  _ \ / ____|  __ \__   __| | |          | |      
   | |__) |   _ _ __  _ __  _ _ __   __ _  | |_) | |    | |__) | | |    | |_ ___  ___| |_ ___ 
   |  _  / | | | '_ \| '_ \| | '_ \ / _` | |  _ <| |    |  ___/  | |    | __/ _ \/ __| __/ __|
   | | \ \ |_| | | | | | | | | | | | (_| | | |_) | |____| |      | |    | ||  __/\__ \ |_\__ \
   |_|  \_\__,_|_| |_|_| |_|_|_| |_|\__, | |____/ \_____|_|      |_|     \__\___||___/\__|___/
                                     __/ |                                                    
                                    |___/                                                     
  Using CompanyName CRONUS USA, Inc.
  Invoke GET on http://172.20.76.160:7048/BC/api/v1.0/companies?$filter=name%20eq%20'CRONUS%20USA%2C%20Inc.'&tenant=default
  Using Company ID 31903fb8-d0e9-ed11-884e-6045bdaca768
  Invoke POST on http://172.20.76.160:7048/BC/api/Microsoft/PerformancToolkit/v1.0/companies(31903fb8-d0e9-ed11-884e-6045bdaca768)/bcptSuites?tenant=default
  Using testpage 149002
  Using Suitecode 10UserTest
  Service Url http://bc4876371986/BC/cs/?tenant=default&company=CRONUS%20USA%2C%20Inc.
  Running Performance Tests for 5 minutes...
  Running performance test failed
  The passed path for -BCPTTestRunnerInternalFolderPath seem to be relative path, converting to absolute.
  Absolute path is C:\ProgramData\BcContainerHelper\extensions\bc4876371986\my\TestRunner\Internal
  Importing AL Test Runner from C:\ProgramData\BcContainerHelper\extensions\bc4876371986\my\TestRunner\Internal\BCPTTestRunnerInternal.psm1
  WARNING: The names of some imported commands from the module 'ALTestRunnerInternal' include unapproved verbs that might
   make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the 
  Verbose parameter. For a list of approved verbs, type Get-Verb.
Removing container
Run-AlPipeline Telemetry Correlation Id: c274c49e-5068-42d6-a5fe-67988c3860e9
Error: RunPipeline action failed. Error: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: At C:\ProgramData\BcContainerHelper\extensions\bc4876371986\my\TestRunner\Internal\AadTokenProvider.ps1:59 char:35 + ... edential = [Microsoft.IdentityModel.Clients.ActiveDirectory.UserPassw ... +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Unable to find type [Microsoft.IdentityModel.Clients.ActiveDirectory.UserPasswordCredential]. Stacktrace: at <ScriptBlock>, C:\ProgramData\BcContainerHelper\extensions\bc4876371986\my\TestRunner\Internal\BCPTTestRunnerInternal.psm1: line 295 at <ScriptBlock>, C:\ProgramData\BcContainerHelper\extensions\bc4876371986\my\TestRunner\RunBCPTTests.ps1: line 237

**Comment by freddydk** [comment]
Currently we are having issues running BCPT tests on 22.
A fix is needed in the artifacts, but I have a workaround which will ship in ContainerHelper one of the next days.
Until then, you can set "doNotRunBcptTests": true in settings.

https://aka.ms/algosettings#donotrunbcpttests
