### ISSUE TITLE
Deliver to AppSource fails

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#508]
@freddydk  there seems to be another issue. 

```Deliver action failed. Error: The property 'string resourceType=Dynamics365BusinessCentralPackageConfiguration' cannot be found on this object. Verify that the property exists. Stacktrace: at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\bd86172d-a0bd-4bbf-8e7d-60d708d4619e\BcContainerHelper\Common\ConvertTo-HashTable.ps1: line 29 at ConvertTo-HashTable, C:\Users\runneradmin\AppData\Local\Temp\bd86172d-a0bd-4bbf-8e7d-60d708d4619e\BcContainerHelper\Common\ConvertTo-HashTable.ps1: line 28 at New-AppSourceSubmission, C:\Users\runneradmin\AppData\Local\Temp\bd86172d-a0bd-4bbf-8e7d-60d708d4619e\BcContainerHelper\AppSource\New-AppSourceSubmission.ps1: line 183 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\Deliver\Deliver.ps1: line 452 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\Deliver\Deliver.ps1: line 99 at <ScriptBlock>, D:\a\_temp\d271be55-709e-4fc2-b374-5dc005a3ac51.ps1: line 2 at <ScriptBlock>, <No file>: line 1```

**Comment by freddydk** [comment]
Will check asap

Sendt fra Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Jonas Wrede ***@***.***>
Sendt: Thursday, May 4, 2023 9:26:15 AM
Til: microsoft/AL-Go ***@***.***>
Cc: Freddy Kristiansen ***@***.***>; Mention ***@***.***>
Emne: [microsoft/AL-Go] Deliver to AppSource fails (Issue #508)


@freddydk<https://github.com/freddydk> there seems to be another issue.

Deliver action failed. Error: The property 'string resourceType=Dynamics365BusinessCentralPackageConfiguration' cannot be found on this object. Verify that the property exists. Stacktrace: at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\bd86172d-a0bd-4bbf-8e7d-60d708d4619e\BcContainerHelper\Common\ConvertTo-HashTable.ps1: line 29 at ConvertTo-HashTable, C:\Users\runneradmin\AppData\Local\Temp\bd86172d-a0bd-4bbf-8e7d-60d708d4619e\BcContainerHelper\Common\ConvertTo-HashTable.ps1: line 28 at New-AppSourceSubmission, C:\Users\runneradmin\AppData\Local\Temp\bd86172d-a0bd-4bbf-8e7d-60d708d4619e\BcContainerHelper\AppSource\New-AppSourceSubmission.ps1: line 183 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\Deliver\Deliver.ps1: line 452 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\Deliver\Deliver.ps1: line 99 at <ScriptBlock>, D:\a\_temp\d271be55-709e-4fc2-b374-5dc005a3ac51.ps1: line 2 at <ScriptBlock>, <No file>: line 1

**Comment by jonaswre** [comment]
FYI - I have this in all "Publish to AppSource" Actions not just in a single repo.

**Comment by freddydk** [comment]
This bug is in the containerhelper preview.
A fix is on it's way.
Thanks for reporting.

**Comment by freddydk** [comment]
A new ContainerHelper preview has been shipped - it should work now.

**Comment by jonaswre** [comment]
Can confirm. It works again.
