### ISSUE TITLE
Self-hosted runner error when no direct commit

### ISSUE THREAD

**Issue by amunoz-ldr** [microsoft/AL-Go#512]
Hi,

I have a problem running actions on our own servers (self-hosted runners). For example, the action “Create new APP”, if it runs on a github runner, works perfectly both with direct commit and without it, however if I configure it to run on my own server ( self-hosted) only works if I allow direct commit, but it doesn't work if I don't, the error is as follows:

`Error: CreateApp action failed. Error: Excepción al llamar a "Start" con los argumentos "0": "El sistema no puede encontrar el archivo especificado" Stacktrace: en CmdDo, C:\Users\AdminGH01\AppData\Local\Temp\3e6829b8-9d92-4a19-b469-ecc32d31cf6b\BcContainerHelper\HelperFunctions.ps1: línea 102 en invoke-gh, C:\Users\UserName\AppData\Local\Temp\3e6829b8-9d92-4a19-b469-ecc32d31cf6b\BcContainerHelper\Common\Invoke-gh.ps1: línea 26 en CommitFromNewFolder, C:\actions-runner\liderit-estandard\_work\_actions\microsoft\AL-Go-Actions\v3.0\AL-Go-Helper.ps1: línea 1182 en <ScriptBlock>, C:\actions-runner\liderit-estandard\_work\_actions\microsoft\AL-Go-Actions\v3.0\CreateApp\CreateApp.ps1: línea 135 en <ScriptBlock>, C:\actions-runner\liderit-estandard\_work\_temp\e32c1507-a6c8-4575-b7bb-4ed22f7c11ea.ps1: línea 2 en <ScriptBlock>, <sin archivo>: línea 1`

The error in Spanish could be translated as “Exception calling "Start" with arguments "0": "The system cannot find the file specified" Stacktrace: on CmdDo”.

Any idea about what is going wrong?
Thank you
Alejandro.

**Comment by freddydk** [comment]
Likely because you do not have GitHub CLI installed on your self-hosted runner?

**Comment by amunoz-ldr** [comment]
That was all, sorry and thank you so much
