### ISSUE TITLE
Deploy to Environment fails on Unauthorized

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#517]
Our deployment workflows have started failing with credential errors--see output below. I have updated the AUTHCONTEXT secrets for both of our environments according to [this doc page](https://github.com/microsoft/AL-Go/blob/main/Scenarios/RegisterSandboxEnvironment.md), without success. Not that any of the secrets we created originally show as having expired yet. Can you shed light on

a) which set of credentials (i.e., under which Secret in the GitHub repository) needs updating. Would this be the AUTHCONTEXT repo secret, or the AZURE_CREDENTIALS org secret? How would we know?

b) the doc page above is a little short on detail as to how the ingredients of AUTHCONTEXT are created (it says "from the pre-requisites," the prerequisites refer out to Microsoft docs about S2S which are equally minimal).  If you can elaborate a little, I will modify the doc accordingly once I have tested it out.

Run microsoft/AL-Go-Actions/Deploy@v2.4
Run try { D:\a\_actions\microsoft\AL-Go-Actions\v2.4\Deploy/Deploy.ps1 -actor $ENV:_actor -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -projects $ENV:_projects -environmentName $ENV:_environmentName -artifacts $ENV:_artifacts -type $ENV:_type } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 4.0.16
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Analyzing artifacts
https://api.github.com/repos/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/artifacts?per_page=100&page=1
project '*'
Analyzing artifacts
https://api.github.com/repos/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/artifacts?per_page=100&page=1
project '*'
https://api.github.com/repos/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/artifacts?per_page=100&page=2
project '*'
Downloading artifact CAI-Software-Precious-Metals-Solution-main-Apps-21.8.92.0
https://api.github.com/repos/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/artifacts/682406183/zip
Apps to deploy
D:\a\CAI-Software-Precious-Metals-Solution\CAI-Software-Precious-Metals-Solution\.artifacts\CAI-Software-Precious-Metals-Solution-main-Apps-21.8.92.0.zip
Attempting authentication to https://api.businesscentral.dynamics.com/.default using clientCredentials...
Authenticated as app ***
https://businesscentral.dynamics.com/***/QA/deployment/url
Using S2S, publishing apps using automation API
ERROR The remote server returned an error: (401) Unauthorized.
Publish-PerTenantExtensionApps Telemetry Correlation Id: 7e1[95](https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/runs/4915588727/jobs/8778313860#step:7:96)6b1-0ae4-4225-9a7e-19f1e5f988c7
Error: Deploying to QA failed.  The remote server returned an error: (401) Unauthorized. Unauthorized {"error":{"code":"Authentication_InvalidCredentials","message":"The server has rejected the client credentials.  CorrelationId:  b50a520f-7f8b-4e02-8292-1b459dc08127."}} (ms-correlation-x = 6062de2c-caa0-7a2c-4349-8a6c1c723684)
Removing BcContainerHelper
Error: Process completed with exit code 1.

**Comment by freddydk** [comment]
AZURE_CREDENTIALS gives access to your Azure Subscription (your keyvault basically).
AUTHCONTEXT is the authcontext for Business Central.
Error: Deploying to QA failed. The remote server returned an error: (401) Unauthorized. Unauthorized {"error":{"code":"Authentication_InvalidCredentials","message":"The server has rejected the client credentials. CorrelationId: b50a520f-7f8b-4e02-8292-1b459dc08127."}} (ms-correlation-x = 6062de2c-caa0-7a2c-4349-8a6c1c723684)

Is the AppId created in the AAD App Registration inside BC (and enabled + have D365 AUTOMATION permissions)?

**Comment by freddydk** [comment]
If your AUTHCONTEXT is using impersonation, you don't need an AAD app.
Use ContainerHelper and run:
`New-BcAuthContext -includeDeviceLogin | New-ALGoAuthContext | Set-Clipboard`
Then you should have your secret in the clipboard after authenticating.

**Comment by buzzwick** [comment]
Aha! I remember that command, and that sequence. I just could not remember where it came from or what (out of the bazillion different paths through all this) initiated it. I have archived it for future reference, thank you!

I also replaced the existing AUTHCONTEXT secrets with the output from New-BcAuthContext, and Deploy To Environment now works. Thanks again! BTW--are these the secrets that expire after 90 days?

Here is the part that I do not understand: I run the PowerShell Terminal in VSCode, and run this command. It seems anonymous, in that it does not take an Environment as a parameter. And yet it correctly identifies our tenant id for the token.  Is this because it knows who I am (because it asks me) and knows that I have access to that tenant (as recorded in AAD)?

I will look into user impersonation for more background.

**Comment by freddydk** [comment]
> Here is the part that I do not understand: I run the PowerShell Terminal in VSCode, and run this command. It seems anonymous, in that it does not take an Environment as a parameter. And yet it correctly identifies our tenant id for the token. Is this because it knows who I am (because it asks me) and knows that I have access to that tenant (as recorded in AAD)?

It initiates a device login and when you login, I can see which tenant the user belongs to.

What we store is the refreshtoken, which is valid for 90 days. We might add a feature in the future which automatically cycles these tokens and refreshes the refreshtoken - but that is in the backlog.
https://github.com/orgs/microsoft/projects/521/views/1?filterQuery=refreshto&pane=issue&itemId=13518504
or
https://github.com/orgs/microsoft/projects/521/views/1?filterQuery=refreshto&pane=issue&itemId=20939181
