### ISSUE TITLE
Deploying to onprem environment

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#519]
Hey @freddydk , 

Is it possible to deploy to onprem environment using AL-GO? (i think i know the answer already :))

Normally, we would use cloud sanbox environments for testing. But for some customers, who are not on SAAS yet and have some strict requirements with 3party integrations, we are forced to have test environment onprem. Therefore, we would like to use AL-GO deploy to onprem environment.

Installing _actions-runner_ is not an issue, and we already did, but it seems that it's not possible to define runner used for deploy step, plus _Publish-PerTenantExtensionApps.ps1_ is designed to work with saas environments only.

Do you have any plans to support onprem deployments? How would you advise to implement onprem deployments?

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
It actually should be possible to specify which runner to use for a specific environment, but it would require some changes to make this work with on-premises.
You are not the first to ask - let me think about whether there is an easy way around this.

**Comment by jonaswre** [comment]
I had this request from customers and partner awell.

**Comment by gntpet** [comment]
I looked around the code & see two changes that are required so far:

1. Ability to specify runner name for DeployTo... step. Currently, you can change runner, but it applies for all steps.
2. Specify AuthContext for onprem environment. You authcontext is tailored for SaaS only.

**Comment by freddydk** [comment]
The 1st part of this is possible today, by specifying. If your GitHub environment name is QA:

```
"DeployToQA": {
  "runs-on": "specialrunner"
}
```

The 2nd part is missing. I assume that you can get to the secrets on your runner - but claiming that this is supported is a stretch,

We could also investigate supporting ALOps.ExternalDeployer directly from AL-Go.
https://www.waldo.be/2020/06/15/deploying-from-devops-the-right-way-enabling-external-deployment-in-onprem-business-central-environments/

**Comment by curateideas** [comment]
I made an on-prem deployment work in a prototype environment with a custom deploy script yesterday. Works like charm!

Same process for SaaS and on-prem customers that need a two-step strategy to the cloud.

**Comment by freddydk** [comment]
Thanks for the heads-up

**Comment by nixpt82** [comment]
> I made an on-prem deployment work in a prototype environment with a custom deploy script yesterday. Works like charm!
> 
> Same process for SaaS and on-prem customers that need a two-step strategy to the cloud.

@curateideas can you share a example?

**Comment by curateideas** [comment]
@nixpt82 , I used these settings 

![image](https://github.com/microsoft/AL-Go/assets/58227881/b4a30fa8-6271-407c-81b9-c93e44b19f8e)

I created a VM with BC 22.5 on-prem and installed a self-hosted runner that has a dedicated tag "on-prem":

![image](https://github.com/microsoft/AL-Go/assets/58227881/df14ad1d-c88a-4812-9e21-9be8c402cf30)

This runner executes a custom PS-Script as mentioned in the documentation.

![image](https://github.com/microsoft/AL-Go/assets/58227881/ce6a41d3-9588-486b-966a-5a2bf1fed6da)

With this script we copy the artifact to a specific folder structure and execute a custom CmdLet that installs the app-file in the database:


```
Param(
    [Parameter(HelpMessage = "Parameters", Mandatory = $true)]
    [hashtable] $parameters
)
$EnvironmentName = $parameters.EnvironmentName

$deployAppsPath = 'C:\Deploy\DeployOnPrem\CustomApps'

Write-Host "Deploying to $EnvironmentName"
$deployApps = $parameters.apps
Write-Host "Cleaning up deployment folder"
Remove-item -Path ($deployAppsPath + '\*.*') -Recurse -Force
Write-Host "Move to deployment folder: $deployApps"
Move-Item -Path $deployApps -destination $deployAppsPath
Write-Host "Expanding artifacts"
$deployArtifacts = Get-ChildItem -Path $deployAppsPath -Filter '*.zip'
foreach ($deployArtifact in $deployArtifacts)
{
    Expand-Archive -Literalpath $deployArtifact.FullName -destination $deployAppsPath -Force
}

# Import custom Deployment Tools

Write-Host "Install or update Apps"
# execute Install CmdLet
```

**Comment by frottke** [comment]
Hi @curateideas,

does your example include an AUTHCONTEXT secret for the onprem environment? We have currently the challenge that we want to use the custom deployto feature ,it seems that an **valid** AUTHCONTEXT is needed for an onprem deployment. That seems to be weird. 

Do you have an workaround?

**Comment by curateideas** [comment]
Hi @frottke ,

yes, I created a repo-secret named "ONPREM_AUTHCONTEXT" that the deployment pipeline could find. It contains the JSON-structure like Saas-AuthContexts but with dummy-values that I don't use. Important thing is to name it [OnPremEnvironmentName]_AUTHCONEXT.

The user that's running the self-hosted runner is configured to be able to publish apps in the OnPrem-Database and the machine that hosts the runner also hosts a dedicated Service Tier for deployments.

**Comment by frottke** [comment]
Hi @curateideas,

thanks for your input. Works like a charm!

**Comment by RasmusAaenDev** [comment]
> @nixpt82 , I used these settings
> 
> ![image](https://private-user-images.githubusercontent.com/58227881/272882894-b4a30fa8-6271-407c-81b9-c93e44b19f8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzI4MDUsIm5iZiI6MTcxODE3MjUwNSwicGF0aCI6Ii81ODIyNzg4MS8yNzI4ODI4OTQtYjRhMzBmYTgtNjI3MS00MDdjLTgxYjktYzkzZTQ0YjE5ZjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA2MDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MTI5NGFjNDhiZTMyNmNiYTk4ZGExMmI1Yzc2NGE0MzQyMThlZDYxNzIwMjA1ZWEwYmIxODRmNzU5Y2YwMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PXSlIp993VAGTceVoC0LGIP6Q9KGUW0UOFveIBh1d68)
> 
> I created a VM with BC 22.5 on-prem and installed a self-hosted runner that has a dedicated tag "on-prem":
> 
> ![image](https://private-user-images.githubusercontent.com/58227881/272884019-df14ad1d-c88a-4812-9e21-9be8c402cf30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzI4MDUsIm5iZiI6MTcxODE3MjUwNSwicGF0aCI6Ii81ODIyNzg4MS8yNzI4ODQwMTktZGYxNGFkMWQtYzg4YS00ODEyLTllMjEtOWJlOGM0MDJjZjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA2MDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNGEzYzFlN2M5Y2E0ZDM5OWM0YzA1NzViNzdjZjhkYzdhNDJmZTk4ZWJlOTc2Zjk1ZThmODZkM2UwYzg0MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6lqiZllDlsxDFLqjCT9GN4yAo2v83_8VtBoqF0zjhS0)
> 
> This runner executes a custom PS-Script as mentioned in the documentation.
> 
> ![image](https://private-user-images.githubusercontent.com/58227881/272884669-ce6a41d3-9588-486b-966a-5a2bf1fed6da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzI4MDUsIm5iZiI6MTcxODE3MjUwNSwicGF0aCI6Ii81ODIyNzg4MS8yNzI4ODQ2NjktY2U2YTQxZDMtOTU4OC00ODZiLTk2NmEtNWEyYmYxZmVkNmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA2MDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YzU4NWY1NDA5MTI4ZDQzNGFjNjYzZGI1MmUzOTJjZDJmZDk0NTVlZjUyNjBkMTljYzdlZDJkZTFhOGZmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A-vlqVzaSxRjDcklyHIIfRMWpPSeZXW0wKziN4BaSjA)
> 
> With this script we copy the artifact to a specific folder structure and execute a custom CmdLet that installs the app-file in the database:
> 
> ```
> Param(
>     [Parameter(HelpMessage = "Parameters", Mandatory = $true)]
>     [hashtable] $parameters
> )
> $EnvironmentName = $parameters.EnvironmentName
> 
> $deployAppsPath = 'C:\Deploy\DeployOnPrem\CustomApps'
> 
> Write-Host "Deploying to $EnvironmentName"
> $deployApps = $parameters.apps
> Write-Host "Cleaning up deployment folder"
> Remove-item -Path ($deployAppsPath + '\*.*') -Recurse -Force
> Write-Host "Move to deployment folder: $deployApps"
> Move-Item -Path $deployApps -destination $deployAppsPath
> Write-Host "Expanding artifacts"
> $deployArtifacts = Get-ChildItem -Path $deployAppsPath -Filter '*.zip'
> foreach ($deployArtifact in $deployArtifacts)
> {
>     Expand-Archive -Literalpath $deployArtifact.FullName -destination $deployAppsPath -Force
> }
> 
> # Import custom Deployment Tools
> 
> Write-Host "Install or update Apps"
> # execute Install CmdLet
> ```

I couldn't get this working, because I used different names for my scripts, so I managed to find the code which is being run and found that the .ps1 file has to be named according to EnvironmentType and not EnvironmentName.

What makes this work is the following combination of settings:
1. The settings file includes a DeployTo<EnvironmentName> object (e.g. DeployToMyLocalServer)
  The object includes an EnvironmentType, which has an assignment that is **not** SaaS (e.g. MyDeploymentProcedure)
2. Next there has been added an Environment to the Github Repository or Organization which has the same identifier as the DeployTo.. object (e.g. MyLocalServer)
3. In the Github Repository or the organization a Secret called either AUTHCONTEXT or <EnvironmentName>_AUTHCONTEXT, with dummy information (e.g. AUTHCONTEXT= {"TenantID":"any-id","Scopes":"any-scope","RefreshToken":"none"}), exists.
4. Inside the .Github folder of your project a file called DeployTo<EnvironmentType>.ps1 exists. Notice this is named after the deployment type, not the environment (e.g. DeployToMyDeploymentProcedure.ps1)
