### ISSUE TITLE
Deploy step never times out and cannot be cancelled

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL-Go#521]
A CI/CD workflow is stuck in the Deploy step. Usually it takes about a minute or two, but this has been running for more than an hour.

![image](https://github.com/microsoft/AL-Go/assets/8398485/5e9fd1bb-f776-4e29-b419-92307e073b5e)

The workflow cannot be cancelled, I have tried both from the workflow and from the Runners, but it just keeps running.
I cannot get any output from the workflow as it is still running, so I cannot see what went wrong.

I had a CICD worflow in another repo fail in deploy that was running at approximately the same time, so maybe a conflict where two deployment to the same environment collides. I'm ok with that failing, it should be a rare case, but a workflow running forever is a problem. Maybe there could be some timeout?

I guess it stops when the cost exceeds the limit 😱
Any ideas?

**Comment by AskeHolst** [comment]
Just found out that GH actions have a 6 hour limit, so it should stop this afternoon, I'll get back with the output.

**Comment by freddydk** [comment]
We are actually working on adding some timeout defaults.
But... - I haver never heard of jobs that couldn't be cancelled.
The only jobs I have seen hanging are ones using docker containers - and deploy isn't...
Strange.

**Comment by AskeHolst** [comment]
It did cancel after 6 hours.
Turns out it was on publishing the app in the second project of the repo. The app in the first project published fine.
I'm running it again, but again it is stuck, so I'll get back in another 6 hours with more information.

**Comment by AskeHolst** [comment]
Nothing to see in the environment.
The second app is special in that it is empty, just a app.json so far. But it compiles to an app in CICD. It is not needed in the deployment until we add the logic, but there is really no way to exclude it. 
Maybe the reason lies in the app.

**Comment by freddydk** [comment]
Publishing empty apps takes forever???
It is a sandbox environment?

**Comment by freddydk** [comment]
Is it to prod?
Empty app in CD seams to work:
![image](https://github.com/microsoft/AL-Go/assets/10775043/b1a7fb2a-7395-49dd-92d7-72d425abe608)

**Comment by AskeHolst** [comment]
It's a cloud sandbox. 
But now I'm getting "GitHub Actions has encountered an internal error when running your job." on jobs from anything like CheckForUpdates to PostProcess - across multiple repos. Probably unrelated, but it means everything is failing, so I have to solve that first...

**Comment by AskeHolst** [comment]
And I still don't know that it has anything to do with the fact that it is an empty app, it was just the only thing I could think of as being different.

**Comment by freddydk** [comment]
partial outage - whatever that means

**Comment by freddydk** [comment]
Could you list the full output of deploy (or send it to me in an email)

Mine worked:
![image](https://github.com/microsoft/AL-Go/assets/10775043/f76e8ffc-9b2b-4bfe-a790-45dc726a5970)

Do you still see the problem today? (maybe it was caused by the outage)

**Comment by AskeHolst** [comment]
The deploy step worked without issue now. 
I start to get the feeling that yesterday was just a bad day for GitHub. I suggest we close this and forget about it.

**Comment by freddydk** [comment]
Thanks for the info - and on behalf of GitHub and Microsoft - sorry:-(
