### ISSUE TITLE
Extenal Project Dependencies dont get loaded

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/AL-Go#531]
For some reason the pipeline seems to identify the release correctly but is not able to download it.
I also checked the .dependencies folder in the runners directory. The folder gets created, but no apps end up getting downloaded.

I tracked it down to this line I think:
https://github.com/microsoft/AL-Go/blob/7df81408735ebe7bd63e1cf8a35ab499012cb918/Actions/Github-Helper.psm1#L201

Part from the build pipeline:
```
Downloading dependencies
  Locating all Apps artifacts from probing paths
  Analyzing releases https://api.github.com/repos/SpareBrainedIdeas/Spare-Brained-Licensing/releases
  Downloading release Runtime 2.0.203909.154 for V21, projects *, type Apps
  project '*'
  Locating all TestApps artifacts from probing paths
  Analyzing releases https://api.github.com/repos/SpareBrainedIdeas/Spare-Brained-Licensing/releases
  Downloading release Runtime 2.0.203909.154 for V21, projects *, type TestApps
  project '*'
```
after this it continues with the previous release download

Settings:
```
"appDependencyProbingPaths": [
        {
            "repo": "SpareBrainedIdeas/Spare-Brained-Licensing"
        }
    ],
```

**Comment by freddydk** [comment]
Do you have a dependency to this app from another app in your repo?
Does it fail later with a compile error?
What does your app.json look like?

**Comment by freddydk** [comment]
Got it.
The appDependencyProbingPaths is currently only supporting dependencies from other AL-Go repositories, with a specific naming strategy for release artifacts like apps, test apps and 3rd party dependencies.
In order to use this dependency, you should use

```
"installApps": [
    "https://github.com/SpareBrainedIdeas/Spare-Brained-Licensing/releases/download/v2.0.202309.154/Spare.Brained.Ideas.AB_Spare.Brained.Licensing_2.0.202309.154_runtime.app.zip"
]
```
instead, that should work.

This way you won't be able to just get the latest release, but always have a dependency to a specific release.

**Comment by StefanMaron** [comment]
That’s already much better, I used to commit the app file into the repo to use it with installApps. I did not know I could just paste a URL :)

Thanks 😊

/Stefan
________________________________
Von: Freddy Kristiansen ***@***.***>
Gesendet: Saturday, May 13, 2023 6:40:22 AM
An: microsoft/AL-Go ***@***.***>
Cc: Stefan Maroń ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/AL-Go] Extenal Project Dependencies dont get loaded (Issue #531)


Got it.
The appDependencyProbingPaths is currently only supporting dependencies from other AL-Go repositories, with a specific naming strategy for release artifacts like apps, test apps and 3rd party dependencies.
In order to use this dependency, you should use

"installApps": [
    "https://github.com/SpareBrainedIdeas/Spare-Brained-Licensing/releases/download/v2.0.202309.154/Spare.Brained.Ideas.AB_Spare.Brained.Licensing_2.0.202309.154_runtime.app.zip"
]


instead, that should work.

This way you won't be able to just get the latest release, but always have a dependency to a specific release.
