### ISSUE TITLE
Workshop - Getting started - Error running second workflow

### ISSUE THREAD

**Issue by zpeters** [microsoft/AL-Go#540]
I'm following https://github.com/microsoft/AL-Go/blob/main/Workshop/GetStarted.md.  I have successfully followed the instructions up to "The Update AL-Go System Files workflow will start and after a few minutes"

At this step the first workflow that triggers is successful

The second workflow that triggers ends in the following error:
[CI/CD: .github#L1](https://github.com/tigunia/repo1/commit/678faa15534b19a55f00651d24450f9f134fd13b#annotation_11274337550)
GitHub Actions has encountered an internal error when running your job.

Investigating this further i see the following diffs that appear to be mismatches in environment settings?

https://github.com/tigunia/repo1/commit/678faa15534b19a55f00651d24450f9f134fd13b#annotation_11274337550

The only thing that stands out is in the prior step it is described to enter `microsoft/AL-Go-PTE@preview` when the default url appears to be `main`

Thank you,

**Comment by freddydk** [comment]
The reason for this is, that v3.1 shipped yesterday, which means that today (and until new features are shipped in preview), preview == main == v3.1

I will be updating the workshop to no longer require you to switch to preview.

**Comment by zpeters** [comment]
I'm happy to take a stab at a PR for the docs if you need any assistance

**Comment by freddydk** [comment]
Help is always welcome:-)

**Comment by zpeters** [comment]
Added PR #544 .  Happy to make adjustments, add screenshots or whatever else you need
