### ISSUE TITLE
Deploy Workflow fails.

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#542]
There is another issue with dependency handling after the build. 

We have a customer customization they have a dependency on "our" apps and other isv apps.

The ISV apps are for obvious reason provided as runtime apps. 
If we want to deploy these apps to a sandbox the thrid-party app and partialy our apps won't need to be deployed.

This boils down to the same issue as #415 we need more control over which apps are deployed/published and delivered.

I would prefer to be able to configure each app in the nuspec file so I only need to do it ones and not in every app where I use it. 

But in short term it would be enough to get the option to ignore apps for deploy/publish and delivery.

`Error: Deploying to ENV failed.  AppFile C:\Users\runneradmin\AppData\Local\Temp\a5161132-6a78-457e-a5c1-f9e8804d4305\Third-Party.app is a runtime package. You will have to specify a running container in containerName in order to analyze dependencies between runtime packages`

**Comment by freddydk** [comment]
Hmmm - I thought I fixed this issue and would ignore runtime packages (assuming that they already was deployed as I cannot deploy them anyway).

Can you give me full log? (either here or by email)

Thanks

**Comment by jonaswre** [comment]
I've sent you the logs by mail. 

But I still think some configuration to be able to configure which apps should be deployed an which shouldn't. 

There might be cause where I need to deploy runtimes as well.

**Comment by freddydk** [comment]
I will have a look today or tomorrow (is pretty caught up today)

**Comment by jonaswre** [comment]
No problem. I'll remove the enviroment again to be able to release.

**Comment by freddydk** [comment]
Looked at the logs.
I am not saying that we don't need more control over which apps to install and what not, I think we will have to re-visit this when re-opening the nuget discussions.
but... - for this bug it is a little simpler.

I earlier fixed a similar bug, when using Publish-PerTenantExtensionApps.
Basically when I run into a runtime package, I ignore it (and all its dependencies).
Why is this OK?
Well - I cannot install the runtime package on an online environment anyway, That is not supported.
So, you have to install the runtime package and all its dependencies manually (or using other means) before installing your apps here - and if the runtime package dependency is already satisfied, so is all its dependencies as well - so, I can just ignore it and assume that it is installed.
If it isn't installed - you will get an error that the app is not installed.
and... - I should do the same when using dev endpoint (using Publish-BcContainerApp), from AL-Go towards an online environment -> just ignore runtime packages.
I added the parameter in BcContainerHelper an hour ago - will fix AL-Go tomorrow.

**Comment by jonaswre** [comment]
I think specially for Saas this is pretty much the only thing you can do. But for delivery more control is essential. 

Have you ever talked with the Dev Team about exposing the App Manifest file even in runtimes? For better dependency management it would be useful to be able to parse out useful data from runtime package.

**Comment by freddydk** [comment]
Agree.

On the app manifest, it can be extracted from runtime packages using the ALC compiler - will consider how this can be made more accessible.

**Comment by freddydk** [comment]
This was deployed to preview today.
The other side of this will be included in a future feature

**Comment by jonaswre** [comment]
Can confirm, it works now.

**Comment by jonaswre** [comment]
Hmm...

The runtimes are now excluded but the order in which apps are deployed is not correct.

` Status Code 422 : Unprocessable Entity The extension could not be deployed, because it tries to replace the existing AppSource app 'BeyondAttributesCore' with id '11411223-4bab-440b-bdf8-a296dced1967', which is a dependency to the following AppSource apps: 'BeyondServiceItemTracking by BEYONDIT GmbH,BeyondAttributesMGTBridge by BEYONDIT GmbH'`

I now get this error. For a fresh install the order thats currently used is correct. But in this case the correct way this needs to be installed is top down not bottom up. 

So during dev I get the same error. What I will then do is go to the leaf and start publishing top down. So that all my dependencies are eather present as dev or not being updated. 
This error will always appear in new enviroments if you have this depth in your dependencies.

**Comment by freddydk** [comment]
Got it - so these apps where installed from AppSource originally? and then they are replaced by an app in the Dev Scope - and that needs to be all apps?

**Comment by jonaswre** [comment]
Yes they were originally installed from AppSource. 
Yes they are replaced by an Dev Scope App.
Well if the version is higher then - yes - it and its dependents need to be updated. This can quickly mean all apps but technicly doesn't need to be all apps.
