### ISSUE TITLE
Merge pull request step fails

### ISSUE THREAD

**Issue by zpeters** [microsoft/AL-Go#543]
Following the guide up to https://github.com/microsoft/AL-Go/blob/main/Workshop/AddAnApp.md

After the PR merge is completed an action kicks off to finalize the merge.  This appears to fail

https://github.com/tigunia/repo1/actions/runs/4995017552

![Opera Snapshot_2023-05-16_124554_github com](https://github.com/microsoft/AL-Go/assets/39647/dca81394-f43d-41c6-bf5d-402cca5584c9)

If i hover over the error message the only thing i can do is click on the link to the merge (which was completed successfully)

I have attached the raw job logs

[raw-job-logs.txt](https://github.com/microsoft/AL-Go/files/11490589/raw-job-logs.txt)

I did a basic scan for errors and i was only finding the word "error" in the embedded powershell code (i could be missing something)

please let me how i can help test this some more or help in other ways!

**Comment by freddydk** [comment]
Which secrets did you create at this time?
It looks like they might have spaces or newlines in them.

**Comment by freddydk** [comment]
Did you create this:
![image](https://github.com/microsoft/AL-Go/assets/10775043/f575d224-2330-49bb-8366-631b7f524ca0)

as an organizational secret (instead of variable)?

That would explain the problem

**Comment by zpeters** [comment]
I think you might be on to something.  When i initially set this repo up i did specify the environment secrets, but i think i deleted and recreated it since.  I will confirm and if thats the case i will close this out

**Comment by zpeters** [comment]
Confirming this was the fix.  Sorry for any confusion i have caused!
