### ISSUE TITLE
Create Test App error

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/AL-Go#546]
I am following the example processes in a new repo and I am getting this error using the "Create a new test app" action.  The "Create a new app" action worked fine.

The log file is attached. I have added you to the repo [tscottjendev](https://github.com/tscottjendev)/[Freddy](https://github.com/tscottjendev/Freddy) for review if needed.

> CreateTestApp
CreateApp action failed. Error: pull request create failed: GraphQL: GitHub Actions is not permitted to create or approve pull requests (createPullRequest)  ExitCode: 1 Commandline: gh pr create --fill --head roslsnlx.1zb --repo tscottjendev/Freddy --base main  Stacktrace: at CmdDo, C:\Users\runneradmin\AppData\Local\Temp\eeccefe8-942d-4c13-aca2-67dcf06cba56\BcContainerHelper\HelperFunctions.ps1: line 130 at invoke-gh, C:\Users\runneradmin\AppData\Local\Temp\eeccefe8-942d-4c13-aca2-67dcf06cba56\BcContainerHelper\Common\Invoke-gh.ps1: line 26 at CommitFromNewFolder, D:\a\_actions\microsoft\AL-Go-Actions\v3.1\AL-Go-Helper.ps1: line 1135 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v3.1\CreateApp\CreateApp.ps1: line 135 at <ScriptBlock>, D:\a\_temp\9518e91e-d417-4f8a-b101-74c9af61eacb.ps1: line 2 at <ScriptBlock>, <No file>: line 1

[logs_4.zip](https://github.com/microsoft/AL-Go/files/11505339/logs_4.zip)

**Comment by freddydk** [comment]
The reason for this is that you are missing this setting:
![image](https://github.com/microsoft/AL-Go/assets/10775043/3382331a-de10-423b-9daf-f981f68dd2b0)
(under Settings->Actions->General->Workflow Permissions)

If this setting is not set, you need to set direct COMMIT to Y.

**Comment by freddydk** [comment]
This issue will also benefit from adding the "Use GhTokenWorkflow" as suggested in issue #555
