### ISSUE TITLE
Dependency on BCPT in a non-BCPT-Test-App

### ISSUE THREAD

**Issue by waldo1001** [microsoft/AL-Go#547]
Probably a simple question, but I'm going to ask anyway ...

I have an app that uses a dependency on BCPT, so it's not a BCPT test app, but it does add some new functionality to it .. .  

Here's the pipeline: https://github.com/waldo1001/waldo.BCPerfTool/actions/runs/5008416441

I don't seem to be able to figure out a way to add the BCPT app in the container to make the app publishing work 🤔

**Comment by freddydk** [comment]
I have created 2 PRs on your repo - you can pick any one of them.

First one Moves the apps to TestFolders and sets doNotRunTests to true.
TestFolders will automatically discover test app dependencies and install the necessary dependencies.
Else AL-Go will only find apps which have been installed in the container and you could use the installApps setting to locate and install the bcperftool (would be a bit cumbersome though).

Second one is using a new construct called CompilerFolders, which causes AL-Go to compile without containers.
CompilerFolders also finds dependencies in all 1st party apps (where we normally look for things that have been installed only)
Over the next months, compilterfolders will be default and all apps will build using this - currently there isn't much performance gain as it still needs to create a container to run tests etc. and this will be done synchronously (unless you specify doNotPublishApps, which I also did).

**Comment by waldo1001** [comment]
Thanks so much, Freddy.

I went for a mix of both: DoNotRunTests, but also the compilerFolders, as that resembles a lot the ALOps "compiler without a container" by finding the right dependencies and such.
