### ISSUE TITLE
Changelog includes wrong commits.

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#559]
This is related to https://github.com/microsoft/AL-Go/issues/229.

The changelog should only include commits upto the commit used in the release not upto the latest. 

This issue can be reproduced by running "Create Release" before the CI/CD Build has completed.

**Comment by freddydk** [comment]
Sounds like a bug, will investigate

**Comment by freddydk** [comment]
Like the create release API, the generate release notes api also needs the target_commitish parameter.
Testing a fix now.
