### ISSUE TITLE
ARM template for GitHub runner is failing on VM extension deployment step (vmextension1)

### ISSUE THREAD

**Issue by dawid-gierszewski-solteq** [microsoft/AL-Go#560]
Hello!

I am trying to create a self-hosted runner and following the steps from the scenario (https://github.com/microsoft/AL-Go/blob/main/Scenarios/SelfHostedGitHubRunner.md). Deployment is failing with the following error:

![image](https://github.com/microsoft/AL-Go/assets/57171348/2f4ea0cf-b2f4-430e-854c-8775680e11cf)

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'vmextension1'. Error message: \"Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: '.NET Framework 4.8 was installed, but a reboot is required. \r\n Please reboot the system and try to install/upgrade Chocolatey again.\r\nAt C:\\Windows\\TEMP\\chocolatey\\chocoInstall\\tools\\chocolateysetup.psm1:815 char:11\r\n+           throw \".NET Framework 4.8 w...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "}]}`

A few weeks ago, it worked fine.

**Comment by dawid-gierszewski-solteq** [comment]
Running the script (initbuildagent.ps1) manually on VM, rebooting and then configuring runner made the runner up & running.

**Comment by freddydk** [comment]
You could probably also just have restarted the VM - I would guess that this would have re-started the installation as well.
Will see why this happens, thanks

**Comment by yul-zhou** [comment]
Hey @freddydk,

The reason for this problem is that the latest release of chocolatey upgrade their target .NET Framework to 4.8 (https://docs.chocolatey.org/en-us/choco/release-notes). Since the image lacks this dependency, the install script will try to install .Net Framework 4.8 and wait for the restart, leading to the breakfailed deployment.

**Comment by freddydk** [comment]
@yul-zhou thanks for the info - will check this today

**Comment by freddydk** [comment]
Tried a number of things and couldn't repro, but the reason for this was, that my test scripts were using Windows Server 2022 - not Windows Server 2019... - and:
![image](https://github.com/microsoft/AL-Go/assets/10775043/06b22a71-509e-433f-8039-0b07d44c2d8e)

So, I will fix two things.
1. Set default OS to Windows Server 2022
2. During initialize, if dotnet 4.8 isn't installed, it will be installed.

**Comment by freddydk** [comment]
This is fixed in the latest version of the ARM templates.
