### ISSUE TITLE
Dotnet variables

### ISSUE THREAD

**Issue by amunoz-ldr** [microsoft/AL-Go#568]
Hi,

Is it there any way to set-up al-go in order to allow an extension to use dotnet variables? We have a customer running BC19 onpremise without any chance to upgrade and we would like to take advantage to use the ci/cd workflows.

Thanks.

**Comment by freddydk** [comment]
AL-Go for GitHub might not be the best fit.
Especially, if you are planning to stay on BC 19 - and use dotnet framework DLLs etc.

**Comment by amunoz-ldr** [comment]
Ok, thank you anyway

**Comment by freddydk** [comment]
If the goal is just to allow dotnet variables, you can probably just set "EnablePerTenantExtensionCop": false in the repo settings file and then the cop is disabled.
Onprem can however pull many other things along.

**Comment by freddydk** [comment]
Thinking about it (and if other people find this), you could create a file called `NewBcContainer.ps1` in your .AL-Go folder.
This will override the container creation and in that script, you can copy your DLLs into the container.

The NewBcContainer function looks like this (without the comments):
```
Param([Hashtable]$parameters)
# here you could add other parameters to New-BcContainer
New-BcContainer @parameters
# here you could copy files into the container
Invoke-ScriptInBcContainer $parameters.ContainerName -scriptblock { $progressPreference = 'SilentlyContinue' }
```

Note though, that as we change AL-Go in the future, overrides like these are sometimes broken and you might have to change things.

**Comment by amunoz-ldr** [comment]
Thank you we'll try it

**Comment by frottke** [comment]
Hi @amunoz-ldr ,

would you mind to share your solution?

I've tried similar with the solution provided by Freddy, but I can't seem to get it working. 

I created in the".Al-Go" directory an file called "NewBcContainer.ps1", at first I wasn't sure if it gets executed so I tried some less useful commands to get an "reaction" in the shape of an error. For example:

```
Param([Hashtable]$parameters)
# here you could add other parameters to New-BcContainer
New-BcContainer @parameters
Remove-BcContainer -containerName $parameters['containerName']
```

It seems that there is some error handling to prevent something like this? @freddydk .

The following script is the one that is the result after some hours of trial and error

```
Param([Hashtable]$parameters)
# here you could add other parameters to New-BcContainer
New-BcContainer @parameters

# here you could copy files into the container
$DependencyFolder =  ${github.workspace} + "/.netpackages"

Get-ChildItem $DependencyFolder -Filter *.dll | 
Foreach-Object {
    Copy-Item -Path $_.FullName -Destination "C:\Windows\Microsoft.NET\Assembly\"
}
```

Currently, copying the dlls to the service tier is no concern due to setting in the AL-Go-Settings.json "doNotPublishApps": true

**Comment by amunoz-ldr** [comment]
Hi, 
I'm just doing this:

```
Param([Hashtable]$parameters)
New-BcContainer @parameters
$script = {
    $dirOrigen = #Place here the path to \.netpackages
    $dirDestino = "C:\Program Files (x86)\Microsoft Dynamics NAV\190\RoleTailored Client"
    $dirServicio = "C:\Program Files\Microsoft Dynamics NAV\190\Service\Add-Ins"
    Get-ChildItem -Path $dirOrigen | Copy-Item -Destination $dirDestino
    Get-ChildItem -Path $dirOrigen | Copy-Item -Destination $dirServicio
}
Invoke-ScriptInBcContainer $parameters.ContainerName -scriptblock $script
```

Hope this help
