### ISSUE TITLE
Analyze Job fails on first run of CI/CD in new repo based on AL-Go-PTE with error 404

### ISSUE THREAD

**Issue by curateideas** [microsoft/AL-Go#57]
After creating a new repo from the AL-Go-PTE template the first CI/CD run started with the first push fails with error 404 in the step "ReadSettings".

In scenario No. 1 I followed the intructions until step 14.

The action started with the push but failed at Job "Analyze"

![image](https://user-images.githubusercontent.com/58227881/145642284-959fd553-9b69-465c-a8e6-971bba610c1f.png)

Are there any settings missing? Preconditions of scenario No. 1 are met.

**Comment by freddydk** [comment]
A fix will be deployed within the next hour for this.

**Comment by curateideas** [comment]
Works now! Thanks for your instant fix, @freddydk.
