### ISSUE TITLE
When using appDependencyProbingPaths set to latestBuild, the API Returns 404

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/AL-Go#572]
To me it looks like this endpoint is not pulbic anymore.

![image](https://github.com/microsoft/AL-Go/assets/24838311/409dcaaf-a194-45d3-837c-ed6b2659d55d)

**Comment by freddydk** [comment]
Sorry for the delay, do you still have this problem?
The endpoint is not public on private repositories.

**Comment by StefanMaron** [comment]
That explains it, I was running this pipeline on a private repo. 
I worked myself around this issue by placing all apps in the same project scope within the repo. 

But this is still a bit unfortunate since most companies would want to have their repos private. If dependencies between them are not supported, it should at least be documented I would say.

**Comment by freddydk** [comment]
Oh, Of course dependencies to private repositories are supported.
You just need to specify the name of the secret containing a token with access to that repo in the appDependencyProbingPath.
Explained here: https://github.com/microsoft/AL-Go/blob/main/Scenarios/AppDependencies.md

**Comment by StefanMaron** [comment]
Aight, thanks! Should have found that myselft :man_facepalming:
