### ISSUE TITLE
PTE Scenario. App folder launch.json is ignored and always create and use launch.json in the parent folder

### ISSUE THREAD

**Issue by nvtopalov** [microsoft/AL-Go#574]
Hello,
I am just getting started with the AL go for Git Hub. Tried a few times the scenario for PTE, but on the step for "12. Open the HelloWorld.al file, modify the string and press F5. Depending on authentication selected VS Code might ask for the credentials you provided earlier.", it always creates a new .vscode folder with launch.json in the parent folder and ignore the launch.json created previously by the "localDevEnv.ps1" script inside the app folder. 

Maybe I am missing something in the AL extension configuration? 

![image](https://github.com/microsoft/AL-Go/assets/36190518/2841c5bc-1608-4e88-8b39-c4e3e90ece24)

Thanks

**Comment by freddydk** [comment]
It looks like you didn't open the workspace?

**Comment by nvtopalov** [comment]
Thanks. Seems like I overlooked that. 
Sorry for the bothering you for that silly mistake.
