### ISSUE TITLE
Custom private repository template - authorization problem

### ISSUE THREAD

**Issue by azwierzchowskitnp** [microsoft/AL-Go#575]
Hi

I don't want to clone or modify AL GO actions, but I'd like to have a custom, private repository template with some additional workflows and a few additional steps added to the standard AL GO workflows. Then I want to manually update my template from the AL Go PTE template when needed and use "Update AL-Go System Files" workflow to update my repositories from there. Unfortunately it is not possible now, because CheckForUpdates action can only download from public repositories. Can you modify `Actions/CheckForUpdates/CheckForUpdates.ps1` file and send GitHub token in the Authorization header when repository template zip is downloaded?

Current code:

``` PowerShell
 # Download the template repository and unpack to a temp folder
    $headers = @{             
        "Accept" = "application/vnd.github.baptiste-preview+json"
    }
```

New code:
``` PowerShell
 # Download the template repository and unpack to a temp folder
    $headers = @{             
        "Accept" = "application/vnd.github.baptiste-preview+json"
        "Authorization" = "token $token"
    }
```

Thank you,
Andrzej

**Comment by freddydk** [comment]
@azwierzchowskitnp - during review I was made aware that having a private AL-Go-PTE template repo means that you will loose the connection to AL-Go.
You cannot have a private fork of AL-Go. You can have a private AL-Go-PTE repo, but you will not be able to uptake changes to AL-Go in that and thus - we will for sure break you when we make changes to actions and PTE templates.

Lets setup a meeting and discuss what exactly you want to achieve with this to see if there are better options.
Please send a meeting request (this week or next) to freddyk at microsoft dot com.
Thanks

**Comment by freddydk** [comment]
Reopening after further discussions
