### ISSUE TITLE
Upload Artifacts during Release Fails

### ISSUE THREAD

**Issue by JacoBothaDyn** [microsoft/AL-Go#576]
We have been using the Delivery to Storage to deliver Artifacts to Azure Storage for about 4 months now. 

Delivery still works during CI/CD Workflow, but during release it fails with a 410 error code. 

Error: Deliver action failed. Error: Response status code does not indicate success: 410 (Gone).   Stacktrace: at InvokeWebRequest, /home/runner/work/_actions/microsoft/AL-Go-Actions/v3.1/Github-Helper.psm1: line 105 at DownloadArtifact, /home/runner/work/_actions/microsoft/AL-Go-Actions/v3.1/Github-Helper.psm1: line 728 at <ScriptBlock>, /home/runner/work/_actions/microsoft/AL-Go-Actions/v3.1/Deliver/Deliver.ps1: line 156 at <ScriptBlock>, /home/runner/work/_actions/microsoft/AL-Go-Actions/v3.1/Deliver/Deliver.ps1: line 155 at <ScriptBlock>, /home/runner/work/_actions/microsoft/AL-Go-Actions/v3.1/Deliver/Deliver.ps1: line 151 at <ScriptBlock>, /home/runner/work/_actions/microsoft/AL-Go-Actions/v3.1/Deliver/Deliver.ps1: line 99 at <ScriptBlock>, /home/runner/work/_temp/7a8d979a-3600-467f-9165-1d2bf311d56a.ps1: line 2 at <ScriptBlock>, <No file>: line 1
AL-Go action ran: Deliver Telemetry Correlation Id: 44901c8b-107e-406b-b6ca-0d983184e17a
Removing BcContainerHelper
Error: Process completed with exit code 1.

Using Al-Go for PTE version: V3 (I Think) updated just before attempting this release again. 

Using "runs-on" Ubuntu-Latest as well. (which has been working well)

**Comment by freddydk** [comment]
Sounds like it is trying to download an artifact from a build, which is expired.
Deliver during CI/CD will take what was just build and the deliver in the release should grab the release you are releasing - but it sounds like something is wrong here.

Any chance I could get access to the repo and have a look what is happening?

Alternatively, extract the full log and email that to me (freddyk at microsoft dot com)

**Comment by JacoBothaDyn** [comment]
I'll send over the log of both the CICD and the Release Actions.

**Comment by freddydk** [comment]
Sorry for the late reply - this issue is fixed in the preview version of AL-Go for GitHub.

The reason for this is that the release action queries list of builds to find the artifacts you are going to release, and it doesn't ignore expired builds.
In your case it find an old -Dependencies- artifact from an old build and downloads to analyze -> the download fails.

If you run update AL-Go System Files with microsoft/AL-Go-PTE@preview (or microsoft/AL-Go-Actions@preview) then your release workflow should work after upgrading.

**Comment by freddydk** [comment]
We expect to ship a new version of AL-Go for GitHub to prod in ~1 week.
