### ISSUE TITLE
UpdateVersionNumber fails on the Create release Action

### ISSUE THREAD

**Issue by rbability** [microsoft/AL-Go#577]
When kicking off the Action and setting a +0.1 in the "New Version Number in main branch..." part of the Action, the step "UpdateVersionNumber" fails for me repeatedly with the message:
`IncrementVersionNumber action failed. Error: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified" Stacktrace: at CmdDo, C:\WINDOWS\TEMP\566ebb7e-c3cf-4815-bb75-81879aac89b1\BcContainerHelper\HelperFunctions.ps1: line 102 at invoke-gh, C:\WINDOWS\TEMP\566ebb7e-c3cf-4815-bb75-81879aac89b1\BcContainerHelper\Common\Invoke-gh.ps1: line 26 at CommitFromNewFolder, C:\actions-runner-02\_work\_actions\microsoft\AL-Go-Actions\v3.1\AL-Go-Helper.ps1: line 1135 at <ScriptBlock>, C:\actions-runner-02\_work\_actions\microsoft\AL-Go-Actions\v3.1\IncrementVersionNumber\IncrementVersionNumber.ps1: line 122 at <ScriptBlock>, C:\actions-runner-02\_work\_temp\74667900-dabe-46f9-b7f7-35321f671cb3.ps1: line 2 at <ScriptBlock>, <No file>: line 1`

I can not figure out which "file" it can not find / what it expects from me.
If I leave the field for the new Version number blank, the action skips that step and the job finishes without errors. So everything else except the adjustment of the version number seems to be OK.

I am probably missing some prerequisite for that to be able to work?

**Comment by freddydk** [comment]
Assuming that you are running a self-hosted runner for all jobs, this is likely because you don't have GitHub CLI installed (https://docs.github.com/en/github-cli/github-cli/quickstart)
I will try to check for this earlier and return a better error message.

**Comment by rbability** [comment]
Thank you very much @freddydk! You are correct in both points. We run self-hosted runners and somehow I missed the hint in the documentation about the requirement to have GitHub CLI installed. Sorry for that!
I installed GitHub CLI and it started to work.

If someone else finds this and has the same issue, one note:
Do not forget to restart your Runner Services. GitHub CLI adds itself to the path variable in Windows, so it can be found from everywhere, but this only has an effect on the GH Runners if they are restarted. Otherwise you will end up with the same error message, despite having GitHub CLI installed.
