### ISSUE TITLE
Internal Server Error when publishing

### ISSUE THREAD

**Issue by rolandpthompson** [microsoft/AL-Go#592]
I've just used the Publish to Environment to successfully push to a sandbox.
I now try to the same repo to another sandbox (in the same tenant), and i just keep getting an internal server error

<img width="795" alt="image" src="https://github.com/microsoft/AL-Go/assets/6749639/81a96619-8491-41a9-ad15-9ca06bd4f673">

I can manually upload the app file, and I have recreated the sandboxes and it seems to do the same.

Any ideas?

**Comment by freddydk** [comment]
It's very hard to see much with so little info, but I can see one thing, which you could change.
It looks like you have created the EnvironmentName secret to map the environment name - try to remove the secret and add this setting instead:

```
"DeployTo<GitHub Environment Name>": {
    "EnvironmentName": "<Business Central Environment Name>"
}
```

**Comment by rolandpthompson** [comment]
I have seen that message before, couldn't find any reference to it in the settings.md file though (https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md), which file does it go in?

What format should it be, if say my environment name is SX_QA

**Comment by freddydk** [comment]
what is the name of your GitHub Environment ?
what is the name of your Business Central Environment ?

**Comment by rolandpthompson** [comment]
GitHub environment name is **SX_QA** and the BC Environment is **QA**

What's the advantage of this over the way I am doing it now?

**Comment by freddydk** [comment]
In .github/AL-Go-Settings.json

```
"DeployToSX_QA": {
    "EnvironmentName": "QA"
}
```

Problem is that secrets are masked in the output and in some places not transferred.

**Comment by rolandpthompson** [comment]
Ah i see,

so this is now my amended settings file, do I also need to add the others as separate ones too?

```
﻿{
    "type":  "PTE",
    "templateUrl":  "https://github.com/microsoft/AL-Go-PTE@main",
    "gitHubRunner":  "self-hosted",
    "Environments":  [
                         "SX_QA",
                         "SX_UAT (FAT)",
                         "SX_PROD (Production)"
                     ],
    "DeployToSX_QA": {
        "EnvironmentName": "QA"
    }
}
```

Like

```
﻿{
    "type":  "PTE",
    "templateUrl":  "https://github.com/microsoft/AL-Go-PTE@main",
    "gitHubRunner":  "self-hosted",
    "Environments":  [
                         "SX_QA",
                         "SX_UAT (FAT)",
                         "SX_PROD (Production)"
                     ],
    "DeployToSX_QA": {
        "EnvironmentName": "QA"
    },
    "DeployToSX_UAT": {
        "EnvironmentName": "UAT"
    },
    "DeployToSX_PROD": {
        "EnvironmentName": "Production"
    }
}
```

**Comment by freddydk** [comment]
Yes, then you should be able to remove the environmentName secrets.

**Comment by rolandpthompson** [comment]
Great, I'll give it a go.#

Thanks Freddy

**Comment by freddydk** [comment]
Assuming that this fixed the issue
