### ISSUE TITLE
Docker container not cleaning up properly 

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#598]
I think there is some sort of storage leak when running self-hosted runner. 

We have the issue that our VM runs out of storage.
This has happens every 2-4 month maybe.  

I first contributed this to microsoft releasing lots of new artifacts in a short period. This would cause a lot of artifacts accumulating but this doesn't seem to be the case this time. 
We had 30 GB Artifacts and 200 GB docker files. 
30 GB artifacts seems normal but 200 GB docker files a bit much. 

I have a little powershell script thats purges everything older then a day. 
```
docker image prune -a --filter "until=24h" -f

Get-ChildItem –Path "C:\bcartifacts.cache" -Recurse | Where-Object {($_.LastWriteTime -lt (Get-Date).AddDays(-1))} | Remove-Item -Force -Recurse
```  

But this didn't solve it this time. 
It seems like there were tons of exited container that where still "using" the images so they couldn't be purged. 

I had to add the following in the beginning of my script to free up the space this time. 
```docker rm $(docker ps --filter status=exited -q)```

I'm contemplating, running this script every month or so, to be sure no storage accumulates. But I thought other might run into a simular issue and running this every month doesn't solve this issue for good it just makes it less likely. 

Maybe there is something that can be done in the al-go cleanup to prevent this for everybody.

**Comment by freddydk** [comment]
Thanks
I actually just added the docker image prune with a filter to Flush-ContainerHelperCache last week.
It looks like maybe I should look into added a mechanism to remove exited containers as well - probably with a flag (and then add this flag to AL-Go).

**Comment by freddydk** [comment]
I guess this code inside of Flush-ContainerHelperCache would work:

```
docker container ls --format "{{.ID}}:{{.Names}}" --no-trunc -a --filter "status=exited" | ForEach-Object {
    $containerID = $_.Split(':')[0]
    $containerName = $_.Split(':')[1]
    $inspect = docker inspect $containerID | ConvertFrom-Json
    $finishedAt = [DateTime]::Parse($inspect.state.FinishedAt)
    if ([DateTime]::Now.Subtract($finishedAt).Days -ge $keepDays) {
        Write-Host "Removing container $containerName"
        docker rm $containerID -f
    }
}
```

**Comment by jonaswre** [comment]
This seems good but have you investigated why containers are not removed properly in the first place? This feels like a patch on a leak. I think each run shouldn't leave any unwanted data behind.

**Comment by freddydk** [comment]
It is definitely the intention that every workflow run cleans up the container - the code should do this.
If you have any logs from workflow runs where this isn't the case, I would love to see them?
I haven't experienced this myself.

**Comment by jonaswre** [comment]
I've just checked our runner again the last 5 days didn't collect any exited container i'll check periodically to see if they accumlate maybe this helps to narrow it down.

**Comment by freddydk** [comment]
> I've just checked our runner again the last 5 days didn't collect any exited container i'll check periodically to see if they accumlate maybe this helps to narrow it down.

Yep, if I can get the logs from a run, which doesn't cleanup the containers - I will be able to discover why.
In the meantime, we will implement the cleanup of exited containers which are more than KeepDays old in the Flush-ContainerHelperCache called from AL-Go.

**Comment by pzentner** [comment]
I just wanted to add that we are experiencing the same issue. I can't pinpoint where it comes from either, but it mainly seems like the containers that are left over on my end are from the image creation and not the actual containers use to run the pipelines.

I am contributing this to running the preview version of AL-Go and experiencing sometimes issues here and there, which break the pipeline. And, if the entire process doesn't make it far enough, it seems that it can't clean up the container. I will certainly try to keep an eye out as well to see what actually causes this.

**Comment by freddydk** [comment]
Leftover containers from building images should have been removed with the change I made to ContainerHelper here:
https://github.com/microsoft/navcontainerhelper/pull/3107

**Comment by pzentner** [comment]
Thanks Freddy. I will monitor it and see, if those were leftovers from before the change or not. I cleaned up all self hosted runners yesterday again, so it should not happen again, if everything works.
