### ISSUE TITLE
"Remote Refs"?

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#600]
When a pull request merge is kicked off, the Initialization action fails with these messages: "couldn't find remote ref refs/pull/40/merge." 

Pull request succeeds, code is merged, CI/CD runs without error.

Where to look to correct this?

Run actions/checkout@v3
  with:
    lfs: true
    ref: refs/pull/40/merge
    repository: CAI-Software-Inc/CAI-Software-Precious-Metals-Solution
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-depth: 1
    submodules: false
    set-safe-directory: true
  env:
    workflowDepth: 1
    ALGoOrgSettings: {"doNotPublishApps": true,"artifact": "https://bcartifacts.azureedge.net/sandbox/[2](https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/runs/5521706983/jobs/10070211933#step:2:2)2.0.54157.55210/us"}
    ALGoRepoSettings: 
Syncing repository: CAI-Software-Inc/CAI-Software-Precious-Metals-Solution
Getting Git version info
  Working directory is 'D:\a\CAI-Software-Precious-Metals-Solution\CAI-Software-Precious-Metals-Solution'
  "C:\Program Files\Git\bin\git.exe" version
  git version 2.41.0.windows.1
  "C:\Program Files\Git\bin\git.exe" lfs version
  git-lfs/[3](https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/runs/5521706983/jobs/10070211933#step:2:3).3.0 (GitHub; windows amd6[4](https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/runs/5521706983/jobs/10070211933#step:2:4); go 1.19.3; git 77deabdf)
Temporarily overriding HOME='D:\a\_temp\de8[5](https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/runs/5521706983/jobs/10070211933#step:2:5)4350-9743-4edf-b7[6](https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/runs/5521706983/jobs/10070211933#step:2:6)4-b1eb031bd64c' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
"C:\Program Files\Git\bin\git.exe" config --global --add safe.directory D:\a\CAI-Software-Precious-Metals-Solution\CAI-Software-Precious-Metals-Solution
Deleting the contents of 'D:\a\CAI-Software-Precious-Metals-Solution\CAI-Software-Precious-Metals-Solution'
Initializing the repository
  "C:\Program Files\Git\bin\git.exe" init D:\a\CAI-Software-Precious-Metals-Solution\CAI-Software-Precious-Metals-Solution
  Initialized empty Git repository in D:/a/CAI-Software-Precious-Metals-Solution/CAI-Software-Precious-Metals-Solution/.git/
  "C:\Program Files\Git\bin\git.exe" remote add origin https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution
Disabling automatic garbage collection
  "C:\Program Files\Git\bin\git.exe" config --local gc.auto 0
Setting up auth
  "C:\Program Files\Git\bin\git.exe" config --local --name-only --get-regexp core\.sshCommand
  "C:\Program Files\Git\bin\git.exe" submodule foreach --recursive "sh -c \"git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :\""
  "C:\Program Files\Git\bin\git.exe" config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
  "C:\Program Files\Git\bin\git.exe" submodule foreach --recursive "sh -c \"git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :\""
  "C:\Program Files\Git\bin\git.exe" config --local http.https://github.com/.extraheader "AUTHORIZATION: basic ***"
"C:\Program Files\Git\bin\git.exe" lfs install --local
Updated Git hooks.
Git LFS initialized.
Fetching the repository
  "C:\Program Files\Git\bin\git.exe" -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/pull/40/merge:refs/remotes/pull/40/merge
  Error: fatal: couldn't find remote ref refs/pull/40/merge
  The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 12[8](https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/runs/5521706983/jobs/10070211933#step:2:8)
  Waiting 12 seconds before trying again
  "C:\Program Files\Git\bin\git.exe" -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/pull/40/merge:refs/remotes/pull/40/merge
  Error: fatal: couldn't find remote ref refs/pull/40/merge
  The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 128
  Waiting 1[9](https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/runs/5521706983/jobs/10070211933#step:2:9) seconds before trying again
  "C:\Program Files\Git\bin\git.exe" -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/pull/40/merge:refs/remotes/pull/40/merge
  Error: fatal: couldn't find remote ref refs/pull/40/merge
  Error: The process 'C:\Program Files\Git\bin\git.exe' failed with exit code [12](https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/actions/runs/5521706983/jobs/10070211933#step:2:12)8

**Comment by aholstrup1** [comment]
From the error message and your description, it sounds like you merged the PR while the Pull Request Build was running. Is that the case? 
refs/pull/40/merge is a reference GitHub creates and updates as long as the PR is open. Once the PR is merged the reference will disappear as well.

**Comment by buzzwick** [comment]
That makes plausible sense.  I will pay attention to that going forward, and pause before merging. Thanks!

**Comment by aholstrup1** [comment]
No problem :) This is a question we've gotten before so we might want to look into failing/canceling PR Builds more gracefully. I've added an item to the backlog [Fail Pull Request Build more gracefully
](https://github.com/orgs/microsoft/projects/521?pane=issue&itemId=33062935)
