### ISSUE TITLE
Error: RunPipeline action failed. Error: Cannot stop process "wsmprovhost (197448)" because of the following error: Access is denied

### ISSUE THREAD

**Issue by Michel-up** [microsoft/AL-Go#602]
in Build Pipeline Removing container
                 
  Error: RunPipeline action failed. Error: Cannot stop process "wsmprovhost (197448)" because of the following error: Access is denied 
  Removing BcContainerHelper
  Error: Process completed with exit code 1.

any idea why access is denied? 
i am using "NT AUTHORITY/Network Service" as User account

**Comment by freddydk** [comment]
So, this is a self-hosted runner using Network Service as user account?
Isn't there a full stack trace somewhere in the log?

**Comment by Michel-up** [comment]
yes this is a self-hosted runner using Network Service as user account

there is this:
Removing container
    _____                           _                               _        _                 
   |  __ \                         (_)                             | |      (_)                
   | |__) |___ _ __ ___   _____   ___ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
   |  _  // _ \ '_ ` _ \ / _ \ \ / / | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
   | | \ \  __/ | | | | | (_) \ V /| | | | | (_| | | (_| (_) | | | | || (_| | | | | |  __/ |   
   |_|  \_\___|_| |_| |_|\___/ \_/ |_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|   
                                             __/ |                                             
                                            |___/                                              
  Get Event Log from container
  Getting event log for bc5544170557
  Run-AlPipeline Telemetry Correlation Id: d89d068f-f1ca-43e5-b338-d252dec387b8
  Error: RunPipeline action failed. Error: Cannot stop process "wsmprovhost (197448)" because of the following error: Access is denied Stacktrace: at Remove-BcContainerSession<Process>, C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\7c851169-5442-4168-b69c-0ed480861b7e\BcContainerHelper\ContainerHandling\Remove-NavContainerSession.ps1: line 29 at <ScriptBlock>, C:\GitHubRunners\actions-runner\_work\_actions\microsoft\AL-Go-Actions\v3.1\RunPipeline\RunPipeline.ps1: line 277 at <ScriptBlock>, C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\7c851169-5442-4168-b69c-0ed480861b7e\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2519 at <ScriptBlock>, C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\7c851169-5442-4168-b69c-0ed480861b7e\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2497 at Run-AlPipeline, C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\7c851169-5442-4168-b69c-0ed480861b7e\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 856 at <ScriptBlock>, C:\GitHubRunners\actions-runner\_work\_actions\microsoft\AL-Go-Actions\v3.1\RunPipeline\RunPipeline.ps1: line 393 at <ScriptBlock>, C:\GitHubRunners\actions-runner\_work\_temp\b1ff8ed0-4362-4371-a2c1-dbf5bebb2f12.ps1: line 2 at <ScriptBlock>, <No file>: line 1
  AL-Go action ran: RunPipeline Telemetry Correlation Id: ffc24eaf-c778-4ec2-b943-603e4b482ee9
  Get Event Log from container
  Getting event log for bc5544170557
  Removing BcContainerHelper

**Comment by freddydk** [comment]
BcContainerHelper is kill the PS Process inside the container before removing the session as this is know to have caused hanging sessions. It looks like NetWork Service is not allowed to kill the PS Session.
I will add some resilience to this (ignoring that failure and continuing to remove the contianer session without).
