### ISSUE TITLE
Run CI/CD in container with DisableWriteInsideTryFunctions = false

### ISSUE THREAD

**Issue by AndriiPrystaia** [microsoft/AL-Go#615]
Good day @freddydk .

We have CI/CD workflow for AppSource app that have a dependency to Core app - and in this Core app we use INSERT method inside Try function.

Here is an article that it is not recommended:  https://learn.microsoft.com/en-us/dynamics-nav/handling-errors-by-using-try-functions

And workflow fails with following error:

```
Error: RunPipeline action failed. Error: Could not install the extension 'Core app' on tenant 'default' and company '' due to the following error: 'Call to the function 'INSERT' is not allowed inside the call to 'TryConfigureExtensionHttpClientRequestsAllowance' when it is used as a TryFunction.' and AL stack trace:  "Core Installation"(CodeUnit 71060077).TryConfigureExtensionHttpClientRequestsAllowance line 10 - Core "Core Installation"(CodeUnit 71060077).OnInstallAppPerDatabase line 3 - Core "Extension Triggers"(CodeUnit 2000000010).OnInstallAppPerDatabase(Event) line 2  Stacktrace: at Invoke-ScriptInBcContainer, C:\Users\apr\AppData\Local\Temp\a28eeaf6-8406-43e2-886e-e700f30bbc3c\BcContainerHelper\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 112 at <ScriptBlock>, C:\Users\apr\AppData\Local\Temp\a28eeaf6-8406-43e2-886e-e700f30bbc3c\BcContainerHelper\AppHandling\Publish-NavContainerApp.ps1: line 402 at Publish-BcContainerApp, C:\Users\apr\AppData\Local\Temp\a28eeaf6-8406-43e2-886e-e700f30bbc3c\BcContainerHelper\AppHandling\Publish-NavContainerApp.ps1: line 157 at <ScriptBlock>, C:\Users\apr\AppData\Local\Temp\a28eeaf6-8406-43e2-886e-e700f30bbc3c\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 790 at <ScriptBlock>, C:\Users\apr\AppData\Local\Temp\a28eeaf6-8406-43e2-886e-e700f30bbc3c\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1158 at <ScriptBlock>, C:\Users\apr\AppData\Local\Temp\a28eeaf6-8406-43e2-886e-e700f30bbc3c\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1093 at <ScriptBlock>, C:\Users\apr\AppData\Local\Temp\a28eeaf6-8406-43e2-886e-e700f30bbc3c\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 894 at Run-AlPipeline, C:\Users\apr\AppData\Local\Temp\a28eeaf6-8406-43e2-886e-e700f30bbc3c\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 856 at <ScriptBlock>, C:\Windows\System32\actions-runner\_work\_actions\microsoft\AL-Go-Actions\v2.2\RunPipeline\RunPipeline.ps1: line 344 at <ScriptBlock>, C:\Windows\System32\actions-runner\_work\_temp\ee3a3ea3-1b34-4627-9968-b73e60b64281.ps1: line 1 at <ScriptBlock>, <No file>: line 1
AL-Go action ran: RunPipeline Telemetry Correlation Id: 16ab037f-25f2-4861-af97-4eeadc26d041
Removing BcContainerHelper
Error: Process completed with exit code 1.
```

So my question is: 
By default, for Cloud BC versions parameter DisableWriteInsideTryFunctions is false in CustomSettings.config:

```
  <!--
    Specifies whether to raise an error when AL code that is executed in the scope of a TryFunction writes to the database.
    It is recommended to update the AL code to avoid writing to the database from a TryFunction. However, in cases where this is not possible, setting this value to false allows TryFunctions to write to the database, and behave as they did in Dynamics NAV 2016.
  -->
  <add key="DisableWriteInsideTryFunctions" value="false" />
```

But for Docker version created with BcContainerHelper in Al-Go default is true.

and we have a situation that settings in our CI/CD environment is different from PROD environment. 

I tried to override parameters using: 
.AL-Go\NewBcContainer.ps1

```
Param(
    [Hashtable]$parameters
)

New-BcContainer @parameters
 
(Get-Content "C:\Program Files\Microsoft Dynamics NAV\220\Service\CustomSettings.config") | ForEach-Object {$_ -replace 'add key="DisableWriteInsideTryFunctions" value="true"','add key="DisableWriteInsideTryFunctions" value="false"'} | Set-Content -Path "C:\Program Files\Microsoft Dynamics NAV\220\Service\CustomSettings.config"

Invoke-ScriptInBcContainer -containerName $parameters.ContainerName -scriptblock { $progressPreference = 'SilentlyContinue' }
```

But unfortunately, this not helped.
Any advice will be great help.

**Comment by freddydk** [comment]
The code in NewBcContainer.ps1 is run on the host, meaning that your attempt to change the settings file is happening on the host (not inside the container). Also, changing settings requires a service tier restart.
The way to add custom settings to a container is to add this:

```
 -additionalParameters @('--env CustomNavSettings=DisableWriteInsideTryFunctions=false')
```

to New-BcContainer.
However - in $parameters, additionalparameters are already defined, so you should do this:

```powershell
Param(
    [Hashtable]$parameters
)

$parameters.additionalParameters += @('--env CustomNavSettings=DisableWriteInsideTryFunctions=false')
New-BcContainer @parameters
Invoke-ScriptInBcContainer -containerName $parameters.ContainerName -scriptblock { $progressPreference = 'SilentlyContinue' }
```

That should do the trick for now.
I will investigate and add this to the default.

**Comment by AndriiPrystaia** [comment]
@freddydk This is huge!
It works!!!
Thanks a lot. And have a great weekend!

**Comment by freddydk** [comment]
Talked to the backend team and the problem here is actually that the value in the Container (true) is correct.
This setting was created to ensure backwards compatibility (by setting it to false) and the entire idea was then that it should be true on SaaS. Something went wrong and we ended up running SaaS with this value set to false.
We will be changing that - SaaS will eventually have this value set to true, knowing that this is a breaking change - it won't happen overnight.
So,... - you can use the workaround above for now.
We are not going to change AL-Go or BcContainerHelper to change the default, as the default is the right long term value and people seeing this issue adopting the same workaround should know, that they should refactor their app to not need this workaround.
Hope this makes sense?

**Comment by AndriiPrystaia** [comment]
@freddydk thank you for thoroughly investigating this matter.
The workaround you've provided is proving to be highly effective, and the provided ready-to-use code will make implementation easy for all users.
Regarding the anticipated future change in the Saas version - setting it to true, we are committed to promptly updating our code to ensure its compatibility with the upcoming changes.
We sincerely appreciate your dedicated efforts in resolving all these specific issues in AL-Go and for developing this exceptional and convenient automation tool for Business Central.
Thank you once again for your outstanding work!
