### ISSUE TITLE
(Question) Update .gitignore / exclude launch.json?

### ISSUE THREAD

**Issue by fvet** [microsoft/AL-Go#62]
**Reference**
https://github.com/microsoft/AL-Go/blob/main/Scenarios/GetStarted.md

> 14. Back in VS Code, you will see that in addition to your changes in HelloWorld.al, the **launch.json** was also modified with the information about the local environment. Stage your changes, commit and push

1. Our current **.gitignore** template contains some extra lines not to track certain files. 
One of these is the 'launch.json', since it can be different per developer. Is it intentional to have this file tracked?

```
launch.json
```

2. When working with 3rd party extensions, some extensions add extra folders / files that should not be tracked either. What would be the recommendation for those? Contribute to the .gitignore on this repo and manage a common config (instead of creating a custom template)?

```
.alcache/
.altemplates/
```

**Comment by freddydk** [comment]
On launch.json - some of the workflows will modify the launch.json. Not sure if this would work if it is in .gitignore, will check

The .gitignore file if just copied from the template and can subsequently easily be modified per repository and is not part of the system files, which gets updated.

**Comment by freddydk** [comment]
Shipped in v0.2
