### ISSUE TITLE
Error: The environment block used to start a process cannot be longer than 65535 bytes.

### ISSUE THREAD

**Issue by mazhelez** [microsoft/AL-Go#620]
See: https://github.com/microsoft/ALAppExtensions/actions/runs/5643755210/job/15287721005?pr=24198#step:8:201:~:text=Error%3A%20RunPipeline,file%3E%3A%20line%201

> Error: RunPipeline action failed. **Error: The environment block used to start a process cannot be longer than 65535 bytes.**  Your environment block is 73068 bytes long.  Remove some environment variables and try again. Stacktrace: at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\9597813d-c355-41e8-a483-21987b0ca47b\BcContainerHelper\HelperFunctions.ps1: line 27 at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\9597813d-c355-41e8-a483-21987b0ca47b\BcContainerHelper\BcContainerHelper.psm1: line 13 at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\9597813d-c355-41e8-a483-21987b0ca47b\BcContainerHelper\Import-BcContainerHelper.ps1: line 30 at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\9597813d-c355-41e8-a483-21987b0ca47b\BcContainerHelper\BcContainerHelper.ps1: line 8 at DownloadAndImportBcContainerHelper, D:\a\_actions\microsoft\AL-Go-Actions\preview\AL-Go-Helper.ps1: line 309 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\RunPipeline\RunPipeline.ps1: line 32 at <ScriptBlock>, D:\a\_temp\a2d75a54-af6e-435b-a2de-575451996563.ps1: line 2 at <ScriptBlock>, <No file>: line 1

**Comment by freddydk** [comment]
We probably need to cleanup how we set things.
For a number of the settings, they are both in ENV:SETTINGS and ENV:APPFOLDERS
