### ISSUE TITLE
[Bug] No error message when access to KeyVault is not possible

### ISSUE THREAD

**Issue by rbability** [microsoft/AL-Go#621]
Bug is maybe a bit harsh, maybe it is just not working as I would expect ;-)

Today we had issues running the "UpdateALGoSystemFiles" Action, failing at the Step "Update AL-Go system files" with the message:

`
Error: CheckForUpdates action failed. Error: A personal access token with permissions to modify Workflows is needed. You must add a secret called GhTokenWorkflow containing a personal access token.
`

Earlier in the step "Read secrets" we spotted this:

`
AzureRm.KeyVault Module is available in version 2.1.0
AzureRm.Profile Module is available in version 2.1.0
Using AzureRM version 2.1.0
Masking value for clientSecret
Successfully connected to Azure Key Vault.
Could not find secret ghTokenWorkflow in Github secrets or Azure Key Vault.
The following secrets was not found: ghTokenWorkflow (Secret ghTokenWorkflow)
Removing BcContainerHelper
`

The KeyVault in question contains also other Secrets used by other AL-Go Actions like CI/CD or TestNextMajor etc. and they worked fine.

To make it short:
The Issue was that I earlier restricted access to this particular KeyVault from a specific IP Address / Subnet because I saw no reason that this one is accessible from all over the Internet since we use Self-Hosted runners only. Also the KeyVault includes information for Code Signing, so I do not feel very good having it accessible from everywhere.

In the end the UpdateALGoSystemFiles Action failed beause it is not running on a Self-Hosted runner by default and because of the IP restriction it was not able to access the KeyVault. It took a while to figure that out, because as you can see above, in the Logs it said "Successfully connected to Azure Key Vault" which was just not possible ;-)

It would have helped having a clearer error message here (if this is even possible for you to find out at this step) and it would be great to have this action running on a Self-hosted runner too (if possible), so we can lock down our KeyVaults and make everything a bit safer.

**Comment by freddydk** [comment]
The reason for having Update AL-Go System files always running on GitHub hosted agents is to avoid a dead-lock situation, where the self-hosted runner isn't working and you cannot run Update AL-Go System Files to change the runner.

We are looking at ways to run Update AL-Go System Files locally and create a PR from there instead to make additional ways and after that - we could change the workflow to also be able to run on self-hosted runners (as there would be a workaround).
