### ISSUE TITLE
Publish to AppSource Library App

### ISSUE THREAD

**Issue by nixpt82** [microsoft/AL-Go#624]
Im trying to publish to appsource a App that haves a dependency from other repo. It fails saying cannot find the dependency app. 

- In the /.AL-Go/settings.json i set the property "generateDependencyArtifact": true

But it seems only the main app get publish!?!

 Dependency to projects '*' in https://github.com/xxxxxxx/yyyy@main, version latest, release status release
Azure.Storage Module is available in version 2.1.0
Using Azure.Storage version 2.1.0
Attempting authentication to *** using clientCredentials...
Authenticated as app ***
AppSource MainAppFolder .\MainApp
Main App File:
-MainApp_21.2.39.0.app
Library App Files:
- None

**Comment by jonaswre** [comment]
The whole dependency handling when publishing to AppSource is not super great yet. We are currently publishing all apps to AppSource.

**Comment by freddydk** [comment]
If you set generateDependencyArtifact to true in .AL-Go\settings.json - then the build should generate a dependency artifact and that should also be delivered to AppSource (for the apps, where the publisher name is the same as the main app)
If this doesn't work, please let me know.

**Comment by nixpt82** [comment]
I did that, seems that identifies both artifacts but keeps showing

 Library App Files:
- None

**Comment by freddydk** [comment]
Would it be possible for me to get access to the repo in order to have a look at this?

**Comment by nixpt82** [comment]
@freddydk Sorry was in holidays. I will give access to the repo. 

I saw that when the app creates the request in the appsource removes the Library app from the live version to the draft version.

**Comment by nixpt82** [comment]
Is this the reason? 

 "Make sure that these dependencies are part of your submission or that they have already been uploaded to AppSource and that they are available for the targeted country/region and release"

Do we need to submit the library app before? Isnt possible to uploaded in the same request?

**Comment by freddydk** [comment]
if you set generateDependencyArtifact to true in .AL-Go/settings.json - it should include dependencies in the submission - else you need to submit the library app another way or beforehand

**Comment by nixpt82** [comment]
@freddydk i do that, i can see them getting downloaded but the Library Apps shows "None"



Downloading artifact xxxxxxxxxxx-main-Apps-1.4.49.0
https://api.github.com/repos/SK-Consulting-S-A/xxxxxxxxxxx/actions/artifacts/922653111/zip
D:\a\xxxxxxxxxxx\xxxxxxxxxxx\.artifacts\xxxxxxxxxxx-main-Apps-1.4.49.0.zip
Analyzing artifacts
https://api.github.com/repos/SK-Consulting-S-A/xxxxxxxxxxx/actions/artifacts?per_page=100&page=1
project 'xxxxxxxxxxx'
**Downloading artifact xxxxxxxxxxx-main-Dependencies-1.4.49.0
https://api.github.com/repos/SK-Consulting-S-A/xxxxxxxxxxx/actions/artifacts/922653116/zip
D:\a\xxxxxxxxxxx\xxxxxxxxxxx\.artifacts\xxxxxxxxxxx-main-Dependencies-1.4.49.0.zip
Artifacts:
- xxxxxxxxxxx-main-Apps-1.4.49.0
- xxxxxxxxxxx-main-Dependencies-1.4.49.0**
Applying settings from D:\a\xxxxxxxxxxx\xxxxxxxxxxx\.github\AL-Go-Settings.json
Applying settings from D:\a\xxxxxxxxxxx\xxxxxxxxxxx\.AL-Go\settings.json
Analyzing repository
Checking project dependencies
Azure.Storage Module is available in version 2.1.0
Using Azure.Storage version 2.1.0
Attempting authentication to https://api.partner.microsoft.com/.default using clientCredentials...
Authenticated as app ***
AppSource MainAppFolder Fisqal - xxxxxxxxxxx
Main App File:
- SK Consulting S.A._Fisqal - xxxxxxxxxxx_22.3.49.0.app
Library App Files:
- None

**Comment by nixpt82** [comment]
Hi @freddydk Did you got opportunity to check the repo? 

I look on the Delivery.ps1 action looks for some reason the counter of the libraries app, always gives 0 "Empty".

**Comment by freddydk** [comment]
A fix for this is currently in preview.
Same as #1093 and #1110
