### ISSUE TITLE
Update AL-GO system files fails.

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/AL-Go#626]
Log file attached.

Getting 

> Using template from https://github.com/microsoft/AL-Go-PTE@main)
> Using ArchiveUrl https://api.github.com/repos/microsoft/AL-Go-PTE/zipball/main)
> The remote server returned an error: (404) Not Found.
> Not Found
> 
> ...retrying in 1 minute
> Error: The remote server returned an error: (404) Not Found.
> 

[logs_213.zip](https://github.com/microsoft/AL-Go/files/12168565/logs_213.zip)

What am I missing now?

**Comment by tscottjendev** [comment]
I order to get this work, I had to specify the template repo to be different than the one in the settings file.  Not sure why, maybe it was from when @freddydk  was helping with #425.  Anyway, so I specified the url manually and somehow picked up a trailing ")" in the url.  I removed that and now the Update AL-GO system files works.  

With the updated AL-Go the CI/CD process also now works.

Why was the update failing?

**Comment by mazhelez** [comment]
Hey @tscottjendev 

Happy to hear you managed to fix the problem yourself.

It was failing because it tried to fetch the template from branch **main)** (with closing bracket at the end... yes, that is a valid branch name). However, such branch does not exist and hence the 404 error.
