### ISSUE TITLE
Error: Initialization of container failed

### ISSUE THREAD

**Issue by stoilovkr** [microsoft/AL-Go#627]
I get this error when running `microsoft/AL-Go-Actions/RunPipeline@v3.1`
On step: `Creating container`
RunPipeline action failed. Error: Initialization of container bc5670934957 failed Stacktrace: at Wait-BcContainerReady<Process>, C:\Users\runneradmin\AppData\Local\Temp\0831edbb-8a95-4ca7-8ab1-fe4cc0036fcc\BcContainerHelper\ContainerHandling\Wait-NavContainerReady.ps1: line 42 at New-BcContainer....

Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
  Exporting Application to CRONUS
  Removing Application from tenant
  Modifying Business Central Service Tier Config File for Docker
  Creating Business Central Service Tier
  Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
  Starting Business Central Service Tier
  Importing license file
  Copying Database on localhost\SQLEXPRESS from tenant to default
  Taking database tenant offline
  Copying database files
  Attaching files as new Database default
  Putting database tenant back online
  Mounting tenant database
  Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
  Sync'ing Tenant
  Tenant is Operational
  Stopping Business Central Service Tier
  Installation took 231 seconds
  Installation complete
  Initializing...
  Setting host.containerhelper.internal to 172.19.224.1 in container hosts file
  Starting Container
  Hostname is bc5670934957
  PublicDnsName is bc5670934957
  Using NavUserPassword Authentication
  Creating Self Signed Certificate
  Self Signed Certificate Thumbprint D8D[465](https://github.com/RogerAI/corpay-apps-businesscentral-extension/actions/runs/5670934957/job/15368149551#step:8:471)7BB2F3E2B076EE819F44FBB09E06F9404F
  DNS identity bc5670934957
  Modifying Service Tier Config File with Instance Specific Settings
  Modifying Service Tier Config File with settings from environment variable
  Setting EnableTaskScheduler to False
  Starting Service Tier
  Registering event sources
  Creating DotNetCore Web Server Instance
  Using application pool name: BC
  Using default container name: NavWebApplicationContainer
  Copy files to WWW root C:\inetpub\wwwroot\BC
  Create the application pool BC
  Create website: NavWebApplicationContainer without SSL
  Update configuration: navsettings.json
  Done Configuring Web Client
  Enabling Financials User Experience
  Using license file 'c:\run\my\license.bclicense'
  Import License
  Your program license does not permit you to run this version of the Business Central.
  
  Contact your system administrator to upgrade your license.
  at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
  at <ScriptBlock>, C:\Run\navstart.ps1: line 196
  at <ScriptBlock>, C:\Run\start.ps1: line 384
  at <ScriptBlock>, <No file>: line 1Error
  Using artifactUrl https://bcartifacts.azureedge.net/sandbox/22.3.58346.59037/dk
  Using installer from C:\Run\210-new
  Installing Business Central
  Installing from artifacts
  Starting Local SQL Server
  WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
  start...
  Starting Internet Information Server
  Copying Service Tier Files
  c:\dl\sandbox\22.3.58346.59037\platform\ServiceTier\Program Files
  c:\dl\sandbox\22.3.58346.59037\platform\ServiceTier\System64Folder
  Copying PowerShell Scripts
  c:\dl\sandbox\22.3.58346.59037\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
  c:\dl\sandbox\22.3.58346.59037\platform\WindowsPowerShellScripts\WebSearch
  Copying Web Client Files
  c:\dl\sandbox\22.3.58346.59037\platform\WebClient\Microsoft Dynamics NAV
  Copying ModernDev Files
  c:\dl\sandbox\22.3.58346.59037\platform
  c:\dl\sandbox\22.3.58346.59037\platform\ModernDev\program files\Microsoft Dynamics NAV
  Copying additional files
  Copying ConfigurationPackages
  C:\dl\sandbox\22.3.58346.59037\dk\ConfigurationPackages
  Copying Test Assemblies
  C:\dl\sandbox\22.3.58346.59037\platform\Test Assemblies
  Copying Extensions
  C:\dl\sandbox\22.3.58346.59037\dk\Extensions
  Copying Applications
  C:\dl\sandbox\22.3.58346.59037\platform\Applications
  Copying Applications.DK
  C:\dl\sandbox\22.3.58346.59037\dk\Applications.DK
  Copying dependencies
  Copying ReportBuilder
  Importing PowerShell Modules
  Restoring CRONUS Demo Database
  Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
  Exporting Application to CRONUS
  Removing Application from tenant
  Modifying Business Central Service Tier Config File for Docker
  Creating Business Central Service Tier
  Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
  Starting Business Central Service Tier
  Importing license file
  Copying Database on localhost\SQLEXPRESS from tenant to default
  Taking database tenant offline
  Copying database files
  Attaching files as new Database default
  Putting database tenant back online
  Mounting tenant database
  Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
  Sync'ing Tenant
  Tenant is Operational
  Stopping Business Central Service Tier
  Installation took 231 seconds
  Installation complete
  Initializing...
  Setting host.containerhelper.internal to 172.19.224.1 in container hosts file
  Starting Container
  Hostname is bc567093[495](https://github.com/RogerAI/corpay-apps-businesscentral-extension/actions/runs/5670934957/job/15368149551#step:8:501)7
  PublicDnsName is bc[567](https://github.com/RogerAI/corpay-apps-businesscentral-extension/actions/runs/5670934957/job/15368149551#step:8:573)0934957
  Using NavUserPassword Authentication
  Creating Self Signed Certificate
  Self Signed Certificate Thumbprint D8D4657BB2F3E2B076EE819F44FBB09E06F9404F
  DNS identity bc5670934957
  Modifying Service Tier Config File with Instance Specific Settings
  Modifying Service Tier Config File with settings from environment variable
  Setting EnableTaskScheduler to False
  Starting Service Tier
  Registering event sources
  Creating DotNetCore Web Server Instance
  Using application pool name: BC
  Using default container name: NavWebApplicationContainer
  Copy files to WWW root C:\inetpub\wwwroot\BC
  Create the application pool BC
  Create website: NavWebApplicationContainer without SSL
  Update configuration: navsettings.json
  Done Configuring Web Client
  Enabling Financials User Experience
  Using license file 'c:\run\my\license.bclicense'
  Import License
  Your program license does not permit you to run this version of the Business Central.
  
  Contact your system administrator to upgrade your license.
  at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
  at <ScriptBlock>, C:\Run\navstart.ps1: line 196
  at <ScriptBlock>, C:\Run\start.ps1: line 384
  at <ScriptBlock>, <No file>: line 1

Started showing up after I added our license file. But what license do we need? We are building AppSource app, we don't need On Premise, just cloud on web client.

**Comment by freddydk** [comment]
Well, either you need a license for the version of BC used or you use the CRONUS license (= no license) which should work perfectly for development in AL-Go

**Comment by stoilovkr** [comment]
Yes, if I use no license the build passes, but I get a build warning 

> When building an AppSource App, you should create a secret called LicenseFileUrl, containing a secure URL to your license file with permission to the objects used in the app.

And we obtained a license file from PartnerSource, but when I added the secure URL to our license file, it fails with this. So, I am confused, what license do we need?

**Comment by freddydk** [comment]
With BC 22 and above - the CRONUS license is fine.
For earlier versions - a license is required.
The warning will be removed in one of the next versions.
