### ISSUE TITLE
(Question) Parameter for Flush-ContainerHelperCache - keepdays 

### ISSUE THREAD

**Issue by fvet** [microsoft/AL-Go#63]
We've installed a self-hosted runner (for testing purposes) on a non-dedicated server that already contained quit some cached content under **C:\bcartifacts.cache** and pre-configured **docker images**. Some maintenance tasks on the server clean the cache / prune the outdated images after **30** days.

When running the **CI/CD** github action on a self-hosted runner, most of the cache / images had been removed on this server, probably due to the `Flush-ContainerHelperCache -keepdays 3` for self-hosted runners?

Would it be possible to configure the `-keepdays` so we can apply a different / higher value?

https://github.com/microsoft/AL-Go-Actions/blob/6fefa0c6b2088eb89b7491ec347b454b744c78ea/RunPipeline/RunPipeline.ps1#L130.

**Comment by freddydk** [comment]
Will check what we can do about this.

**Comment by freddydk** [comment]
We will add a config setting called cacheKeepDays, which default is set to 3
Note that you will need to set this in all repos using your self-hosted runner

**Comment by freddydk** [comment]
Shipped in v0.2
