### ISSUE TITLE
Name and metadata version number from CI/CD are unusable.

### ISSUE THREAD

**Issue by stoilovkr** [microsoft/AL-Go#631]
When we set the `storageContextSecretName` variable in format:
`{"StorageAccountName":StorageAccountName,"StorageAccountKey":"StorageAccountKey,"ContainerName":ContainerName,"BlobName":"{version}/{project}-{type}.zip"}`,
 the CI/CD pipeline generates the artifacts with name AND metadata coming from the build number. But we need the artifacts to be with name and metadata version of what we specify in the `app.json` file instead. Because a human needs to set those version number, when introducing breaking/non breaking changes. Is this possible to achieve? Or even the other way would work, if the bulld number takes the version of what we set in `app.json` and then it will name the artifact with that version number.

**Comment by stoilovkr** [comment]
I see that other people asked this same question several times before, so closing this one. For future references, there is already an answer in the closed issues.

**Comment by freddydk** [comment]
Yeah, the repo version number is for the project (or collection of apps).

If you set versioningStrategy to 16 in .AL-Go/settings.json, then version numbers will be the same on the repo reelase artifacts as those in the apps. It also means that all apps in the repo will have the same version number - maybe this fixes your issue?
