### ISSUE TITLE
[Cosmetic] name parameter in Actions has a leading "blank"

### ISSUE THREAD

**Issue by rbability** [microsoft/AL-Go#636]
Today I spotted that some yaml Files have a leading "blank" in the "name:" parameter.
The ones I found were:

- CI/CD
- Create release
- Current
- IncrementVersionNumber
- NextMajor
- NextMinor
- PublishToEnvironment
- Update AL-Go System Files

I stumbled upon this when we started to use the GitHub Teams integration and tried to subscribe to specific Actions / Workflows. There you can add filters and filter for example by the name of a workflow. But some did work and some did not. Until I figured out that some yaml files have a leading blank in the name and some do not.

So if you (in Teams) subscribe like this for the "Test Next Major" workflow:
`subscribe owner/reponame workflows:{name:"Test Next Major" event:"workflow_dispatch","pull_request","push","schedule"}`
the bot will never send information into your Teams channel. If you use
`subscribe owner/reponame workflows:{name:" Test Next Major" event:"workflow_dispatch","pull_request","push","schedule"}`
instead, it works because of the leading blank in the name: parameter.

It would be nice if we could have consistent name parameters in the yaml files, if this does not break anything else.

**Comment by freddydk** [comment]
The reason is really to have the workflow mostly used sorted at the top (space in front).
Currently GitHub doesn't support grouping of actions, but might do so eventually.

**Comment by freddydk** [comment]
We did this after GitHub started adding a "more workflows" button - and caused us to have a number of the most used workflows below a more... button.
Another option would of course be to prefix the lesser used ones with an _ (I did try a non-blank space - that didn't work)

**Comment by freddydk** [comment]
If somebody comes up with a better solution for sorting the workflows, then we can always change that (even though your Teams integration then will have to be edited).

**Comment by rbability** [comment]
As you described your intentions behind the naming schema, I think you already found the best solution. Thinking about it, I basically never need to click on the "more..." button when using the Actions tab on GitHub, thanks to your naming. Sometimes people tend to force sorting by prefixing a number, but this makes things hard to read. Now it is still alphabetically sorted in "2 blocks". First block the important actions alphabetically, which makes reading very quick and a 2nd block of less frequently used Actions, also alphabetically sorted. I think you nailed it.

And I see no problem if it stays for this for a long time. It will break certain GitHub Teams Bot subscriptions if you change it later, but since nobody commented on this so far, it seems that not many people are using it anyway.

Keeping it like it is, I think has the most benefit for the majority of users right now.

Thanks for explaining the reasons behind the naming to me!
