### ISSUE TITLE
The environment block ***ed to start a process cannot be longer than 65535 bytes.

### ISSUE THREAD

**Issue by thomasbook** [microsoft/AL-Go#647]
It's pulling all the org secrets we have not just the one we use??

    secrets: {
    "FASTLANE_SESSION": "***",
    "MONGO_DEV_PW": "***",
    "EXPO_USERNAME": "***",
    "FASTLANE_PASSWORD": "***",
    "ANDROID_JKS": "***",
    "AWS_ACCESS_KEY_ID": "***",
    "SLACK_TOKEN": "***",
    "ES_USER_DEV": "***",
    "MAPBOX_TOKEN": "***",
    "GOOGLE_SERVICE_ACCOUNT": "***",
    "BISON_PAYMENTS_API_URL": "***",
    "DBX_HOST": "***",
    "MAILOSAUR_API_KEY": "***",
    "FASTLANE_PASSPHRASE": "***",
    "MUI_LICENSE_KEY": "***",
    "MONGO_DEV_DATABASE_ADMIN_URL": "***",
    "AWS_SECRET_ACCESS_KEY": "***",
    "SHEETJS_TOKEN": "***",
    "PERCY_TOKEN": "***",
    "PLAY_STORE_CREDENTIALS": "***",
    "DBX_TOKEN": "***",
    "github_token": "***",
    "KUBECONFIG_PROD_EAST": "***",
    "GOOGLE_PRIVATE_KEY": "***",
    "QAQC_MONGO_DEV_PW": "***",
    "DATABRICKS_CLUSTER_ID_REPL_2": "***",
    "SLACK_WEBHOOK": "***",
    "ADMIN_PAT": "***",
    "AWS_SECRET_ACCESS_KEY_SST_DEV": "***",
    "TELIC": "***",
    "DOCKER_TOKEN": "***",
    "AWS_ACCESS_KEY_ID_SST_DEV": "***",
    "DATABRICKS_CLUSTER_ID_DATASCIENCE": "***",
    "ES_PASSWORD_DEV": "***",
    "DATABRICKS_CLUSTER_ID_REPL_81": "***",
    "APPLE_TEAM_ID": "***",
    "SAUCELABS_USER": "***",
    "PAYMENTS_LAUNCHDARKLY_SDK_CLIENT_SIDE_ID": "***",
    "GHTOKENWORKFLOW": "***",
    "SENTINEL": "***",
    "READ_ONLY_PAT": "***",
    "BUSINESS_CENTRAL_SUBSCRIPTION_KEY": "***",
    "SLACK_WEBHOOK_INFRA": "***",
    "SONAR_TOKEN": "***",
    "DOCKER_USER": "***",
    "DATABRICKS_CLUSTER_ID_REPL_73LTS": "***",
    "SHEETJS_PASSWORD": "***",
    "BUSINESS_CENTRAL_CLIENT_SECRET_V2": "***",
    "SAUCELABS_ACCESS_KEY": "***",
    "AWS_SECRET_ACCESS_KEY_SST_PROD": "***",
    "BC_LICENSEFILE": "***",
    "SLACK_API_TOKEN": "***",
    "SAUCELABS_REGION": "***",
    "MONGO_DEV_DATABASE_QAQC_URL": "***",
    "AWS_REGION": "***",
    "JIRA_TOKEN": "***",
    "EXPO_PASSWORD": "***",
    "AWS_ACCESS_KEY_ID_SST_PROD": "***",
    "DATABRICKS_CLUSTER_ID_INTEGRATIONBI": "***",
    "SHEETJS_USER": "***",
    "VAULT_ADDR": "***",
    "DSS_TOKEN": "***"
  }

**Comment by freddydk** [comment]
This issue is fixed in AL-Go Preview

**Comment by thomasbook** [comment]
This worked thanks!
