### ISSUE TITLE
Undo Transfer Error

### ISSUE THREAD

**Issue by nixpt82** [microsoft/AL-Go#648]
When we do undo of a transfer of a item with variante code in a diferent unit of measure of the Base unit. 

The system gives this error:

**Invoiced Quantity must have the same value as Quantity in Item Journal Line Journal Template Name='',Journal Batch Name='',Line No.='0'.**

AL call stack: 
"Item Jnl.-Check Line"(CodeUnit 21).RunCheck line 86 - Base Application by Microsoft
"Item Jnl.-Post Line"(CodeUnit 22).Code line 15 - Base Application by Microsoft
"Item Jnl.-Post Line"(CodeUnit 22).PostSplitJnlLine line 12 - Base Application by Microsoft
"Item Jnl.-Post Line"(CodeUnit 22).RunWithCheck line 16 - Base Application by Microsoft
"Item Jnl.-Post Line"(CodeUnit 22).OnRun(Trigger) line 3 - Base Application by Microsoft
"Undo Posting Management"(CodeUnit 5817).PostItemJnlLine line 16 - Base Application by Microsoft
"Undo Posting Management"(CodeUnit 5817).PostItemJnlLineAppliedToList line 44 - Base Application by Microsoft
"Undo Transfer Shipment"(CodeUnit 9030).PostItemJnlLine line 62 - Base Application by Microsoft
"Undo Transfer Shipment"(CodeUnit 9030).Code line 56 - Base Application by Microsoft
"Undo Transfer Shipment"(CodeUnit 9030).OnRun(Trigger) line 15 - Base Application by Microsoft
"Posted Transfer Shpt. Subform"(Page 5744).UndoShipmentPosting line 6 - Base Application by Microsoft
"Posted Transfer Shpt. Subform"(Page 5744)."UndoShipment - OnAction"(Trigger) line 2 - Base Application by Microsoft
"Transfer Order Subform"(Page 5741)."Quantity Shipped - OnDrillDown"(Trigger) line 9 - Base Application by Microsoft

**Comment by freddydk** [comment]
This doesn't seem to be an AL-Go problem.
Please use normal support channels for creating a bug on this.
