### ISSUE TITLE
Use as template button missing on github repo

### ISSUE THREAD

**Issue by SanderORBID** [microsoft/AL-Go#65]
I'm not seeing the "use as template" button in this repo.

**Comment by freddydk** [comment]
You can see the template repositories + some usage scenarios here: https://github.com/microsoft/AL-Go#al-go-for-github

**Comment by freddydk** [comment]
https://aka.ms/algopte is for PTEs (has the use as template button)
https://aka.ms/algoappsource is for appsource apps (has the use as template button)
