### ISSUE TITLE
Code sign using HSM module KeyVault not triggering during CI/CD

### ISSUE THREAD

**Issue by stoilovkr** [microsoft/AL-Go#652]
We are using a Key Vault with HSM module. During CI/CD the Sign step is not visible nor triggering. What secrets/settings should we pass so it will trigger. So far (the relevant part of) `settings.json` file is:
```
{
  "BcContainerHelperVersion": "preview",
  "applicationInsightsConnectionStringSecretName": "AZ_APPLICATION_INSIGHTS",
  "storageContextSecretName": "AZ_STORAGE_CONTEXT",
  "keyVaultCodesignCertificateName": "{valid-name-of-the-cert}"
}
```

The storageContext secret is successfully read as the CI/CD is publishing unsigned apps where we want.
I also have another Github secret called `AZURE_CREDENTIALS` with compressed json like:
`{"TenantId":"{tenant-id}","ClientId":"{client-id}","ClientSecret":"{client-secret}"}`

I haven't referenced this secret anywhere as I expect that it should be picked by the action. 

Dump from Read secrets:
Run microsoft/AL-Go-Actions/ReadSecrets@v3.1
Run try { D:\a\_actions\microsoft\AL-Go-Actions\v3.1\ReadSecrets/ReadSecrets.ps1 -settingsJson $ENV:_settingsJson -secrets $ENV:_secrets -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 5.0.5
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Masking value for clientSecret
Trying to get the secret(licenseFileUrl) from the github environment.
Could not find secret licenseFileUrl in Github secrets or Azure Key Vault.
Trying to get the secret(insiderSasToken) from the github environment.
Could not find secret insiderSasToken in Github secrets or Azure Key Vault.
Trying to get the secret(codeSignCertificateUrl) from the github environment.
Could not find secret codeSignCertificateUrl in Github secrets or Azure Key Vault.
Trying to get the secret(codeSignCertificatePassword) from the github environment.
Could not find secret codeSignCertificatePassword in Github secrets or Azure Key Vault.
Trying to get the secret(AZ_STORAGE_CONTEXT) from the github environment.
Masking value for AZ_STORAGE_CONTEXT
Secret(AZ_STORAGE_CONTEXT) was retrieved from the github environment.
Masking value for AZ_STORAGE_CONTEXT.StorageAccountKey
storageContext successfully read from secret AZ_STORAGE_CONTEXT
Trying to get the secret(gitHubPackagesContext) from the github environment.
Could not find secret gitHubPackagesContext in Github secrets or Azure Key Vault.
The following secrets was not found: licenseFileUrl (Secret licenseFileUrl), insiderSasToken (Secret insiderSasToken), codeSignCertificateUrl (Secret codeSignCertificateUrl), codeSignCertificatePassword (Secret codeSignCertificatePassword), keyVaultCertificateUrl (Secret ), keyVaultCertificatePassword (Secret ), keyVaultClientId (Secret ), gitHubPackagesContext
Removing BcContainerHelper

Screenshots from Run pipeline:
![image](https://github.com/microsoft/AL-Go/assets/55063078/bb8e694b-3615-42bf-843e-b48a41224fc2)

As I understand for the new way of code signing, we don't need to provide url and password, nor we have them. What are we missing in order to have the CI/CD sign the package.

**Comment by aholstrup1** [comment]
From your logs it looks like you're running AL-Go in version 3.1. Is that correct? The sign action is currently in preview and shipping with the next release 

If you are on preview (or upgrade to version 3.2 once that's available), here's what you'll need:
* The AZURE_CREDENTIALS secret (what you described above sounds correct)
* The keyVaultCodesignCertificateName setting (looks like you have that one already)
* You also need to provide the key vault name. There are two options for this: Either add a setting called "keyVaultName" or add `“keyVaultName” : “{your keyvault name}” ` to your AZURE_CREDENTIALS construct.

If all of these are provided, the signing should be triggered. 

Regarding your screenshot, please note that the signing does **not** happen as part of Run Pipeline, but runs in the step immediately after. 
![image](https://github.com/microsoft/AL-Go/assets/117829001/9f00a485-1bd1-4809-9712-08d448169f6f)

Let me know if that works for you or if there are any other questions to this.

**Comment by stoilovkr** [comment]
It works after I switched to preview version and added the key vault name in AZURE_CREDENTIALS. Thanks!
