### ISSUE TITLE
In preview: Using an HSM Code Signing Cert, CI/CD fails

### ISSUE THREAD

**Issue by BMI-Mike** [microsoft/AL-Go#653]
This is due to a missing mandatory settings.json parameter. 

In the Sign step of CI/CD I receive this error:

```
Secrets: {"licenseFileUrl":"***","insiderSasToken":"***","codeSignCertificateUrl":"","codeSignCertificatePassword":"","keyVaultCertificateUrl":"","keyVaultCertificatePassword":"","keyVaultClientId":"","gitHubPackagesContext":"","applicationInsightsConnectionString":""}
    artifactCacheKey: 
    containerName: bc5822555729
    _azureCredentialsJson: ***
    _timestampService: http://timestamp.digicert.com
    _digestAlgorithm: SHA256
    _pathToFiles: ./.buildartifacts/Apps/*.app
    _parentTelemetryScopeJson: 
Error: Unexpected error when running action. Error Message: Cannot process command because of one or more missing mandatory parameters: settingsJson., StackTrace: at <ScriptBlock>, D:\a\_temp\197b8bd8-df1e-[41](https://github.com/BMI-Software/OfficeProducts-AppSource/actions/runs/5822555729/job/15793900820#step:9:42)94-a21f-3f81[44](https://github.com/BMI-Software/OfficeProducts-AppSource/actions/runs/5822555729/job/15793900820#step:9:45)8729df.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
Error: Process completed with exit code 1.
```

Since I am using an HSM Cert, providing a proper keyVaultCodesignCertificateName value in .AL-Go/settings.json should be all that is required.

This was working just fine for several weeks.  All of our projects began to fail simultaneously, starting roughly 20 hours ago.

I'm not sure if this is a duplicate of #652

**Comment by freddydk** [comment]
What version of AL-Go are you running?
preview?
Did you upgrade AL-Go system Files ~20 hours ago?

**Comment by freddydk** [comment]
For now you have two options really
1. Revert the PR which updated the AL-Go System files ~20 hours ago
2. Wait for the PR I created above to be merged in and deployed to preview - will happen tomorrow morning european timezone.

**Comment by BMI-Mike** [comment]
> What version of AL-Go are you running? **AL-Go for GitHub,d15c25e25c4b0033da9f99970e3a420e231f7fbc**
preview? **Yes**
Did you upgrade AL-Go system Files ~20 hours ago? **Yes**

**Comment by BMI-Mike** [comment]
Ok, thanks Freddy.  It's currently late here in the US.  I'll first try the update in the morning.  If that doesn't work, then ill revert the PR and give that a go.

**Comment by freddydk** [comment]
You will need to update AL-Go System Files, before it works (after we submit a fix) - then it will work.

**Comment by freddydk** [comment]
New preview should be deployed now - you should be able to update and sign

**Comment by BMI-Mike** [comment]
Thank you Freddy.  I can confirm this issue has been resolved!
