### ISSUE TITLE
Error @ Read Secrets step

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#662]
Hey @freddydk , 

Has something change recently. I'm getting the following error message in our pipelines today

`Unexpected error when running action. Error Message: Cannot bind argument to parameter 'gitHubSecrets' because it is an empty string., StackTrace: at <ScriptBlock>, D:\a\_temp\25fd1a97-8bc5-4767-96f3-0a569867b550.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
`
![image](https://github.com/microsoft/AL-Go/assets/16342128/0a69c06b-576d-4aad-ae40-3353f0a1f76c)

If I try to update AlGoSystemFiles, i get the same error message

![image](https://github.com/microsoft/AL-Go/assets/16342128/15ba769a-042e-4b29-88ea-0c2f97e3d90a)

**Comment by freddydk** [comment]
I think there was an error during the latest deployment - will get this fixed asap.

**Comment by freddydk** [comment]
Could you email me the full log of your run, thanks?

**Comment by freddydk** [comment]
Found out what it was - should work again now

**Comment by freddydk** [comment]
Please re-run and let me know, thanks

**Comment by gntpet** [comment]
It's working now. Thank you @freddydk

**Comment by freddydk** [comment]
It looks like another bug in the same area.

**Comment by freddydk** [comment]
@DerekHotguns if you run Update AL-Go System files and retry, this should be hotfixed

**Comment by DerekHotguns** [comment]
@freddydk Thank you. 
Update fixes this issue. And it's generated next one. I'm not sure which environment effect this one:
![image](https://github.com/microsoft/AL-Go/assets/122437836/ea9825db-62df-400f-a725-683c6240b0c2)
Manually and by VS Code I could install the extension, but GitHub action generate error which pointed BC default object.
App registration account has broadly rights to BC.

**Comment by DerekHotguns** [comment]
Answer to my question: my fault. App registration didn't contain D365 AUTOMATION permission set. Hotfix works.
