### ISSUE TITLE
Required status checks on PRs in multi-project repos

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL-Go#667]
We set the main branch to require a successful build before a PR can be merged. This is best practice.
In multi-project repos there are multiple build jobs, one per project. But a PR only kicks off a build of the project affected by the PR (which is smart to save time).

Given a multi-project repo with projects Lib, DK and GB: If we require "Build Lib", "Build DK" and "Build GB": Then a PR for a change in DK will never meet requirements (as Lib and GB does not build).
There is no single job in the workflow that will indicate success or failure of the builds. 

Any ideas on how to get around this?

**Comment by freddydk** [comment]
I think this requires us to make a Pull Request Status Check job in the PullRequestHandler or like.

**Comment by AskeHolst** [comment]
A PR Status Check job would make it a lot easier. 
Also for set up, currently the names for the builds are different depending on whether projects are used or not. With a dedicated job, it would be easier to know what to require. When setting the required checks, you must search for the name. When searching for you get current and historic names of jobs run. A single job that hopefully never changes name  would help a lot.

**Comment by freddydk** [comment]
I will mark this with in Preview when it is available in preview.
