### ISSUE TITLE
[Parameter Request] Please expose RulesetFile

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/AL-Go#67]
Not all rules that are checked by the code analyzers always need to apply, especially when developing a PTE.
To be able to disable certain rules or to lower severity, the parameter `RulesetFile` of `Run-AlPipeline` needs to be added to `.AL-GO/settings.json`

**Comment by freddydk** [comment]
Will look at this

**Comment by freddydk** [comment]
Shipped in v0.2
