### ISSUE TITLE
Building only changed dependant projects

### ISSUE THREAD

**Issue by eh-ciellos** [microsoft/AL-Go#673]
Our scenario is as:
https://github.com/eh-ciellos/Contoso-App2/
We have three projects on the same repo. No other project on other repo is being used as a dependency.

 

App2 project is the dependency project for App2.it and App2.dk.
So, if App2 has a new change, we should have a full build.
Suppose there are changes in the App2.it, then we need to build App2.it and use the existing latest build for App2 as a dependency.

 

Our end goal is to have only the changed project built on CICD action if project is not App2. Else all three projects should be built starting from App2(dependency).

If I commit a change on App2.it\App2.it\HelloWorld.al to the "dev" branch and create a Pull Request. The Pull Request Build action will get triggered and only build this project App2.it.
As soon as I merge the Pull Request to the "main" branch, CICD gets triggered and starts building App2, App2dk, and App2.it, which were not subject to any new committed change. 
I believe this is the issue.

 

Wanted scenario: When I merge the Pull Request to the "main" branch, CICD gets triggered and starts building App2.it only. It must re-use existing latest artifacts for any dependant projects.

What can make us achieve the wanted scenario?
Do you have any suggestions/solutions regarding this issue?

The forked repos to showcase this issue are as below:
https://github.com/eh-ciellos/Contoso-App2
https://github.com/eh-ciellos/AL-Go
https://github.com/eh-ciellos/AL-Go-Actions

**Comment by freddydk** [comment]
For multi-project repositories, the CI/CD pipeline always produces full builds, which can be used for releasing etc. there are many reasons why I really don't want to go away from this.
One being this example:
1. You checkin a bug in w1 - then that build fails.
2. Now you checkin a feature in dk - that build uses the latest good w1 build and succeeds.
3. Now you release - but the source of w1 in the repo is not the same as the app build.

The suggested work mechanism is to have an open Pull Request while finalizing your feature and fixing code review issues. You will have multiple PR builds (which are incremental) and then only one complete build when you merge.

I do see that if you check-in many tiny features this process might not be the best.

You can achieve what you want by splitting your projects into multiple repositories - you could trigger a build in the depending repo when a build in the dependent repo is done.
This isn't supported out-of-the-box in AL-Go for GitHub, but can be achieved by adding a workflow to the depending repository, which gets triggered after successful builds.

**Comment by freddydk** [comment]
If you are worried about the timing, we are working on making builds much faster and splitting test execution from building, so that your workflows will finish much faster.
You can try to add these properties to .github/AL-Go-Settings.json:

useCompilerFolder: true
doNotPublishApps: true

then building will become much faster - but tests are no longer running.
We are working on that part.

**Comment by freddydk** [comment]
You can actually do one more thing - it will still build all projects, but if you instead of useProjectDependencies in .github/AL-Go-Settings.json, then create an appDependencyProbingPaths structure in the .AL-Go/settings.json for each project (like https://github.com/BusinessCentralApps/include) then it will not use nested apps building, but instead build all apps in parallel.

**Comment by eh-ciellos** [comment]
Suppose we opted for splitting our projects into multiple repositories. We ended up with three repositories: App2, App2.it and App2.dk. We made a change to App2.dk, which will use the latest artifact from App2. 
What is the purpose of building App2 when the build in App2.dk is done?

Going back to our need for 1 repository with multiple projects.
We are not so worried about timing than having all the projects in one repo for better readability and ease of use on developer side.
This scenario expects App2.dk and App2.it to be built whenever App2 gets a change merged but not the opposite.
However, if a bug was checked in App2 we are not merging the PR until it gets build successfully in the PR. So App2.dk will use the latest artifact and code too since we did not merge it.
Based on this what strategy can we use to have all our projects in one repository?

**Comment by freddydk** [comment]
> What is the purpose of building App2 when the build in App2.dk is done?

You would not set it up to build App2 when App2.dk is built - it would be the other way around.
Also, in a setup like this, the code in App2.it and App2.dk is typically very limited and many countries will use w1 (from main repo).

But... - back to having things in one repo - with AL-Go, you would have to live with the system building all projects on commit.
It is a cornerstone in AL-Go to have every CI/CD build being a complete build. I don't see a good way of creating partial commit builds with AL-Go for GitHub.

Sorry.

**Comment by freddydk** [comment]
Both fullBuildPattern and alwaysBuildAllProjects refers to the PullRequest build - not CI/CD (yes, I know documentation is wrong, will fix that).

CI/CD will always produce full builds.
