### ISSUE TITLE
Export Release Notes

### ISSUE THREAD

**Issue by naviprobeha** [microsoft/AL-Go#674]
Hello!

Is there a posibility to export the release notes (just the body text) of a release to the artifacts folder on artifact upload? 

A text file containing the release notes for a given release would enable us to communicate this to our customers and partners in a n easy manner.

/Håkan

**Comment by freddydk** [comment]
So, you want the text from the upper part here:
![image](https://github.com/microsoft/AL-Go/assets/10775043/06d5089b-b63b-4b75-b6e9-67ab41f86480)

as an asset below?

It isn't something we have on our plans as you have the ability to modify the release notes on the release after creating it, so you might have a difference?

**Comment by freddydk** [comment]
BTW - you can also get the release notes by using the GitHub CLI (if you are doing things automated):

```
gh release download 6.0.0 --repo microsoft/bcsamples-bingmaps.pte --dir c:\temp\v6.0
gh release view 6.0.0 --repo microsoft/bcsamples-bingmaps.pte > c:\temp\v6.0\releasenotes.md
```

Gives you release notes and artifacts from a release in c:\temp\v6.0

**Comment by naviprobeha** [comment]
Ah, great!
That would do the trick for us.

/Håkan
NaviPro AB

25 aug. 2023 kl. 09:52 skrev Freddy Kristiansen ***@***.***>:

﻿

BTW - you can also get the release notes by using the GitHub CLI (if you are doing things automated):

gh release download 6.0.0 --repo microsoft/bcsamples-bingmaps.pte --dir c:\temp\v6.0
gh release view 6.0.0 --repo microsoft/bcsamples-bingmaps.pte > c:\temp\v6.0\releasenotes.md


Gives you release notes and artifacts from a release in c:\temp\v6.0
