### ISSUE TITLE
Does AL-Go supports HSM Secured Certificates?

### ISSUE THREAD

**Issue by janlehmkuhl** [microsoft/AL-Go#675]
Does AL-Go Support HSM Secured Certificates? We are currently in the situation that our certificate has expired and we now have a new certificate secured with HSM.

https://github.com/microsoft/AL-Go/issues/564#issuecomment-1677202513

**Comment by janlehmkuhl** [comment]
Does anyone have an idea of how to integrate an HSM-secured certificate (DigiCert) with Azure Key Vault? To be honest, we're somewhat desperate and neither DigiCert nor Microsoft can assist us.

**Comment by janlehmkuhl** [comment]
After going back and forth with DigiCert, we found out that there was a system error when uploading the CSR file. Once that was corrected, it now works.

**Comment by freddydk** [comment]
Thanks for the update

**Comment by janlehmkuhl** [comment]
Seems to be related to our Build Agents; everything runs smoothly under the GitHub Runner.

**Comment by aholstrup1** [comment]
The error message "The file cannot be signed because it is not a recognized file type for signing or it is corrupt." sounds a bit like the NavSip.dll isn't registered successfully on your self-hosted runner. Not sure why that is though. Have you been able to sign .app files on these machines before?

**Comment by janlehmkuhl** [comment]
It is the first time ever signing an app with azuresigntool because we switched from a password-protected PFX-File to an HSM KeyVault. I will try to setup a new agent.

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Alexander Holstrup ***@***.***>
Gesendet: Wednesday, September 6, 2023 7:39:28 PM
An: microsoft/AL-Go ***@***.***>
Cc: Lehmkuhl, Jan ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/AL-Go] Does AL-Go supports HSM Secured Certificates? (Issue #675)


The error message "The file cannot be signed because it is not a recognized file type for signing or it is corrupt." sounds a bit like the NavSip.dll isn't registered successfully on your self-hosted runner. Not sure why that is though. Have you been able to sign .app files on these machines before?

**Comment by janlehmkuhl** [comment]
Unfortunately, it still fails with a new build agent. Exactly in the same place. I have installed the GitHub CLI, PowerShell 7 and the DotNET SDK 6.0 in addition to Docker. Something still seems to be wrong with this NAVSIP.dll. What could be missing?

**Comment by freddydk** [comment]
What user is the self-hosted agent running as?

**Comment by janlehmkuhl** [comment]
![image](https://github.com/microsoft/AL-Go/assets/94679485/76a4bbae-0c76-47d0-ab0f-3357a5fe31d2)

**Comment by freddydk** [comment]
Could you try to change that to Local System Account?
(which should be the same - but I am confused that there is a password)

**Comment by janlehmkuhl** [comment]
Unfortunately, this did not help.

![image](https://github.com/microsoft/AL-Go/assets/94679485/7145730b-adc8-4b68-9a70-f87301b7266f)

**Comment by freddydk** [comment]
OK - could you try to run the agents as an admin user maybe? (or network_Service)
(just to rule out that)

**Comment by janlehmkuhl** [comment]
No problem, let's find out. But the problem is still there, unfortunately. Thanks for the tips

**Comment by freddydk** [comment]
@aholstrup1 - can you find out whether the NAVSip.dll has any dependencies (maybe on some C++ runtime or like, which might not be installed on this runner)?
