### ISSUE TITLE
A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider

### ISSUE THREAD

**Issue by Bartvt21** [microsoft/AL-Go#682]
Hello,

We are using AL-Go AppSource App Template to build our app for the AppSource. We have set the following secrets: LicenseFileUrl, CodeSignCertificateUrl and CodeSignCertificatePassword. When building we ran into the following error:

`Unexpected error when running action. Error Message: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider. (0x800B0109), StackTrace: at Invoke-ScriptInBcContainer, C:\Users\runneradmin\AppData\Local\Temp\70019b3c-f5b0-4ac6-9187-5cb0363658a1\BcContainerHelper\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 112 <- at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\70019b3c-f5b0-4ac6-9187-5cb0363658a1\BcContainerHelper\AppHandling\Publish-NavContainerApp.ps1: line 403 <- at Publish-BcContainerApp, C:\Users\runneradmin\AppData\Local\Temp\70019b3c-f5b0-4ac6-9187-5cb0363658a1\BcContainerHelper\AppHandling\Publish-NavContainerApp.ps1: line 157 <- at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\70019b3c-f5b0-4ac6-9187-5cb0363658a1\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 792 <- at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\70019b3c-f5b0-4ac6-9187-5cb0363658a1\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2111 <- at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\70019b3c-f5b0-4ac6-9187-5cb0363658a1\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2080 <- at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\70019b3c-f5b0-4ac6-9187-5cb0363658a1\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2065 <- at <ScriptBlock>, C:\Users\runneradmin\AppData\Local\Temp\70019b3c-f5b0-4ac6-9187-5cb0363658a1\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 896 <- at Run-AlPipeline, C:\Users\runneradmin\AppData\Local\Temp\70019b3c-f5b0-4ac6-9187-5cb0363658a1\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 858 <- at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v3.2\RunPipeline\RunPipeline.ps1: line 363 <- at <ScriptBlock>, D:\a\_temp\abb9e6dd-bc40-4d59-80d4-c5b3ef1505d8.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1`

Is our certificate not supported by the trust provider?. Does anyone have some information about this?

Thanks in advance!

Kind Regards,

Bart van Tongeren

**Comment by freddydk** [comment]
Is this a self-signed certificate?
If not, where did you buy your certificate? and when?
What is the expiration date?

**Comment by Bartvt21** [comment]
Is is not a signed certifcate. We bought the certificate at Xolphin SSL Cerficaten and it is provided by [Sectigo ](https://www.sectigo.com/)

Expiration date is ~06-07-26.

**Comment by Bartvt21** [comment]
Hello @freddydk,

We wanted to inquire if there might be a possible solution available for the current issue. Our development process has encountered a bit of a standstill, and we find ourselves in the position of needing to make a decision regarding the pipeline we should employ. Your insights and assistance in this matter are greatly appreciated.

Thank you in advance for your time and consideration.

**Comment by freddydk** [comment]
And the certificate is a code signing certificate? (not a SSL certificate)
I was pretty sure that code signing certificates issued in July needed to be on a hardware module or a HSM keyvault???

**Comment by Bartvt21** [comment]
It is a code signing certificate and we got it on a hardware module (usb stick) and by email.

Our supplier instructed us also to install three other certificates. Two intermediate and one root certificate.

**Comment by freddydk** [comment]
I don't think you can use the old way of doing code signing with the new certificates.
I think you need to have the certificate in a HSM KeyVault and then use the new Sign Action.

**Comment by freddydk** [comment]
Also, I have never heard about these 3 certificates before - but if they need to be installed in order to code sign the "old" way, then maybe they should be installed in the container???

**Comment by freddydk** [comment]
@Bartvt21 could you describe to other people what the problem was?
It might help other people coming here with the same issue.

Thanks

**Comment by Bartvt21** [comment]
Our solution was to add an Azure KeyVault and install our certificate there instead of just specifying the secrets: CodeSignCertificateUrl and CodeSignCertificatePassword.

**Comment by teadypicker** [comment]
@Bartvt21 can you please describe the way you added your certificate to Azure from the USB? We purchased a USB with a Code Signing Certificate in Sectigo and looking for the way to transfer it to  Azure.

**Comment by Bartvt21** [comment]
@teadypicker we currently sign the apps locally on a computer with the Code Signing Certificate as we yet did not found a solution to use the token on the online pipeline. But we are still investigating on this.

@freddydk do you maybe have a suggestion on how to use Code Signing Certificates on hardware tokens? Or are there still Code Signing Certificates available without a hardware token?

**Comment by freddydk** [comment]
It needs to be in an HSM Azure KeyVault for AL-Go to use it.
