### ISSUE TITLE
Feature Request: Different failOn settings per different Actions

### ISSUE THREAD

**Issue by jmaherBMI** [microsoft/AL-Go#696]
I would like to be able to specify the setting failOn as warning for my CI/CD action but not for my Test Next Major action.  Is this something that is currently possible?

**Comment by freddydk** [comment]
in the .github folder you will find workflow specific settings files.
If you move the global "failon" setting to .github/AL-Go-Settings.json - then you can override it in the workflow specific settings files.

If you prefer to have "failon" in the project settings file (.AL-Go/settings.json), then you can also use conditional settings in your project settings.
https://aka.ms/algosettings#conditional-settings

**Comment by jmaherBMI** [comment]
Thank you for the quick response!
