### ISSUE TITLE
[Preview] Deployment to Production fails

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#697]
Latest Preview throws error when deploying to production.

```Error: Unexpected error when running action. Error Message: The property 'EnvironmentType' cannot be found on this object. Verify that the property exists., StackTrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go\cd65fef534b14be11e4d0e3c9905869fad786d36\Actions\Deploy\Deploy.ps1: line 152 <- at <ScriptBlock>, D:\a\_temp\79601050-54d4-49ce-b85b-ddc049eab844.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1```

Setup used to setup the environment: https://github.com/microsoft/AL-Go/blob/main/Scenarios/RegisterProductionEnvironment.md

Thanks

**Comment by freddydk** [comment]
Will have a look at this right away

**Comment by freddydk** [comment]
QQ - did the Publish To Environment create a new environment in your repo settings?

**Comment by jonaswre** [comment]
The environment existed before I ran the workflow. And no new environment was created.

**Comment by freddydk** [comment]
OK - I found the issue - will deploy a fix in a bit

**Comment by jonaswre** [comment]
Thanks, alot.

**Comment by freddydk** [comment]
If you Update AL-Go System Files - it should work again.

**Comment by jonaswre** [comment]
It works again. Thanks. 

Feel free to close the issue
