### ISSUE TITLE
Remove Warning Message for Designated Build-Agents in AL-Go Configuration

### ISSUE THREAD

**Issue by janlehmkuhl** [microsoft/AL-Go#700]
We currently have a large number of repositories running on AL-Go. To better distribute the workload across our build agents, we want to assign specific tasks to designated build agents. Once a week, we want all repositories to be checked for the Next Minor version. A designated build agent should handle this task so that it can process all repositories in sequence and only have to download the latest Next Minor version once. This way, other build agents won't be blocked the next day if all available build agents are still occupied with Next Minor tests.

For example, we have set the "gitHubRunner" property to "nextminor" in the .github/NextMinor.settings.json for the Next Minor pipelines. The same goes for Next Major. As a result, the build job is really only executed by a build agent with the "nextminor" tag. The only thing that bothers us is the error message GitHub displays, even though it generally works as intended and we find the current setup useful.

Furthermore, we've set up organization-wide ALGoOrgSettings. These settings specify that all jobs are run by self-hosted runners, including those with the additional "nextminor" and "nextmajor" tags.

**From our perspective, everything works as we envision it, but the error message is bothering us. My question, therefore, is: Is it intended in AL-Go for us to configure our repositories this way, and if so, can the error message be removed?**

![image](https://github.com/microsoft/AL-Go/assets/94679485/74d40519-dada-4c54-8c5d-17f518ed9add)
![image](https://github.com/microsoft/AL-Go/assets/94679485/24247cdd-f9e7-423f-ba97-3193cbf25d6c)

**Comment by freddydk** [comment]
The warning is a bug.
The Warning should be there when githubRunner is defined in project settings files (as this isn't used), but it is totally OK to define githubRunner in workflow settings files.
