### ISSUE TITLE
Inconsistent AuthTokenSecret Behavior in Multiple Projects: 'Secrets are not available' Error in Main and Preview Versions of AL-Go, Potential BcContainerHelper Issue

### ISSUE THREAD

**Issue by janlehmkuhl** [microsoft/AL-Go#708]
Currently, we are facing an issue in multiple projects where appDependencyProbingPath is encountering problems with AuthTokenSecret. Despite a secret being displayed in the PowerShell session, LocalDevEnv.ps1 still prints the message 'Secrets are not available.' The Problem exists in Main and Preview Version of AL-Go. Maybe an BcContainerHelper Issue?

![image](https://github.com/microsoft/AL-Go/assets/94679485/ec1772ed-b05f-41a4-9652-f401bc5e89ab)

![image](https://github.com/microsoft/AL-Go/assets/94679485/417dba3e-af70-4060-8d57-5a2057581035)

**Comment by janlehmkuhl** [comment]
With this template repository "freddydk/AL-Go@issue708" it works.

**Comment by freddydk** [comment]
I will deploy to preview tonight - then you would need to switch the repos over to preview (before I remove the issue708 branch from my fork).
If you forget one - then I will have to recreate a branch with that name for you to run anything (including Update AL-Go System Files).

**Comment by curateideas** [comment]
Hello @freddydk , since @janlehmkuhl is out-of-office, I'm taking over communication. We did a couple of tests with the latest fix today and it seems, that problem is resolved.
