### ISSUE TITLE
Previous Apps dependency not installed.

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#709]
I want to remove a dependency from an PTE that was already released before. 

But there seems to be an issue with the current way dependencies are handled when installing a previous app.

Dependencies are only calculated based on the current version not on the previous version. This means if you need a dependency for the previous version it needs to be present in the current. Which means you can't remove dependencies if they are ever released in github.

**Comment by jonaswre** [comment]
@freddydk do you need a repo to reproduce?

**Comment by freddydk** [comment]
If possible, yes please:-)

**Comment by jonaswre** [comment]
I've created a setup to reproduce this.

https://github.com/byndit/TestRepo1
https://github.com/byndit/TestRepo2

Steps I've taken:
1. Create TestRepo1
2. Add TestApp1
3. Run CI/CD (TestRepo1)
4. Create TestRepo2
5. Add TestApp2
6. Add a dependency in TestApp2 to TestApp1
7. Run CI/CD (TestRepo2)
8. Create a release (TestRepo2)
9. Remove dependency to TestApp1
10. Run CI/CD 

And the CI/CD in TestRepo2 fails now.

**Comment by freddydk** [comment]
Got it, I understand why this happens
Will consider what to do....

**Comment by jonaswre** [comment]
thx. do you still need the repos?

**Comment by freddydk** [comment]
The fix for this is in the next version of ContainerHelper.
Including unknown app dependencies from previous apps.
Note that if the previous apps use an earlier version of an app (and is incompatible with the version used by your app), then that situation is not (and wasn't) supported.
In a case like that, you would have to set the project setting skipUpgrade to true.

**Comment by jonaswre** [comment]
Thanks alot this is fixed it for me. Feel free to close this issue when you see fit.

**Comment by freddydk** [comment]
Thanks for the info - and thanks for the very detailed repro repos - makes it much easier to understand and fix issues like this.

**Comment by freddydk** [comment]
Shipped in v4.0
