### ISSUE TITLE
Questions about Al-Go-PTE

### ISSUE THREAD

**Issue by Steven-Bale** [microsoft/AL-Go#71]
Hello, 

First of all, thanks for these two samples for CI\CD, it makes my life easier for CI-CD. :)

It's not an issue but a question : i want to push some apps on AppSource but some of my customers wants to have these apps on BC sandboxes (and porduction)

For now, i installed with ranges 50000..99999 on customers tenant with AL-Go-PTE but i want to install them with their "appsource" ranges before they are available in AppSource (just to avoid to lose data because the ranges are not the same)

Is there any possibilities to publish these apps (with appsource ranges) on customer tenants (sandbox and production) with the AL-Go-PTE ?

I tried but i have an error message :

Run microsoft/AL-Go-Actions/RunPipeline@v0.2
Run D:\a\_actions\microsoft\AL-Go-Actions\v0.2\RunPipeline/runpipeline.ps1 -actor 'Steven-Bale' -token '***' -parentTelemetryScopeJson '{"Parameters":{},"Emitted":false,"CorrelationId":"7f264268-03a2-4881-b26c-d3ad4a68538a","ParentId":"","AllParameters":{},"TopId":"7f264268-03a2-4881-b26c-d3ad4a68538a","Name":"AL-Go workflow ran: CiCd","StartTime":"\/Date(1647865971408)\/","Properties":{"eventId":"DO0091","bcContainerHelperVersion":"3.0.3","isAdministrator":"True","stackTrace":"[\n  InitTelemetryScope at TelemetryHelper.ps1: line 204\n  CreateScope at TelemetryHelper.psm1: line 44\n  WorkflowInitialize.ps1 at WorkflowInitialize.ps1: line 17\n  0833bd42-d139-47ee-b546-e56b5688c612.ps1 at 0833bd42-d139-47ee-b546-e56b5688c612.ps1: line 1\n  \u003cScriptBlock\u003e at \u003cNo file\u003e\n]"},"EventId":"DO0091"}' -project '.' -settingsJson '{"testDependencies":[],"ghTokenWorkflowSecretName":"GhTokenWorkflow","cacheKeepDays":3,"skipUpgrade":false,"templateUrl":"https://github.com/microsoft/AL-Go-PTE@v0.2","SendExtendedTelemetryToMicrosoft":false,"appFolders":["app"],"installTestApps":[],"failOn":"error","templateBranch":"","keyVaultCertificateUrlSecretName":"","repoVersion":"1.0","githubRunner":"windows-latest","keyVaultClientIdSecretName":"","artifact":"","licenseFileUrlSecretName":"LicenseFileUrl","customCodeCops":[],"storageContextSecretName":"StorageContext","keyVaultName":"","runNumberOffset":0,"installPerformanceToolkit":false,"appSourceCopMandatoryAffixes":[],"keyVaultCertificatePasswordSecretName":"","additionalCountries":[],"doNotBuildTests":false,"applicationDependency":"18.0.0.0","appRevision":0,"alwaysBuildAllProjects":false,"installOnlyReferencedApps":true,"installTestFramework":false,"country":"fr","enableCodeCop":false,"appDependencies":[],"installTestLibraries":false,"memoryLimit":"","testFolders":[],"repoName":"Project1","codeSignCertificateUrlSecretName":"CodeSignCertificateUrl","installTestRunner":false,"rulesetFile":"","cacheImageName":"my","type":"PTE","PartnerTelemetryConnectionString":"","codeSignCertificatePasswordSecretName":"CodeSignCertificatePassword","companyName":"","adminCenterApiCredentialsSecretName":"AdminCenterApiCredentials","doNotRunTests":false,"enableUICop":false,"appDependencyProbingPaths":[{"projects":"*","release_status":"release","repo":"https://github.com/salaniko/SBSI-Spare-Brained-Licensing.git","version":"1.0"}],"installApps":[],"insiderSasTokenSecretName":"InsiderSasToken","MicrosoftTelemetryConnectionString":"InstrumentationKey=84bd9223-67d4-4378-8590-9e4a46023be2;IngestionEndpoint=https://westeurope-1.in.applicationinsights.azure.com/","versioningStrategy":0,"appBuild":4}' -secretsJson '{"licenseFileUrl":"","insiderSasToken":"","CodeSignCertificateUrl":"","CodeSignCertificatePassword":"","KeyVaultCertificateUrl":"","KeyVaultCertificatePassword":"","KeyVaultClientId":"","StorageContext":""}'
Downloading BcContainerHelper latest version
BcContainerHelper version 3.0.3
BcContainerHelper emits usage statistics telemetry to Microsoft
use settings and secrets
Analyzing repository
Downloading dependencies ...
Getting all the artifacts from probing paths
Getting releases from https://github.com/salaniko/SBSI-Spare-Brained-Licensing.git
Analyzing releases https://api.github.com/repos/salaniko/SBSI-Spare-Brained-Licensing/releases
Downloading release 1.0
project '*'
https://api.github.com/repos/salaniko/SBSI-Spare-Brained-Licensing/releases/assets/59857176
Getting all the artifacts from probing paths
Getting releases from https://github.com/salaniko/SBSI-Spare-Brained-Licensing.git
Analyzing releases https://api.github.com/repos/salaniko/SBSI-Spare-Brained-Licensing/releases
Downloading release 1.0
project '*'
Analyzing releases https://api.github.com/repos/sbsi-salaniko/Project1/releases
Using 1.0 as previous release
Downloading release 1.0
project '*'
https://api.github.com/repos/sbsi-salaniko/Project1/releases/assets/60109387
D:\a\Project1\Project1\artifacts\Project1-Apps-1.0.1.0.zip
Invoke Run-AlPipeline
Parameters
Pulling Generic Image
Creating Container
Resolving dependencies
Installing apps
Compiling apps
Removing Container
Run-AlPipeline Telemetry Correlation Id: 96f321f2-7b99-45c9-b[66](https://github.com/sbsi-salaniko/Project1/runs/5627065088?check_suite_focus=true#step:5:66)7-69fe6eede481
Error: App generation failed with exit code 1
AL-Go action ran: RunPipeline Telemetry Correlation Id: 5d51ce9f-4172-4e8b-b25e-a34a1f2[163](https://github.com/sbsi-salaniko/Project1/runs/5627065088?check_suite_focus=true#step:5:163)7e
Removing BcContainerHelper
Error: Process completed with exit code 1.

Thanks.
Steven.

**Comment by freddydk** [comment]
You cannot install an AppSource App on a production environment without having the app in AppSource.
You can install an AppSource App on a sandbox environment in the Dev Scope.
Using https://aka.ms/al-go-appsource should do this when publishing your app to sandbox environments as part of CD.
