### ISSUE TITLE
Validate with specific BC-version

### ISSUE THREAD

**Issue by naviprobeha** [microsoft/AL-Go#712]
For use with customers on on-prem, we would like to force validation with a specific BC version. In this case BC21.
Is there a setting to force this?

Regards
Håkan

**Comment by freddydk** [comment]
If you set the `artifact` setting in the project settings file, you control which artifacts are used for building.
https://aka.ms/algosettings#artifact

**Comment by naviprobeha** [comment]
Great! Just to be sure:

I set the "artifact"-parameter to "21.3" in order to expect the 21.3-version of BC. I have already set the country to "se" in the file.
But that resultet in a "not found"-exception.

Is there a sertain format for the wildcard?

**Comment by freddydk** [comment]
Examples of:
```
<storageaccount>/<type>/<version>/<country>/<select>
```
would be
```
//21.3/us/latest
```
or
```
/sandbox/21.5.1234.1234/dk/closest
```
etc.
