### ISSUE TITLE
Use of <environment>_AuthContextSecretName

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#720]
By way of clarification regarding the aliased AuthContext values: Assuming I have an environment JMDEV, with an environment secret called just AUTHCONTEXT (not JMDEV_AuthContext). Is this the proper syntax for aliasing that secret to another environment?

"repoVersion": "22.1",
"versioningstrategy": 16,
"JMDEMO_AuthContextSecretName":"JMDEV_AuthContext",

For more clarity, here is the log from the workflow that updated the Settings file:

Run $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 5.0.5
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Masking value for clientSecret
Trying to get the secret(JMDEMO-AuthContext) from the github environment.
Could not find secret JMDEMO-AuthContext in Github secrets or Azure Key Vault.
Trying to get the secret(JMDEV_AuthContext) from the github environment.
Could not find secret JMDEV_AuthContext in Github secrets or Azure Key Vault.
Trying to get the secret(AuthContext) from the github environment.
Masking value for AuthContext
Secret(AuthContext) was retrieved from the github environment.
Masking value for AuthContext.RefreshToken
Masking value for AuthContext.ClientID
AuthContext successfully read from secret AuthContext
Trying to get the secret(JMDEMO-EnvironmentName) from the github environment.
Could not find secret JMDEMO-EnvironmentName in Github secrets or Azure Key Vault.
Trying to get the secret(JMDEMO_EnvironmentName) from the github environment.
Could not find secret JMDEMO_EnvironmentName in Github secrets or Azure Key Vault.
Trying to get the secret(EnvironmentName) from the github environment.
Could not find secret EnvironmentName in Github secrets or Azure Key Vault.
Trying to get the secret(projects) from the github environment.
Could not find secret projects in Github secrets or Azure Key Vault.
The following secrets was not found: JMDEMO-AuthContext, JMDEMO_AuthContext (Secret JMDEV_AuthContext), JMDEMO-EnvironmentName, JMDEMO_EnvironmentName, EnvironmentName, projects
Removing BcContainerHelper

**Comment by buzzwick** [comment]
I was trying to avoid the trouble of creating a new AUTHCONTEXT for JMDEMO, but in the end that is what seems to have done it.  The settings file now contains these lines, but as you mention I think the second one should be unnecessary:

 "JMDEMO_AuthContextSecretName":"JMDEV_AuthContext",
  "JMDEMO_AuthContextSecretName": "AuthContext",

Is the difference between JMDEMO-AuthContext and JMDEMO_AuthContext explained somewhere, or is that just covering all the bases by checking for both underscore and hypenation?

**Comment by freddydk** [comment]
No difference - checking for both.
One of these are not allowed in GitHub secrets - the other is not in Azure KeyVault (I think)

**Comment by freddydk** [comment]
You should not need the JMDEV_AuthContextSecretName - any chance I can see this?

**Comment by buzzwick** [comment]
You should have write access to this repository CAI-Software-Inc/Precious-Metals-Solution. If not, let me know.

**Comment by freddydk** [comment]
Will have a look tomorrow, thanks

**Comment by freddydk** [comment]
I cannot see which secrets and environments exists with just write access - not sure whether maintainer or admin is needed.

**Comment by buzzwick** [comment]
I made you an Owner for now; we can do a teams call any time today after 3pm EST. Which might be late for you.

**Comment by freddydk** [comment]
Got it, now I understand what is going on...

By creating the AUTHCONTEXT secret underneath an environment in GitHub, it is ONLY accessible while deploying to that environment - in that case you cannot use it from other environments.

If you create a repository secret called AUTHCONTEXT - it becomes the default AUTHCONTEXT for ALL environments.

If you create a repository secret called JMDEV_AUTHCONTEXT - it becomes the default for JMDEV environment ONLY and you can use the secretname construct to use it from other environments.

Hope this helps.

**Comment by buzzwick** [comment]
Actually, that makes perfect sense. Not that I would have been able to figure it out, but it does makes sense of the AUTHCONTEXT, <Repository>AUTHCONTEXT, and <ENVIRONMENT>_AUTHCONTEXT hierarchy. Which is indeed a hierarchy, just like all the Settings file levels. 

I will rearrange some authcontext secrets (wish I could just rename them) and retest. Extremely helpful, thank you.

**Comment by buzzwick** [comment]
That seems to have got rid of the AuthContext errors. We did get one new error on a deployment, see the bottom of the log:
Current runner version: '[2](https://github.com/CAI-Software-Inc/Precious-Metals-Solution/actions/runs/6332443113/job/17199295226#step:1:2).309.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095[6](https://github.com/CAI-Software-Inc/Precious-Metals-Solution/actions/runs/6332443113/job/17199295226#step:1:7)38e18286ca9a3d1956744)
Download action repository 'actions/download-artifact@v3' (SHA:9bc31d5ccc31df68ecc42ccf4149144866c47d8a)
Download action repository 'microsoft/AL-Go-Actions@v3.2' (SHA:04af70430923a[11](https://github.com/CAI-Software-Inc/Precious-Metals-Solution/actions/runs/6332443113/job/17199295226#step:1:13)71b8a52f81bd00bb4dd9[17](https://github.com/CAI-Software-Inc/Precious-Metals-Solution/actions/runs/6332443113/job/17199295226#step:1:21)9fc)
Complete job name: Deploy to JMDEV
7s
Run actions/checkout@v3
Syncing repository: CAI-Software-Inc/Precious-Metals-Solution
Getting Git version info
Temporarily overriding HOME='D:\a\_temp\82d927a1-1cff-4590-8316-43c7ca5f63a1' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
"C:\Program Files\Git\bin\git.exe" config --global --add safe.directory D:\a\Precious-Metals-Solution\Precious-Metals-Solution
Deleting the contents of 'D:\a\Precious-Metals-Solution\Precious-Metals-Solution'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
Determining the checkout info
Checking out the ref
"C:\Program Files\Git\bin\git.exe" log -1 --format='%H'
'1e03dff96f78c94d14ef4cb97249dc6762bf24ea'
1s
Run actions/download-artifact@v3
No artifact name specified, downloading all artifacts
Creating an extra directory for each artifact that is being downloaded
starting download of artifact Precious-Metals-Solution-main-Apps-22.1.30.0 : 1/2
Total number of files that will be downloaded: 1
starting download of artifact Precious-Metals-Solution-main-BuildOutput-22.1.30.0 : 2/2
Total number of files that will be downloaded: 1
There were 2 artifacts downloaded
Artifact Precious-Metals-Solution-main-Apps-22.1.30.0 was downloaded to D:\a\Precious-Metals-Solution\Precious-Metals-Solution\.artifacts\Precious-Metals-Solution-main-Apps-22.1.30.0
Artifact Precious-Metals-Solution-main-BuildOutput-22.1.30.0 was downloaded to D:\a\Precious-Metals-Solution\Precious-Metals-Solution\.artifacts\Precious-Metals-Solution-main-BuildOutput-22.1.30.0
Artifact download has finished successfully
16s
Run $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
27s
Run microsoft/AL-Go-Actions/ReadSettings@v3.2
Run $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 5.0.7
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Applying settings from D:\a\Precious-Metals-Solution\Precious-Metals-Solution\.github\AL-Go-Settings.json
Applying settings from D:\a\Precious-Metals-Solution\Precious-Metals-Solution\.AL-Go\settings.json
SETTINGS:
{
    "keyVaultCertificateUrlSecretName":  "",
    "microsoftTelemetryConnectionString":  "InstrumentationKey=84bd9223-67d4-4378-8590-9e4a46023be2;IngestionEndpoint=https://westeurope-1.in.applicationinsights.azure.com/",
    "type":  "AppSource App",
    "sendExtendedTelemetryToMicrosoft":  false,
    "appBuild":  30,
    "installTestApps":  [

                        ],
    "versioningStrategy":  16,
    "installApps":  [

                    ],
    "installTestLibraries":  false,
    "runNumberOffset":  0,
    "codeSignCertificatePasswordSecretName":  "codeSignCertificatePassword",
    "vsixFile":  "",
    "country":  "us",
    "partnerTelemetryConnectionString":  "",
    "insiderSasTokenSecretName":  "insiderSasToken",
    "doNotRunTests":  false,
    "runs-on":  "windows-latest",
    "generateDependencyArtifact":  false,
    "templateUrl":  "https://github.com/microsoft/AL-Go-AppSource@main",
    "keyVaultCertificatePasswordSecretName":  "",
    "rulesetFile":  "",
    "shell":  "powershell",
    "memoryLimit":  "",
    "keyVaultClientIdSecretName":  "",
    "testFolders":  [

                    ],
    "githubRunner":  "windows-latest",
    "doNotBuildTests":  false,
    "environments":  [

                     ],
    "companyName":  "",
    "assignPremiumPlan":  false,
    "artifact":  "https://bcartifacts.azureedge.net/sandbox/22.0.54157.55210/us",
    "ghTokenWorkflowSecretName":  "ghTokenWorkflow",
    "enableTaskScheduler":  false,
    "enableCodeCop":  false,
    "DeployToJMDEV":  {
                          "EnvironmentName":  "DEV"
                      },
    "repoVersion":  "22.1",
    "doNotPublishApps":  true,
    "JMDEMO_AuthContextSecretName":  "JMUAT_AUTHCONTEXT",
    "githubRunnerShell":  "powershell",
    "appFolders":  [

                   ],
    "cacheKeepDays":  3,
    "bcptTestFolders":  [

                        ],
    "updateDependencies":  false,
    "cacheImageName":  "my",
    "treatTestFailuresAsWarnings":  false,
    "additionalCountries":  [

                            ],
    "licenseFileUrlSecretName":  "licenseFileUrl",
    "enableUICop":  false,
    "customCodeCops":  [

                       ],
    "appDependencies":  [

                        ],
    "doNotRunBcptTests":  false,
    "skipUpgrade":  false,
    "DeployToWRDEMO":  {
                           "EnvironmentName":  "DEMO"
                       },
    "appDependencyProbingPaths":  [
                                      {
                                          "release_status":  "latestBuild",
                                          "repo":  "CAI-Software-Inc/Precious-Metals-Solution"
                                      }
                                  ],
    "useCompilerFolder":  false,
    "installTestFramework":  false,
    "keyVaultCodesignCertificateName":  "",
    "installOnlyReferencedApps":  true,
    "obsoleteTagMinAllowedMajorMinor":  "",
    "applicationDependency":  "[18](https://github.com/CAI-Software-Inc/Precious-Metals-Solution/actions/runs/6332443113/job/17199295226#step:1:22).0.0.0",
    "applicationInsightsConnectionStringSecretName":  "applicationInsightsConnectionString",
    "appSourceCopMandatoryAffixes":  [
                                         "CAI"
                                     ],
    "keyVaultName":  "",
    "failOn":  "error",
    "DeployToRMPRODUCTION":  {
                                 "EnvironmentName":  "PRODUCTION"
                             },
    "projects":  [

                 ],
    "JMDEV_AuthContextSecretName":  "JMUAT_AUTHCONTEXT",
    "DeployToRMDEMO":  {
                           "EnvironmentName":  "DEMO"
                       },
    "testDependencies":  [

                         ],
    "appRevision":  0,
    "codeSignCertificateUrlSecretName":  "codeSignCertificateUrl",
    "configPackages":  [

                       ],
    "useProjectDependencies":  false,
    "unusedALGoSystemFiles":  [

                              ],
    "buildModes":  [

                   ],
    "DeployToJMUAT":  {
                          "EnvironmentName":  "UAT"
                      },
    "templateBranch":  "",
    "installPerformanceToolkit":  false,
    "PullRequestTrigger":  "pull_request_target",
    "doNotSignApps":  false,
    "repoName":  "Precious-Metals-Solution",
    "DeployToJMDEMO":  {
                           "EnvironmentName":  "Sandbox"
                       },
    "alwaysBuildAllProjects":  false,
    "DeployToWRPRODUCTION":  {
                                 "EnvironmentName":  "PRODUCTION"
                             },
    "installTestRunner":  false,
    "adminCenterApiCredentialsSecretName":  "adminCenterApiCredentials"
}
GitHubRunnerJson="windows-latest"
GitHubRunnerShell=powershell
Removing BcContainerHelper
[19](https://github.com/CAI-Software-Inc/Precious-Metals-Solution/actions/runs/6332443113/job/17199295226#step:1:23)s
Run microsoft/AL-Go-Actions/ReadSecrets@v3.2
Run $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 5.0.7
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Masking value for clientSecret
Trying to get the secret(JMDEV-AuthContext) from the github environment.
Could not find secret JMDEV-AuthContext in Github secrets or Azure Key Vault.
Trying to get the secret(JMUAT_AUTHCONTEXT) from the github environment.
Masking value for JMUAT_AUTHCONTEXT
Secret(JMUAT_AUTHCONTEXT) was retrieved from the github environment.
Masking value for JMUAT_AUTHCONTEXT.RefreshToken
Masking value for JMUAT_AUTHCONTEXT.ClientID
JMDEV_AuthContext successfully read from secret JMUAT_AUTHCONTEXT
Trying to get the secret(AuthContext) from the github environment.
Could not find secret AuthContext in Github secrets or Azure Key Vault.
Trying to get the secret(JMDEV-EnvironmentName) from the github environment.
Could not find secret JMDEV-EnvironmentName in Github secrets or Azure Key Vault.
Trying to get the secret(JMDEV_EnvironmentName) from the github environment.
Could not find secret JMDEV_EnvironmentName in Github secrets or Azure Key Vault.
Trying to get the secret(EnvironmentName) from the github environment.
Could not find secret EnvironmentName in Github secrets or Azure Key Vault.
Trying to get the secret(projects) from the github environment.
Could not find secret projects in Github secrets or Azure Key Vault.
The following secrets was not found: JMDEV-AuthContext, AuthContext, JMDEV-EnvironmentName, JMDEV_EnvironmentName, EnvironmentName, projects
Removing BcContainerHelper
14s
Run $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
Using JMDEV_AuthContext secret as AuthContext
environmentName=DEV
environmentName (as Base64)=REVW
projects=*
5m 7s
Run microsoft/AL-Go-Actions/Deploy@v3.2
Run $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 5.0.7
BC.HelperFunctions emits usage statistics telemetry to Microsoft
project '*'
Apps to deploy
D:\a\Precious-Metals-Solution\Precious-Metals-Solution\.artifacts\Precious-Metals-Solution-main-Apps-22.1.30.0
Attempting authentication to https://api.businesscentral.dynamics.com/user_impersonation offline_access using refresh token...
Authenticated using refresh token as user David Baldwin (David.Baldwin@matthey.com)
https://businesscentral.dynamics.com/cc7f83dd-bc5a-4682-9b3e-062a900[20](https://github.com/CAI-Software-Inc/Precious-Metals-Solution/actions/runs/6332443113/job/17199295226#step:1:24)2a2/DEV/deployment/url
Publishing apps using development endpoint
Publishing CAI Software_CAI Software Precious Metals Solution_[22](https://github.com/CAI-Software-Inc/Precious-Metals-Solution/actions/runs/6332443113/job/17199295226#step:1:26).[1](https://github.com/CAI-Software-Inc/Precious-Metals-Solution/actions/runs/6332443113/job/17199295226#step:2:1).30.0.app to https://api.businesscentral.dynamics.com/v2.0/DEV/dev/apps?SchemaUpdateMode=synchronize
Exception calling "GetResult" with "0" argument(s): "An error occurred while sending the request."
An error occurred while sending the request.
The underlying connection was closed: An unexpected error occurred on a receive.
Publish-BcContainerApp Telemetry Correlation Id: e449e883-83f2-485a-b780-adc08beb7c5f
Error: Deploying to DEV failed.  Exception calling "GetResult" with "0" argument(s): "An error occurred while sending the request."
Removing BcContainerHelper
Error: Process completed with exit code [1](https://github.com/CAI-Software-Inc/Precious-Metals-Solution/actions/runs/6332443113/job/17199295226#step:3:1).

**Comment by freddydk** [comment]
For that error, I think you need to login to the environment to see what the error is there.
You can also in the DeployToDEV setting set SyncMode to ForceSync.
https://aka.ms/algosettings#deployto
