### ISSUE TITLE
PullRequestStatusCheck does not stop a failed PR

### ISSUE THREAD

**Issue by spesotskiy** [microsoft/AL-Go#721]
Hi!

I see that few weeks ago there was added PullRequestStatusCheck which should not allow committing a PR that does not pass tests, for example. It is what I miss now. 
I am updated to AL:Go 3.2 (so I have the working GhTokenWorkflow set), but PR's get accepted regardless of the action results. I suspect that something is wrong with my (dirty) secrets.

In [Actions/PullRequestStatusCheck/README.md ](https://github.com/microsoft/AL-Go/blob/main/Actions/PullRequestStatusCheck/README.md) I read that: 
 - GITHUB_TOKEN must be set as an environment variable when calling this action

Then in [AL-Go 3.2 release](https://github.innominds.com/microsoft/AL-Go/releases/tag/v3.2) I see:
- **Issue 555** Now, you can set the checkbox called Use GhTokenWorkflow to allowing you to use the GhTokenWorkflow instead of the GITHUB_TOKEN - making sure that workflows are triggered

Ok. As GITHUB_TOKEN is not the best option (according to issue 555) I would like to use GhTokenWorkflow for sure. 
I didn't get, where the **_"Use GhTokenWorkflow"_** checkbox is placed.
Could you update the release note by maybe adding a small picture there, showing this checkbox so that anyone could easily find?
I couldn't find a documentation searching for "Use GhTokenWorkflow"? Is it documented?

Thanks!

**Comment by spesotskiy** [comment]
By the way, https://github.com/microsoft/AL-Go-AppSource/blob/main/.github/workflows/PullRequestHandler.yaml is not in sync with https://github.com/microsoft/AL-Go/blob/main/Templates/AppSource%20App/.github/workflows/PullRequestHandler.yaml
What is the right way to create a new AppSource repository if https://github.com/microsoft/AL-Go-AppSource seems to be out of date.

**Comment by spesotskiy** [comment]
So I have taken the latest version of workflows from https://github.com/microsoft/AL-Go
Now I get the following error for [Pull Request Status Check]

**Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' for action 'microsoft/AL-Go-Actions/PullRequestStatusCheck@main'.**

Similar error on CI/CD:
**Can't find 'action.yml', 'action.yaml' or 'Dockerfile' for action 'microsoft/AL-Go-Actions/DetermineDeliveryTargets@v3.2'.**

So how to get a consistent version of the workflows that would include PullRequestStatusCheck?

**Comment by spesotskiy** [comment]
The last question. 
What is a planned release date for the next AL-Go version, that includes PullRequestStatusCheck action?

**Comment by freddydk** [comment]
This month - one of the next days - need a few final fixes
