### ISSUE TITLE
Publish to Environment - (AL-Go for Github - AppSource App template)

### ISSUE THREAD

**Issue by XPLJohnPalma** [microsoft/AL-Go#724]
Hi Guys

Good day,

May I ask for some help with the **Publish to Environment** to AL-Go for Github - AppSource App template.

I set it up to deploy the update to our SandboxUAT environment but it is throwing as an error.

![image](https://github.com/microsoft/AL-Go/assets/144302486/6d2280be-ca11-4acd-89e1-b504d66e6267)

and here is what it says in BC

"An extension with same app Id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx' already exists in the AppSource marketplace with name 'XPL Travel' and publisher 'Explorer Technologies Pty Ltd'. Please use the extension marketplace to install the extension from AppSource or use a new app Id for your per-tenant extension."

Thank you in advance

John

**Comment by jonaswre** [comment]
Hi,

there is a limitation.

You can't use as S2S connection. AppSource Apps can only be installed as dev.

There is PowerShell helper that can create the AuthContext to impersonate a user. That will cause the App to be installed as dev. 

I'll looking it up and get back to you.

**Comment by XPLJohnPalma** [comment]
Hi Jonas,

Thank you for your response. Its a bit clearer now, but may ask for your help on how to apply or to use this(the link) on our github. I'm a bit new with the solution and there is a bit of a vague area for me. 

Thank you

John

**Comment by XPLJohnPalma** [comment]
Hi Freddy, Hi Jonas

Good day,

Is it possible to have an option in the "Publish to Environment" to deploy as DEV or PTE?

Thank you in advance

John

**Comment by jonaswre** [comment]
Hi John,

AppSource Apps can't be published as PTE. 

The only way to get AppSource App into Environments is by publishing them as DEV or install them through AppSource.

This has one big disadvantage.

> But this has the obvious downside that your app will be uninstalled when the environment updates.

But if this is acceptable for your usecase. 

You can create a AuthContext using the `-includeDeviceLogin` flag this will create an authentication as if a user would log in using vscode. 

```
$authContext = New-BcAuthContext -includeDeviceLogin
New-ALGoAuthContext -authContext $authContext | Set-Clipboard
```

AL-Go understands that is AuthContext can only be used for DEV deployments and will act accordingly. 

@freddydk will the token still expire or do you have any mechanism to automaticlly refresh the token?

**Comment by freddydk** [comment]
The token will expire after ~90 days.
I did try to add a feature to store/cache the new refresh token, but GitHub workflows doesn't have permissions to write secrets.
