### ISSUE TITLE
SignTool Error: This file format cannot be signed

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL-Go#725]
Builds are failing in multiple repos due to apps not being signed. 
Nothing in the repos have changed, I guess this is a compiler change. I think it makes sense to track it here until we know the cause. 

Output: 
`
  Downloading certificate file to container
  Downloading C:\ProgramData\BcContainerHelper\Extensions\bc6294041334\my\de22994f-2159-4102-99e0-010e8a796f3e.pfx
  Downloading using WebClient
  Downloading Signing Tools
  Installing Signing Tools
  Signing c:\sources\.output\pryme_pryme Time_2.2.2147483647.0.app
  Done Adding Additional Store
  
  SignTool Error: This file format cannot be signed because it is not recognized.
  SignTool Error: An error occurred while attempting to sign: c:\sources\.output\pryme_pryme Time_2.2.2147483647.0.app
  
  Number of errors: 1
  
  
  Signing apps took 6 seconds
`

**Comment by AskeHolst** [comment]
I see that this will be resolved with this: https://github.com/microsoft/navcontainerhelper/issues/3190

**Comment by freddydk** [comment]
Yeah - it was a surprise that this change was done in 22.5 as well - will release containerhelper asap.
Setting "bccontainerhelperversion" to "preview" in an organizational variable called ALGoOrgSettings will fix the issue now.
