### ISSUE TITLE
Al-Go jobs are slower than they used to be

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL-Go#729]
We see that most workflows are slower now than a few weeks ago. 
The build part was always variable, depending on the load on our self-hosted agents and the use of cache. But the non-build jobs have got a lot slower in general. 

Not a big issue, and maybe there is a good reason for it, just wanted you to know.

Example from a few weeks ago (build of two project redacted):
![image](https://github.com/microsoft/AL-Go/assets/8398485/567edee9-28d6-4890-8267-f068a34dd21b)

A run from this week, same repo no major change in the repo.
![image](https://github.com/microsoft/AL-Go/assets/8398485/7adbe746-d3de-425f-865b-a553fe5c5d0f)

**Comment by AskeHolst** [comment]
This seems to be a GitHub issue on Windows agents: https://github.com/actions/runner-images/issues/8380
Closing this as not related to Al-Go.

**Comment by AskeHolst** [comment]
Just as a follow-up, I switched to run-on ubuntu-latest, and that is very fast, so absolutely a Windows issue.

Same CICD run on Ubuntu:
![image](https://github.com/microsoft/AL-Go/assets/8398485/d321492a-0de8-4c78-b98b-afab8b5d513e)

**Comment by freddydk** [comment]
Yeah, we noticed that as well on our builds - the windows latest fluctuates a lot lately.
If you expand the steps in initialize - what is the steps taking the time?
