### ISSUE TITLE
[Nice to Have] Add space when including a URL in the workflow output steps

### ISSUE THREAD

**Issue by fvet** [microsoft/AL-Go#734]
When actions are ran, often the workflow steps provide usefull output to navigate to a (github) url.
Often, the output is ended with a '.' which is concatenated to the url, failing to simply click and open the url (without explicitely removing the final dot). Would be nice if the code was scanned for these occurences and a space was added (or the dot removed)

**As-is**

_You can create the PR manually by navigating to https://github.com/xxxx/Apps/tree/add-existing-app/main/230927175554._

**To be**

_You can create the PR manually by navigating to https://github.com/xxxx/Apps/tree/add-existing-app/main/230927175554_

**Comment by freddydk** [comment]
Good point - maybe enclose URLs with [https://www.bing.com], then I guess it should be click'able.

**Comment by freddydk** [comment]
I did a regex search for places where a variable in a string was followed by a period - and found only this one occurrance
Removed the . in the next preview to fix this one.
Is in the next preview version
