### ISSUE TITLE
[Question] Ruleset location in multi project / app repo?

### ISSUE THREAD

**Issue by fvet** [microsoft/AL-Go#736]
I'm trying to configure a single Github repo with multiple projects, all referencing a common ruleset.

**Current situation**
- DevOps repo 1
  - App folder  (with .vscode\settings.json containing the app's settings, ruleset)
  - Test folder  (with .vscode\settings.json containing the app's settings, ruleset)
- DevOps repo 2
  - App folder  (with .vscode\settings.json containing the app's settings, ruleset)
  - Test folder   (with .vscode\settings.json containing the app's settings, ruleset)
- DevOps repo X
  - ...

**Expected result**
- Github repo 1
  - Project folder 1
    - App folder
    - Test folder
  - Project folder 2
    - App folder
    - Test folder
  - Project folder X
    - ...

Merging the different DevOps repo's into a single github repo and managing the apps via different projects / folders is clear.

I'd like to avoid maintaining the same ruleset per project / app and am looking for a best practice on **where** to put the common ruleset file (as mentioned here : https://aka.ms/algosettings#rulesetFile)

Currently, each app has it's own (copy) of a `app.ruleset.json` file (saved / referenced via .vscode\settings.json) 

![image](https://github.com/microsoft/AL-Go/assets/25268332/5afefd78-76a6-49a0-99e5-d55484d78e42)

In the AL-Go repo settings, I have set the reference to a new `app.ruleset.json` file ...

![image](https://github.com/microsoft/AL-Go/assets/25268332/262a36e4-d165-4840-9a90-4ff304e19d3e)

... stored under the root folder.

![image](https://github.com/microsoft/AL-Go/assets/25268332/e9df1e89-70b0-4362-b187-58ad97614bd4)

Resulting into this workflow failure:

```
Error: AL1033 An error occurred while loading the included rule set file c:\sources\app.ruleset.json - Could not find file 'c:\sources\app.ruleset.json'.
  App generation failed with exit code 1
```
![image](https://github.com/microsoft/AL-Go/assets/25268332/5c58fbbc-98a6-430c-b756-ebc9f7a1fafa)

**Question**
Where to put the ruleset file for the workflows so all app builds can reference the same file? 
(Both for the actions/workflows and when working in VS Code)

---
To verify: in VS Code, we will normally work on 'project' level (and won't open the repo's root folder). If the solution would be to manage only one ruleset on \root, hopefully the .vscode\settings.json al.rulesetPath location will allow to search outside the currentlyopened project folder.

**Comment by freddydk** [comment]
If you set the "rulesetFile" setting in .github/AL-Go-Settings.json, then it will be the default ruleset file for all projects.
You can still override the setting in a project by adding it to the .AL-Go/settings.json for that project.
The setting needs to be relative to the project folder - "../app.ruleset.json" will cover this if your projects are 1 level down.
