### ISSUE TITLE
[Question] AL-Go settings and repository structure for multi-projects purpose 

### ISSUE THREAD

**Issue by beemubotokka** [microsoft/AL-Go#738]
How to handle settings with Environments parameter, when project delivery includes at least two country localizations?
Currently both projects are on separate folders, them al-go settings.json file include only one specified environment name Like A, and B on other. On GitHub Environments settings I have four environment names A, B, C and D as they found in BC. 
Problem is, when I Deploying with CICD action, then both projects will be deployed to A and B environments. And action also tries to do same on C and D environment. Should I use A_AuthContext on Environment settings or what is correct syntax to point Projects to individual environment?
Thanks.

**Comment by freddydk** [comment]
In repository settings, you can specify a DeployTo structure for your environments.
In that, you can specify which projects should be deployed to the environment. Default is * = All.
https://aka.ms/algosettings#deployto

**Comment by freddydk** [comment]
And for the AuthContext - you can specify that as a secret underneath the environment in GitHub (called AUTHCONTEXT) or you can create repository secrets called environmentname_AUTHCONTEXT - both works.
environmentname_AUTHCONTEXT has precedence.

**Comment by beemubotokka** [comment]
Thank you. 
Following syntax seems to successfully processed:

 "Environments": [
    "Sandbox", 
     "Sandbox-PROD"
  ],
  "DeployToSandbox": {
    "EnvironmentName": "Sandbox",
    "Projects": "A"
  },
    "DeployToSandbox-PROD": {
"EnvironmentName": "Sandbox-PROD",
      "Projects": "B"
    }
}

But on CICD.yaml and it's Deploy part goes still to partially failure. Deploy gather all list of GitHub environments and tries to deploy on them? Environments which found at settings deployed well, but other goes to failure. Which settings parameter avoid to this happen?

![image](https://github.com/microsoft/AL-Go/assets/61850274/1e42c702-dd74-4334-b0c6-8d59d4b8bb6a)

**Comment by freddydk** [comment]
In general, environments are deducted from GitHub environments
If you are using a free SKU, you do not have GitHub environments, therefore we also support environments setting.
In the deployToStructure for the environment, you can specify ContinuousDeployment: false to avoid CD.
You can also use the ExcludeEnvironments setting to exclude a list of environments.

**Comment by beemubotokka** [comment]
Ok, Thank you.
Seems to be easier to create environment variables only for needs. And this special case, (Production) tag, skip one of the environments.  At the beginning I assume, that al-go settings file is list for to be processed environments.
We are using licensed version and MFA also brings some extra actions for GitHub use (org variable, workflow auth).
