### ISSUE TITLE
How do I override installApps per workflow?

### ISSUE THREAD

**Issue by bmi-it** [microsoft/AL-Go#739]
I have a project that builds on top of a 3rd party app.  I have been provided runtime app files.  The problem that I face is: the current version of 3rd party app works in BC v22, but it does not install in v23 (via nextMinor and nextMajor at the time of this writing).  I can't override installApps on a per workflow basis. Rather, it seems to merge the two settings together.

I added an installApps statement in AL-Go-Settings.json referencing the proper version of the runtime app that works for v22.  No problem here.  CICD runs fine, etc.

I added an installApps statement into Test Next Major.settings.json and Test Next Minor.settings.json so that a new version of the 3rd party runtime app is installed for v23.

In nextMinor and nextMajor, I expected to see the new 3rd party app loaded successfully.

What I actually see is both the old app and new app trying to install and the workflows stop because the old app is not compatible with v23.

Is there a better way to handle installApps per workflow?

**Comment by freddydk** [comment]
It is correct that settings, which are arrays are merged, not overridden.
The reason for this is to allow you specify specific apps you want to install on a high level without "destroying" lower level installapps.
But you are on the right path.
In this particular situation, what you would need to do is to move the "original" installApps to a project specific workflow setting (using CICD) following this naming:

```
<project>/.AL-Go/<workflowName>.settings.json
```

For single project repo - that is in the root.
Then you would have to have installApps in 4 of these settings files:

.AL-Go/CICD.settings.json
.AL-Go/Test Current.settings.json
.AL-Go/Test Next Major.settings.json
.AL-Go/Test Next Minor.settings.json

You can also specify them in repo workflow settings in the .github folder - then you just need to create CICD.settings.json next to Test Current.settings.json.

**Comment by freddydk** [comment]
You can also centralize things by using conditionalSettings:
https://aka.ms/algosettings#conditional-settings

In that case - you can specify the InstallApps for the workflows in one place - you still need to move the current version InstallApps into a condition saying "CICD" and "Test Current" (and maybe Test Next Minor)

**Comment by BMI-Mike** [comment]
Hi Freddy,
  I was able to get CICD, nextMinor, and nextMajor to work OK using the strategy described in your first response.  But, I have a new problem when using localDevEnv.ps1 to create a local development environment. All of the 3rd party apps are not installed automatically.

I assume at this point I need a .AL-Go/<username>.settings.json file for every user that works on this project in order to work around this.  

Is there another way to do it?

**Comment by freddydk** [comment]
You should be able to create settings for a workflow called localdevenv (although it isn't really a workflow), which should be read when running localDevEnv (or cloudDevEnv for that script)

**Comment by BMI-Mike** [comment]
I still have to give this a try.  I should know more later today or tomorrow.  Thanks for your help and guidance thus far.

**Comment by BMI-Mike** [comment]
I was able to get this to work.  Thank you.  

I am using Azure keyVault settings for local environments and within GitHub workflows.
