### ISSUE TITLE
For private repositories Environments are available only in premium packages

### ISSUE THREAD

**Issue by miljance** [microsoft/AL-Go#74]
In scenario 3 the environments have to be created in order to successfully setup the continuous deployment. 
https://github.com/microsoft/AL-Go/blob/main/Scenarios/RegisterSandboxEnvironment.md
Can the environments perhaps be avoided in order to support users with github Team licence?

**Comment by freddydk** [comment]
I discovered the same.
Thinking about adding support for a list of environments in repo-settings as well.

**Comment by freddydk** [comment]
This is fixed in v1.0 - you can now add environments to the repo settings file.
Will update documentation as well.
Sample:

`"environments" : [ "QA", "PROD (Production)" ]
`

**Comment by miljance** [comment]
Great! 👍 Thank you. I will give it a spin.
