### ISSUE TITLE
How use both linux and windows self-hosted runners

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/AL-Go#743]
Related to question #735 of my colleague:

The documentation mentions the following for the "runs-on" settings:

**Setting runs-on to ubuntu-latest will run all non-build jobs on Linux, build jobs will still run windows-latest (or whatever you have set in githubRunner)**

So we've set the settings to:

```
  "runs-on": "ubuntu-latest",
  "githubrunner": "self-hosted",
```

We've 2 self-hosted runners: 1 on linux, 1 on windows.

When the CI/CD workflow is run, it appears that builds are done using the ubuntu runner instead of the windows runner. I was expecting the windows runner to be used. 

![image](https://github.com/microsoft/AL-Go/assets/92365904/53850cda-5646-40e4-9561-e6766d5c21c6)

What am I missing here?

**Comment by freddydk** [comment]
Your runners will have some tags:
![image](https://github.com/microsoft/AL-Go/assets/10775043/f18fe00f-6d89-443f-991b-75aec7c928b0)

If you (in runs-on or gitHubRunner) use a combination of multiple of these tags like:

![image](https://github.com/microsoft/AL-Go/assets/10775043/37441b9e-1441-492f-a882-e6f489413417)

Then it will only use the runner, which matches all.

**Comment by dsaveyn** [comment]
Ok, I did not know that:) Thank you very much.

**Comment by freddydk** [comment]
In the GitHub workflow file, it looks like this (if setting runs-on and updating system files):

![image](https://github.com/microsoft/AL-Go/assets/10775043/ee3585ef-9a10-4c9b-9dd0-823ed6c83d45)

**Comment by BertDeTemmerman** [comment]
Just to be sure:

Using the settings
```
"githubrunner": "self-hosted,Windows",
"runs-on": "ubuntu-latest",
```
for runners
![image](https://github.com/microsoft/AL-Go/assets/34303738/7c40e6b2-9be8-493a-b1c4-d77cf2cbde6f)

will make this work?

(As I can't seem to figure out the difference between `githubrunner` and `runs-on` ...)

**Comment by freddydk** [comment]
ubuntu-latest is GitHub hosted linux runners.
windows-latest is GitHub hosted windows runners.
self-hosted are your own runners (if you gave them the self-hosted tag). You could give them bertsrunners instead.
self-hosted can be windows or linux, depending on what you setup.
self-hosted, windows would be your self-hosted windows runners (if you gave it this tag)
self-hosted, linux would be your self-hosted linux runners (again if you gave it this tag)

GitHubRunner defines what is used for jobs, which requires a container, default is the value of runs-on, unless runs-on equals ubuntu-latest, then it defaults to windows-latest.

runs-on defines what is used for all other jobs - default is windows-latest.

So, with

```
"githubrunner": "self-hosted,Windows",
"runs-on": "ubuntu-latest"
```

you will use GitHub hosted Linux runners for all jobs, which doesn't require a container and your self-hosted agent for jobs which requires a container (build/test jobs)

**Comment by BertDeTemmerman** [comment]
Thanks, that makes it more clear! :)
