### ISSUE TITLE
Question: Self Hosted runner - Software required

### ISSUE THREAD

**Issue by BMI-Mike** [microsoft/AL-Go#755]
I'm trying to use a self-hosted runner on internal hardware.

I'm using Windows Server 2022, enabled containers, disabled defender, installed git, installed .NET SDK (for dotnet command below), and installed the GitHub runner software.  Everything is ok, except the workflow operations that sign apps.  

```
Install AzureSignTool
  AL-Go action ran: Sign Telemetry Correlation Id: 9e712198-37fd-4434-8372-d7495fb60e26
  Error: Unexpected error when running action. Error Message: The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again., StackTrace: at <ScriptBlock>, C:\actions-runner\_work\_actions\microsoft\AL-Go-Actions\v3.3\Sign\Sign.ps1: line 25 <- at <ScriptBlock>, C:\actions-runner\_work\_temp\f7ff8c83-a6c8-4712-871e-9cabd9f[50](https://github.com/BMI-Software/BMI-SupplyAutomate/actions/runs/6388220503/job/17337932860#step:9:52)fdf.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
  Error: Process completed with exit code 1.
```

I know there is an Azure solution in the documentation, but for cost purposes, my company would prefer to run this on internal hardware for now.

What might I be missing?

**Comment by jonaswre** [comment]
I not sure about the signing tool.

> The term 'dotnet' is not recognized as the name of a cmdlet

This tells me dotnet is not found in the path maybe thats a place to look for a solution.

**Comment by jonaswre** [comment]
From the error it doesn't seem to be successful in allowing the agent to use it. Did you set the env var as the user or for the full computer?

**Comment by BMI-Mike** [comment]
@jonaswre - It's set for the entire system.  If I "echo %PATH%" as the same user that runs the GitHub Runner service, I see the path to the dotnet.exe binary specified.  I rebooted the entire runner PC to ensure the new path was picked up.

**Comment by freddydk** [comment]
And you do have dotnet 7 installed on the machine?

These are the things I install when running https://aka.ms/getbuildagent (beside docker and other standard stuff):

https://github.com/microsoft/nav-arm-templates/blob/master/additional-installforbuildagent.ps1

**Comment by BMI-Mike** [comment]
Yes, I have the .NET 7 SDK installed on the machines.  And I have a system PATH set to Git and .NET

<img width="425" alt="image" src="https://github.com/microsoft/AL-Go/assets/35507227/bab64101-c53b-4abb-abaa-7b41ffa9df48">

**Comment by BMI-Mike** [comment]
After looking at https://github.com/microsoft/nav-arm-templates/blob/master/additional-installforbuildagent.ps1

I do not have VSCode, 7zip or the GitHub CLI installed.  I should give that a try.

**Comment by BMI-Mike** [comment]
VSCode, 7zip and GitHub CLI installed.  Different Error!  It's now looking for AzureSignTool.

```
AL-Go action ran: Sign Telemetry Correlation Id: 8ab91ad8-6e78-4582-976e-cc873d8159fb
Error: Unexpected error when running action. Error Message: The term 'AzureSignTool' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again., StackTrace: at <ScriptBlock>, C:\actions-runner\_work\_actions\microsoft\AL-Go-Actions\v3.3\Sign\Sign.ps1: line 51 <- at RetryCommand, C:\actions-runner\_work\_actions\microsoft\AL-Go-Actions\v3.3\AL-Go-Helper.ps1: line 2209 <- at <ScriptBlock>, C:\actions-runner\_work\_actions\microsoft\AL-Go-Actions\v3.3\Sign\Sign.ps1: line 46 <- at <ScriptBlock>, C:\actions-runner\_work\_temp\f3dbc14e-c8c2-4610-8ac5-f6170984e1ab.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
Error: Process completed with exit code 1.
```

I'll try `dotnet tool install --global AzureSignTool`

**Comment by freddydk** [comment]
@aholstrup1 do you know what pre-requisites AzureSignTool has?

**Comment by aholstrup1** [comment]
AzureSignTool is an open-source tool available here https://github.com/vcsjones/AzureSignTool

When I look in their readme, they only mention Windows / Windows Server as a [requirement](https://github.com/vcsjones/AzureSignTool?tab=readme-ov-file#requirements). I assume you have that :) 

I can also see someone else had the same [issue ](https://github.com/vcsjones/AzureSignTool/issues/199)around .NET 7 as you did. Could you try the mitigation mentioned in that issue? Otherwise I would open up an issue for AzureSignTool. Not sure if there's anything we can do from the Al-Go side. 

Another thing you could try.. Since the action works on GitHub runners you could try having a look at how GitHub sets up their runners. They have an open-source repository with the code they use to create their runner images https://github.com/actions/runner-images

**Comment by BMI-Mike** [comment]
@aholstrup1, I tried the mitigation mentioned in the links, but I didn't have an environment variable set that was causing an issue to remove.

I also tried uninstalling .NET 7 and only had .NET 6 installed, but I receive errors when trying to install azuresigntool.

<img width="816" alt="image" src="https://github.com/microsoft/AL-Go/assets/35507227/d0e0fb01-8673-4ed1-9cd8-c9a93c268233">

I'm only chasing this down as we were running out of runner minutes per month.

**Comment by BMI-Mike** [comment]
It looks like I had to run: `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org`

You can either run this command or install Visual Studio (not Code) of some flavor too.

**Comment by BMI-Mike** [comment]
Well, I made it a step closer.  AzureSignTool now runs, but I'm now running into the next error:

```
Install AzureSignTool
  Tool 'azuresigntool' is already installed.
Signing files:
- C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate EvolutionX Connector_1.9.5[73](https://github.com/BMI-Software/BMI-SupplyAutomate/actions/runs/6451160964/job/17511444946#step:9:77).0.app
- C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate Unified AR Connector_1.9.573.0.app
- C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate_1.9.573.0.app
Register NavSip
  
info: AzureSignTool.SignCommand[0]
      => File: C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate Unified AR Connector_1.9.573.0.app
      Signing file.
info: AzureSignTool.SignCommand[0]
      => File: C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate_1.9.573.0.app
      Signing file.
info: AzureSignTool.SignCommand[0]
      => File: C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate EvolutionX Connector_1.9.573.0.app
      Signing file.
fail: AzureSignTool.SignCommand[0]
      => File: C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate EvolutionX Connector_1.9.573.0.app
      The file cannot be signed because it is not a recognized file type for signing or it is corrupt.
fail: AzureSignTool.SignCommand[0]
      => File: C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate Unified AR Connector_1.9.573.0.app
      The file cannot be signed because it is not a recognized file type for signing or it is corrupt.
fail: AzureSignTool.SignCommand[0]
      => File: C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate EvolutionX Connector_1.9.573.0.app
      Signing failed with error [80](https://github.com/BMI-Software/BMI-SupplyAutomate/actions/runs/6451160964/job/17511444946#step:9:84)0B0003.
fail: AzureSignTool.SignCommand[0]
      => File: C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate Unified AR Connector_1.9.573.0.app
      Signing failed with error 800B0003.
fail: AzureSignTool.SignCommand[0]
      => File: C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate_1.9.573.0.app
      The file cannot be signed because it is not a recognized file type for signing or it is corrupt.
fail: AzureSignTool.SignCommand[0]
      => File: C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate_1.9.573.0.app
      Signing failed with error 800B0003.
info: AzureSignTool.SignCommand[0]
      => File: C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate EvolutionX Connector_1.9.573.0.app
      Stopping file signing.
info: AzureSignTool.SignCommand[0]
      => File: C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate Unified AR Connector_1.9.573.0.app
      Stopping file signing.
info: AzureSignTool.SignCommand[0]
      => File: C:\actions-runner\_work\BMI-SupplyAutomate\BMI-SupplyAutomate\.buildartifacts\Apps\Business Management International - MBS_BMI SupplyAutomate_1.9.573.0.app
      Stopping file signing.
info: AzureSignTool.SignCommand[0]
      Successful operations: 0
info: AzureSignTool.SignCommand[0]
      Failed operations: 3
Retrying after 5 seconds...
```

This error repeats three times and ultimately fails.

**Comment by freddydk** [comment]
You probably need this pre-requisite:
https://aka.ms/vs/17/release/vc_redist.x64.exe
or maybe the earlier version
https://www.microsoft.com/de-DE/download/details.aspx?id=40784

**Comment by BMI-Mike** [comment]
I'll give it a try now.  Thanks.

**Comment by BMI-Mike** [comment]
@freddydk Installing https://aka.ms/vs/17/release/vc_redist.x64.exe was the solution to the last set of error messages!

Thank you @freddydk and @aholstrup1

**Comment by freddydk** [comment]
We will add some checks to the workflows and issue warnings if these pre-requisites are not in place.

**Comment by BMI-Mike** [comment]
> We will add some checks to the workflows and issue warnings if these pre-requisites are not in place.

I hate to ask, but is there someplace that describes the prerequisites for a self-hosted runner used with AL-Go?

**Comment by freddydk** [comment]
Not really, this article: https://github.com/microsoft/AL-Go/blob/main/Scenarios/SelfHostedGitHubRunner.md just describes how to create an azure VM using aka.ms/getbuildagent.
Will add a section with pre-requisites.

**Comment by freddydk** [comment]
doc update (including pre-reqs): https://github.com/microsoft/AL-Go/pull/762
