### ISSUE TITLE
Some PRs do not trigger Pull Request Status Check

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL-Go#763]
We now have the Pull Request Status Check job which solved the issue with #667 

Unfortunately some PRs, like Increment Version does not trigger a PR build, leaving it in limbo (see below).

I agree that Increment Version should not need a PR build as a version increase should never cause problems. But it actually costs more time to have an admin come in and force the PR than just having to wait for the PR build. 

Would it be possible to kick off a very small workflow that just runs the Pull Request Status Check with success?

![image](https://github.com/microsoft/AL-Go/assets/8398485/dd40787f-46d9-4a7a-a4b0-040dd2a6ab01)

**Comment by aholstrup1** [comment]
What version of Al-Go are you using? We merged a PR related to this issue https://github.com/microsoft/AL-Go/pull/749 recently. That fix should be in preview right now.

**Comment by AskeHolst** [comment]
Latest main, but we are not running preview.
I updated to preview in the repo and I can see that Increment Version does trigger a PR build now, great - thank you.
