### ISSUE TITLE
[Question] appFolders usage for multi-project repo

### ISSUE THREAD

**Issue by fvet** [microsoft/AL-Go#769]
Scenario:
- 2 apps :
  - Core (AppSource prefix ESCA)
  - Trade (AppSource prefix ESCB) 
- Trade has a dependency on Core
- Both apps are managed within the **same** (multi-project) repo
- No external dependencies

![image](https://github.com/microsoft/AL-Go/assets/25268332/34dd237d-37d0-4c19-86e7-a874aaaff9f3)

Core does compile ok.
Trade does not detect the dependency to Core.
How should we configure the `appFolders` property for this scenario?

I've added the 'Core/App' as dependend app. But the 'Core' app is not detected when building Trade.

```
Run microsoft/AL-Go-Actions/RunPipeline@v3.3
Run $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
Import from C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\BcContainerHelper.ps[1](https://github.com/DynavisionISV/Apps/actions/runs/6524970974/job/17717164068#step:8:1)
BcContainerHelper version 6.0.0
BC.HelperFunctions emits usage statistics telemetry to Microsoft
use settings and secrets
Analyzing repository
  Checking type
  Warning: The folder 'Core/App' for project 'Trade' cannot be resolved or does not contain an app.json file. Skipping.
  Checking appFolders, testFolders and bcptTestFolders
  Application Dependency 18.0.0.0
  Checking artifact setting for project
  Downloading artifacts from https://bcartifacts.azureedge.net/sandbox/23.0.12034.13132/us
  Updating app- and test Dependencies
  Analyzing Test App Dependencies
No performance test apps found in bcptTestFolders in .AL-Go\settings.json
Warning: No test apps found in testFolders in .AL-Go\settings.json
Warning: No apps found in appFolders in .AL-Go\settings.json
Checking appDependencyProbingPaths
Repository is empty, exiting
```

Examples listed here are using the 'appDependencyProbingPaths' instead, so not clear when to use appFolders  vs appDependencyProbingPaths

- https://freddysblog.com/2022/04/28/structuring-your-github-repositories/
- https://github.com/BusinessCentralApps/Contoso-App2/blob/main/App2.it/.AL-Go/settings.json

Other references used:

- https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md#appfolders

**Comment by fvet** [comment]
For my reference:

Paths need to be relative to the **project** folder.

Changed appFolders setting to

`appFolders": ["..\\Core\\App"],`

**Comment by freddydk** [comment]
appFolders are folders in the project
appDependencyProbingPaths are dependencies to other projects (which might be in the same repo)
in appDependencyProbingPaths you can set release_status to include - then it will include the dependent apps from the other project in the build of this project
You can also remove appDependencyProbingPaths and instead set useProjectDependencies to true and run Update AL-Go System Files - then it will build apps in dependency order.

**Comment by fvet** [comment]
Thanks, I've enabled `useProjectDependencies` which does the trick and now does sequential builds based on the dependency order 👍

![image](https://github.com/microsoft/AL-Go/assets/25268332/e106a395-0916-4f69-ab42-9c9f28d257d2)

PS: I was mainly trying to get to know AL-GO using below links
https://github.com/microsoft/AL-Go#usage-scenarios
https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md

But found out the **Workshops** sections contains a lot of useful (more in-depth) scenarios / information as well.
https://github.com/microsoft/AL-Go/tree/main/Workshop

Might be interesting to add some links to these workshops pages on the landing page as well?

**Comment by freddydk** [comment]
The workshop will be added to the README
