### ISSUE TITLE
Builds fails mostly the first time.

### ISSUE THREAD

**Issue by FrankAuwers** [microsoft/AL-Go#777]
When the build in the pipeline is run for the first time, al most every time it fails.
But when you do the re-run failed jobs, it works.

[Build . (Default) / . (Default)](https://github.com/scapta/Scaptify/actions/runs/6545437582/job/17773930062#step:48:635)
Unexpected error when running action. Error Message: Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder C:\ProgramData\BcContainerHelper\Extensions\bc6545437582\PsTestTool and retry. You might also have URL or Company name wrong., StackTrace: at Run-TestsInBcContainer, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-TestsInNavContainer.ps1: line 516 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 827 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2382 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2326 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2270 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 904 <- at Run-AlPipeline, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 866 <- at <ScriptBlock>, C:\action-runners\1\_work\_actions\microsoft\AL-Go-Actions\v3.3\RunPipeline\RunPipeline.ps1: line 371 <- at <ScriptBlock>, C:\action-runners\1\_work\_temp\8cd6d2f9-15a4-4f55-a6b3-af69861a16fa.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1

**Comment by freddydk** [comment]
Not something I have seen before - I would need to full log of the first (failing) and second (succeeding) run in order to investigate why this is

**Comment by FrankAuwers** [comment]
In attachment the log files.

[Log Fail First Run.zip](https://github.com/microsoft/AL-Go/files/12927559/Log.Fail.First.Run.zip)
[Log Success Second Run.zip](https://github.com/microsoft/AL-Go/files/12927560/Log.Success.Second.Run.zip)

**Comment by FrankAuwers** [comment]
Yesterday and today the problem didn't occur anymore.
