### ISSUE TITLE
Apply to existing repo

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/AL-Go#78]
Can I just put the files and folders into an existing repo to "apply" the template?  Or is there something about having created the repo from a template that would be missing?

**Comment by freddydk** [comment]
I guess you should be able to copy the .AL-Go and the .github folders to an existing repo and you should be good to go - I have not tried.
If you haven't specified AppFolder and TestFolders in the settings file, it will enumerate folders in the repo to find app folders automatically.

**Comment by freddydk** [comment]
This blog post should cover this topic
https://freddysblog.com/2022/04/27/migrating-to-al-go-for-github/
