### ISSUE TITLE
Exclude '.altestrunner/' from template .gitignore

### ISSUE THREAD

**Issue by fvet** [microsoft/AL-Go#782]
Following #62 

When creating a new github repo using the AL-GO-AppSource (or AL-GO-PTE) template, the default .gitignore file should ideally also exclude any `.altestrunner` folder content.

![image](https://github.com/microsoft/AL-Go/assets/25268332/29d0fddc-04e1-4391-840a-ed35a92fa568)

---

More info
https://jpearson.blog/2019/11/18/al-test-runner-for-visual-studio-code/

![image](https://github.com/microsoft/AL-Go/assets/25268332/c29f2fc8-4440-4fa8-b388-b6cd1b1911a7)

**Comment by freddydk** [comment]
Will add this to the default .gitignore
