### ISSUE TITLE
Error Message: The build depth is too deep, the maximum build depth is 1 although AL-Go System Files are updated

### ISSUE THREAD

**Issue by BertDeTemmerman** [microsoft/AL-Go#786]
**Problem**
When doing a PR from a feature branch where a new dependency app is created into main where the main app already exists, I get the error:
`Unexpected error when running action. Error Message: The build depth is too deep, the maximum build depth is 1. You need to run 'Update AL-Go System Files' to update the workflows.`

But when I trigger the update on the main or the feature branch, no update is needed.
![image](https://github.com/microsoft/AL-Go/assets/34303738/2fa1463d-f7d8-462d-a15a-97158a55890d)
![image](https://github.com/microsoft/AL-Go/assets/34303738/a0bb3c84-662f-4aed-af41-c24145b36521)

**Context**
I got a Core app, and a new Shopfloor app depending on the core.
Al-Go Settings already has `"useProjectDependencies": true` in main.

**Solution**
After some testing, when commiting directly to main, the same error occurs.
But then the system files get updated by Update AL-Go System Files, and the ci-cd build with the main and shopfloor app completes succesfully.

**Conclusion**
The Update AL-Go System Files can only be triggered by a ci-cd run, not by a pull-request run.

**Problem**
When creating a new app, as the first dependency on an existing app, you have to commit to main directly.
You can't commit the app to a feature branch, and pull requesting the code into main.
The pipeline will fail as the pipeline isn't updated yet for a build depth of 2, and it's impossible to update the pipeline.

**Comment by freddydk** [comment]
That looks like a bug
You should be able to introduce the dependency in the feature branch and then run Update AL-Go System files in that feature branch - and then create a PR with this to main.

**Comment by freddydk** [comment]
Tried this on one of my own repositories - added a new project in a development branch.
Build job ended up saying ...
![image](https://github.com/microsoft/AL-Go/assets/10775043/b58eeda6-47a4-4d78-aac9-a00f0081cf6b)

Running Update AL-Go System files on that branch:
![image](https://github.com/microsoft/AL-Go/assets/10775043/428c2abf-4d69-46cb-a3a3-08fa4606f042)

PR into that development branch looks fine:
![image](https://github.com/microsoft/AL-Go/assets/10775043/b7c471ff-51a6-48e2-9c9d-03de3539f029)

After merging the PR - the build now succeeds:
![image](https://github.com/microsoft/AL-Go/assets/10775043/d921d06e-9077-4dcc-b473-fdc1fad37399)

And I can now merge this into main as well.

**Comment by BertDeTemmerman** [comment]
I've investigated some more:
Looks like I have updated the AL-Go System Files, via a PR from the Update AL-Go System Files.

Update AL-Go System Files

```
Fri, 20 Oct 2023 11:12:20 GMT
Calculated dependency depth to be 2
Fri, 20 Oct 2023 11:12:20 GMT
Checking .github\workflows\*
Fri, 20 Oct 2023 11:12:20 GMT
- AddExistingAppOrTestApp.yaml
Fri, 20 Oct 2023 11:12:20 GMT
- CICD.yaml
Fri, 20 Oct 2023 11:12:21 GMT
Updated workflow ' CI/CD' (.github\workflows\CICD.yaml) available
Fri, 20 Oct 2023 11:12:21 GMT
- CreateApp.yaml
Fri, 20 Oct 2023 11:12:21 GMT
- CreateOnlineDevelopmentEnvironment.yaml
Fri, 20 Oct 2023 11:12:21 GMT
- CreatePerformanceTestApp.yaml
Fri, 20 Oct 2023 11:12:21 GMT
- CreateRelease.yaml
Fri, 20 Oct 2023 11:12:21 GMT
- CreateTestApp.yaml
Fri, 20 Oct 2023 11:12:21 GMT
- Current.yaml
```

So the systemfiles were updated and merged
![image](https://github.com/microsoft/AL-Go/assets/34303738/04adcdf2-d3d4-4e65-be1f-bd63493f424e)

But somehow the build failed again after rerunning the failed jobs.
[Pull Request Build]PullRequestHandler.yaml Feature/3 shopfloor
```
Fri, 20 Oct 2023 11:18:55 GMT
AL-Go action ran: DetermineProjectsToBuild Telemetry Correlation Id: 0b1865be-ec09-42b0-96d2-dab1f2d9e625
Fri, 20 Oct 2023 11:18:55 GMT
Error: Unexpected error when running action. Error Message: The build depth is too deep, the maximum build depth is 1. You need to run 'Update AL-Go System Files' to update the workflow
```



I've now got an extra app: Shopfloor Advanced, depending on the Shopfloor app.
The PR build succeeds.
And it takes it's dependencies from the main branch, using the correct build order.
`ProjectDependenciesJson={"Core":[],"Shopfloor":["Core"],"Shopfloor Advanced":["Shopfloor","Core"]}`




It's likely possible I did something wrong friday that failed to create the correct order/build.
As you are saying that this should work, and it works in your test case, I'm closing this.
Thanks!

**Comment by RedFoxUA** [comment]
I have the same issue (based on standard Doc "Dependencies #1 - Dependencies to a project in the same repository" staring from part "... The recommended solution to this problem is to set a repository setting called useProjectDependencies to true and then run Update AL-Go System Files. ..")

![image](https://github.com/microsoft/AL-Go/assets/39195466/846b8419-b2cb-495d-a197-c6767ad1d9f2)

**Comment by freddydk** [comment]
@RedFoxUA - please don't reply to old closed issues.
If you have a problem, please create a new issue and include logs and details on what goes wrong.
Thanks
