### ISSUE TITLE
App Version is not taken from App.json

### ISSUE THREAD

**Issue by MilosMikulasek-TTL** [microsoft/AL-Go#79]
Good morning,

I am testing the scenario 11. [Set up CI/CD for an existing AppSource App](https://github.com/microsoft/AL-Go/blob/main/Scenarios/SetupCiCdForExistingAppSourceApp.md)

I added existing Source App and tune the workflow to run with no issues
**Then I added Source App Test to the project and now I am stuck with error at [Build] - [Run pipeline] - [Compiling test apps]**
`  Using Version 1.0.9.1
  Using Symbols Folder: D:\a\app3\app3\.packages
  Downloading symbols: Astral 365_Astral Apply_1.0.19.0.app
  Url : http://172.24.244.187:7049/BC/dev/packages?publisher=Astral%20365&appName=Astral%20Apply&versionText=1.0.19.0&tenant=default
  ERROR The remote server returned an error: (404) Not Found.`

Even I do have specified at App.json file
`"version":  "1.0.19.0",`
The system generates it's own ...
` Using Version 1.0.9.1`

Could you advice please, how can force it to use the version as is at App.json?

Thank you,
Milos Mikulasek

**Comment by freddydk** [comment]
Version numbers are auto-increasing and your test app should just have a dependency to version 1.0.0.0 of the main app - you don't want to be maintaining version numbers in dependencies.

**Comment by freddydk** [comment]
You can read about VersioningStrategy here: https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md

**Comment by MilosMikulasek-TTL** [comment]
Thanks a lot Freddy, I will go through the VersioningStrategy.

Just before I do ... how should I maintain the dependency between App & testApp? (suppose it could be explained at the document?)

My App3 repository got following App/Test folders
. Astral Apply (here is the App.json file with defined version)
. Astral Apply Test (here is the App.json with defined dependencies - one of them is the Astral Apply incl. version no.)

**Comment by freddydk** [comment]
When your App and the TestApp is in the same repo, then the testApp should just have a dependency on the app (version 1.0.0.0)
They will always be built together, no reason to make it hard.
If you have another repo with a third app, which has a dependency on the first repo (with App), you specify appDependencyProbingPaths in settings - basically just point to the other repo and it will automatically download latest released versioin.
(will update the documentation soon)

**Comment by MilosMikulasek-TTL** [comment]
Thanks a lot Freddy. Will try ...
