### ISSUE TITLE
410 Gone Error in Publish to Environment

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#790]
Getting "The remote server returned an error: (410) Gone" when running Publish to Environment in a repository that requires another repo in order to build. Have tested, as best we can, the various elements (AL-Go Settings, ALGOORGSETTINGS, AUTHCONTEXT, GHTOKENWORKFLOW). Cannot determine which server or what is "gone."  Need help tracking down the source of the error.

Here is ALGOORGSETTINGS:

{"doNotPublishApps":true,"artifact":"https://bcartifacts.azureedge.net/sandbox/22.0.54157.55210/us","appDependencyProbingPaths":[{"repo":"CAI-Software-Inc / Precious-Metals-Solution","release_status":"release","AuthTokenSecret": "GhTokenWorkflow"}]}

Here is log:

Run $ErrorActionPreference = "STOP"
13s
Run microsoft/AL-Go-Actions/ReadSettings@v3.0
Run try { D:\a\_actions\microsoft\AL-Go-Actions\v3.0\ReadSettings/ReadSettings.ps[1](https://github.com/CAI-Software-Inc/Johnson-Matthey-UK/actions/runs/6656344027/job/18088700881#step:4:1) -actor $ENV:_actor -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -project $ENV:_project -getenvironments $ENV:_getenvironments -includeProduction ($ENV:_includeProduction -eq 'Y') -release ($ENV:_release -eq 'Y') -get $ENV:_get } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 6.0.0
BC.HelperFunctions emits usage statistics telemetry to Microsoft
SettingsJson={"keyVaultCertificateUrlSecretName":"","microsoftTelemetryConnectionString":"InstrumentationKey=84bd9223-67d4-4378-8590-9e4a46023be2;IngestionEndpoint=https://westeurope-1.in.applicationinsights.azure.com/","type":"PTE","sendExtendedTelemetryToMicrosoft":false,"appBuild":8,"installTestApps":[],"versioningStrategy":0,"installApps":[],"installTestLibraries":false,"runNumberOffset":0,"codeSignCertificatePasswordSecretName":"codeSignCertificatePassword","country":"us","partnerTelemetryConnectionString":"","insiderSasTokenSecretName":"insiderSasToken","doNotRunTests":false,"runs-on":"windows-latest","generateDependencyArtifact":false,"templateUrl":"https://github.com/microsoft/AL-Go-PTE@main","keyVaultCertificatePasswordSecretName":"","rulesetFile":"","licenseFileUrlSecretName":"licenseFileUrl","memoryLimit":"","keyVaultClientIdSecretName":"","testFolders":[],"githubRunner":"windows-latest","doNotBuildTests":false,"environments":[],"companyName":"","assignPremiumPlan":false,"artifact":"https://bcartifacts.azureedge.net/sandbox/22.0.54[15](https://github.com/CAI-Software-Inc/Johnson-Matthey-UK/actions/runs/6656344027/job/18088700881#step:4:16)7.55210/us","ghTokenWorkflowSecretName":"ghTokenWorkflow","enableTaskScheduler":false,"enableCodeCop":false,"repoVersion":"1.0","doNotPublishApps":true,"doNotSignApps":false,"unusedALGoSystemFiles":[],"githubRunnerShell":"powershell","cacheKeepDays":3,"bcptTestFolders":[],"updateDependencies":false,"cacheImageName":"my","treatTestFailuresAsWarnings":false,"additionalCountries":[],"enableUICop":false,"customCodeCops":[],"appDependencies":[],"doNotRunBcptTests":false,"appDependencyProbingPaths":[{"AuthTokenSecret":"GhTokenWorkflow","release_status":"release","repo":"CAI-Software-Inc / Precious-Metals-Solution"}],"installTestFramework":false,"keyVaultName":"","installOnlyReferencedApps":true,"obsoleteTagMinAllowedMajorMinor":"","applicationDependency":"18.0.0.0","applicationInsightsConnectionStringSecretName":"applicationInsightsConnectionString","shell":"powershell","failOn":"error","projects":[],"testDependencies":[],"appRevision":0,"codeSignCertificateUrlSecretName":"codeSignCertificateUrl","configPackages":[],"useProjectDependencies":false,"appSourceCopMandatoryAffixes":[],"buildModes":[],"templateBranch":"","installPerformanceToolkit":false,"appFolders":[],"repoName":"Johnson-Matthey-UK","alwaysBuildAllProjects":false,"skipUpgrade":false,"installTestRunner":false,"adminCenterApiCredentialsSecretName":"adminCenterApiCredentials"}
GitHubRunnerJson="windows-latest"
GitHubRunnerShell=powershell
Removing BcContainerHelper
8s
Run microsoft/AL-Go-Actions/ReadSecrets@v3.0
Run try { D:\a\_actions\microsoft\AL-Go-Actions\v3.0\ReadSecrets/ReadSecrets.ps1 -settingsJson $ENV:_settingsJson -secrets $ENV:_secrets -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 6.0.0
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Trying to get the secret(Sandbox-AuthContext) from the github environment.
Could not find secret Sandbox-AuthContext in Github secrets or Azure Key Vault.
Trying to get the secret(Sandbox_AuthContext) from the github environment.
Could not find secret Sandbox_AuthContext in Github secrets or Azure Key Vault.
Trying to get the secret(AuthContext) from the github environment.
Masking value for AuthContext
Secret(AuthContext) was retrieved from the github environment.
Masking value for AuthContext.RefreshToken
Masking value for AuthContext.Scopes
Masking value for AuthContext.TenantID
Masking value for AuthContext.ClientID
AuthContext successfully read from secret AuthContext
Trying to get the secret(Sandbox-EnvironmentName) from the github environment.
Could not find secret Sandbox-EnvironmentName in Github secrets or Azure Key Vault.
Trying to get the secret(Sandbox_EnvironmentName) from the github environment.
Could not find secret Sandbox_EnvironmentName in Github secrets or Azure Key Vault.
Trying to get the secret(EnvironmentName) from the github environment.
Could not find secret EnvironmentName in Github secrets or Azure Key Vault.
Trying to get the secret(projects) from the github environment.
Could not find secret projects in Github secrets or Azure Key Vault.
Trying to get the secret(GhTokenWorkflow) from the github environment.
Masking value for GhTokenWorkflow
Secret(GhTokenWorkflow) was retrieved from the github environment.
The following secrets was not found: Sandbox-AuthContext, Sandbox_AuthContext, Sandbox-EnvironmentName, Sandbox_EnvironmentName, EnvironmentName, projects
Removing BcContainerHelper
0s
Run $ErrorActionPreference = "STOP"
Using AuthContext secret as AuthContext
authContext=***
environmentName=SANDBOX
environmentName (as Base64)=U0FOREJPWA==
projects=*
7s
Run microsoft/AL-Go-Actions/Deploy@v3.0
Run try { D:\a\_actions\microsoft\AL-Go-Actions\v3.0\Deploy/Deploy.ps1 -actor $ENV:_actor -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -projects $ENV:_projects -environmentName $ENV:_environmentName -artifacts $ENV:_artifacts -type $ENV:_type } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 6.0.0
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Analyzing artifacts
https://api.github.com/repos/CAI-Software-Inc/Johnson-Matthey-UK/actions/artifacts?per_page=100&page=1
project '*'
Analyzing artifacts
https://api.github.com/repos/CAI-Software-Inc/Johnson-Matthey-UK/actions/artifacts?per_page=100&page=1
project '*'
Downloading artifact Johnson-Matthey-UK-main-Apps-1.0.11.0
https://api.github.com/repos/CAI-Software-Inc/Johnson-Matthey-UK/actions/artifacts/67048[32](https://github.com/CAI-Software-Inc/Johnson-Matthey-UK/actions/runs/6656344027/job/18088700881#step:4:34)44/zip
Error: The remote server returned an error: (4[1](https://github.com/CAI-Software-Inc/Johnson-Matthey-UK/actions/runs/6656344027/job/18088700881#step:5:1)0) Gone. 

Gone

Error: Deploy action failed. Error: The remote server returned an error: (410) Gone.   Gone  Stacktrace: at InvokeWebRequest, D:\a\_actions\microsoft\AL-Go-Actions\v3.0\Github-Helper.psm1: line 91 at DownloadArtifact, D:\a\_actions\microsoft\AL-Go-Actions\v3.0\Github-Helper.psm1: line 716 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v3.0\Deploy\Deploy.ps1: line 100 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v3.0\Deploy\Deploy.ps1: line 99 at <ScriptBlock>, D:\a\_temp\87f84fb4-4dfc-4f55-8db5-[199](https://github.com/CAI-Software-Inc/Johnson-Matthey-UK/actions/runs/6656344027/job/18088700881#step:5:201)acfc60cca.ps[1](https://github.com/CAI-Software-Inc/Johnson-Matthey-UK/actions/runs/6656344027/job/18088700881#step:6:1): line 2 at <ScriptBlock>, <No file>: line 1
AL-Go action ran: Deploy Telemetry Correlation Id: 9d8aa576-fcbd-4c79-8679-a87390403adc
Removing BcContainerHelper
Error: Process completed with exit code [1](https://github.com/CAI-Software-Inc/Johnson-Matthey-UK/actions/runs/6656344027/job/18088700881#step:7:1).

**Comment by freddydk** [comment]
Sorry for the very late reply
It looks like the build might have expired, which is why you would get the Gone message.
The only way to keep a build indefinitely is either to use GitHub Packages, storage or like - or to create a release and then have depending repositories use releases.

**Comment by buzzwick** [comment]
Thanks. Has not recurred, but this explanation sheds that much more light on the inner workings of the AL-Go actions nonetheless.
