### ISSUE TITLE
powershell: command not found error when using the ubuntu settings

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/AL-Go#792]
I have the configuration 

"DeployToSandbox": {
        "EnvironmentType": "SaaS",
        "EnvironmentName": "Sandbox",
        "Branches": [
          "main"
        ],
        "Projects": "*",
        "SyncMode": "ForceSync",
        "ContinuousDeployment": true,
        "runs-on": "ubuntu-latest"
    },

I also have a self-hosted agent.

the "runs-on": "ubuntu-latest" causes a deployment error in my setup.

` $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
  try {
    /home/runner/work/_actions/microsoft/AL-Go-Actions/v4.0/ReadSettings/ReadSettings.ps1 -project $ENV:_project -get $ENV:_get
  }
  catch {
    Write-Host "::ERROR::Unexpected error when running action. Error Message: $($_.Exception.Message.Replace("`r",'').Replace("`n",' ')), StackTrace: $($_.ScriptStackTrace.Replace("`r",'').Replace("`n",' <- '))";
    exit 1
  }
  Error: powershell: command not found`

**Comment by gntpet** [comment]
got the same issue :(

**Comment by freddydk** [comment]
The DeployTo will get a shell property to control which shell to use - PR is here: https://github.com/microsoft/AL-Go/pull/1031
