### ISSUE TITLE
CheckForUpdates and Dependabot

### ISSUE THREAD

**Issue by frottke** [microsoft/AL-Go#796]
Hi @freddydk ,

a quick question about the "CheckForUpdates" step. Is it planned or generally possible to implement/trigger this functionality via Dependabot?

Thank you!

**Comment by freddydk** [comment]
Haven't looked into dependabot.
It is possible to run Update AL-Go System files on a schedule, but I have Dependabit on my list of things to look into

**Comment by freddydk** [comment]
CheckForUpdates can be automated by adding a schedule to .github/AL-Go-Settings.json, like:

```
  "UpdateGitHubGoSystemFilesSchedule": "0 0 * * *"
```

This will however use direct COMMIT (which might not be allowed).
I will add an item to the backlog for allowing Update AL-Go System Files to be able to create Pull Requests and then allow dependabot to approve PRs automatically when created from Update AL-Go System Files.

**Comment by freddydk** [comment]
Transferred to project backlog
https://github.com/orgs/microsoft/projects/521/views/1?filterQuery=update+&pane=issue&itemId=44366441
