### ISSUE TITLE
"No matching artifacts found", when the dependency latest workflow execution is TestNextMinor, TestNextMajor or TestCurrent

### ISSUE THREAD

**Issue by mstoilov-isystems-group** [microsoft/AL-Go#799]
Hi,
I have got a problem with one of our pipelines.
We have an app which has a dependency to other repository. In .AL-Go\settings.json I have appDependencyProbingPaths with  "version":"latest" and "release_status": "latestBuild":

 "appDependencyProbingPaths": [
    {
      "repo": "https://github.com/MYORG/MYDEPENDENCY",
      "version": "latest",
      "release_status": "latestBuild",
      "authTokenSecret": "GETARTIFACTSFROMBUILDS",
      "projects": "*"
    }
  ]
  
  MYDEPENDENCY app has no recent changes, respectively there are no recent builds, but last artifacts are not expired.
Every week we are running TestNextMajor, TestNextMinor, TestCurrent pipelines on MYDEPENDENCY app.
  
In the build pipeline for my app I am receiving an error that no matching artifacts are found for the dependency MYDEPENDENCY:
![image](https://github.com/microsoft/AL-Go/assets/144775121/323915cc-fde0-4d85-8164-3d120e8e69ce)

After digging around I found what is causing the problem. 
In Github-Helper.psm1 GetArtifacts function, when artifacts are filtered artifactPattern  is  `*-main-*-*` and buildOutputPattern  is `*-main-BuildOutput-*` 

In this case buildOutputArtifacts from  TestNextMajor, TestNextMinor, TestCurrent are also retrieved, because their name matches the pattern. "D365BC_ISLICENSING-main-BuildOutput-NextMajor-20231022"  for example. 
This causes a problem in the end of GetArtifacts function where matchingArtifacts  workflow id is compared with the first workflow id  from buildOutputArtifacts - basically it compares the workflow id of my real artifact with the workflow id of the NextMajor BuildOutput and the GetArtifacts returns empty result with "No matching artifacts found" in the log.

`$matchingArtifacts += @($artifacts.artifacts | Where-Object { !$_.expired -and $_.name -like $artifactPattern })
$buildOutputArtifacts += @($artifacts.artifacts | Where-Object { !$_.expired -and $_.name -like $buildOutputPattern })
`

`$result = $matchingArtifacts | Where-Object { $_.workflow_run.id -eq $buildOutputArtifacts[0].workflow_run.id }`

**Comment by freddydk** [comment]
You are right, this is a regression

**Comment by jfr** [comment]
fixing issues during conference - you're the best 👏 @freddydk

**Comment by freddydk** [comment]
This should now be fixed, sorry for the inconvenience
