### ISSUE TITLE
CheckForUpdates warning after removal of feature branches from CICD

### ISSUE THREAD

**Issue by wiktortomaszewski** [microsoft/AL-Go#801]
Hi!

We decided to disable CICD trigger on feature/* branches by removing it from "branches" array in CICD.yaml. The reason for this is mostly saving time on the runners, and having CICD trigger on Pull Request seems to be satisfactory for our scenario. However now the CheckForUpdates job considers this to be a change, and gives us a warning about newer version of AL-Go files available. 
This can be observed by the PR created by UpdateGitHubGoSystemFiles action. 

<img width="511" alt="image" src="https://github.com/microsoft/AL-Go/assets/109514481/1ddaebe3-e284-4f90-9aac-82d9300abb27">

I guess we could name our feature branches in a different way to skip the trigger, but I'm considering if maybe there is a different way to handle it?

**Comment by freddydk** [comment]
There is...

See https://aka.ms/algosettings#cicdpushbranches
