### ISSUE TITLE
The link https://docs.microsoft.com/en-us/azure/developer/github/github-key-vault is redirected to https://learn.microsoft.com/en-us/azure/developer/github, but I can not find the page where it describe how to setup the key vault for access from GitHub.

### ISSUE THREAD

**Issue by freddydk** [microsoft/AL-Go#818]
The link https://docs.microsoft.com/en-us/azure/developer/github/github-key-vault is redirected to https://learn.microsoft.com/en-us/azure/developer/github, but I can not find the page where it describe how to setup the key vault for access from GitHub.
Can you update this to  the correct link?

_Originally posted by @FrankAuwers in https://github.com/microsoft/AL-Go/issues/182#issuecomment-1809912737_

**Comment by jonaswre** [comment]
I used this https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows#use-the-azure-login-action-with-a-service-principal-secret.

Not quite straight forward but gave me all I needed.
