### ISSUE TITLE
The term 'AzureSignTool' is not recognized

### ISSUE THREAD

**Issue by FrankAuwers** [microsoft/AL-Go#819]
I try to setup the pipeline with signing the app but I get every time that the AzureSignTool is not recognized.
We are running this on a self hosted VM.
Are we missing or forgot something?

The error:
AL-Go action ran: Sign Telemetry Correlation Id: 572376d3-7bcc-40de-911c-9f55990bfcfd
Error: Unexpected error when running action. Error Message: The term 'AzureSignTool' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again., StackTrace: at <ScriptBlock>, C:\action-runners\1\_work\_actions\microsoft\AL-Go-Actions\v4.0\Sign\Sign.ps1: line 51 <- at RetryCommand, C:\action-runners\1\_work\_actions\microsoft\AL-Go-Actions\v4.0\AL-Go-Helper.ps1: line 2201 <- at <ScriptBlock>, C:\action-runners\1\_work\_actions\microsoft\AL-Go-Actions\v4.0\Sign\Sign.ps1: line 46 <- at <ScriptBlock>, C:\action-runners\1\_work\_temp\9dfb99d1-9776-43ae-8dcd-40a7600ebb2b.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
Error: Process completed with exit code 1.

**Comment by freddydk** [comment]
@aholstrup1

**Comment by FrankAuwers** [comment]
After restart of the VM it works

**Comment by aholstrup1** [comment]
Thanks for reporting back @FrankAuwers. I'll close the issue then

**Comment by jonaswre** [comment]
Funny thing I had the same Issue today... I needed to start runners as normal user. I think some of the requirements where not present in the service user that started it. Just FYI...
