### ISSUE TITLE
CI for multi country App Source

### ISSUE THREAD

**Issue by MilosMikulasek-TTL** [microsoft/AL-Go#82]
Hi Freddy,

Could you advice settings for existing multi country App Source CI/CD - to arrange CI loop test for all listed countries? ...

Thanks a lot,
Milos Mikulasek

**Comment by freddydk** [comment]
You can create a setting in the settings file called additionalCountries, like:

```
    "additionalCountries":  [ "de", "dk", "it" ]
```
Then it will build all 4 countries (your primary and these).
You can also add this to the Test Current.settings.json in the .github folder - then it won't run on CI, but only on the Test Current wrorkflow tests (the setting will be specific for that workflow).
If you then add this to the Al-Go-Settings.json and re-run Update AL-Go System fieles:

```
    "CurrentSchedule":  "0 2 * * *",
```

then the Test Current workflow will run every night at 2.

**Comment by freddydk** [comment]
I did just discover that there is a bug when setting additionalCountries, without also setting artifact in the settings file.
If you set artifact to "////latest" in the settings file, it should work just fine.
Will fix this bug asap.

**Comment by MilosMikulasek-TTL** [comment]
Thanks a lot, artifact: "////latest" settings looks good. Started 20 minutes ago and action is still running ...

**Comment by MilosMikulasek-TTL** [comment]
ends with success, thank you Freddy
