### ISSUE TITLE
Publishing nomenclature

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#820]
[AL-Go](https://github.com/microsoft/AL-Go/tree/main)/[Workshop](https://github.com/microsoft/AL-Go/tree/main/Workshop)/PublishToProduction.md

Says "Note that the default version is "current" - **this will deploy the release with the name "current".** If you want to just use the latest build, you would specify "latest":"

But in Issue #809, freddyk says 

"AL-Go would never expect a release called current - as you would have to delete that and re-create that again and again.
A release should have a version number."

and 

"current is the latest released version (i.e. the current version on the market) - not branch specific"

So it would seem that an edit to the workshop is in order?

**Comment by freddydk** [comment]
I will fix the workshop material accordingly - I understand the misunderstanding, sorry for this.

**Comment by buzzwick** [comment]
Not at all, thanks. I was just glad I found that workshop text again, because I knew that "something I read somewhere" had started me down the path I was on. 

Fixed a couple more setup issues, and now this repo compiles and deploys perfectly. It's a beautiful thing...
