### ISSUE TITLE
Indirect dependencies not resolved correctly in multi project repo

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#823]
I have the following dependency setup.

1. A <- [B1 <- B2]
2. A <- C <- D

B1 and B2 are in the same repo.
When building B2, A is not installed as a dependency and missing when compiling B2.
If created the following repos to show the issue.
 
[AppA](https://github.com/byndit-demo/App-A)
[AppB](https://github.com/byndit-demo/App-B)
[AppC](https://github.com/byndit-demo/App-C)
[AppD](https://github.com/byndit-demo/App-D)

The second case works fine.

**Comment by freddydk** [comment]
The reason for this is that when building B2, the output from B1 build is used as artifact when publishing to the build container - it doesn't resolve any missing dependencies in this scenario.
Will investigate what the best approach to a fix would be here...

**Comment by jonaswre** [comment]
If you need write access to the repos let me know.

**Comment by freddydk** [comment]
Would be nice, then I will re-platform a few of the repos to a test AL-Go version and make some tests.

**Comment by jonaswre** [comment]
You should have recieved a few invites.

**Comment by freddydk** [comment]
App-B now builds after adding a fix to an AL-Go branch.
Will check what the consequences of this fix is on a broader scale before creating a PR.

**Comment by freddydk** [comment]
The fix basically generates an artifact with the dependencies used when building B1 and using that in B2 (together with the apps from B1)

**Comment by jonaswre** [comment]
Thanks alot. Will update my real repo once its in preview.
