### ISSUE TITLE
[Enhancement] Different server URLs for pull and push of GitHub packages

### ISSUE THREAD

**Issue by skeck** [microsoft/AL-Go#827]
As a partner, we follow the recommended scenario and use an Enterprise Github organization. Our AppSource apps and the associated Github packages are located in this organization. Our customers use their own Github organization (teams) that they manage/own. Our developers are members of both organizations. The repos there contain customer-specific PTE apps that complement our AppSource apps. The PTE apps in the customer organization are dependent on our AppSource apps that are in the partner organization.

In the secret `gitHubPackagesCredential` I can specify values for `serverUrl` and `token`. During a build within the customer organization, the packages are then pulled from the partner organization serverUrl but also pushed to the partner organization serverUrl.

- `RunPipeline.ps1` uses `$gitHubPackagesCredential.serverUrl `and` $gitHubPackagesCredential.token` as parameters for `InstallMissingDependencies` -> means pulling the packages.
- `Deliver.ps1 `uses the same values to push the package.

Wish list: A distinction between pull and push would be very helpful for us. From a customer perspective, I would like to pull the Github packages from the partner organization. However, I would like to host the packages resulting from my own PTE-build in my own Github organization (e.g. for billing and/or legal reasons). If we could have more specific settings in `$gitHubPackagesCredential` in addition to the existing one, that would be great. Something like `$gitHubPackagesCredential.pushToServerUrl` + token, `$gitHubPackagesCredential.pullFromServerUrl` + token.

Many thanks

**Comment by jonaswre** [comment]
Hi, the nuget package handling is currently being worked on to allow for these kind of szenarios. There is a discussion on this topic for external and internal dependency handling. Splitting it in the way you suggested would have the drawback that if you split pushing a pulling your customers won't be able to resolve their own apps, only your apps. Which would defeat the purpose for pushing in the first place.


@freddydk it might be useful to be able to publish to multiple feeds. This would allow you to deliver released apps to a separate nuget feed for your partners and customers. You probably wouldn't want your customers to resolve in your "dev" feed.

**Comment by skeck** [comment]
> Splitting it in the way you suggested would have the drawback that if you split pushing a pulling your customers won't be able to resolve their own apps, only your apps. Which would defeat the purpose for pushing in the first place.

true, didn't think of that. We usually only have a single PTE app in the customer repo and also use these packages for custom deployments only, but of course a generic approach is needed.

I also missed that, which would make my wish obsolete: https://github.com/microsoft/AL-Go/issues/261 :)

**Comment by jonaswre** [comment]
You could use the Delivery Overrides to create custom code for your customer to push to a blob storage or something similar. 

https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md#custom-delivery

Btw. letting your customer publish into your feed works but is not good practice. I'm pretty sure they could then override your AppSource Apps and break your pipelines.

**Comment by freddydk** [comment]
Yeah, the idea is that every repo should publish packages to your own organization and then you should be able to specify a number of feeds you trust, where AL-Go will search for packages from "other" providers.
Assuming we will have this in preview this year.

**Comment by skeck** [comment]
> You could use the Delivery Overrides to create custom code for your customer to push to a blob storage or something similar.
> 
> https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md#custom-delivery
> 

That's what i do right now. Works great, but i want to override as little as possible

> Btw. letting your customer publish into your feed works but is not good practice. I'm pretty sure they could then override your AppSource Apps and break your pipelines.

i agree

**Comment by jonaswre** [comment]
The Delivery/deploy "Overrides" don't really replace existing functions they are more of an addon. So I wouldn't be to worried about these. They are there for these kind of szenarios. But they still have the obvious drawback of needing to maintain them across your customers.

**Comment by skeck** [comment]
Would be an option. I just don't want to modify the intended nuget process by using a serverUrl that points to another feed than that of my own organization, prevent Deliver.ps1 pushing the package to that feed and in the end having a (hard to maintain) custom delivery to push it to my own organisation instead. While it's technically not overriding a script, it just doesn't feel right to me

thanks you all for your input, looking forward to the preview
