### ISSUE TITLE
S2S Deployment

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#830]
From the ContinuousDeployment.md Workshop segment in the section on Impersonation:
"Complete the login **with a Business Central user, which has access to deploy applications** in the environment setup for continuous deployment."

In the S2S section, where it says 

"setup an AAD App and register it inside the Business Central environment you want to deploy to"

For S2S, is the app being registered the BC extension being deployed, or is it GitHub needing "access to deploy applications."?

I'm not clear why we would be authenticating a user in one case and the app being deployed in the other, so I thought it must be GitHub needing the access. 

Either way, I need to be able to advise our client's IT department as to which "app" it is that needs to be registered in Entra ID. Thanks.

**Comment by freddydk** [comment]
Setting up the AAD App and registering it in BC is step 1+2 here: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/automation-apis-using-s2s-authentication

**Comment by buzzwick** [comment]
Thanks, I am familiar with that doc page. At this point I think it is our client (owners of the site we are trying to deploy to) who needs to do the app registration and so forth. Because we do not have admin access.

For the moment I am going to assume that the app that needs to be registered is our product offering; the one that resides in our GitHub repository. Correct me if I am wrong about that. Because all of the documentation I have seen so far assumes that everyone knows what "app" is being referred to.
