### ISSUE TITLE
Cannot build using older version of BC

### ISSUE THREAD

**Issue by kennetlindberg** [microsoft/AL-Go#833]
When trying to build anything using an older version of BC (by setting "artifact": "/onprem/20.1.0.0/fi/closest" for example), I get this error. It works if I use the latest version of BC but all older versions I have tried fails. I will attach the full log.

[AlGoError.log](https://github.com/microsoft/AL-Go/files/13451044/AlGoError.log)

`[Build . (Default) / . (Default)](https://github.com/consilia-solutions/bank-pro/actions/runs/6970838871/job/18969626941#step:48:323)
Unexpected error when running action. Error Message: re-exec error: exit status 1: output: hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) ExitCode: 1 Commandline: docker build --isolation=process --memory 8G --no-cache --tag my:onprem-20.1.39764.39901-fi c:\bcartifacts.cache\mq2udsw0.0ov, StackTrace: at DockerDo, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\HelperFunctions.ps1: line 259 <- at New-BcImage, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\ContainerHandling\New-NavImage.ps1: line 694 <- at New-BcContainer, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\ContainerHandling\New-NavContainer.ps1: line 623 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 761 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 993 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 922 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 904 <- at Run-AlPipeline, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 866 <- at <ScriptBlock>, C:\3\_work\_actions\microsoft\AL-Go-Actions\v4.0\RunPipeline\RunPipeline.ps1: line 371 <- at <ScriptBlock>, C:\3\_work\_temp\935eb052-18cf-4b7a-b279-e7f658d01440.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1`

**Comment by kennetlindberg** [comment]
I forgot to mention that this happened in both an "old" Azure VM build machine and in a freshly created one.

**Comment by freddydk** [comment]
And if you try to use a GitHub hosted agent? (not self-hosted)

**Comment by kennetlindberg** [comment]
It works on a GitHub hosted agent.

**Comment by freddydk** [comment]
How did you create your azure hosted VMs?
Did you try https://aka.ms/getbuildagent?

That is what I use and that seems to install all pre-reqs.

**Comment by kennetlindberg** [comment]
Yes, kind of , I used a powershell script that I got from you which uses the same template if I'm not mistaken (https://raw.githubusercontent.com/microsoft/nav-arm-templates/master/buildagent.json).

Actually, I got it working now, by replacing

`"artifact": "/OnPrem/20.1.0.0/fi/closest"`

with

`"artifact": "//20.1.0.0/fi/closest"`

in `.AL-Go/settings.json`.

**Comment by freddydk** [comment]
That is strange...

**Comment by AskeHolst** [comment]
We have a similar issue in the Creating Container step on our self-hosted runners, I cannot get them to build anything, but github runners are fine. It started just over a week ago on both runners at the same time.
The runners were created about a year ago, using https://aka.ms/getbuildagent 
The runners have plenty of space (low disk space was a cause of a similar issue previously), and I see nothing in the logs, I even updated docker and zapped it.
I probably should try to create a new runner.

I do **not** specify artifact myself though.

Example output:

```
  Sync'ing Tenant
  Tenant is Operational
  Stopping Business Central Service Tier
  Installation took 215 seconds
  Installation complete
  New-Bcimage Telemetry Correlation Id: fa5c75e2-3aab-4843-9bd0-c056f3ee0996
  New-BcContainer Telemetry Correlation Id: e9008288-bd1b-4885-92ac-6ade3117d539
Removing container
  Get Event Log from container
  Getting event log for bcPTRLibrary7024123124
  Error: No such object: bcPTRLibrary7024123124
  Removing Desktop shortcuts
Run-AlPipeline Telemetry Correlation Id: aab4ef14-a021-4e39-a61e-8120cc069a00
AL-Go action ran: RunPipeline Telemetry Correlation Id: 45c03671-a9ca-4321-abc3-6ad60b46bfbc
Error: Unexpected error when running action. Error Message: re-exec error: exit status 1: output: hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) ExitCode: 1 Commandline: docker build --isolation=process --memory 8G --no-cache --tag my:sandbox-23.1.13431.14246-gb-mt c:\bcartifacts.cache\jhctaign.dop, StackTrace: at DockerDo, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\HelperFunctions.ps1: line 259 <- at New-BcImage, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\ContainerHandling\New-NavImage.ps1: line 694 <- at New-BcContainer, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\ContainerHandling\New-NavContainer.ps1: line 623 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 761 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 993 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 922 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 904 <- at Run-AlPipeline, C:\ProgramData\BcContainerHelper\6.0.0\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 866 <- at <ScriptBlock>, C:\1\_work\_actions\microsoft\AL-Go-Actions\v4.0\RunPipeline\RunPipeline.ps1: line 371 <- at <ScriptBlock>, C:\1\_work\_temp\a28e9721-b5c0-46a3-bdaf-969c07abc7fe.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
Error: Process completed with exit code 1.

```

**Comment by freddydk** [comment]
@AskeHolst - do you have remote desktop access to the runners?
Can you create a BC container manually on these?
Like running this:

```
$ErrorActionPreference = "stop"
$credential = New-Object pscredential -ArgumentList 'admin', $PasswordSecret.SecretValue
$artifactUrl = Get-BCArtifactUrl -country us -select latest
New-BCContainer -containerName bcserver `
                -accept_eula `
                -Auth 'UserPassword' `
                -artifactUrl $artifactUrl `
                -Credential $credential `
                -imagename 'my'
```

**Comment by freddydk** [comment]
and... - are the runners Windows Server 2019 or 2022 ?

**Comment by AskeHolst** [comment]
@freddydk Creating a container manually errors out at the same point (building the image), so this is unrelated to Al-Go.
Building without specifying an image works fine.
Should I create a BCCH issue for this?

**Comment by freddydk** [comment]
There is an error in Containerhelper on this - I just cannot repro this on any machine I have tested:-(
What OS - what updates are installed?
Then I will try to setup a similar macine

**Comment by kennetlindberg** [comment]
Hi, I'm having this exact issue now again. Is it due to faulty images again?

**Comment by freddydk** [comment]
Please create a new issue and include as much info as possible (also when it started to fail).

**Comment by AskeHolst** [comment]
I'm seeing the problem as well we say it starting yesterday. Al-go was updated on the weekend, could be related or not.
It affect both our runners, one created a month ago the other last year, both using https://aka.ms/getbuildagent

**Comment by freddydk** [comment]
Does it work if you switch to AL-Go-PTE@main? (which is v5.0)
or @v4.1?
In all cases, create a new issue and include logs then I will have a look
