### ISSUE TITLE
KeyVault access with pushing to AppSource with AL-Go

### ISSUE THREAD

**Issue by FrankAuwers** [microsoft/AL-Go#834]
Hi,

we get the following error after we publish our app with AL-Go for Github when the keyvault is accesed:

does not have a publisher Microsoft Entra tenant ID, so it cannot use key vaults. The publisher's Microsoft Entra tenant ID must be specified at publish time.

Is there a setting that we missed for this, our can we not publish our extenstons with AL-Go for AppSource with keyvault access?

**Comment by FrankAuwers** [comment]
Yes, The app is also published to AppSource. And in a docker environment we can access our key vault.
But when the app is published to AppSource and we install it we get in our telemetry the error:
does not have a publisher Microsoft Entra tenant ID, so it cannot use key vaults. The publisher's Microsoft Entra tenant ID must be specified at publish time.
And also the values are not retrieved with the installed app.
The key vault is registered as described in the documentation provide by Microsoft.

**Comment by freddydk** [comment]
Strange
If you say that it works when you deploy it to a docker container, then it seems like nothing is wrong with the app and it should be on the service tier (hence the registration).
Do you have one or multiple apps? Could you maybe loop me into the mailthread you have with them?

**Comment by FrankAuwers** [comment]
Hi Freddy,

I forwarded you an e-mail with the conversation that we had with Microsoft about access our key vault.

**Comment by FrankAuwers** [comment]
Fi Freddy,
I just send you the e-mail again.

**Comment by freddydk** [comment]
Thanks, just replied - I don't think the issue is related to AL-Go - let's continue on e-mail.

**Comment by FrankAuwers** [comment]
It was a firewall problem.
