### ISSUE TITLE
Error with Environment Secrets.

### ISSUE THREAD

**Issue by FrankAuwers** [microsoft/AL-Go#840]
This worked before, but now I get always an error. I try several setups.

The error:
Error: Unexpected error when running action. Error Message: No Authentication Context found for environment (XPR365-QA). You must create an environment secret called AUTHCONTEXT or a repository secret called XPR365-QA_AUTHCONTEXT., StackTrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v4.0\Deploy\Deploy.ps1: line 53 <- at <ScriptBlock>, D:\a\_temp\3df304d4-83df-40d9-b678-0be7ec4ca62c.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1

But if we try to create a reposotory secret with the name XPR365-QA_AUTHCONTEXT, we get the next error from GitHub:
Failed to add secret. Secret names can only contain alphanumeric characters ([a-z], [A-Z], [0-9]) or underscores (_). Spaces are not allowed. Must start with a letter ([a-z], [A-Z]) or underscores (_).

**Comment by freddydk** [comment]
If you are using GitHub environments, you can create the authcontext secret under the environment as an environment secret called AUTHCONTEXT (without the prefix).

If you are setting up environments in settings, you should create the environment as XPR365QA and then use

```
"DeployToXPR365QA": {
    "EnvironmentName": "XPR365-QA"
}
```

And then create the secret called XPR365QA_AUTHCONTEXT

**Comment by Dansko-Thad** [comment]
What is supposed to go into the secret exactly?  I'm running into this as well and I don't understand what is supposed to be the value of that secret.

**Comment by freddydk** [comment]
An accesstoken has a validity period of ~60 minutes. Adding that as a secret would require you to modify that with every deployment.

You can find the format of the authcontext secret used for deployment here:
https://github.com/microsoft/AL-Go/blob/main/Workshop/ContinuousDeployment.md
or
https://github.com/microsoft/AL-Go/blob/main/Scenarios/RegisterSandboxEnvironment.md

**Comment by Dansko-Thad** [comment]
Thank you so much, that helps immensely.  This is my first time trying to set all this up for an OnPrem project and it's a lot to absorb in a short period.
