### ISSUE TITLE
DeployToXXXX_QA fails with error: Environment URL '' is not a valid http(s) URL, so it will not be shown as a link in the workflow graph.

### ISSUE THREAD

**Issue by mail2joh** [microsoft/AL-Go#844]
Hi
DeployToXXXX_QA fails with error:
_Unexpected error when running action. Error Message: Authentication failed. Authentication failed, StackTrace: at <ScriptBlock>, /home/runner/work/_actions/microsoft/AL-Go-Actions/v4.0/Deploy/Deploy.ps1: line 169 <- at <ScriptBlock>, /home/runner/work/_temp/cb9764fd-e77f-4702-a69c-2d27a86b0728.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
Process completed with exit code 1.
Environment URL '' is not a valid http(s) URL, so it will not be shown as a link in the workflow graph._

DeployToXXXX_QA fails both from CICD and publish to environment.
Publish to environment work last 28 nov 2023 08:10 GMT
and have not worked since 20 nov 2023 17:30 GMT
![image](https://github.com/microsoft/AL-Go/assets/19235259/ad71225e-da7f-4fb0-9b8c-f396f229ca3e)

I have tried with new DeployTo, which I am using now and the old way.
I have tried borh windows and ubuntu, which iI am using now.
![image](https://github.com/microsoft/AL-Go/assets/19235259/34b8232b-2b1f-4b7b-89f4-7bf2aeefc264)

Please help me to get DeployToXXXX_QA to work again.

/J

**Comment by freddydk** [comment]
Looking at the error above - it says that the refresh token is not valid - it might have expired - then you need to recreate the authcontext secret with a new value.

I think your settings looks fine, here are the recommendations:

If the name of the environment (in GitHJub) is XXX_QA and the name of the environment in BC admin center is BC_QA - then this setting should work:

```
"DeployToXXX_QA": {
  "EnvironmentName": "BC_QA",
  "SyncMode": "ForceSync"
}
```
We do not recommend setting properties, which you don't change.
The recommended authcontext secret should be created as an environment secret and be called AUTHCONTEXT. If you do not use environment secrets, you can still call it AUTHCONTEXT, then it will be used for all environments - or you can call it XXX_QA_AUTHCONTEXT.

**Comment by mail2joh** [comment]
Hi, now it works.
Thank you.

I do not know why, because had allready tried to update authcontext before I created this issue.

XXX_QA is set both as github and BC environment.
Do you mean that I should not use settings if they do not change default values.
So I should not use settings
  _"DeployToXXX_QA": {
    "EnvironmentType": "SaaS",
    "EnvironmentName": "XXX_QA",
    "Branches": [
      "main"
    ],
    "Projects": "*",
    "SyncMode": "ForceSync",
    "ContinuousDeployment": true,
    "runs-on": "ubuntu-latest"
  },
  "DeployToXXX_UAT": {
    "EnvironmentType": "SaaS",
    "EnvironmentName": "XXX_UAT",
    "Branches": [
      "main"
    ],
    "Projects": "*",
    "SyncMode": "ForceSync",
    "ContinuousDeployment": false,
    "runs-on": "ubuntu-latest"
  },_

but use only these settings:
  _"DeployToXXX_QA": {
    "SyncMode": "ForceSync",
    "runs-on": "ubuntu-latest"
  },
  "DeployToXXX_UAT": {
    "SyncMode": "ForceSync",
    "ContinuousDeployment": false,
    "runs-on": "ubuntu-latest"
  },_

I tried both setting now when Publish worked and both settings worked.

**Comment by freddydk** [comment]
at https://aka.ms/algosettings#deployto you can see the defaults for these things and for this:

EnvironmentType is SaaS by default - no need to set that
EnvironmentName is the same as the github environment name - no need to set that
branches is main by default.
projects is * by default
runs-on defaults to whatever runs-on is globally - no need to set that.

The rest is special - you should set that.
