### ISSUE TITLE
Next Major Pipelines Failing Due to Missing 'Newtonsoft.Json.dll

### ISSUE THREAD

**Issue by janlehmkuhl** [microsoft/AL-Go#845]
We are experiencing an issue with our "Next Major" pipelines that has surfaced recently. The critical error causing the failure is:

**Error Message:**
"Cannot bind parameter 'Path' to the target. Exception setting 'Path': 'Cannot find path 'C:\build\vsix\extension\bin\Newtonsoft.Json.dll' because it does not exist."

This issue started occurring about a week ago. We run our pipeline tests weekly, and the last successful run was the previous week. This problem is affecting all our projects, including AppSource and PTEs. Steps already taken include removing all Docker Images and Containers on the Build Agents and cleaning the _work directories. An excerpt of the log is attached for reference.

**Comment by janlehmkuhl** [comment]
[logs_1055.zip](https://github.com/microsoft/AL-Go/files/13598858/logs_1055.zip)

**Comment by aholstrup1** [comment]
At first glance, it looks related to https://github.com/microsoft/navcontainerhelper/issues/3254. There is a fix for that available but it's still in preview. 
If you set the _bcContainerHelperVersion_ setting to _preview_ it should work again (see e.g. https://github.com/microsoft/BCApps/blob/main/.github/AL-Go-Settings.json)

Alternatively, you might have to wait until the next version of bccontainerhelper is released. @freddydk might know when we plan on creating a new release of bccontainerhelper.

**Comment by freddydk** [comment]
6.0.2 has been released
