### ISSUE TITLE
Dependency on third party app

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#846]
Question:
How do we manage a dependency on a third party app--which might be installed on our development environment, but for which we do not have access to a repository for GitHub builds. Is there a way to specify a dependency in Settings and point to a runtime .app file (which we do have access to)? How is this normally handled?

**Comment by freddydk** [comment]
You can use the InstallApps setting - https://aka.ms/algosettings#installapps

**Comment by buzzwick** [comment]
Took a few tries to get the punctuation right, but this works fine now. In future, I will remember to scan the Settings page to look for more exciting features like this one! Thanks very much.

**Comment by buzzwick** [comment]
These are both Dropbox links, which I get by right-clicking on a file in a Dropbox folder and selecting  "Copy Dropbox link." You have to change the 0 at the end, to a 1.

You can also get OneDrive links, and possibly Sharepoint.

 "installApps": [
    "https://www.dropbox.com/scl/fi/9b06xxxx5wv0nt5yb/Suxxxxxxxx.runtime.app?rlkey=f8vv3ww7gybcph2wwrkimgh0w&dl=1",
    "https://www.dropbox.com/scl/fi/k51miwxofx19prvwmlvf6/Johxxxxxxxx.app?rlkey=c7zxcwphz62hcai4xxxxxayc&dl=1"
  ],
