### ISSUE TITLE
Create Online Dev. Environment for [main / .] 

### ISSUE THREAD

**Issue by Marhoon** [microsoft/AL-Go#861]
I try to Create Online Dev. Environment for [main / .] as QA
I get error 

Unexpected error when running action. Error Message: The remote server returned an error: (401) Unauthorized.

However i sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code 

Any advice

**Comment by freddydk** [comment]
If you could paste the full log here, then we might be able to see what happened

**Comment by Marhoon** [comment]
Happy New Year Sir @freddydk 
The Error Log I am getting

[Create Development Environment](https://github.com/Dynamics-Business-Solutions/Bahrain-Generic-Reports-Extension/actions/runs/7315249647/job/19928711263#step:17:106)
Unexpected error when running action. Error Message: The remote server returned an error: (401) Unauthorized., StackTrace: at New-BcEnvironment, C:\ProgramData\BcContainerHelper\6.0.3\BcContainerHelper\Saas\New-BcEnvironment.ps1: line 102 <- at CreateDevEnv, D:\a\_actions\microsoft\AL-Go-Actions\v4.0\AL-Go-Helper.ps1: line 1797 <- at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v4.0\CreateDevelopmentEnvironment\CreateDevelopmentEnvironment.ps1: line 40 <- at <ScriptBlock>, D:\a\_temp\90ef3eb6-623e-4ff7-9da3-aaa483b75ca1.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1

**Comment by freddydk** [comment]
Thanks, same to you:-)

I do not have access to your repository - I cannot follow the link.
But... - based on the stacktrace, I can see that it fails while trying to dump companies and users in the environment after the creation, meaning that the environment has been created, but isn't accessible by the user used for the authentication.

The user needs access to the admin center API - but also to the automation API in the new environment.
