### ISSUE TITLE
LicenseFileUrl

### ISSUE THREAD

**Issue by Marhoon** [microsoft/AL-Go#862]
LicenseFileUrl should include the path of our Microsoft partner developer license! correct?

We cannot see any example of how we upload this file in azure storage and use in it in GitHub AL-Go

appreciate if we can find any example.

Also, can we keep it in any other storage?

**Comment by freddydk** [comment]
Just need to be a direct download url - any storage will work.
Wrote a blog-post some years ago on this - not sure if this still holds: https://freddysblog.com/2017/02/26/create-a-secure-url-to-a-file/

**Comment by Marhoon** [comment]
Sir @freddydk,
 
Amazing its working like a charm, thank you so much. Now I am working on app Certificate so i can upload the SSL and the password.

One more question for each app I need signing with same certificate we have correct ?
And then same password and same SSL for all app we can used? correct me if I am wrong

**Comment by freddydk** [comment]
You can use the same certificate for now, no problem.

but... - in June 2023, the requirements for code signing certificates changes and when you renew your code signing certificate, you will no longer be able to get a .pfx cert and use it locally - you will need to use a HSM secured KeyVault to store your cert. in and use the new mechanism for signing.
