### ISSUE TITLE
Cannot build / install app after force-abort a debug-session during Test with AutoCommit

### ISSUE THREAD

**Issue by PeterBizz** [microsoft/AL-Go#865]
### Scenario: 
 - OnPrem Development
 - Debug a Test procedure with [TransactionModel(TransactionModel::AutoCommit)]
 - Need to do at least one update to the database during the debug session
 - From a breakpoint Stop Debug session (Shift F5)

### Pressing F5 to rebuild and start a new debug session fails with following output: 

Using Windows authentication.
[2024-01-04 11:07:19.12] Sending request to http://localhost:7049/BCTest/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default
[2024-01-04 11:07:32.99] Error: An error occured while processing the request.
Request ID: 65fd7eee-a9cd-4fa3-aeb0-0410fab70907
Session ID: ad688567-7460-4bd9-827f-8446aafeaa0c

If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.
[2024-01-04 11:07:33.01] The request for path /BCTest/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: Could not install the extension 'xxxxxxxxx (version 'xxxxxxx') on tenant 'default' and company '' due to the following error: 'We could not update the data right now.
Please try again later.

Technical details:
**A record was locked for use in another session.** Administrators can see current locks on the Database Locks page or use telemetry (Snapshot ID: 62a89b12-9a31-4b64-a599-5478038152a4)'

### Further actions/ resolution for now
The Database Locks Page is empty, 
the only resolution is to kill the SQL proces that has the most Locks, i.e.:
`declare @Locker as int
declare @cnt as integer
declare @stmt as Varchar(200)
select top 1 @locker = request_session_id , @cnt= count(*) from sys.dm_tran_locks group by request_session_id order by 2 desc

set @stmt = 'KILL ' + cast( @locker  as varchar(33))
if (@cnt > 20  ) begin
select @stmt, @cnt
exec (@stmt)
end else
  select @cnt as 'No large lock count found' `

## Required behaviour
All SQL processes starting during Debug with test should be stopped when Debugging is stopped

**Comment by freddydk** [comment]
Is this related to AL-Go for GitHub??? (or should this have been created somewhere else)

**Comment by PeterBizz** [comment]
Oops, sorry. Is not AL-Go issue but AL issue. Will create it there
