### ISSUE TITLE
AppSource App Licensing Control

### ISSUE THREAD

**Issue by Marhoon** [microsoft/AL-Go#867]
Any advice how we can manage the licensing for app we publish on AppSource, so we manage trail license and sale license and prevent any not license customer to use it.

**Comment by freddydk** [comment]
I think AppSource supports monetization today, else there are partners who have created licensing modules for this.
AL-Go for GitHub doesn't provide any special support for this.

**Comment by jonaswre** [comment]
We have a solution for license management. You can reach out to me if you are intrested.
