### ISSUE TITLE
Publish to QA

### ISSUE THREAD

**Issue by Marhoon** [microsoft/AL-Go#868]
When we publish the to QA Env.

We are getting the following error:

[Deploy to QA](https://github.com/Dynamics-Business-Solutions/Bahrain-Generic-Reports-Extension/actions/runs/7444546544/job/20251919903#step:15:164)
Deploying to QA failed. Unable to publish app. Please open the Extension Deployment Status Details page in Business Central to see the detailed error message.

When we check the error in the QA Cronus Company find attached Log
[Log1.txt](https://github.com/microsoft/AL-Go/files/13857874/Log1.txt)

**Comment by freddydk** [comment]
Please embed the log in the post formatted as code in the future (a line with ``` before and after the log content)
It looks like you are using S2S authentication to deploy the app.
When deploying using S2S authentication - it will deploy using Extension Management thinking it is a per tenant extension.
You cannot do this with AppSource apps.
If you instead use impersonation (your authcontext should contain a refreshtoken instead of clientid and cliensecret) then it will indeed deploy using DevEndpoint (like VS Code)

**Comment by Marhoon** [comment]
Hi Sir @freddydk 

Yes i am using S2S, which my token using {"TenantID":"<TenantID>","ClientID":"<theClientID>","ClientSecret":"<theClientSecret>"}

So S2S will be only for PTE?

And what do you mean using authcontext should contain a refreshtoken , appreciate your advise.
