### ISSUE TITLE
Manage different NextVersion runners in Org settings

### ISSUE THREAD

**Issue by janlehmkuhl** [microsoft/AL-Go#869]
Due to the large number of repositories, we work with the **AL-Go Org settings**. 

We have currently set up in the Org settings that the **"gitHubRunner"** is a special runner. However, we want all **NextMinor, NextMajor and Current pipelines** to be executed by a **different GitHubRunner**. 

**Question**: Can this also be mapped via the org settings or do we really have to revise every NextVersion YAML in every repository?

**Comment by freddydk** [comment]
You should be able to use Conditional Settings - https://aka.ms/algosettings#conditional-settings - and create a condition on "workflowName": [ "Test Current", "Test Next Minor", "Test Next Major" ]

Try it out and let us know whether it works for you.

**Comment by janlehmkuhl** [comment]
This has solved a major maintenance problem for us. Thanks for the help. It worked!

**Comment by janlehmkuhl** [comment]
Unfortunately, I have to reopen this case. The setting has worked for the Test Current, Test Next Minor, Test Next Major. Unfortunately, it overwrites the gitHubRunner for all other pipelines and the conditional settings are working on all pipelines now, not only the Next [..] workflows.

![image](https://github.com/microsoft/AL-Go/assets/94679485/81d40c35-2b7e-43dd-af15-0460943bf690)

**Comment by freddydk** [comment]
My bad - it is "workflows", not "workflowName" - sorry about this.

**Comment by freddydk** [comment]
Documentation is correct though - it states "workflows" - but me reply above was wrong (changed it now)

**Comment by janlehmkuhl** [comment]
Now it works, thank you! 👍
