### ISSUE TITLE
Improve Error Handling when CLI is missing

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#870]
A colleague recently encountered the following issue. 

```
Error: Exception when calling Start with 0 argument(s): "The system cannot find the file specified"
Stack trace: at CmdDo, C:\Users\<username>\AppData\Local\Temp\tmpDFF3.tmp.psm1: Line 262
at invoke-gh<Process>, C:\Users\<username>\AppData\Local\Temp\tmpDFF3.tmp.psm1: Line 322
at CreateDevEnv, C:\Users\<username>\AppData\Local\Temp\tmpE013.tmp.ps1: Line 1558
at <ScriptBlock>, C:\<app>\.AL-Go\localDevEnv.ps1: Line 128
for <ScriptBlock>, <No file>: Line 1
```

The issue was that github cli wasn't installed. Is that a recent requirement? He never had a problem before. This is present in the latest preview. If github cli is a new requirement maybe it would be good da add a better error message, to point the user the solution. 

for your convenience the lines that cause the issue. 
https://github.com/microsoft/AL-Go/blob/7b6ca6ca4c1e3b621f2234b17de17ebdc32da304/Actions/AL-Go-Helper.ps1#L1558

https://github.com/microsoft/navcontainerhelper/blob/ef8b276b6524185c8a1ccbcaf81bcf69bd9be827/Common/Invoke-gh.ps1#L30

To be honest im not sure why the try catch isn't catching the error. Maybe because its started in a new process?

**Comment by freddydk** [comment]
Are you running PS5 or PS7?

**Comment by jonaswre** [comment]
> Are you running PS5 or PS7?

It's was on my colleages computer. So will ask him tomorrow. But im 99% sure it was von ps5

**Comment by pri-kise** [comment]
It seems that I was having a similiar in the BaseApp Contribution Pilot.

I'm using PS5.

I installed Github CLI and now get the following error:
```
.....
Checking System Requirements

LicenseFileUrl
--------------
When developing PTEs, you can optionally specify a developer licensefile with permissions to object IDs of your dependant apps

Local path or a secure download URL to license file  (default none) 
none selected

Error: To get started with GitHub CLI, please run:  gh auth login
Alternatively, populate the GH_TOKEN environment variable with a GitHub API authentication token.

ExitCode: 4
Commandline: gh repo view --json owner,name 
Stacktrace: bei CmdDo, C:\Users\kise\AppData\Local\Temp\tmp869F.tmp.psm1: Zeile 290
bei invoke-gh<Process>, C:\Users\kise\AppData\Local\Temp\tmp869F.tmp.psm1: Zeile 322
bei CreateDevEnv, C:\Users\kise\AppData\Local\Temp\tmp87E8.tmp.ps1: Zeile 1558
bei <ScriptBlock>, C:\Users\kise\source\AL\Microsoft\BusinessCentralApps\App\.AL-Go\localDevEnv.ps1: Zeile 128
bei <ScriptBlock>, <Keine Datei>: Zeile 9
```

**Comment by jonaswre** [comment]
The Error was in ps5
