### ISSUE TITLE
Failed publish attempts prevent next publish attempt

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#872]
Is there a procedure to get around this problem:

I run Publish to Environment, which fails due to an authentication error.
I fix the authentication error (refresh the impersonation token) and run Publish to Environment again.
This now fails with "Unprocessable Entity A duplicate package ID is detected."

What is happening is the failed publish is leaving a package on the server, even though it is not published and does not appear in the Extension Management list.

Now I have to increase the version number or force another build to get a higher version number. And even this sometimes fails with the same Unprocessable Entity error--for example, if I run CI/CD to get another build artifact and then try to deploy using "latest."

We are not using releases, because no Production environments, per your recommendation.

How should we be handling this? Is there some way around this "phantom" package problem?

**Comment by Marhoon** [comment]
In Extension Management can you see the App? did you try to unpublish it?

**Comment by buzzwick** [comment]
Nope. That's the thing. It never shows in Extension Management. Even when GitHub is saying a duplicate package exists, you cannot see any such extension in BC.

**Comment by freddydk** [comment]
Very strange that you are able to "publish something" with an expired refreshtoken...
I mean, with an expired refreshtoken you should never get inside.

Would it be possible for me to see the full logs of two Publish To Environments (the one with the expired token) and the one failing afterwards?

**Comment by gntpet** [comment]
I have reported the same issue here: https://github.com/microsoft/AL-Go/issues/557

It's a problem with 'dev endpoint' deployments. I 'solved' by swtching to s2s authentication (see Freddys' [blog ](https://freddysblog.com/2022/05/06/deployment-strategies-and-al-go-for-github/)), then it deploys app in PTE scope, and skips apps with the same version. It would be nice, if AL-GO could check if that version is already installed or not for 'dev scope' as well.

The downside 'pte scope' approach, you get tones of old app versions in "Installed Extensions" view. This is a view from a few days. You can imagine, how much old version accumulates there for an active project.

![image](https://github.com/microsoft/AL-Go/assets/16342128/3fffa570-56b7-49b9-bff5-b5ca2a2175e4)

**Comment by freddydk** [comment]
@gntpet got it, but @buzzwick states that this happens when the authentication has expired - meaning that the first deploy should not succeed. That's what puzzles me on this one.

**Comment by buzzwick** [comment]
I can clarify further—if a deployment to an environment fails (say for example an expired token), the app is “uninstalled “ from the environment. That is, it is no longer available in the UI, and does not show in the Extension Management list.

And yet, a subsequent Publish (after renewing the token) fails with “duplicate package id found.”

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by freddydk** [comment]
@buzzwick - based on your description, I tried to create a repro which does exactly this.
I cannot repro this problem. When AL-Go fails to get an access token from the Refreshtoken. it will never actually contact the server - meaning that it cannot uninstall nor publish anything.
![image](https://github.com/microsoft/AL-Go/assets/10775043/2f76c3a7-3343-4f5e-a4a9-b40ff4543c0b)

I do however trust that you are seeing something - so something else must be happening here.

Maybe you have multiple environments and some fail and some passes on the first attempt - and then on the second attempt, the ones that passed on the first failed?

**Comment by buzzwick** [comment]
We do have multiple environments, but I see this problem even when deploying to a single environment. 

I will try to do some testing against a single controlled environment and see if I can reproduce it at will.  I certainly have no trouble reproducing it when I do not want to!

**Comment by freddydk** [comment]
If you have some outputs from the logs (one where it had expired and one after updating) - I would like to see them.

**Comment by buzzwick** [comment]
Working on it. I have to wait 90 minutes for this new auth token to expire, so that I get the same error.

**Comment by buzzwick** [comment]
No luck. I deliberately let our authcontext expire, Deploy failed, but apps are still in place. 
If I run into the problem again, I should be able to capture a log from the most recent deploy and also from the last successful deploy and offer them for comparison.

**Comment by buzzwick** [comment]
This might be a result of BC updates being pushed out by Microsoft. So far as I know, AL-Go can only publish extensions as Dev (although the post above indicates that using S2S authentication would enable PTE deployment). Dev extensions are "uninstalled" by MS BC updates.  But they are not actually removed--"cleaned"-- from the environment. So this could be why successive attempts to deploy, without incrementing either a build or a version number, fail. Continuing to test.

**Comment by freddydk** [comment]
That is a good observation - I will ask the moderndev team what happens in this case.

**Comment by buzzwick** [comment]
So here is a possible example of successful vs. failed deployments. Our client updated BC on three of their sandbox environments. This uninstalls our main extension, because we use the Dev endpoint to deploy. I ran Publish to environment on all three environments simultaneously. It succeeded on two; failed on one. I have included a success log archive and a fail log archive. It would seem that all three should succeed if two succeed; the failed environment should, if anything, have been _behind_ the other two environments in terms of version. 
[logs_failed.zip](https://github.com/microsoft/AL-Go/files/14015144/logs_failed.zip)
[logs_succeeded.zip](https://github.com/microsoft/AL-Go/files/14015145/logs_succeeded.zip)

**Comment by buzzwick** [comment]
Now we can reproduce the scenarios I described earlier:  An attempt to deploy a _later_ version (minor version increment) fails due to authentication failure. A successive attempt to deploy the same version fails "because the same package ID already exists in a published extension."  Which suggests that somehow the package is being "left" at the environment but not installed (it is not visible in Extension Management), or some version log is being updated without installing the extension. Here are those two logs: the first authentication failure log and the second "unprocessable entity" log.
[duplicate-package-id.zip](https://github.com/microsoft/AL-Go/files/14016135/duplicate-package-id.zip)
[authentication-failure.zip](https://github.com/microsoft/AL-Go/files/14016136/authentication-failure.zip)

**Comment by freddydk** [comment]
Thanks - this gives me a hint - and definitely closer to a solution.
On the UAT you are using a refreshtoken as auth - is this a PROD environment or a Sandbox environment?

On the other 8 environments - are they sandbox environments or production environments?
Are you using RefreshToken as authentication or ClientId/ClientSecret?

Thanks

**Comment by buzzwick** [comment]
All of these environments are Sandbox--we are currently not deploying to any Production environments. 
All use RefreshToken (New-BcAuthContext); it is only the UAT, JMSandbox and JMDEV that have expirations on that authentication set to 90 minutes--that is why they fail so often, because I forget to renew every time I run an Action.
Last night I removed the "continuousDeployment = false" from the Settings file for JMUAT. That way it went ahead and deployed during a CI/CD run, instead of being skipped but spiking the ability to deploy manually.

**Comment by buzzwick** [comment]
Some more examples of this sequence; I am pretty sure that a failed publish "pulls" (as in it disappears from the Extension Management list) the installed version of the app, but leaves it hanging around such that a successive attempt to publish the same version fails with the "Duplicate Package ID" message. Here are two logs: "Unprocessable entity" is a failure to publish (but not because of authentication), and "Duplicate Package ID" represents the subsequent attempt to publish the same version.

[Duplicate package ID.zip](https://github.com/microsoft/AL-Go/files/14130916/Duplicate.package.ID.zip)
[Unprocessable entity.zip](https://github.com/microsoft/AL-Go/files/14130917/Unprocessable.entity.zip)

**Comment by freddydk** [comment]
I do have an idea of what is wrong here and will provide a workaround/fix

**Comment by buzzwick** [comment]
Thank you. That will be a great relief, because our client is breathing down our necks to have "stable" environments and deployments.
In the meantime--so far I have not discovered a way to initiate a Build to generate artifacts, without initiating some Deploy sequence. Is there one?

**Comment by buzzwick** [comment]
More data: Log below records a session where an "unprocessable entity" error definitely uninstalled the DEV app from the target environment. 
[unprocessable entity (2).zip](https://github.com/microsoft/AL-Go/files/14185793/unprocessable.entity.2.zip)

**Comment by freddydk** [comment]
I have will have a fix for this, which you can try out, but it requires you to use a development branch of AL-Go for GitHub.
If you run Update AL-Go System Files with `freddydk/AL-Go@unprocessible` then you it shouldn't happen anymore.

If you can confirm this - then I can create a PR on main with this, thanks

**Comment by buzzwick** [comment]
Updated the system files and ran a CI/CD (builds from the AL-Go update failed; I had to remove our codesigning flags because that's not working yet). But that failure did not uninstall the app from the environments. The CI/CD was successful on two of the three environments for one client. Failed on their "Sandbox" environment, with "unprocessable entity". 
Publish to that environment failed with "zero arguments" error.
Second Publish to that environment succeeded; same artifact.
Logs are below, in order. 
Seems like a partial success, at least.

[1_UnprocessableEntity.zip](https://github.com/microsoft/AL-Go/files/14203395/1_UnprocessableEntity.zip)
[2_ZeroArguments.zip](https://github.com/microsoft/AL-Go/files/14203396/2_ZeroArguments.zip)
[3_Success.zip](https://github.com/microsoft/AL-Go/files/14203397/3_Success.zip)

**Comment by freddydk** [comment]
I have added some additional logs when/if this happens again, that should give me some more info.
Please post new logs when possible (and add info about the environment name that fails:-))
Thanks

**Comment by buzzwick** [comment]
I will try to be as diligent as possible about tracking what happens, and will post logs. We have several other clients with sandbox environments that we are deploying to, but no one else has (so far) called to complain that our app has disappeared from their environment. Just this one client and their three sandboxes--and not always the same one. The other client deployments are all failing for known authentication reasons--so far no "unprocessible entity" failures from them.

**Comment by freddydk** [comment]
I will close this bug for now.
If this re-appears, please create a new bug with full log for me to investigate (with additional info)
For the unpublish, please see #409 and https://github.com/microsoft/navcontainerhelper/issues/2808
