### ISSUE TITLE
Deployment to QA

### ISSUE THREAD

**Issue by Marhoon** [microsoft/AL-Go#874]
We have two teams one working on 1.0.x.x and other team working on 2.0.x.x we have issue that both versions deploy to the same QA Environment.

And this is creating break code issue.

How can we solve that?

or can we make manual deployment to QA, and stop the auto on?

**Comment by freddydk** [comment]
Using https://aka.ms/algosettings#deployto you can control which branches are deploying to which environments and which environments have continuous deployment.
