### ISSUE TITLE
Deployment fails when opening "Extension Installation Status" page

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#875]
Extension deployment fails/stops when you open "Extension Installation Status" page

It gives this error:
`The job for id '00000000-0000-0000-0000-000000000000' was not found.`

Steps to reproduce:
1. Run 'Publish-to-environment' via AL-GO
2. Open "Extension Installation Status" page. First, you will see status unknown. If you try to refresh, job will fail with the error above. it will break deployment job as well.

Best Regards, 
Gintautas

**Comment by Chira-DAIPOST** [comment]
I encountered this error yesterday while attempting to manually upload an extension. Even though the deployment itself succeeded, It seems like the status just didn't update correctly. It says 'NOT FOUND', Summary: Operation was not found, Error Details: Deployment job not found' with Job ID: 00000000-0000-0000-0000-000000000000.
