### ISSUE TITLE
S2S Authentication - Clarification

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#885]
Tyro question:

We have been struggling to get S2S authentication to work for GitHub deployment in a client environment to which we do not have admin access. We had them register "AL-Go for GitHub" as an application, and send us the ClientID and Client Secret values. But still no luck.

I realized I was not 100% sure whether it was our BC Extension that had to be registered as an application, or GitHub. Or whether it makes a difference, if we have a valid clientID and client secret. Is it the extension being published, or GitHub, that needs to be recognized as an application? When the Workshop says 

"Follow [this](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/automation-apis-using-s2s-authentication) description to setup a Microsoft Entra application and register it inside the Business Central environment you want to deploy to," it does not specify which application exactly is to be registered to Business Central.

**Comment by buzzwick** [comment]
You are right--it does describe in detail the steps to set up service-to-service authentication. But it does so in quintessential Microsoft style, which is to use abstract references whose antecedents are never explained. To use my favorite movie example: if you ask me "Where shall we meet?" and I say "That place where we went that time," you will know in precise detail where to meet--**IF** you already know what "that place" and "that time" refer to. I went to college, and I can follow directions, but when I read

`To set up service-to-service authentication, you'll have to do two things:
Register _an application_ in your Microsoft Entra tenant for authenticating API calls against Business Central.`, 

There is no way of knowing, nor is it explained anywhere exactly what "an application" refers to. GitHub? Our extension? QuickBooks? Also, "for authenticating API calls against Business Central" sounds very different from "for deploying an AL extension to BC, from within AL-Go for GitHub." This can (and did) lead inexperienced users to conclude that these might not in fact be the answers they are searching for.

Incidental question: Is it the case that every AL extension is in fact "making API calls against Business Central," as some implicit part of the extension architecture? 

I am leaning toward the conclusion we reach in [#887](https://github.com/microsoft/AL-Go/issues/887)--that "which application" is meaningless; we just need "an" application, which means "call it anything you want--'AL-Go for GitHub' or 'OurBCExtension'--you just need a valid ClientID and Client Secret (and the appropriate Entra app permissions in BC)." Correct me if I am wrong!

**Comment by freddydk** [comment]
Sorry @buzzwick, but I don't think you are being fair. If you read the full text, then it does continue and tell you what this is.

![image](https://github.com/microsoft/AL-Go/assets/10775043/3892c401-de98-4629-a463-1fe0e0ac0a1d)

Security is complicated and I do agree that the term "application" in the context of Microsoft Entra ID is strange and did cause some confusion for me as well, but in the end, you create an app registration and allow that app registration access to X ressources. That app registration is allowed to forward the access token obtained with these permissions to a set of URLs. Now the owner of the ClientID and the ClientSecret or certificate can now authenticate and obtain the permissions assigned to that app registration.
The app registration is not tied to a specific app, customer, partner, vendor, person or purpose - it is up to the creator of the app registration to determine this. I f.ex. have one app registration I use for various test purposes (many different apps), but for prod purposes, I have more purposeful apps.
Secrets and certificates can be revoked (if compromised) and permissions can be changed - this indirect way of authentication does provide more security than a simple username/password, which everybody understands.

**Comment by buzzwick** [comment]
I wouldn't say I was being unfair so much as I am being a) inexperienced and b) baffled, frustrated, and misled by Microsoft's linguistic affectations. When MS says "register your application," the experienced user understands already what you have just described in these last two paragraphs of explanation. The inexperienced user sees that directive and thinks, _"My_ application?" Is GitHub "my" application? Is my BC extension the "application" they are referring to? (Answer: no, but how am I to know that?)

What I can say is that the two paragraphs you just added provide more clarity and specificity about app registration than I have found in any and all of the Microsoft docs on the subject, or in most of the blog posts by third parties. But even there, GitHub is never mentioned by name. We are not so much "registering" either GitHub or our BC extension--we are, as you say, actually _creating_ a set of credentials that GitHub (or some API app, which is what the instructions explicitly reference) can _use_ to (among other things) __install_ an extension_ in Business central. Once this is known as you have explained, it all makes perfect sense. So thanks very much for the additional clarification; that provides a boatload of additional clarity. Now I almost know what I am doing!
