### ISSUE TITLE
Trying to debug S2S Authentication failure

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#887]
Followed the instructions in the Workshop on Continuous Deployment. Created (technically had the tenant owner create) an app registration, with these API permissions
![appreg-permissions](https://github.com/microsoft/AL-Go/assets/40246434/9abf154e-945f-4600-9726-237501f290ba)

and these permissions inside Business Central:
![BC API permissions](https://github.com/microsoft/AL-Go/assets/40246434/d1e45de6-bc90-4c13-a626-c1daf8c97905)

Then used this
`New-BcAuthContext -clientID $clientID -clientSecret $clientSecret -tenantID $tenantID | New-ALGoAuthContext | Set-Clipboard`

to generate a new authcontext. Which works:

`Attempting authentication to https://api.businesscentral.dynamics.com/.default using clientCredentials...
Authenticated as app 229eca59-a9c8-41ae-8013-f12adfe7fc8e`

But Publish to Environment using that Authcontext fails:

Error: Deploying to Sandbox failed.  The remote server returned an error: (401) Unauthorized. Unauthorized {"error":{"code":"Authentication_InvalidCredentials","message":"The server has rejected the client credentials.  CorrelationId:  f7904a28-9b7d-4ab9-ad1a-41a9b714037d."}} (ms-correlation-x = a6821e87-a2f2-2d08-5b9f-523b17f83dbd)

Full log here:

[S2S-failure.zip](https://github.com/microsoft/AL-Go/files/14030100/S2S-failure.zip)

How do we find out where this is failing?

**Comment by freddydk** [comment]
These lines:
```
Attempting authentication to https://api.businesscentral.dynamics.com/.default using clientCredentials...
Authenticated as app ***
```
tells me that ClientID and ClientSecret is OK - authentication works.
This:
```
Publishing apps using automation API
```
Tells me that it is using automation API (not DevEndpoint)
and this:
```
https://api.businesscentral.dynamics.com/v2.0/Sandbox/api/microsoft/automation/v2.0/companies
ERROR The remote server returned an error: (401) Unauthorized.
```
indicates that while you are authenticated, you are not authorized - i.e. the ClientID mapping in the Business Central App Registrations page is either not existing, doesn't have the right permissions or is disabled.

**Comment by buzzwick** [comment]
Thank you, this at least validates what we are doing, up to a certain point in the process. And helping me appreciate the meanings of "authenticated" vs. "authorized." By way of unpacking your final comment:  I take "the ClientID mapping in the Business Central App Registrations page" to refer to this:
![image](https://github.com/microsoft/AL-Go/assets/40246434/c45ee32e-6c26-4e49-bbc7-e03f24b643b4)

From which we can surmise that it exists, and is Enabled. Which leaves "doesn't have the right permissions." I think the only documentation I have found on "the right permissions" has been in third-party blog entries. If you know of an authoritative source, by all means pass it along. In the meantime we will continue to research and test on our own, under the assumption that we have done the app registration part correctly.

Question: It seems that the NAME of the app registration may be immaterial--that is, as long as GitHub has access to a token generated using SOME valid ClientID and Client Secret, then the deployment can _authenticate_. The registered Client ID needs appropriate permissions in BC in order to allow publishing an extension, but once again it appears that the NAME of the registered app makes no difference. Is that correct?

**Comment by freddydk** [comment]
I think the name of the App Registration (and in the Application card above) is just for human readability.
Did you click "Grant Content" above to grant the registered app Consent?

**Comment by buzzwick** [comment]
I am beginning to get the picture now regarding what "app registration" actually is. I think the name used is in fact immaterial; the point is to have a valid client ID and client secret. 

Yes, the "Grant Consent" step is the one I am pursuing now. We requested this (we don't have the necessary admin privileges for this environment). I have to go through a third party to make  sure the "Grant Consent" action has indeed been executed. Will advise., although at this point this is clearly no longer an AL-Go issue.

**Comment by buzzwick** [comment]
Maybe it **is** still an AL-Go setup issue: We have moved on to a new error:

`Deploying to UAT failed.  The remote server returned an error: (400) Bad Request. Bad Request {"error":{"code":"Application_DialogException","message":"You do not have sufficient permissions to manage extensions.`

These are the permissions for the app registration in the UAT environment:

![image](https://github.com/microsoft/AL-Go/assets/40246434/a0e4ea98-5863-4f0f-8ea9-dfe9f82c6ea8)

If you can confirm that these are sufficient for GitHub deployment, then we can move on to some other possible deficiency. If these are documented somewhere in the Workshop docs, forgive me for not finding them. So far, blogs have been the only source mentioning these permissions specifically.  Thanks.

**Comment by buzzwick** [comment]
It looks like those permissions are adequate. Our client performed the Grant Consent operation, and our extension is now deploying through GitHub as PTE. Hard slog to get here, but now that we know the path, it looks easy. Thank you for your help.
