### ISSUE TITLE
Issue with RDLC with apps compiled in pilelines

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/AL-Go#888]
I am not sure if this is an issue with Al-GO directly, but I am a bit desperate with this issue already.

I have one customer with custom document report layouts. One update introduced an error saying that one field is not present in the dataset. But I do only get the error on the customers sandbox, not locally in my docker container.

After further investigation I can now say that this definitely related to the compiling in AL-Go.
If I deploy the app generated from AL-GO manually, as PTE I still get the error. So its not related to the deployment.

When I compile the exact same app locally with cs code and upload the app as PTE, I do not get the error.

Any idea what could be causing this or how to track down this issue?
It starts to become quite annoying.

This issue persists since over one month now trough several versions.

**Comment by freddydk** [comment]
If you compile the app in both the pipeline and with VS Code and then use BcContainerHelper Extract-AppFileToFolder with both apps - what differences do you see?

**Comment by StefanMaron** [comment]
Thank you very much! 

The issue was a dependency. I did not create a new release for the dependency, therefore AL-Go pulled on older version of the dependency.
