### ISSUE TITLE
ServerInstance 'MicrosoftDynamicsNavServer$BC' failed to reach  status 'Running' on this server due to the following error: 'Cannot start the service.'.

### ISSUE THREAD

**Issue by FrankAuwers** [microsoft/AL-Go#891]
Yesterday, everything works fine.
Today I just run the Create Release action, with increment the version number.
And now the CI/CD workflow fails every time with the message that the service cannot start.

See log file.
[logs_610.zip](https://github.com/microsoft/AL-Go/files/14049004/logs_610.zip)

**Comment by freddydk** [comment]
Are you setting up an Azure KeyVault for the Container?
This seems to be the step that is failing - maybe you have a relative APP ID URI?
Error seams to be the same as https://github.com/microsoft/navcontainerhelper/issues/3300 - but I never heard whether they found out what was wrong?

**Comment by FrankAuwers** [comment]
Yes, there is also a keyvault in use for this app.

**Comment by FrankAuwers** [comment]
But, it was working until yesterday. And there is nothing changed as only the version number.

**Comment by freddydk** [comment]
What is the Application ID Uri of your App Registration?
Some time ago, it became mandatory that this was an absolute URI (not a relative).
Maybe some code in BC now assumes that it is always absolute - and for people who have an old App Registration, this then fails.

I am guessing

You could try to set the "artifact" setting in .github/AL-Go-Settings.json to the version, where the build worked yesterday.

**Comment by freddydk** [comment]
https://learn.microsoft.com/en-us/entra/identity-platform/reference-app-manifest#identifieruris-attribute

**Comment by freddydk** [comment]
@FrankAuwers did you resolve the problem? What was wrong?

**Comment by FrankAuwers** [comment]
With BC version 23.3.14876.15617 it work,
 but with BC version 23.3.14876.15704 it fails.

For now I have removed de key vault settings out of the /.AL-Go/Settings.json and then it works also for BC version 23.3.14876.15704.

But this means I can not access our key vault from a docker environment. For now I solved this by making event available and have an other app that can deliver these values.

**Comment by freddydk** [comment]
OK, thanks.

**Comment by freddydk** [comment]
Will close the issue here, since this has been resolved, but keep the nextmajor issue in BcContainerHelper as this still is a problem
