### ISSUE TITLE
Documentation unclear about apps property for deployment

### ISSUE THREAD

**Issue by cegekaJG** [microsoft/AL-Go#893]
The documentation on custom deployment scripts describes the parameter `$parameters.apps` as follows:

(https://github.com/microsoft/AL-Go/blob/ddd94d3927e14dff2b45f9907f245513d202d8f4/Scenarios/settings.md?plain=1#L250)

The example lists a path to a `.zip` file, but in my case, it's a path the unzipped folder of the `.zip`. Is this outdated? Or can it be both, and my custom script needs to be able to handle either? Is it possible for the parameter to be a list of strings?
The equivalent to the delivery script is `$parameters.appsFolder`, which implies that the path leads to a folder, and there's only one of them. If `$parameters.apps` is the same way, wouldn't it be clearer to rename it to `appsFolder` instead?

**Comment by freddydk** [comment]
Updated the documentation. Currently I am not going to add another parameter in the custom deployment you can use Copy-AppFilesToFolder if you need to get all apps in a folder - else you can pass apps directly to Publish-PerTenantExtensionApps or Publish-BcContainerApp.
