### ISSUE TITLE
Signing failed with error 800B010A.

### ISSUE THREAD

**Issue by FrankAuwers** [microsoft/AL-Go#894]
Just an new PTE repository created and add a new project with sample code with the action "Create a new app".

When the CI.CD workflow start and the signing part is triggered, it fails.
[logs_5.zip](https://github.com/microsoft/AL-Go/files/14051703/logs_5.zip)

**Comment by freddydk** [comment]
Please include the logs - my computer tells me the file download is dangerous.

**Comment by FrankAuwers** [comment]
These are the logs, just downloaded from github.
[logs_5.zip](https://github.com/microsoft/AL-Go/files/14052695/logs_5.zip)

**Comment by freddydk** [comment]
OK, thanks - please note that the new certificate will not be delivered as .pfx and you need to use a different process to sign your app.
Dmitry Katson describes this in his blog: https://katson.com/code-signing-in-2024/
Please note though that the secret:
![image](https://github.com/microsoft/AL-Go/assets/10775043/fefe9285-73d0-4cbb-9a44-7ced8b582b20)
Needs to be compressed JSON (no linefeeds or spaces)
