### ISSUE TITLE
Where to put  'githubRunner' 

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#895]
[Scenarios](https://github.com/microsoft/AL-Go/tree/main/Scenarios)
/SelfHostedGitHubRunner.md says

"Now navigate to your project settings file (.AL-Go/settings.json) and set gitHubRunner to self-hosted."

But a pull request yields this warning:

Warning: Property 'githubRunner' should not exist in .AL-Go\settings.json

Is there some other place where gitHubRunner belongs?

**Comment by freddydk** [comment]
gitHubRunner is a repo setting and should exist in .github/AL-Go-Settings.json instead.
Will fix the scenarios sample.
