### ISSUE TITLE
PublishToEnvironment not recognizing environment from settings in private repo

### ISSUE THREAD

**Issue by curateideas** [microsoft/AL-Go#90]
In a private repo the environments configured in the .AL-Go\settings.json are not recognized in the Publish-To-Environment-action in a **private** repo.

Settings are configured this way:

![image](https://user-images.githubusercontent.com/58227881/165143604-c85ad3ec-9ea5-4048-bd36-97688a511a0e.png)

ReadSettings finds the environment but does not pass it to the deploy step.

![image](https://user-images.githubusercontent.com/58227881/165144300-8d8e7b37-3113-4189-8c66-9c389a266bbc.png)

In the case of a public repo, it recognizes both, the repo's environment and the environment from the settings:

![image](https://user-images.githubusercontent.com/58227881/165145602-73785fc5-7383-4ae5-be32-054d7eed14b2.png)

**Comment by freddydk** [comment]
Found the bug, will deploy a fix for this tomorrow.

Reason is that your GitHub account is a free account - it works if you have a Teams or Enterprise account. But then again - the environments setting was introduced in order to work when using a free account - it of course must work.

**Comment by freddydk** [comment]
Shipped in v1.2 - if you update your AL-Go system files, you should be good to go.

**Comment by curateideas** [comment]
Works now, thank you for your immediate response.

Have a follow-up issue with the secrets. After investiation will create another issue for that or a PR.

**Comment by freddydk** [comment]
If you have an environment called QA - you need to create a secret in that environment called AUTHCONTEXT.
If you don't use the environments feature in GitHub, the secrets needs to be called QA_AUTHCONTEXT to match the environment.

**Comment by curateideas** [comment]
Second case is the issue: the corresponding script searches for "AUTHCONTEXT" in the repository secrets instead of "QA_AUTHCONTEXT". This way there is only one connection to an environment that can be configured per Repo.

In PublishToEnvironment.yaml:

![image](https://user-images.githubusercontent.com/58227881/165316043-61d8788c-f8b7-4457-babf-22a003c4a0a6.png)

I'm testing a fix in a fork at this moment.

**Comment by freddydk** [comment]
Right on top - it is looking for QA-AUTHCONTEXT (line 88) - needs to be a dash, not an underscore.

**Comment by freddydk** [comment]
bummer - it works in an Azure KeyVault - will make a fix for supporting dash or underscore.
Thanks for reporting.

**Comment by freddydk** [comment]
Did not test the PR yet - but this should add support for looking for both QA-AUTHCONTEXT and QA_AUTHCONTEXT
Probably the same solution as you have been looking at in your fork.

**Comment by curateideas** [comment]
Again: Thanks, Freddy! Will check this out.

**Comment by curateideas** [comment]
Now working as expected!

I made nearly the same changes but struggled with the End2End Tests, before submitting the PR. There's a learning curve for me...

**Comment by freddydk** [comment]
yeah - I will document what you need in order to run the End 2 end tests - they are fairly heavy - they test out a ton of various things including upgrades from all prior versions to the new...

**Comment by curateideas** [comment]
Is the fix deployed to AL-Go-PTE already? I see no PR in my project after Update System Files.

**Comment by freddydk** [comment]
Not yet - will do so today or tomorrow

**Comment by freddydk** [comment]
BTW - there is another way this can be fixed.
You can create a setting called QA-AUTHCONTEXTSECRETNAME with the value QA_AUTHCONTEXT

There is a generic way in AL-Go to rename secrets by adding a setting called <secret>SECRETNAME

The reason for this is that multiple repositories can share a KeyVault and might have different secrets (like this)
I will still checkin the fix to utilize the _ as that is clearly a bug.
