### ISSUE TITLE
CI/CD not triggering for custom branches

### ISSUE THREAD

**Issue by cegekaJG** [microsoft/AL-Go#902]
One of our repos has a branch, `testmaster`, which is used to deploy multiple features to approve to a test environment. I'd like to trigger the CI/CD workflow and deploy the same way it's set up for the default branch. From the documentation, it seemed like `CICDPushBranches` and `CICDPullRequestBranches` would do the trick, but nothing changed. I understand that generally, GitHub won't trigger a workflow if it's not included in the branch filter in the `on:` property, but is there some way to add the branch to the whitelisted branches? Or is modifying the workflow file the only way to trigger the workflow?
If that's the case, what's the purpose of `CICDPushBranches` and `CICDPullRequestBranches`?

**Comment by freddydk** [comment]
You need to run Update AL-Go System files after modifying CICDPushBranches and/or CICDPullRequestBranches - did you do this?

**Comment by cegekaJG** [comment]
Running the `Update AL-Go System files` workflow only added a `templateSHA` to `AL-Go-Settings.json`.
I actually noticed that the workflow also failed to update from 4.0 to 4.1 for multiple repos - I had to replace the files manually.
I am using a custom template forked from microsoft/AL-GoPTE (CBS-BC-AT/AL-Go), but I haven't modified the workflows.

**Comment by freddydk** [comment]
Where did you add CICDPushBranches? (which settings file)

You should never replace files manually - you should run update AL-Go System files with standard.
By replacing files manually - you might cause things to stop working altogether.
