### ISSUE TITLE
[GitHub Warning]: Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by louagej** [microsoft/AL-Go#905]
When I start a new repository from AL-Go-PTE, the anotations shows this warning

![image](https://github.com/microsoft/AL-Go/assets/7229592/bbed060d-f400-4bea-b4f5-0ad1ea321a10)

[Initialization](https://github.com/louagej/BCTestMe/actions/runs/7714564434/job/21027077152)
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20: actions/checkout@v3.
For more information see: [GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.)

**Comment by freddydk** [comment]
Preview has been updated with node 20 versions of all actions - will be released to prod soon.
