### ISSUE TITLE
Environment not appearing in CI/CD workflow

### ISSUE THREAD

**Issue by louagej** [microsoft/AL-Go#907]
Hi,

I have 2 environments setup /.AL-Go/settings.json
```json
  "DeployToTEST": {
    "EnvironmentName": "TEST",
    "continuousDeployment": false
  },
  "DeployToDEV": {
    "EnvironmentName": "DEV",
    "continuousDeployment": true
  }
```

When the CICD workfow runs, only DEV appears in the Matrix: Deploy:

![image](https://github.com/microsoft/AL-Go/assets/7229592/dee5efc6-9206-4e64-bea3-56c16994975d)

How can I add the deployment to my TEST environment?

**Comment by freddydk** [comment]
Modify the continuousDeployment (CD) setting for the test environment to be true.

Note also that DeployTo is a repository setting and the environments should be in .github/AL-Go-Settings.json and not in .AL-Go/settings.json - this change would be necessary if your repository had multiple projects.

**Comment by louagej** [comment]
Hi Freddy,

thank you for pointing me the setting belongs to .github/AL-Go-Settings.json.
I moved the setting and then manually deployed the app with the workflow `Publish To Environment` to the TEST environment 🚀
