### ISSUE TITLE
Creating test environment fails (both for PTE and AppSource)

### ISSUE THREAD

**Issue by MichaelDieringer** [microsoft/AL-Go#908]
**### Error: Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'gh' with working directory 'C:\BusinessCentralALGoForGIT\MichaelTestApp'. Den angivne fil blev ikke fundet."
Stacktrace: at CmdDo, C:\Users\mid\AppData\Local\Temp\tmpaszjfb.tmp.psm1: line 262
at invoke-gh<Process>, C:\Users\mid\AppData\Local\Temp\tmpaszjfb.tmp.psm1: line 322
at CreateDevEnv, C:\Users\mid\AppData\Local\Temp\tmphhn2aj.tmp.ps1: line 1559
at <ScriptBlock>, C:\BusinessCentralALGoForGIT\MichaelTestApp\Testing\.AL-Go\localDevEnv.ps1: line 128
at <ScriptBlock>, <No file>: line 1**
PS C:\BusinessCentralALGoForGIT\MichaelTestApp>

**Comment by freddydk** [comment]
This is likely because you haven't installed GitHub CLI.
Next version will give a better error message on this.

**Comment by MichaelDieringer** [comment]
many thanks - work :-)
