### ISSUE TITLE
AL-Go AppSource: CreateLocalDevEnv.ps1 fails

### ISSUE THREAD

**Issue by FrankAuwers** [microsoft/AL-Go#912]
![image](https://github.com/microsoft/AL-Go/assets/37549404/c524e546-b02f-478d-87ad-024177eff71f)

This is the first time we see this error. Until now it has always worked.

**Comment by freddydk** [comment]
Do you have GitHub CLI installed on this machine?

**Comment by FrankAuwers** [comment]
That was the trick,

thanks Freddy.
