### ISSUE TITLE
Error deploying app to sandbox enviroment with Microsoft Service Declaration app dependency

### ISSUE THREAD

**Issue by davidaparicioalvarez** [microsoft/AL-Go#913]
I have a problem with the CI/CD action. WhenGithubI starts a sync after committing, the CI/CD action runs to build the app but it cannot be deployed to a sandbox environment.

My project modifies a Microsoft Service Declaration page control (e2ae191d-8829-44c3-a373-3749a2742d4d:Microsoft_Service Declaration_23.0.0.0.app). Initially, the project build failed because it did not find the Microsoft Service Declaration dependency. To resolve this, I added "installApps": ["Dependencies//*.zip"] to .AL-Go/settings.json and downloaded the Microsoft Service Declaration application as a zip file in the "Dependecies" directory.

With this new configuration, the build runs without problems, but deployment to sandboxes fails because they have the Microsoft Service Declaration installed by default.

The log is:

Run microsoft/AL-Go-Actions/Deploy@v4.1
Run $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
Downloading BcContainerHelper latest version from CDN
Import from C:\ProgramData\BcContainerHelper\6.0.4\BcContainerHelper\BcContainerHelper.ps1
BcContainerHelper version 6.0.4
BC.HelperFunctions emits usage statistics telemetry to Microsoft
project '*'
Apps to deploy
D:\a\XXXXXX\XXXXXX\.artifacts\XXXXXX-main-Apps-1.0.55.0
D:\a\XXXXXX\XXXXXX\.artifacts\XXXXXX-main-Dependencies-1.0.55.0
Attempting authentication to https://api.businesscentral.dynamics.com/user_impersonation offline_access using refresh token...
Authenticated using refresh token as user XXXXXX
EnvironmentUrl: https://businesscentral.dynamics.com/XXXXXX
(https://github.com/APAWARE/XXXXXX/actions/runs/7723392076/job/21055388320#step:7:42)/Sandbox
Publishing apps using development endpoint
Publishing Microsoft_Service Declaration_23.2.14098.14562.app to https://api.businesscentral.dynamics.com/v2.0/Sandbox/dev/apps?SchemaUpdateMode=synchronize
Status Code [42](https://github.com/APAWARE/XXXXXX/actions/runs/7723392076/job/21055388320#step:7:44)2 : Unprocessable Entity
The extension could not be deployed because it is already deployed as a global application or a per tenant application. The extension that is already deployed is Service Declaration by Microsoft 23.2.14098.1[45](https://github.com/APAWARE/XXXXXX/actions/runs/7723392076/job/21055388320#step:7:47)62 published as Global application.

Publish-BcContainerApp Telemetry Correlation Id: 3124a9bc-1f96-[47](https://github.com/APAWARE/XXXXXX/actions/runs/7723392076/job/21055388320#step:7:49)36-a3[48](https://github.com/APAWARE/XXXXXX/actions/runs/7723392076/job/21055388320#step:7:50)-5e[55](https://github.com/APAWARE/XXXXXX/actions/runs/7723392076/job/21055388320#step:7:57)fb90a024
Error: Deploying to Sandbox failed.  Status Code 422 : Unprocessable Entity The extension could not be deployed because it is already deployed as a global application or a per tenant application. The extension that is already deployed is Service Declaration by Microsoft 23.2.14098.14[56](https://github.com/APAWARE/XXXXXX/actions/runs/7723392076/job/21055388320#step:7:58)2 published as Global application. 
Error: Process completed with exit code 1.

what am I doing wrong?

Thanks for the answer.

David.

**Comment by freddydk** [comment]
This bug was in BcContainerHelper and is fixed now in the preview branch.
If you switch to AL-Go preview or add a setting called "BcContainerHelperVersion": "preview" to your .github/AL-Go-Settings.json, then you should get this now.

**Comment by davidaparicioalvarez** [comment]
Thanks you so much for the incalculable work!!!

**Comment by davidaparicioalvarez** [comment]
Hi Freddydk, same error with BcContainerHelper preview version

**Comment by freddydk** [comment]
Please post a new log with the latest - there should be more information in the log for me.

**Comment by davidaparicioalvarez** [comment]
Now, it is working. Installed from scratch Windows, docker and Git.

Thanks for you help.
