### ISSUE TITLE
CodeSigning variables

### ISSUE THREAD

**Issue by MichaelDieringer** [microsoft/AL-Go#914]
Following the documents, I need to assign some secrets for signing my code. 

"KeyVaultCertificateUrlSecretName": "KeyVaultCertificateUrl",
"KeyVaultCertificatePasswordSecretName": "KeyVaultCertificatePassword",
"KeyVaultClientIdSecretName": "KeyVaultClientId",

Well, I always used azuresigntool.exe for signing. and, I used the following structure:
azuresigntool sign -kvt $(TennantID) -kvu $(SigningVaultURL)  -kvc $(SigningCertname)  -kvi $(SigningClientid) -kvs $(SigningClientSecret) -tr $(URLTimeStampServer)  -td sha256 $(FileName)

I can figure out 
KeyVaultCertificateUrl = SigningVaultURL
KeyVaultClientId = SigningClientid

but, what about the  KeyVaultCertificatePassword?

We do have several apps, can I create my secrets globaly, or should I use the repository?

**Comment by freddydk** [comment]
Dmitry Katson wrote a blog post about code signing with AL-Go https://katson.com/code-signing-in-2024/

**Comment by freddydk** [comment]
If you are using the legacy signing mode (you have a pfx and a pfx password), then you need to create two secrets
codeSignCertificateUrl
codeSignCertificatePassword

The first containing a direct download URL to your Certificate and the second would be the password.
The KeyVault settings you are looking at has nothing to do with code signing - they are for your container and/or dev environment to have keyvault access.

**Comment by MichaelDieringer** [comment]
Many thanks - all fixed :-)
