### ISSUE TITLE
Creating local docker container with dependencies in the same repository.

### ISSUE THREAD

**Issue by FrankAuwers** [microsoft/AL-Go#915]
Hi,

I thought that if the dependency apps are also in the same repository, that they also be installed. In the CD/CI workflow it does this.

**I have the following situation:**
Sorted App folders
- C:\Data\GitHub\scapta\xpr365\Financials\Financials App
External dependencies
- 03da99d5-3e63-49e4-bb50-713dfe3f16a8:Scapta_XPR365 Library_19.1.6.0.app
- 0019930d-6712-442b-a825-09f9a80feedc:Scapta_XPR365 Trade_19.2.6.0.app
- a810b100-2f08-4d30-b374-f0006405c85c:Scapta_XPR365 Master Data_19.2.8.0.app     
- 534d17d3-ab80-4b48-afd3-9bd642aaeec3:Scapta_XPR365 Projects_19.1.15.0.app       
- c6c713d1-898b-4ef6-9364-d2e05c00e76d:Scapta_XPR365 Babelway_19.2.5.0.app        
- 437dbf0e-84ff-417a-965d-ed2bb9650972:Microsoft_Base Application_23.0.0.0.app    
- 63ca2fa4-4f03-4f2b-a480-172fef340d3f:Microsoft_System Application_23.0.0.0.app 

**Then in the compiling of the app it works and it find also the otherrapps:**
Compiling C:\Data\GitHub\scapta\xpr365\Financials\Financials App
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\230\Service to assemblyProbingPath
Removing dotnet Framework Assemblies
Using Symbols Folder: C:\Data\GitHub\scapta\xpr365\Financials\Financials App\.alPackages
Processing dependency Microsoft_Application_23.0.0.0 ()
Dependency App exists
Processing dependency Microsoft_System_23.0.0.0 ()
Dependency App exists
Processing dependency Scapta_XPR365 Library_19.1.6.0 (03da99d5-3e63-49e4-bb50-713dfe3f16a8)
Dependency App exists
Processing dependency Scapta_XPR365 Trade_19.2.6.0 (0019930d-6712-442b-a825-09f9a80feedc)
Dependency App exists
Processing dependency Scapta_XPR365 Master Data_19.2.8.0 (a810b100-2f08-4d30-b374-f0006405c85c)
Dependency App exists
Processing dependency Scapta_XPR365 Projects_19.1.15.0 (534d17d3-ab80-4b48-afd3-9bd642aaeec3)
Dependency App exists
Processing dependency Scapta_XPR365 Babelway_19.2.5.0 (c6c713d1-898b-4ef6-9364-d2e05c00e76d)
Dependency App exists
Compiling...

**But when the app is being published the following error occurs:**
Publishing Scapta_XPR365 Financials_19.3.20240201.74745.app to http://172.22.205.164:7049/BC/dev/apps?SchemaUpdateMode=synchronize&tenant=default
Status Code 422 : Unprocessable Entity
Extension compilation failed
error AL1024: A package with publisher 'Scapta', name 'XPR365 Library', and a version compatible with '19.1.6.0' could not be loaded. Symbols for the requested app XPR365 Library by Scapta 19.1.6.0 could not be found in the database.
error AL1024: A package with publisher 'Scapta', name 'XPR365 Trade', and a version compatible with '19.2.6.0' could not be loaded. Symbols for the requested app XPR365 Trade by Scapta 19.2.6.0 could not be found in the database.
error AL1024: A package with publisher 'Scapta', name 'XPR365 Master Data', and a version compatible with '19.2.8.0' could not be loaded. Symbols for the requested app XPR365 Master Data by Scapta 19.2.8.0 could not be found in the database.     
error AL1024: A package with publisher 'Scapta', name 'XPR365 Projects', and a version compatible with '19.1.15.0' could not be loaded. Symbols for the requested app XPR365 Projects by Scapta 19.1.15.0 could not be found in the database.
error AL1024: A package with publisher 'Scapta', name 'XPR365 Babelway', and a version compatible with '19.2.5.0' could not be loaded. Symbols for the requested app XPR365 Babelway by Scapta 19.2.5.0 could not be found in the database.
src/Reports/SalesJobInvoiceWord.Report.al(1852,37): error AL0185: Codeunit 'SCA.PRO.JobInvoiceMgt' is missing

**I this something that is going wrong in the script or must I do some configuration changes in the AL-Go settings file?**

**Comment by freddydk** [comment]
Is this a multi-project repo? or are these apps in the same project?
or did you checkin the .app files? or are they maybe downloaded via GitHub Packages?
I need the full log to figure out how the dependent .app files came to be there?

**Comment by FrankAuwers** [comment]
Freddy,

I send you a invite for this repository with read access. I hope you can see now everything you need.
