### ISSUE TITLE
Instructions unclear in scenario #3

### ISSUE THREAD

**Issue by cegekaJG** [microsoft/AL-Go#916]
When trying to deploy to a SaaS environment, I got the same error as #792. I read the instructions again from the top and noticed they are asking for `BcContainerHelper PowerShell` to be installed on my computer.

https://github.com/microsoft/AL-Go/blob/5000d6cab2bbfc0b2aae59a07ee863d6aaa61154/Scenarios/RegisterSandboxEnvironment.md?plain=1#L2

I'm not sure what is meant by that - obviously you don't mean my personal computer, but there's no further elaboration or redirect to another guide. Honestly, I think the error is unrelated to whether I have `BcContainerHelper` installed, but for clarity's sake, I think it would be a good idea to either explain this requirement, or link to another article does.

**Comment by freddydk** [comment]
BcContainerHelper os not needed for this step at all, will remove that.
