### ISSUE TITLE
Workflow Publish To Environment skips PROD environment

### ISSUE THREAD

**Issue by louagej** [microsoft/AL-Go#937]
Hi,

I want to publish a release to a PROD environment:

![image](https://github.com/microsoft/AL-Go/assets/7229592/e202d948-b831-4124-87bd-ebf067af0bee)

The Environment is setup with an AUTHCONTEXT:

![image](https://github.com/microsoft/AL-Go/assets/7229592/3a9e8d09-b338-46bc-9fd6-2f5a48195c2e)

But the Matrix Deploy just skips the step:

![image](https://github.com/microsoft/AL-Go/assets/7229592/c88a01ed-2811-4b06-8f51-8c3a68d3c7f3)

![image](https://github.com/microsoft/AL-Go/assets/7229592/294618b9-9fad-4dca-b381-23e0417c9bf7)

This is my `.github/AL-Go-Settings.json` file:

```
{
  "type": "PTE",
  "templateUrl": "https://github.com/microsoft/AL-Go-PTE@main",
  "DeployToTEST": {
    "EnvironmentName": "TEST_UAT_PRODUCTIE_29112023",
    "continuousDeployment": true
  },
  "DeployToTEST2": {
    "EnvironmentName": "TEST_UAT_12022024",
    "continuousDeployment": true
  },
  "DeployToPROD": {
    "EnvironmentName": "Production",
    "continuousDeployment": false
  }
}
```

These are al my environments:

![image](https://github.com/microsoft/AL-Go/assets/7229592/961ffe7d-c382-4848-99a9-02dc556cc465)

The environments `TEST_UAT_12022024` and `TEST_UAT_PRODUCTIE_29112023` are deployed during CICD workflow without any issues

**Comment by freddydk** [comment]
In Use workflow from, you should use the main branch - you don't need a release branch to publish apps from a specific release.
The release you want to publish is specified in `app version to deploy`.
Release branches are primarily for troubleshooting/hotfixing
If it still doesn't work - please provide the full log for the initialize job, this should explain why the environment is skipped.

**Comment by louagej** [comment]
Hi,

The main branch in our company contains all development features and so isn't suitable for releasing to production.
I'm using cherry picking to release certain new features or hotfixes that were developed in the main branch to production.
So I guess my branching strategy is not how it should be used.
Let's assume example below... I want my hotfix `Hotfix1` to be released before `CR2` is released to production.
Is it possible to achieve this with the `Publish To Environment` workflow?

> **Our Current Branching**

```mermaid

%%{init: { 'logLevel': 'debug', 'theme': 'base', 'gitGraph': {'rotateCommitLabel': true}, 'themeVariables': {
              'tagLabelColor': '#ff0000',
              'tagLabelBackground': '#00ff00',
              'tagLabelBorder': '#0000ff'
       }}}%%
gitGraph
  commit id: "1" tag: "v1.0.0.0"
  branch UAT
  branch Production
  checkout main
  branch CR1
  commit id: "2"  tag: "CR1"
  checkout main
  merge CR1 id: "3" tag: "v1.0.1.0"
  checkout UAT
  merge main id: "12" tag: "v1.0.1.0"
  checkout main
  checkout Production
  merge main  id: "22" tag: "v1.0.1.0"
  checkout main
  branch CR2
  commit id: "4"  tag: "CR2"
  checkout main
  merge  CR2 id: "5" tag: "v1.0.2.0"
  checkout UAT
  merge main id: "13" tag: "v1.0.2.0"
  checkout main
  branch Hotfix1
  commit id: "6" tag: "CR1 Fix"
  commit id: "7" tag: "CR1 Fix"
  checkout main
  merge  Hotfix1 id: "8"  tag: "v1.0.3.0"
  checkout UAT
  merge main  id: "14" tag: "v1.0.3.0"
  checkout main
  checkout Production
  cherry-pick id:"6" tag: "v1.0.1.1"
```

**Comment by louagej** [comment]
@freddydk ,

I realized that there is a setting `CICDPushBranches` that I can use for that.
But it didn't completely solve the problem.
I have added 2 extra setting in the `.github/AL-Go-Settings.json`:
1. `"CICDPushBranches": ["main","uat/*"],`
2. `"DeployToTEST": {"Branches": ["uat/uat"]}`

This is how my file `.github/AL-Go-Settings.json` looks like now:
```json
{
  "type": "PTE",
  "templateUrl": "https://github.com/microsoft/AL-Go-PTE@preview",
  "CICDPushBranches": [
    "main",
    "uat/*"
  ],
  "DeployToTEST": {
    "EnvironmentName": "TEST_UAT_PRODUCTIE_29112023",
    "continuousDeployment": true,
    "Branches": [
      "uat/uat"
    ]
  },
  "DeployToTEST2": {
    "EnvironmentName": "TEST_UAT_22022024",
    "continuousDeployment": true,
    "Branches": [
      "uat/uat"
    ]
  },
  "DeployToPROD": {
    "EnvironmentName": "Production",
    "continuousDeployment": false,
    "Branches": [
      "main"
    ]
  },
  "templateSha": "3cc6fcecbe3916c40e0e8bee473b9a51feaa9dfb"
}
``` 

When I merge a pull Request in the **`uat/uat`** branch I get the expected behavior that the app is build.
But the deployment is skipped.
![image](https://github.com/microsoft/AL-Go/assets/7229592/80c822cc-9554-46c6-ada2-8aad75ef4711)


And when I merge a pull Request in the **`main`** branch I also get the expected behavior that the app is build.
But the deployment is done to my DeployToTEST and DeployToTEST2 enviroment.

![image](https://github.com/microsoft/AL-Go/assets/7229592/b3020fb0-e7a6-4d91-b2b3-51c4529b130b)

**Comment by freddydk** [comment]
Will have a look.
I assume that these settings changes are made in the uat/uat branch as the main branch.

**Comment by louagej** [comment]
yes, changes are made in both branches

**Comment by freddydk** [comment]
The issue here is that while you have defined DeployToTEST and DeployToTEST2, there are no environments called TEST and TEST2.
They are called TEST_UAT_22022024 and TEST_UAT_PRODUCTIE_29112023

The environmentName specified in the DeployTo key is the GitHub Environment name and the structure can define a environmentname property if that differs from the GitHub environment name.
If the GitHub environmentname and the BC environment name are the same - you don't need the environmentname property in the structure.

The way I found this was by looking in Determine Deployment Environments under Initialization:
![image](https://github.com/microsoft/AL-Go/assets/10775043/6f3eb0ac-bad8-4d4a-888b-8a0375d586d6)

**Comment by louagej** [comment]
@freddydk ,

Thank you for your input again.
I have the expected result now.

I changed my environment names in the repository settings to be in line with the `DeployTo`+`<<Environment Name>>` from my .github/AL-Go Settings>.json

![image](https://github.com/microsoft/AL-Go/assets/7229592/fad9f908-db06-4bd0-adb6-46731aea4e1d)

The CI/CD workflow on the `main` branch now builds, but doesn't deploy

![image](https://github.com/microsoft/AL-Go/assets/7229592/d1e81aae-e884-480d-96ab-6ef8d7feee63)

And the CI/CD workflow on the `uat/uat` branch now builds, and deploys to my environments:

![image](https://github.com/microsoft/AL-Go/assets/7229592/3cbddd3f-571d-4a32-9eef-191e89e906bc)

**Comment by freddydk** [comment]
Awesome, thanks for the info
