### ISSUE TITLE
the "The specified blob does not exist" error when run example from the page "https://github.com/microsoft/AL-Go/blob/main/Workshop/Projects.md"

### ISSUE THREAD

**Issue by RedFoxUA** [microsoft/AL-Go#939]
Run example from page https://github.com/microsoft/AL-Go/blob/main/Workshop/Projects.md
and set values:
- "artifact": "https://bcartifacts.azureedge.net/sandbox/23.0.12034.13450/dk"
- "artifact": "https://bcartifacts.azureedge.net/sandbox/**22.0.54157.55210**/us"
- "artifact": "https://bcartifacts.azureedge.net/sandbox/**22.0.54157.55210**/w1"

When run "Stage the changes in VS Code, Commit the changes and Sync." step, I received the error:
"Error: Unexpected error when running action. Error Message: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found." **The specified blob does not exist**. <?xml"

And question - where I can take actual release to replace data for "..sandbox/**22.0.54157.55210**/us"?

Thank you in advance.

**Comment by freddydk** [comment]
You can use this instead 22.0.54157.62753
That should work - I will fix the workshop based on this bug, thanks for reporting.

**Comment by RedFoxUA** [comment]
thank you!

**Comment by RedFoxUA** [comment]
thank you!
