### ISSUE TITLE
Error with the Commit action for the "Releasing the apps" in the part "Update HelloWorld.al"

### ISSUE THREAD

**Issue by RedFoxUA** [microsoft/AL-Go#945]
I tried to follow the Doc "Releasing the apps" ( https://github.com/microsoft/AL-Go/blob/main/Workshop/Releasing.md ) and receive the error in the part "Update HelloWorld.al"

![image](https://github.com/microsoft/AL-Go/assets/39195466/c7170bad-f0b8-4f02-b04b-2e717d6d1c1e)

![image](https://github.com/microsoft/AL-Go/assets/39195466/de2da4dd-bc63-460b-ad5d-3b3e94a01516)

I changed nothing, but just follow the Doc.
What is wrong?

**Comment by freddydk** [comment]
Please copy/paste the full build log here instead of adding screenshots, thanks

**Comment by RedFoxUA** [comment]
[logs_14.zip](https://github.com/microsoft/AL-Go/files/14371592/logs_14.zip)
Here

**Comment by freddydk** [comment]
If you click summary on the build, it should tell you what you did wrong - doesn't it?
Else you can open the log of the Compiling step above, which reveals:

##[error]AL0297 The application object identifier '56000' is not valid. It must be within the allowed ranges '[55000..55100]'.

**Comment by RedFoxUA** [comment]
Page https://github.com/microsoft/AL-Go/blob/main/Workshop/Versioning.md

![image](https://github.com/microsoft/AL-Go/assets/39195466/fcc49b33-0c20-4227-9311-113be72298a7)

**Comment by RedFoxUA** [comment]
Next question - it is about "artifact: https://bcartifacts.azureedge.net/sandbox/23.4.15643.16451/us"
I created Repo, lets Imaginate, with the "Name1", then used it for Dependencies action testing (from Doc), then delete it.
Next step - was created new Repo "Name1" (the name is the same) and started testing again from scratch, but not reached the step Dependencies.

**Comment by freddydk** [comment]
Not sure I understand the question? could you elaborate?

**Comment by RedFoxUA** [comment]
OK. 2 tried to follow an example - created (and deleted) and used Repo with the same name.
For "1st" set of actions I reach the place "Multi-projects" step and delete Repo. Then created it again the same name to process all steps from scratch.

Based on your information I can see that System mixed data from current and deleted Repo, which (which has the same name)
