### ISSUE TITLE
Documentation for appDependencyProbingPaths not containing all possible settings

### ISSUE THREAD

**Issue by cegekaJG** [microsoft/AL-Go#950]
After a lot of experimentation, I found that the property `"appDependencyProbingPaths"` has more settings than the documentation describes. For a testing branch, one of our dependencies had to come from the latest build of a branch that wasn't the default branch. The documentation mentions none of this, but by looking at the AL-Go-Actions scripts I discovered that it is in fact possible to specify a custom branch using the property `"branch"`.
If a setting supports a property, it should be included in the documentation.

**Comment by freddydk** [comment]
It definitely should be.
