### ISSUE TITLE
The file app.json should be explicitly forced to json not jsonc

### ISSUE THREAD

**Issue by rdebath** [microsoft/AL-Go#952]
Normal developers with vscode will likely add a mapping that states that files with the `.json` extension are actually in "jsonc" format as this is normal for JSON configuration files. 
eg: `"files.associations": { "*.json": "jsonc" }`

It is also normal for all json files loaded by VSCode to actually be loaded as "jsonc" including `settings.json`, `launch.json`, `ruleset.json` etc.

The file `app.json` in AL (and only that file) is, however, required to be in exactly ECMA-404 JSON format for BC extensions.
Several undesirable and difficult to diagnose effects occur if either comments or additional commas are present.

Therefor; Please add something like this as a default `settings.json` to work around this issue.

``` jsonc
{
    "files.associations": {
        // Beware publish is seriously broken; it fails silently when app.json has comments.
        "app.json": "json"
    },
}
```

**Comment by freddydk** [comment]
Wouldn't this be something to fix in the AL Language extension instead?
I assume the settings you are referring to here is the code-workspace file - or?

**Comment by rdebath** [comment]
Yes, it would, but they refused.
See https://github.com/microsoft/AL/issues/5315 and https://github.com/microsoft/AL/issues/6909
They're using a Json-404 loader just for `app.json` and doing a poor job of actually surfacing the errors.
The most recent error was the AL-Extension just hanging when loading the workspace; I expect more "issues" until they change their mind.

I usually put this in the `settings.json` in the `.vscode` directory of the project.

**Comment by freddydk** [comment]
In the latest AL Language Extension - they now supports comments in app.json.
Problem is, that this breaks every devops solution out there.
PowerShell doesn't support loading json with comments - and certainly not when re-writing app.json after updating version numbers.

**Comment by freddydk** [comment]
I have requested that they revert that and instead force json.

**Comment by rdebath** [comment]
Ah, so that'd be a good reason for them to use Json-404. But as it seems they just switched it to Json5 that's obviously not the reason they didn't change it before.

However, I suspect you need to make it clear that it needs an AL0999 message to warn about the external tools issue rather than a simple revert of the Json5 change as this issue is that VScode will be setup by users to treat `.json` files as `jsonc` and so cause this breakage _without_ any errors in vscode.

The reasons for making the config file allow comments still apply IMO so a revert isn't the correct solution for that reason too.

Also you're wrong about powershell not loading `jsonc`, while you're correct about PS5.1, the PS6/7 versions will read files with comments, though a rewrite will still remove the comments and rewrite it using a dumbed down (dare I say ugly) "prettified" format.

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-7.4
> Beginning with PowerShell 6, the cmdlet supports JSON with comments. JSON comments start with two forward slashes (//) characters. JSON comments aren't captured in the objects output by the cmdlet. Prior to PowerShell 6, ConvertFrom-Json would return an error when it encountered a JSON comment.

**Comment by freddydk** [comment]
I am totally aware that PowerShell 7 can read jsonc - but BcContainerHelper and AL-Go need to be compatible.
To be completely honest, I have much more important things to spend my time on than trying to support comments in app.json.
If people can select pwsh as shell in AL-Go and make it work - they are welcome, but next thing is they will create an issue that we remove comments when we update the json file - any one of those will be resolved as won't fix.

**Comment by rdebath** [comment]
@freddydk 
FYI: I've switched to using the loader below which appears to correctly load vscode `jsonc` files:
```
$json = (Get-Content -Raw -Path ($manifestPath)) `
    -replace "(@(?:""[^""]*"")+|""(?:[^""\n\\]+|\\.)*""|'(?:[^'\n\\]+|\\.)*')|//.*|/\*(?s:.*?)\*/",'$1' `
    -replace "(@(?:""[^""]*"")+|""(?:[^""\n\\]+|\\.)*""|'(?:[^'\n\\]+|\\.)*')|,([\n\s]*[]}])",'$1$2' `
     | ConvertFrom-Json
$json | ConvertTo-Json -Compress -Depth 100 | Set-Content $manifestPath
```
It's a _simple regex_ to remove comments and trailing commas.

Also I'm always using `ConvertTo-Json -Compress` when writing the manifest file so it's **_obviously_** not for people (like regex!).

**Comment by freddydk** [comment]
> I am totally aware that PowerShell 7 can read jsonc - but BcContainerHelper and AL-Go need to be compatible. To be completely honest, I have much more important things to spend my time on than trying to support comments in app.json. If people can select pwsh as shell in AL-Go and make it work - they are welcome, but next thing is they will create an issue that we remove comments when we update the json file - any one of those will be resolved as won't fix.

I will consider doing the same
