### ISSUE TITLE
Error regarding missing methods in Deserialized.Microsoft.Dynamics.Nav.Apps.Types.AppId

### ISSUE THREAD

**Issue by rbability** [microsoft/AL-Go#953]
We get these since last weekend on all our Repos running a TestNextMajor Action. The error message itself is different among the Repos, but they all point to Deserialized.Microsoft.Dynamics.Nav.Apps.Types.AppId.
Maybe it is just related to the current build of the NextMajor Artifacts. I did another run a few minutes ago, but our Runners did not download a new Artifact Build, so I was probably running on the same version as our NextMajor runs during the weekend.

The error happens in the Run pipeline step after Removing the Container. I can not see an error during the previous steps:

> AL-Go action ran: RunPipeline Telemetry Correlation Id: 69c73e26-1729-421f-a459-92da1ddadf79
Error: Unexpected error when running action. Error Message: Method invocation failed because [Deserialized.Microsoft.Dynamics.Nav.Apps.Types.AppId] does not contain a method named 'ToLowerInvariant'., StackTrace: at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1857 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1825 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1477 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1470 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 948 <- at Run-AlPipeline, C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 910 <- at <ScriptBlock>, C:\actions-runner-01\_work\_actions\microsoft\AL-Go-Actions\v4.0\RunPipe
Error: Process completed with exit code 1.

In another Repo it can look like this:

> AL-Go action ran: RunPipeline Telemetry Correlation Id: 1026c188-88d2-465a-8b07-a70004cb0d0a
Error: Unexpected error when running action. Error Message: Cannot bind parameter 'Id'. Cannot convert the "80e80fa9-7100-4885-852c-ac6b053298dd" value of type "Deserialized.Microsoft.Dynamics.Nav.Apps.Types.AppId" to type "System.Guid"., StackTrace: at Invoke-ScriptInBcContainer, C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 112 <- at Get-BcContainerAppInfo, C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\AppHandling\Get-NavContainerAppInfo.ps1: line 76 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 838 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2181 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2170 <- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 948 <- at Run-AlPipeline, C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 910 <- at <ScriptBlock>, C:\actions-runner-01\_work\_actions\microsoft\AL-Go-Actions\v4.0\RunPipeline\RunPipeline.ps1: line 371 <- at <ScriptBlock>, C:\actions-runner-01\_work\_temp\40fa4555-4e69-4cca-ba79-660965519c48.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
Error: Process completed with exit code 1.

I also tested this with a plain "Hello World" project, which has sample No. 1 as an output.

The artifacts used by the run as I am writing this are
Version: 24.0.16561.0
Platform: 24.0.16518.0

Maybe it solves itself once new Artifacts are released, but since I was not able to find anything about this error here nor in the BcContainerHelper Repo, I wanted to ask if someone else is experiencing this since last weekend.

**Comment by freddydk** [comment]
This is fixed in a combination of new artifacts and ContainerHelper preview (as of today).
You can try to move to AL-Go preview (which automatically uses AL-Go preview) and see if this helps?

**Comment by rbability** [comment]
Thank you very much Freddy. I will give it a shot with one of my testing repos and get back to you.
