### ISSUE TITLE
 The specified file is not an extension file

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#960]
Getting a new error during our build runs: 

"Copying Microsoft__Exclude_ReportLayouts_23.1.13431.14502.app from Container 
Copying Microsoft__Exclude_SyncBaseApp__23.1.13431.14502.app from Container
The specified file is not an extension file.
Parameter name: stream"

This is during the compile step, while extensions are being downloaded from the Container.

Any idea how to debug?  Full log transcript here: 
[The specified file is not an extension file.zip](https://github.com/microsoft/AL-Go/files/14422193/The.specified.file.is.not.an.extension.file.zip)

**Comment by freddydk** [comment]
This could be a download error on your self-hosted runner (cached) - could you try a github hosted runner?

**Comment by buzzwick** [comment]
That build went through without errors (log archive below). Note that a couple of other builds seem to have completed normally,  on the self-hosted runner, since the error I sent in. So, not a consistent problem, but did repeat more than once.

This error is not critical; we have moved the code in this repo to another repo in another github organization. 



[build without self hosted.zip](https://github.com/microsoft/AL-Go/files/14440658/build.without.self.hosted.zip)

**Comment by freddydk** [comment]
So, what this means is that one of your self-hosted runners has a failed download cached.
This happens very seldomly.
When my self-hosted runners for some reason fails - I normally just re-create them by re-running https://aka.ms/getbuildagent

**Comment by buzzwick** [comment]
Aha. So intermittent error--as we could see--and strategies for resolving. Very helpful, thank you.
