### ISSUE TITLE
Finer control of "shell"-property

### ISSUE THREAD

**Issue by cegekaJG** [microsoft/AL-Go#962]
During troubleshooting a custom OnPrem deployment solution, I realized (unfortunately rather late) that AL-Go now uses `pwsh` as the PowerShell command by default. The documentation says it's still possible to use the old `powershell` using the property "shell", but that affects all jobs in all runners. I checked "DetermineDeploymentEnvironments", and it didn't look like the property exists in this scope.
Since a runner or environment is far more indicative as to which command of powershell to use, one of these two changes should be made:

1) Add the property "shell" to the properties of the "DeployTo..." object in `.github/AL-Go-settings.json`
2) Add the condition "runner tags" to the conditional settings

Either of these should make it possible to define the PowerShell command per environment.

**Comment by freddydk** [comment]
AL-Go uses pwsh if you are using Linux, as Linux doesn't have powershell 5.
This property then propagates to custom deployment as well, which is unfortunate if the machine you are using doesn't have pwsh.
