### ISSUE TITLE
"internalsVisibleTo" not respected in CI/CD pipeline

### ISSUE THREAD

**Issue by Bertverbeek4PS** [microsoft/AL-Go#963]
In the app.json I got the internalsVisibleTo set:
![image](https://github.com/microsoft/AL-Go/assets/71499421/d3842a3c-0e92-4a3d-b7dc-e3fa196a3738)
When I publish the app and the test app to a docker container everything works fine.

But in the build pipelines I got the error:
 Error: AL0161 'Table "ADLSE Field"' is inaccessible due to its protection level
 
Attached the log files:
[0_Build . (Default)  . (Default).txt](https://github.com/microsoft/AL-Go/files/14423839/0_Build.Default.Default.txt)

Also updated AL Go to the latest version but without any results.
With:
"useCompilerFolder": false,
  "doNotPublishApps": false
or put on true isn't also working.

**Comment by aholstrup1** [comment]
Do you have an app that matches "Tests for Azure Data Lake Storage Export" exactly? And is the publisher of that app set to "The bc2adls team"? 

Not sure if it's the same happening here but we had a similar issue internally not too long ago. The "name" field in one of the "internalsVisibleTo" didn't match with the actual name of the app. If the app name is different than the name in internalsVisibleTo it will fail.

**Comment by Bertverbeek4PS** [comment]
Thanks @aholstrup1. Thst was indeed the issue. Strange never change it.

Really thanks thst you put me in the right direction!!
