### ISSUE TITLE
PREVIEW: The property 'value' cannot be found on this object. Verify that the property exists. 

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#967]
I realized builds started to fail in the latest preview. 

https://github.com/byndit-demo/App-C/actions/runs/8138002495/job/22237806182

**Comment by freddydk** [comment]
Looks like a bug

**Comment by freddydk** [comment]
This should be fixed in the latest version of ContainerHelper (hence uptaken by AL-Go)
