### ISSUE TITLE
Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'C:\build\vsix\extension\bin\Newtonsoft.Json.dll' because it does not exist."

### ISSUE THREAD

**Issue by Katarina-BS** [microsoft/AL-Go#968]
The same error was reported and fixed two months ago, but today we are experiencing it again when running pipeline for NextMajor version.

BcContainerHelper version 6.0.6
artifactUrl: https://bcinsider.azureedge.net/sandbox/24.0.16410.16595/w1

Error occurs when downloading symbols:

Downloading symbols: Microsoft_Application_24.0.16410.16595.app
Url : http://172.18.116.133:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=21.5.0.0&tenant=Default
Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'C:\build\vsix\extension\bin\Newtonsoft.Json.dll' because it does not exist."

Anyone else having the same problem?

@freddydk

**Comment by freddydk** [comment]
Please include full script and full output of how I can repro this, thanks.

**Comment by ericahoekerd** [comment]
We are having the same issue
