### ISSUE TITLE
LicenseFileUrl 

### ISSUE THREAD

**Issue by fvet** [microsoft/AL-Go#970]
@freddydk I'm currently relaunching our 'move to AL-GO' journey internally and have a question on the 'LicenseFileUrl' secret as referenced in various wiki pages / documentation. I was about to configure the 'LicenseFileUrl' secret as described in the wiki, but wondered if this is still valid / required while reading this post about updated Cronus demo licenses. Do we still need a **developers** license to build apps in CI/CD?

https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=2172494757232640

`Developers no longer need partner licenses or powerful customer licenses to do development. `

**Comment by freddydk** [comment]
Majority of people will probably be able to use the CRONUS (DEMO) license for their DevOps needs.
The only reason I can think of, where a dedicated developer license is needed for this is if your tests cannot run under the limitations of the CRONUS (DEMO) license.

**Comment by fvet** [comment]
@freddydk As licenseFileUrl won't be used by the majority of people, would it be possible to remove the warning? 
I would like to get as little 'AL-GO' warnings as possible, so we can focus on the relevant codeAnalyzer warnings instead.

![image](https://github.com/microsoft/AL-Go/assets/25268332/c8dc9a28-b6ed-4f70-b776-e98fd69897c7)

**Comment by freddydk** [comment]
Yeah - probably a good point to remove the warning and leave it as an information in the log
