### ISSUE TITLE
Variable names visible in unused actions steps

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/AL-Go#978]
Sometimes jobs are skipped. The name of unresolved variables/parameters is visible in the these. Is there any way to hide these of replace them? I know this is nitpicking, but it would make it a little bit more pleasant on the eye.

![image](https://github.com/microsoft/AL-Go/assets/92365904/0dadd5cb-6821-469e-be91-112adb1c1c8e)

**Comment by freddydk** [comment]
I think that is something GitHub needs to fix - we do not have any control over this.
