### ISSUE TITLE
Pull Request Build occasionally considerably slow

### ISSUE THREAD

**Issue by cegekaJG** [microsoft/AL-Go#983]
About every fourth run of the "Pull Request Build" action is experiencing considerably longer run times. The action usually takes 5-7 minutes, but occasionally, it will take 12 minutes or more to complete.
The slowdown is occuring during the "Creating Container" step, but the logs don't seem particularly different.

Here's the log from a build that took 3m 41s:
[logs_21722132183.zip](https://github.com/microsoft/AL-Go/files/14604401/logs_21722132183.zip)

And here's a log from a build that took 12m 33s:
[logs_21724911821.zip](https://github.com/microsoft/AL-Go/files/14604403/logs_21724911821.zip)

Is this just a matter of the artifact server experiencing heavy traffic? On top of that, don't these get stored in the repo's cache?

**Comment by freddydk** [comment]
The difference here looks to be mere download performance of artifacts.
We are investigating how we can make artifacts search and download faster, but for now there is little we can do.
If you specify a specific artifact url in the artifact setting, then all ci/cd builds will use that artifact and that will indeed be cached (when using compilerfolder feature)
