### ISSUE TITLE
Upload image

### ISSUE THREAD

**Issue by aholstrup1** [microsoft/AL-Go#990]
![keyvaultaccesspolicies](https://github.com/microsoft/AL-Go/assets/117829001/c93375e0-ce5b-4aa0-a6b9-a845a87fddef)

**Comment by freddydk** [comment]
You dont have to actually submit the issue in order to get the url

**Comment by aholstrup1** [comment]
![Image](https://github.com/user-attachments/assets/b1e1bd09-64cc-4ede-bebf-e59d5c283cbe)
