### ISSUE TITLE
Use AL-Go without subfolder

### ISSUE THREAD

**Issue by Bartvt21** [microsoft/AL-Go#991]
Hello,

We want to integrate AL-Go in an existing project. I have added the .AL-Go and .github folder to the project. We have all parts at root-level and we don't have a subfolder containing our project. Please see attachment as reference. 

When building and deploying I noticed that the artifacts are not created so the deployment could not finish. Specifically in the build segment I see that the Publish artifacts - Build output is not triggered for running. 

I understand why this is not working, but I was wondering if it is possible to integrate AL-Go without the use of a subfolder that has to be specified in the appfolders settings.json?

Best Regards,

Bart van Tongeren

![Schermafbeelding 2024-03-19 114540](https://github.com/microsoft/AL-Go/assets/25530395/eff19b26-cb97-4c5c-b88d-4a85483fc655)

**Comment by freddydk** [comment]
in the .AL-Go/settings.json, you could try to set "appFolders": [ "." ]
It should work - but haven't tested this.

I would recommend to move the app into a subfolder instead though.

**Comment by freddydk** [comment]
Did you manage to make this work?

**Comment by Bartvt21** [comment]
Hello Freddy,

Unfortunately that is not working. I have also tried some other variants like "/", "", "../". But these are also not working.

**Comment by freddydk** [comment]
Could you create a small public repo, which showcases your problem (with a test app or like) and submit a link here.
Thanks

**Comment by freddydk** [comment]
It does build the app and publish artifacts on the build:
![image](https://github.com/microsoft/AL-Go/assets/10775043/8253826a-3809-4348-a07b-55368c05d133)

What are you seeing that doesn't work?

**Comment by Bartvt21** [comment]
The project does not have environment context because of safety reasons. I have invited you to the real project (WODC-BC-Customization).

**Comment by freddydk** [comment]
Please modify .AL-Go/settings.json and set appfolders to [ "." ] like in your test repo - and I will see what happens when building that.

I saw that you did a manual modifications to CICD.yaml - you should never do that - you should modify CICDPushBranches in .github/AL-Go-Settings.json and run Update AL-Go System Files.

https://aka.ms/algosettings#cicdPushBranches

**Comment by Bartvt21** [comment]
I have committed the change. And thank you for bringing that up 👍

**Comment by freddydk** [comment]
This looks like a compile error in the app:
![image](https://github.com/microsoft/AL-Go/assets/10775043/20f67778-1085-401f-91b5-b1d977bd3ede)

do you assume this is an AL-Go problem?

**Comment by Bartvt21** [comment]
I have solved that issue in the meanwhile. I did not have this issue before as you can see in the run history, but I also see that the deployment to the test environment is successful 👍

**Comment by freddydk** [comment]
So, everything works now?

**Comment by Bartvt21** [comment]
Yes, thank you for your support!
