### ISSUE TITLE
ALDoc : CI/CD ignores Deploy Reference Documentation 

### ISSUE THREAD

**Issue by ismailhafid1** [microsoft/AL-Go#994]
i m trying to configure the CD for the reference documentation , but i can't seem to find a way to make it work , and it always ignores the Deploy Reference Documentation .
Running  Deploy Reference Documentation alone works great, 
here is my AL-Go-Settings.json:
```
{
  "type": "PTE",
  "templateUrl": "https://github.com/microsoft/AL-Go-PTE@main",
  "nextMajorSchedule": "0 0 * * 6",
  "nextMinorSchedule": "0 0 * * 6",
  "deployToGitHubPages":true,
  "continuousDeployment":true
}
```
as the Doc says , using the "continuousDeployment":true it will set the Deploy Reference Documentation as a part of CI/CD , and it works , but while running the CI/CD it ignores it without warning or an error .
what am i doing wrong ?
![image](https://github.com/microsoft/AL-Go/assets/143097318/599f9011-8c06-4bc7-b8f7-abf1420ba17e)

**Comment by aholstrup1** [comment]
I think continuously deploying reference documentation is disabled by default. 

Try adding the following construct to your settings:
```json
"ALDoc":  {
                  "deployToGitHubPages": true,
                  "continuousDeployment":  true,
              }
```

See https://github.com/microsoft/AL-Go/blob/8dfde66bdf7b91d0d56d9a97f6f1688e444e067d/Workshop/ReferenceDoc.md#deploying-the-reference-documentation-continuously for more guidance. 

Also feel free to take inspiration from how we set up microsoft/BCApps to use this feature 
https://github.com/microsoft/BCApps/blob/f41aa4050da9d2aa9dce45fccef63398683226f9/.github/AL-Go-Settings.json#L68

**Comment by ismailhafid1** [comment]
Thanks the workflow runs with success but it ignores setup pages and deploy to github pages  :
![image](https://github.com/microsoft/AL-Go/assets/143097318/69796b4f-ac9a-4ffe-8a45-417f3c7b8cda)
i already have "deployToGitHubPages": true, and github pages enabled , using the Deploy Reference Documentation workflow alone deploys the doc in github Pages , am i missing another parameter ? 
while running the workflow , in the "Read Settings" it shows that the deploytogithubpages = true : 
![image](https://github.com/microsoft/AL-Go/assets/143097318/71f67462-c681-4d7c-af61-009c5fbd6144)

**Comment by aholstrup1** [comment]
In the CI/CD workflow in the initialization stage there should be a task called "Determine Delivery Targets". Can you share the log of that? 

E.g. this is the one from BCApps 
<img width="1152" alt="image" src="https://github.com/microsoft/AL-Go/assets/117829001/25ad3fe2-f3fe-4833-bc83-880d724cb3bd">

**Comment by ismailhafid1** [comment]
![image](https://github.com/microsoft/AL-Go/assets/143097318/2181cebd-4ffc-40dd-b6d0-7278a968fe87)
i can see that The remote server returned an error: (403) Forbidden. 
but why does the workflow alone deploys to github pages but in the cicd returns forbidden ?

**Comment by freddydk** [comment]
Looks like a bug - the workflow is trying to determine whether GitHub pages are enabled and it is getting an error trying to determine this.

**Comment by aholstrup1** [comment]
> It looks like the Initialization job requires pages: read access permission

Was just going to say this. I was able to repro in a private repo. The fix was indeed to add 
![image](https://github.com/microsoft/AL-Go/assets/117829001/591e8ae4-5c9c-4e2e-b747-63778b9c7abb)

**Comment by aholstrup1** [comment]
@ismailhafid1 I've deployed the fix to preview now. To get fix now you'll need to:
1. Update your settings to use AL-Go from Preview
`"templateUrl":  "https://github.com/microsoft/AL-Go-PTE@preview"`
2. Run "Update AL-Go System Files"

**Comment by freddydk** [comment]
You can also just run the Update AL-Go System Files and specify ***@***.*** in the input field

Sendt fra Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Alexander Holstrup ***@***.***>
Sendt: Friday, March 22, 2024 8:08:19 AM
Til: microsoft/AL-Go ***@***.***>
Cc: Freddy Kristiansen ***@***.***>; Comment ***@***.***>
Emne: Re: [microsoft/AL-Go] ALDoc : CI/CD ignores Deploy Reference Documentation (Issue #994)


@ismailhafid1<https://github.com/ismailhafid1> I've deployed the fix to preview now. To get fix now you'll need to:

  1.  Update your settings to use AL-Go from Preview
"templateUrl": ***@***.***"
  2.  Run "Update AL-Go System Files"
