### ISSUE TITLE
Create Release action - include version / release name.

### ISSUE THREAD

**Issue by fvet** [microsoft/AL-Go#996]
Would it be possible to update the display name of the 'Create Release' action / workflow to include the release name and/or version, to make the log of actions a bit more readable?

![image](https://github.com/microsoft/AL-Go/assets/25268332/75f045e3-de25-4bd1-9ef4-4fd9b12866a5)

Envisioned overview would be a bit like the releases / tags overview.

![image](https://github.com/microsoft/AL-Go/assets/25268332/e7c74d98-748b-4603-8bc8-6c12d1f9639f)

Expected result

- Create release - v 23.0.3
- Create release - v 23.0.2
- Create release - v 23.0.1

**Comment by aholstrup1** [comment]
Sounds like a good idea 😄 GitHub workflows have a construct called [run-name](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name) we could probably leverage for this. Then we can use the inputs as part of the workflow name. 

```
run-name: Create release - Version ${{ inputs.tag }}
``` 

Could accomplish what you're requesting.

**Comment by aholstrup1** [comment]
@fvet Deployed to preview now. To get the update you'll need to run "Update AL-Go System Files"
